cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js, src/components/thumbnail/tab-panel-documents-subsection-panel.tsx, src/hooks/use-document-sync-to-firebase.ts, src/hooks/use-last-support-view-timestamp.ts, src/hooks/use-sync-mst-prop-to-firebase.ts, src/lib/db-listeners/db-supports-listener.ts, src/lib/db.ts, src/lib/firebase.ts
We can use one of the custom hooks developed as part of the recent document saving reimplementation to handle synchronization back to firebase (which was the part that wasn't working before) and while we're at it we can consolidate the code for querying the time stamp from firebase into a custom hook as well thus bring these related pieces of code together for ease of maintenance.
@scytacki I've assigned @eireland for review but it's here in case you're curious.
=> Fix firebase sync of user's last support view time stamp

src/models/document/document-content.ts, src/models/document/tile-row.ts
This PR fixes a bug that caused all tile drags from the resource area (the left) to the main workspace to place the tile in an existing row (side by side with another tile) instead of making a new row when the drag preview highlight indicates a new row will be made.
Test branch:
https://collaborative-learning.concord.org/branch/resource-drag/?demo
PT story:
https://www.pivotaltracker.com/story/show/181271011
=> Fix resource view tile drag bug

src/lib/db-listeners/db-other-docs-listener.ts, src/lib/db-listeners/db-problem-documents-listener.ts, src/lib/db-listeners/index.test.ts, src/lib/db-listeners/index.ts, src/lib/db.test.ts, src/models/stores/documents.ts
The code was assuming that if the current user doesn't exist in the offering section of firebase that there couldn't be any documents. It is correct that such a user can't have any problem (or planning) documents, but such users can have personal documents and learning logs, so we shouldn't clear those promises in this case. This situation only arises in no-problem-document configurations, which have only been supported for a short time on the 2.2 branch and so real users should not have been affected.
=> Fix multiplying personal documents for no-problem-document configurations

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, s3_deploy.sh, src/clue/app-config.json, src/clue/components/clue-app-content.tsx, src/components/document/document.tsx, src/models/stores/unit-configuration.ts, src/public/curriculum/example-curriculum/example-no-group-share.json
Hides Group from header when unit config auto assigns student to groups.
Hides publish icon from workspace when unit config disables publishing Adds example unit that hides publish and group
Adds cypress to verify visibility of publish icon and group in header
=> Hides Group from header and publish icon when configured in unit config

src/public/curriculum/example-curriculum/example-no-section-problem-tab.json
Adds class work config to see published documents in example-no-secton-problem-tab unit
=> Change example config to show published documents

src/components/tools/table-tool/use-expressions-dialog.tsx, src/models/tools/table/table-content.test.ts, src/models/tools/table/table-content.ts
Identified via rollbar error encountered by an in-class user of 2.1.3, although I think we've seen it locally as well without ever having logged it in PT.
=> Catch exceptions when parsing expressions in table [#181360571]

dependencies-notes.md, package-lock.json, package.json
Update jest configuration to allow us to update some dependencies for which recent versions are published as esm-only.
=> Update dependencies; fix ts-jest config to support ESM-only dependencies

cypress.json, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json, src/components/qa-clear.tsx, src/index.tsx, src/lib/db-clear.ts, src/lib/db.ts, src/lib/firebase-config.ts, src/lib/firebase.ts
This PR has 3 changes:
- improvements to qaClear
- added console and command logging to cypress
- turned on "retries" in the cypress config
The previous approach to qaClear was using the DB and Firebase classes to clear the current anonymous users data from firebase. 
This approach caused several firestore requests to happen including the creation of local documents that would never be used. The change here is to extract this clearing logic out to its own file independent of the DB and Firesbase classes so we can be sure nothing else happens besides clearing the user.
To support this:
- the firebase configuration was extracted from db.ts.
- a new component was added to run the qa clear and display the results
- the index.tsx was updated to render this qa clear and do nothing afterward
The …
=> simplify qaClear, add better logging

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/graph_tool_spec.js, cypress/integration/clue/branch/student_tests/group_test_spec.js, cypress/integration/clue/branch/student_tests/image_tool_spec.js, cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js, cypress/integration/clue/branch/student_tests/student_test_spec.js, cypress/integration/clue/branch/student_tests/table_tool_spec.js, cypress/integration/clue/branch/student_tests/text_tool_spec.js, cypress/integration/clue/branch/student_tests/workspace_test_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_curation_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_network_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_support_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js, cypress/integration/clue/full/student_tests/group_chooser_spec.js, cypress/integration/common/header_test_spec.js
The specs were using top level before and after hooks in many places. 
When multiple specs are run at the same time, all of these top level hooks are grouped together and run before any of the tests are run.  This blog post describes this in more detail: https://glebbahmutov.com/blog/run-all-specs/
This PR moves all of these into describe or context blocks inside of the spec. It also removes the after blocks, which hopefully aren't really needed. The global after block that is added in `support/index.js` should run after all specs have been run.
Unfortunately, I don't think this will fix any of the CI flakey-ness. I think in that case each spec is run independently.  But maybe I'm wrong, so then this should help somewhat.
=> remove cypress global before and after hooks

src/hooks/use-document-sync-to-firebase.test.ts, src/hooks/use-document-sync-to-firebase.ts, src/lib/debug.ts, src/models/stores/documents.ts
This will help when adding middleware that is specific to a document.
With this change, each documents middleware can record just the changes in that document.
Additionally if references are used and a document is copied, these references will still be vaild.
When there is just one tree all ids have to unique to the tree so a document and its copy will have conflicts unless the ids are changed during the copy.
This change was extracted out of a much larger PR so it is easier to review and get merged.
=> Each document is its own MST tree

src/models/tools/tool-tile.test.ts, src/plugins/diagram-viewer/diagram-content.test.ts, src/setupTests.test.ts, src/setupTests.ts
Jest's matches like `expect(value).toBeDefined()` do not tell typescript that the value will be defined afterward. So in future code lines you have to use things like `value.?`
Typescript has support for assertions like this:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions
The `assertIsDefined` uses this to assert its value is not undefined and not null.
It uses Typescript's assert feature above, and it uses Jest's `toBeDefined` and `not.toBeNull`.
Perhaps in the future Jest's expect statements can act as typescript assertions:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41179
=> add assertIsDefined to mix typescript and Jest checking

src/models/mst.test.ts, src/models/tools/tool-tile.test.ts, src/plugins/diagram-viewer/diagram-content.test.ts, src/plugins/diagram-viewer/diagram-content.ts, src/plugins/diagram-viewer/diagram-migrator.ts
this also removes a test that was over zealous.
CLUE does not try to create a ContentModel directly it always either:
- loads the state from the document
- uses the content model's defaultContentModel function
=> fix diagram migration

package-lock.json, package.json, src/plugins/diagram-viewer/diagram-migrator.test.ts, src/plugins/diagram-viewer/diagram-types.ts
this adds multiple input support
It also changes the version of the state stored for the tile.
The new state has an array of inputs so it isn't compatible with the old version.
=> update diagram view to 0.0.12

src/models/document/document-content.ts, src/models/document/document.ts, src/models/stores/documents.ts, src/plugins/drawing-tool/components/drawing-toolbar.tsx
The stamps were not showing up in the drawing tool. This happened because of 2 issues:
1. the default content for the drawing tile was not being passed an appConfig so it couldn't find the configured stamps
2. the stamp tool was not enabled by default on the drawing toolbar
Issue 1 started happened when the document model was made the root of the MST tree. Previously the documents (plural) model was the root of the tree. The appConfig was being looked up by finding a `Documents` parent of the document model. With the change there was no such parent. The fix for this was by using the MST environment to pass the appConfig. 
I wasn't super careful with this approach, but it seems OK.  Perhaps the definition of `IDocumentEnvironment` should be moved.
Issue 2 started happening when the drawing …
=> Fix drawing stamp tool

src/plugins/drawing-tool/components/drawing-layer.tsx, src/plugins/drawing-tool/components/drawing-object-manager.tsx, src/plugins/drawing-tool/components/drawing-toolbar-buttons.tsx, src/plugins/drawing-tool/components/drawing-toolbar.tsx, src/plugins/drawing-tool/components/selection-drawing-tool.tsx, src/plugins/drawing-tool/model/drawing-content.test.ts, src/plugins/drawing-tool/model/drawing-content.ts, src/plugins/drawing-tool/model/drawing-export.ts, src/plugins/drawing-tool/model/drawing-import.ts, src/plugins/drawing-tool/model/drawing-types.ts, src/plugins/drawing-tool/objects/drawing-object.ts, src/plugins/drawing-tool/objects/ellipse.tsx, src/plugins/drawing-tool/objects/image.tsx, src/plugins/drawing-tool/objects/line.tsx, src/plugins/drawing-tool/objects/rectangle.tsx, src/plugins/drawing-tool/objects/vector.tsx, src/plugins/shared-variables/drawing/variable-object.tsx, src/plugins/shared-variables/shared-variables-registration.ts
The main goal of this PR was to break the direct link between the drawing tile code and the diagram-view package. This link existed because the variable chip drawing tool and drawing object depend on the diagram-view package and were hard coded into the drawing tile code.
To get to this goal, I tried to abstract all drawing objects and drawing tools from the core of the drawing tile. I was not completely successful, but most of the tools and objects are now setup declaratively by the drawing-object-manager.
- **Tool and Object Registry**: 
- the list of tools available in the drawing-layer is now based on a registry of IDrawingToolInfo objects
- the list of object types is now maintained by the drawing-object-manager using IDrawingObjectInfo objects, it is used to make a MST Union type …
=> Drawing Tile Plugin support

src/clue/app-config.json, src/components/document/document-or-browser.tsx, src/components/document/document.tsx, src/public/curriculum/example-curriculum/example-no-my-work.json
Demo: https://collaborative-learning.concord.org/branch/no-my-work/?appMode=dev&unit=example-no-my-work
Previously, the primary/editable workspace would not be displayed if my-work navigation was disabled. @lbondaryk asked about the feasibility of this configuration. While looking into it I realized it shouldn't be hard to implement, as this experiment demonstrates.
=> Allow hiding of my work panel/browser

src/components/thumbnail/documents-type-collection.tsx
While testing an unrelated PR I noticed duplicate key warnings from React. Eventually, I tracked it down to redundant publications as a result of a long-standing temporary variable lifetime issue which results in adding two thumbnails for each problem document to the Class Work browser in some circumstances. Odd that we haven't noticed this before.
=> Fix duplicate keys warning from redundant publication thumbnails

src/models/curriculum/unit.test.ts, src/models/curriculum/unit.ts, src/public/curriculum/mothed/mothed.json
Eliminate top-level `navTabs` property which triggered legacy import.
Default to "modern" import format in case of ambiguous content.
Add unit tests to validate import behavior.
=> Fix mothed curriculum

docs/image-map.md, src/models/image-map.test.ts, src/models/image-map.ts, src/models/mst.test.ts, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-export.test.ts, src/models/tools/geometry/jxg-image.ts, src/plugins/drawing-tool/components/__snapshots__/drawing-layer.test.tsx.snap, src/plugins/drawing-tool/components/drawing-layer.test.tsx, src/utilities/image-utils.ts
This makes several changes to the internal workings of the ImageMap.
Also the external API of the ImageMap has changed slightly.
More details can be seen in the image-map.md that is part of this PR.
Here are some of the changes
- additional calls to `getImage` will not start new storage operations if there is one currently on going.
- calls to `getCachedImage` will return an entry immediately after `getImage` is called. This entry will have a status of `storing`.
- when there is an error, `getCachedImage` will return an entry with a status of `error`.
- entries in the cache are always updated not replaced, this makes it possible for components to observe the entry. 
- the usage of `"my/image/url"` in tests was replaced with a valid local URL. Otherwise this resulted in a console warning …
=> ImageMap Refactor

docs/image-map.md, src/models/image-map.test.ts, src/models/image-map.ts
Finally a PR with a small number of files changed.
This adds more complexity, but it seems the easiest way to cut off infinite loops.
There could be an additional test which is more simple and just calls getImage multiple times and checks the response each time. However the autorun looping test is what will be used in practice, so that is the only one I added for now.
=> add a retry limit of 2 to the image map

s3_deploy.sh, s3_website.yml
This removes the invalidations. It also changes the `max_age` setting so the top level index.html has a max_age of 0. This way deployments of production should pickup the new index.html immediately. And since the other resources have hashes in the file names, any changed resource file should be picked up immediately.
One issue I see is the curriculum files. These do not have hashes, so they will take 10min to expire. However from what I can tell the invalidations were only running on the index.html file anyhow so this shouldn't be any different.
Another issue is that the index file of the version builds was being invalidated. Version folders should never change (because tags shouldn't change) so this shouldn't be necessary. In the off change we need to move a tag, all of the files in the …
=> remove invalidations

src/components/tools/geometry-tool/geometry-toolbar.test.tsx, src/models/document/document.ts, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/image/image-content.ts, src/models/tools/table/table-content.test.ts, src/models/tools/table/table-content.ts, src/models/tools/tool-tile.ts, src/models/tools/tool-types.ts, src/plugins/drawing-tool/model/drawing-content.test.ts, src/plugins/drawing-tool/model/drawing-content.ts
This improves the typing of the tile container model hooks and tileEnv.  I started on this because I wanted to add a new hook (which will be in a different PR).
The hook typing was very painful to figure out. I think what I ended up on was good, but getting there was really hard. 
It isn't perfect because it makes all hooks optional even when we know they are defined. But here is what it helps with:
- calling of hooks doesn't need to use any or any casting.
- implementers of hooks now have typing and  documentation available.
- searches for references of hooks in VSCode now work.
The trickiness of this was to solve the following problems:
- not allowing unknown or mis-spelled hooks when tiles are implementing them
- keeping the conditional calling of a hook as simple as `model.hook?()`
- …
=> Tile lifecycle typing

src/models/document/document.ts, src/models/mst.test.ts, src/models/tools/tool-tile.ts, src/models/tools/tool-types.ts
This will be used so tiles can log actions.
It also adds some new MST tests that were written to invalidate an earlier approach I was trying to take. The tests seem like useful documentation so I left them.
There are no new tests for this. However it is covered by existing tests anytime an action happens on a tile.  We really should have a suite of tests that covers the `IToolContentModelHooks` by adding a mock tile and then checking that the hooks are called at the appropriate time. Given the current craziness of the LARA migration and trying to get this CLUE stuff done at the same time, I'm going to skip adding those 😦 But at least the code is covered so it means it doesn't syntax errors not caught by the compiler. 
This is based on this PR: …
=> onTileAction hook

cypress/integration/clue/branch/student_tests/drawing_tool_spec.js, src/lib/logger.ts, src/models/mst.test.ts, src/plugins/drawing-tool/components/drawing-layer.test.tsx, src/plugins/drawing-tool/components/drawing-layer.tsx, src/plugins/drawing-tool/components/drawing-toolbar-buttons.tsx, src/plugins/drawing-tool/components/drawing-toolbar.tsx, src/plugins/drawing-tool/model/drawing-content.test.ts, src/plugins/drawing-tool/model/drawing-content.ts, src/plugins/drawing-tool/model/drawing-export.test.ts, src/plugins/drawing-tool/model/drawing-types.ts, src/plugins/drawing-tool/objects/drawing-object.ts, src/plugins/drawing-tool/objects/ellipse.tsx, src/plugins/drawing-tool/objects/image.tsx, src/plugins/drawing-tool/objects/line.tsx, src/plugins/drawing-tool/objects/rectangle.tsx, src/plugins/drawing-tool/objects/vector.tsx, src/plugins/shared-variables/drawing/use-variable-dialog.tsx, src/plugins/shared-variables/drawing/variable-object.tsx
This logs all MST actions on the drawing tile to the CLUE logging system.
The key actions of add, move, delete have been updated so they log more useful information. 
In order to record the objects being added, the addObject action now requires a snapshot. There isn't a MST+TS way of checking this at compile time. 
To enforce this constraint there is a check added at runtime. This is aggressive, but it did help me find something I forgot so I think it is worth it. As long as we keep our test coverage up, we should see failing tests if the code changes and an object is passed instead of a snapshot.
TODO
=> Drawing Tool Logging

cypress/integration/clue/branch/student_tests/drawing_tool_spec.js, src/plugins/drawing-tool/components/drawing-layer.tsx
This is a little better. It could be improved more, but hopefully this is good enough for now.
It also fixes 3 bugs:
- while first dragging, the highlight of the hovered object was being rendered in its old location and its dragged object location at the same time.
- during the cypress tests the hover object would be set when clicking on an object, then this object would be deleted by clicking on the delete toolbar button. Because during the tests the mouse didn't move to the toolbar, the hover object in the react state was not cleared. So now on the next render the hover object would continue to render the outline of the deleted object, and MST would complain about a deleted object being referenced. 
- if a drawing object was moved perfectly horizontally or vertically the move would not …
=> clean up moving objects, and selecting objects

.eslintrc.js, src/components/chat/chat-panel.test.tsx, src/components/document/canvas.test.tsx, src/components/four-up.test.tsx, src/hooks/document-comment-hooks.test.ts, src/hooks/firestore-hooks.test.ts, src/hooks/network-resources.test.ts, src/hooks/use-document-sync-to-firebase.test.ts, src/hooks/use-stores.test.ts, src/lib/db.test.ts, src/lib/firestore.test.ts, src/lib/teacher-network.test.ts, src/models/document/document.test.ts
var was being used to help with hoisting above jest.mock.
but everything seems to work fine now without it.
=> convert all var to const or let in tests

src/plugins/dataflow-tool/components/dataflow-program.tsx, src/plugins/dataflow-tool/components/ui/dataflow-program-toolbar.tsx, src/plugins/dataflow-tool/model/utilities/node.ts
I just did the quickest thing to make this happen: removed the data storage block from the toolbar that lets you add new nodes. Actually removing the data storage block from code will be postponed until we can someday get to the clean dataflow code story.
=> Hide data storage block from dataflow toolbar

cypress/integration/clue/smoke/single_student_canvas_test.js, docs/document-types.md, functions/src/shared.ts, src/clue/app-config.json, src/components/navigation/section-document-or-browser.tsx, src/components/thumbnail/decorated-document-thumbnail-item.tsx, src/components/thumbnail/documents-type-collection.tsx, src/components/thumbnail/thumbnail-document-item.tsx, src/hooks/use-document-sync-to-firebase.test.ts, src/hooks/use-document-sync-to-firebase.ts, src/lib/db-listeners/db-supports-listener.ts, src/lib/db-types.ts, src/lib/db.ts, src/lib/firebase.ts, src/models/document/document.ts, src/models/stores/supports.ts, src/models/view/nav-tabs.ts
Show multiple version of publications. Document titles show version number of published document based on the number of times the document has been published. Note that original documents publish to one class vs publish to multiple classes will have sequential number because the version numbers depend on how many times a document has been published in total rather than how times a document has been published by type.
Allows deletion of user owned publications. Version numbers do not change when documents are deleted.
=> 181363573 publish delete multiple versions

src/plugins/dataflow-tool/nodes/dataflow-node.scss, src/plugins/dataflow-tool/nodes/factories/control-rete-node-factory.tsx
This makes it so input that `!==1` on the first parameter in hold block will show as a zero.  It also adds the "flipping" animation and shape to the gate socket on the node.  I left a commented-out version in place that will show the actual input in the first parameter.
=> 182835713 control block param fix

src/plugins/dataflow-tool/components/dataflow-program.tsx
- This maintains the "shrink-to-fit" functionality.  
- This adjusts the "zoom-to-fit" functionality such that it only zooms in when the program is excessively small.   
- Since multiple evaluations can happen across a single trigger when sizing down, we check for both conditions to avoid flicker. 
- Broke calculations into variables for clarity and possible future use, can change back if it is a performance hit or not desirable style
=> 182924194 dataflow default zoom

src/plugins/dataflow-tool/components/dataflow-program.tsx, src/plugins/dataflow-tool/components/ui/dataflow-program-topbar.tsx, src/plugins/dataflow-tool/dataflow-registration.ts
- Hides the Record/Play buttons in Dataflow tile
- adds a `showRecordUI` prop to the `DataflowProgramTopbar`
- sets it to `false` so buttons do not render
- this preserves markup and css in case this feature is brought back
- Changes the `titleBase` for a Dataflow tile to `Program`.  This only affects the default title
=> 182942227 dataflow UI fixes

docs/document-registry.md, src/hooks/use-document-sync-to-firebase.ts, src/models/stores/documents.ts, tool-tiles.md
This adds documentation on:
- tile metadata: how a tile can use it, and a caveat about it
- document registry: this is the DocumentsModel, it describes the two instances of this and how they are setup. It also explores the issue of duplicate document instances for the same document in the database.
It removes an unused action called `update`.
It fixes an issue with `window.currentDocument` which is useful for debugging.
=> review tile metadata and document tracking

src/models/history/tree-manager.ts
When an entry is incomplete (active) it is stored in activeHistoryEntries.
When all of the activeExchanges are ended and it has patches, then it is added to the real history and the undo stack.
I first tried using volatile for activeHistoryEntries.  But that meant that it couldn't be modified by the TreeManager actions since it was a MST object that wasn't part of the same MST tree as the TreeManager.
So instead it is part of the actual model state. When we serialize the history we'll only serialize the treeManager.document object, so these incomplete entries will not be saved too.
=> Only store completed entries in the real history

src/models/curriculum/problem.test.ts, src/models/curriculum/problem.ts
Previously, if a `ProblemModel` encountered a configuration which had both legacy and modern properties, it would import it as though it were a legacy configuration, thus ignoring the modern properties, which led to confusion when authoring.
With this PR we now merge the legacy and modern properties with the modern configuration taking precedence in case of conflict.
=> Make import of problem configuration more robust

src/components/thumbnail/decorated-document-thumbnail-item.tsx, src/components/thumbnail/documents-type-collection.tsx
Fixes bug where previously unversioned published documents show "vundefined" in the footer title.
Fixes document sectioning in Classwork tab for teacher documents. This should now look like this
=> 181363573 publish document versioning bug

src/components/navigation/section-document-or-browser.tsx
The basic create does not do this. The special
createDocumentModel must be used instead.
=> setup shared model manager on history doc

src/models/tools/geometry/geometry-content.ts, src/models/tools/table/table-content.ts, src/plugins/data-card-tool/components/case-attribute.tsx, src/plugins/data-card-tool/data-card-content.ts, src/plugins/drawing-tool/model/drawing-content.ts, src/public/curriculum/example-curriculum/example-curriculum.json, src/public/curriculum/mothed/mothed.json
DataCard
- fix label editing
- remove from MothEd curriculum unit
- add to example curriculum unit
Comment out noisy console warnings from `updateAfterSharedModelChanges()`
Eliminate unused import
=> Release tweaks -- DataCard, warnings

src/plugins/data-card-tool/components/case-attribute.tsx, src/plugins/data-card-tool/data-card-content.ts, src/plugins/data-card-tool/data-card-tool.scss, src/plugins/data-card-tool/data-card-tool.test.tsx, src/plugins/data-card-tool/data-card-tool.tsx
**1.  Adds confirmation dialogue to the delete card action on the Data Card**
In `data-card-content.ts`:
- a new view on the model, `isEmptyCase` can test for a case that has no value in any attribute.  This is used to determine whether or not the warning modal will need to show when a user takes action to delete a card.
In `data-card-tool.tsx`:
- the `useCautionAlert` hook is imported and used to create a `showAlert` function
- The `deleteCase` function was renamed `handleDeleteCardClick` as it does not necessarily delete.  It leverages the `isEmptyCase` test above: If the card has any values in any attributes, it puts up the alert.  If the card is empty of values, it deletes without interruption.
- an existing bit of setup work a commented out stub for `shouldShowDeleteField` was …
=> 183040970 data card delete modal

src/plugins/data-card-tool/components/case-attribute.tsx, src/plugins/data-card-tool/data-card-tool.scss, src/plugins/data-card-tool/data-card-tool.tsx
**This PR adds** 
- Functionality for deleting an attribute from a Data Card
- Fixes for the look of an active/editing value in the Data Card title, and the Data Card attribute title and value
**UI Notes:**
on the _existing_ table tile:
- a single click in a cell results in a blue outline
- the next single click OR double-click highlights the entire current value
- a double-click highlights the entire current value
in this PR, on the Data Card:
- the above behavior is replicated
- additionally, a single click on an entirely-highlighted value will result in an active cursor at the end of the value string
**Note on related features in progress**
- This PR does not address some layout issues that exist on the Data Card in terms of column width and text wrapping
- This PR does not address the …
=> 182799776 data card delete attribute

src/components/document/canvas.tsx, src/components/four-up.tsx
this will allow us to put the history controls on top of the overlay.
this change also DRYs the four-up view at little bit
A side effect of the change is that the four-up views in the teacher dashboard are now resizable. Leslie said that was fine for now.
As noted in the comment, this is a bit more complex than it seems necessary due to the scaling applied above the canvas and the fact the canvas doesn't fill the full quadrant.
I used simple arrays for the lookup tables from indexes to strings. This is contrasted with the more explicit approach used in the four-up-grid. Which uses an enumeration:
```
return {
[CellPositions.NorthWest]: getCellScaling(nwPos),
[CellPositions.NorthEast]: getCellScaling(nePos),
[CellPositions.SouthEast]: getCellScaling(sePos),
[CellPositions.SouthWest]: …
```
=> overlay inside of the canvas sometimes

package-lock.json, package.json
The main point of this PR is to update the diagram-view, but as usual this didn't go smoothly.
I had to delete my node_modules to get this to work. After running `npm i`, package-lock.json had lots of changes.  The main change was that the canvas library and all of its dependencies were not included.
Currently `canvas` is marked as an optional peerDependency of jsdom. I think it was like that before too, but for some reason it was being installed. After doing a `npm i` with an empty `node_modules` and npm version 8, this optional peerDependency was not installed. 
I added canvas as top level CLUE devDependency and now most of the changes to package-lock.json were minor version changes and the removal of 
```
"optional": true,
"peer": true
```
I also got a weird Jest failure on one commit …
=> Update version of diagram-view

.github/workflows/ci.yml, cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js, cypress/support/elements/clue/DrawToolTile.js, package-lock.json, package.json, src/plugins/drawing-tool/components/drawing-layer.tsx, src/plugins/drawing-tool/components/drawing-tool.scss, src/plugins/drawing-tool/components/drawing-tool.tsx, src/plugins/drawing-tool/components/drawing-toolbar-buttons.tsx
This fixes an issue with the delete key causing errors after a drawing tile has been removed from the document.
The fix here is to replace the listeners on the window object with a listener on the top level drawing tile component. This listener will receive events from the drawing canvas as well as events from the toolbar. These keyboard events are only sent if an element is focusable. So for the toolbar buttons to work properly the were converted to `<button>` elements so they could would be focusable.
Also this PR:
- upgrades the version of cypress-terminal-report to be compatible with cypress 10.x.x.
- adds a test for using the keyboard to delete drawing tool objects.
- uses a container to run the cypress tests, this seems to help them be more reliable.
=> switch to real button elements

src/components/playback/playback-control.tsx
This PR switches the the playback controls to paused when the end of history is reached. I also fixed a bug where explicitly setting the playback to pause would instead toggle it (potentially starting to play it instead).
It still seems like there are bugs associated with the playback timeline. If you play the history, you'll notice that the point is at the right end of the track for both of the last two history steps.
=> Stop history playing when end of history is reached

src/assets/expand-toggle-icon.svg, src/components/chat/chat-panel-header.tsx, src/components/chat/chat-thread-toggle.scss, src/components/chat/chat-thread-toggle.test.tsx, src/components/chat/chat-thread-toggle.tsx, src/components/chat/chat-thread.tsx
183182552 - Adds toggle to chat header to expand/collapse it. When clicked in the chat panel, the comment selects the tile in the document. When a tile is clicked in the document, it expands the chat panel.
=> Comment selection and expansion.

cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_problem_chat_spec.js, cypress/support/elements/clue/ChatPanel.js, src/components/chat/chat-thread.scss, src/components/chat/chat-thread.tsx, src/components/chat/comment-card.scss, src/components/chat/comment-card.tsx
Fixing a bunch of styling for comments
- Shows the selected comment as green or the color of the problem, mywork, etc.
- This led me to finding and fixing a bug to keep the thread selection and document selection in sync when the document or document comment thread was selected (see logic change in `handleThreadClick`)
- fixes spacing between comments and threads
- Fixes the chat count spacing
Fixing the styling (mainly removing some styles/ids at the individual comment level and moving them up to the thread tickled the cypress tests. I also added a bunch of waits when a new set of comments is loaded because I was finding that the tests were pretty flaky when I was running them locally.
=> 183447406 comments styling

firebase-test/src/documents-rules.test.ts, firestore.rules
Change the rules for document reads to allow all auth'd users to know whether a document exists.  The same rules should still apply to actually reading the document contents though.
=> Allow authed users to know whether a resource/document exists

src/components/tools/table-tool/table-tool.tsx, src/components/tools/table-tool/use-model-data-set.ts, src/components/tools/table-tool/use-table-title.ts, src/models/tools/shared-model-document-manager.ts
This removes MST warnings that were shown when a document with a legacy table tile was loaded by a teacher from the student workspace tab. In this case the document would be first created with the document state and a shared model dataset would be created. And then a firebase listener would fire and the document content would be updated with applySnapshot using the original document from firebase. This series of 2 loads of the document exposed issues with the components.
I choose to fix the components instead trying to deal with this other ways. For example we could probably prevent the firebase listener from firing when the document hasn't changed after the first load. However the generalized version of this problem is how to deal with migrated content. In that generalized case two users …
=> fix MST errors caused by dataSet caching

cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js, cypress/support/elements/clue/DiagramToolTile.js, src/plugins/diagram-viewer/diagram-tool.tsx, src/plugins/diagram-viewer/diagram-toolbar.scss, src/plugins/diagram-viewer/diagram-toolbar.tsx
Adds a toolbar to the diagram tile with two buttons that currently just console log.
This work is mostly based on the drawing tile toolbar. I think there would be a lot of benefit to trying to unify the code for tile toolbars, but it seems outside the scope of this story.
=> Diagram Toolbar

functions/src/shared.ts, functions/test/post-document-comment.test.ts, functions/test/validate-commentable-document.test.ts, src/hooks/document-comment-hooks.test.ts, src/hooks/use-stores.ts, src/models/document/document.test.ts, src/models/document/document.ts, src/models/history/tree-manager.ts, src/models/stores/documents.ts
`contextId` was not read anywhere. In the Firestore rules and functions `context_id` is used instead. `context_id` is written by the firebase function from the request context.  However the Firestore functions were checking for the existence of `contextId` even though it wasn't used. So the tests of this PR can run against the old functions, a `contextId: "ignored"` has been added to the PR.  After the functions are updated we can remove this `contextId: "ignored"`.
The only sketchy thing that was removed was the logic in use-stores.ts. It was setting the value from either the remoteContext or user object. However since contextId is never read this logic still seemed safe to remove.
With the contextId removed, document.ts can construct the IDocumentMetadata by itself.
The `useMemo` isn't …
=> remove contextId

src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/geometry-tool/geometry-shared.tsx, src/components/tools/geometry-tool/geometry-tool.tsx
Removing these undo/redo handlers seems to let the Treemanager version take over and do the right thing.
Fixes 183544050
=> Remove undo/redo handlers on geometry tile.  

dependencies-notes.md, package-lock.json, package.json
- this downgrades nanoid to avoid an dependency issue
- uses a different format for overriding mobx-state-tree and slate-react
- bumps diagram-view to 0.0.17
- locks react-data-grid to the version that our patch is assuming
This might require clearing your `node_modules` folder. It was also tested with the latest npm version 8.19.2. But I'd suspect it to work with any version of npm `>8.3`
=> update diagram view, revise overrides

cypress/e2e/clue/branch/student_tests/canvas_test_spec.js, cypress/support/elements/clue/ResourcesPanel.js, src/components/workspace/workspace.tsx, src/models/document/document-content.ts
This PR fixes two bugs when dragging tiles between documents to copy them.
- Titles are now being copied.
- The order of the tiles is properly retained.
I also added a couple of tests for dragging files to copy them.
=> Fix bugs when dragging to copy tiles from one document to another

src/components/document/canvas.tsx, src/components/playback/playback-control.tsx, src/lib/logger.test.ts, src/lib/logger.ts
Logs events for opening and closing the history controls, starting and stoping playback and seeking with the slider.
The info logged about playback events is: document key, history id, length of history and history index.
I almost got a jest test working for canvas, but ran into trouble trying to mock about bits of TreeManger. If you think that's worth getting working, happy to spend a little more time on it.
=> Logging for playback

src/models/tools/geometry/geometry-content.ts, src/models/tools/image/image-content.ts, src/models/tools/image/image-registration.ts, src/models/tools/table/table-content.ts, src/models/tools/tool-content-info.ts, src/models/tools/tool-metadata.ts, src/models/tools/tool-model-hooks.ts, src/models/tools/tool-types.ts, src/plugins/data-card-tool/data-card-content.ts, src/plugins/data-card-tool/data-card-registration.ts, src/plugins/dataflow-tool/dataflow-registration.ts, src/plugins/dataflow-tool/model/dataflow-content.ts, src/plugins/drawing-tool/model/drawing-content.ts
- rename `ToolContentModelHooks` => `ToolModelHooks` as CODAP may be attaching them directly to the tile and eliminating the `content`
- separate `ToolModelHooks` and `ToolMetadataModel` into their own files for import flexibility
=> Refactor ToolContentModelHooks => ToolModelHooks

src/components/chat/commented-documents.scss, src/components/chat/commented-documents.tsx
Features this is still missing that are in the zeplin specs:
- icons to indicate a user has commented on a document
- icons indicate what kind of document it is (right now they're all the default)
- document icons color coded by the type.
=> Add styling to commented document list

src/components/chat/chat-thread.tsx, src/components/chat/tool-icon-component.tsx, src/components/tools/tool-tile.tsx, src/models/history/tree-manager.test.ts, src/models/history/undo-store.test.ts, src/models/shared/shared-model-document-manager.test.ts, src/models/tools/geometry/geometry-registration.ts, src/models/tools/image/image-registration.ts, src/models/tools/placeholder/placeholder-registration.ts, src/models/tools/table/table-registration.ts, src/models/tools/text/text-registration.ts, src/models/tools/tool-button.ts, src/models/tools/tool-component-info.ts, src/models/tools/tool-content-info.ts, src/models/tools/unknown-content.ts, src/plugins/data-card-tool/data-card-registration.ts, src/plugins/dataflow-tool/dataflow-registration.ts, src/plugins/diagram-viewer/diagram-registration.ts, src/plugins/drawing-tool/drawing-registration.ts, src/plugins/starter/starter-registration.ts
Some clients (like CODAP) may want to adopt the content model without adopting the component model.
=> Separate tool content registration from tool component registration

src/models/stores/documents.ts, src/models/stores/stores.ts
To keep this simple I just removed the warning. 
When we work on:
https://www.pivotaltracker.com/story/show/183291353
> Safeguard the real documents from having their history changed by the history slider. This can be done by adding a flag or some other way to identify the history documents and only loading history into documents with this flag.
We can consider adding another "type" to this flag indicating the document should be read-only like a network/remote document. Then we can add back the warning if it looks like a document should be recording or playing back history.
Initially, in the first commit, I added a `kind` to the DocumentsModel. In the runtime there are only 2 instances of the DocumentsModel:
- class documents
- network documents
Adding this kind to the DocumentsModel …
=> remove "firestore and userContext" warning

src/components/navigation/problem-tab-content.tsx, src/index.tsx, src/lib/debug.ts, src/models/curriculum/section.test.ts, src/models/curriculum/section.ts
The tab component was reporting an error because of onSelect was not provided.
I also added a DEBUG_STORES to make it easier to see if the focusDocument was being updated correctly.
The error was:
> Warning: Failed prop type: The prop `onSelect` is marked as required in `Tabs`, but its value is `undefined` or `null`.
> `onSelect` is required when `selectedIndex` is also set. Not doing so will make the tabs not do anything, as `selectedIndex` indicates that you want to handle the selected tab yourself.
> If you only want to set the inital tab replace `selectedIndex` with `defaultIndex`.
=> fix a error from tab component

src/components/tiles/image/image-tile.tsx, src/components/tiles/tile-component.tsx
When scrubbing history it is easy to quickly add, remove, add, remove... a tile.
This was causing a couple of warnings/errors in the console.
A MST warning was printed because the tile model was being accessed
after it was detached.
A React error was printed because the component state was updated
after the component was unmounted.
These issues happened in debounced methods which I believe were firing
after the tile had been removed.
After the fixes in this commit I cannot reproduce the console messages.
=> handle tile removal better

package-lock.json, package.json, src/plugins/diagram-viewer/diagram-migrator.test.ts
Gets a quick fix to avoid a bug that was causing crashes when documents were loading that had diagram tiles with nodes referencing non-existent variables.
The change to diagram view involved checking each node after the root is created, and destroying any that don't have a valid variable.
I also had to modify the diagram migrator test.
=> Update diagram view

src/models/stores/documents.test.ts, src/plugins/diagram-viewer/diagram-content.test.ts, src/plugins/drawing/components/__snapshots__/drawing-layer-legacy.test.tsx.snap, src/plugins/drawing/components/drawing-layer-legacy.test.tsx
This fixes:
- Document with the same key already exists
- updateAfterSharedModelChanges was called...
- errors from image map when it was trying to load fake URLs
There are still some console messages and errors not fixed by this PR:
```
PASS  src/plugins/data-card/data-card-tile.test.tsx
● Console
console.warn
[mobx] Out of bounds read: 0
115 |
116 |   function getCaseAtIndex(index: number) {
> 117 |     const aCase = self.cases[index],
|                             ^
118 |           id = aCase && aCase.__id__;
119 |     return id ? getCase(id) : undefined;
120 |   }
...
console.error
Error: Uncaught [Error: Function not implemented.]
at reportException (/Users/scott/Development/collaborative-learning/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
...
at …
```
=> remove some console log messages from jest

CHANGELOG.md, package-lock.json, package.json
Version 3.5.0 adds a new variable card button on diagram tiles, adds formatting for variable cards, fixes a diagram tile crash with keyboard DELETE key and fixes some console errors. There are also content changes for Brain and Math units.
- Format Var Name [#183570281](https://www.pivotaltracker.com/story/show/183570281)
- Format Card Color Selector [#183691861](https://www.pivotaltracker.com/story/show/183691861)
- Color Variable Chips to match Card [#183915153](https://www.pivotaltracker.com/story/show/183915153)
- Format Variable cards [#183644075](https://www.pivotaltracker.com/story/show/183644075)
- Add Variable card button on diagram toolbar [#183644160](https://www.pivotaltracker.com/story/show/183644160)
- Format Value and Unit Field …
=> Version 3.5.0 - Dec 13, 2022

package-lock.json, package.json
The latest diagram-view includes a fix for a bug where using your keyboard to delete a card containing an expression would cause CLUE to crash.
=> Bump diagram-view to v0.0.24

src/models/document/document.ts, src/models/document/tile-row.ts, src/models/history/tree-monitor.ts, src/models/history/tree-types.ts, src/models/history/tree.ts, src/models/history/undo-store.test.ts, src/models/history/undo-store.ts, src/models/history/without-undo.ts, src/plugins/data-card/data-card-content.ts
- move `treeMonitor` volatile property from `Tree` to `DocumentModel`
- move shared types from `tree-monitor.ts` to new `tree-types.ts`
- move `withoutUndo()` from `tree-monitor.ts` to new `without-undo.ts`
=> Eliminate history-related import cycles

cypress/e2e/clue/full/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_dividers_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_problem_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_workspace_chat_spec.js, src/components/tiles/tile-component.sass
PT Story: https://www.pivotaltracker.com/story/show/184163782
Sets the `z-index` for the tile dragger handle to `99` so it can be clicked on when it's placed on top of a diagram.
Also disables some Cypress tests that depend on learn.staging.concord.org being fully functional. The site is having some issues which result in those tests failing.
=> fix: diagram tile dragger handle does not move tile (PT-184163782)

src/components/four-up.tsx
The bug was introduced in #1400 when the four-up code was refactored. This would have appeared in version 3.1.0.
=> fix: four-up view allows editing other users' documents [PT-184276344]

package-lock.json, package.json
Updates diagram-view to the latest version.
[Release notes for diagram-view 0.0.25](https://github.com/concord-consortium/quantity-playground/releases)
=> Bump diagram-view to v0.0.25

src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/nodes/factories/sensor-rete-node-factory.tsx
When a sensor block (rete node) receives a `NaN` from data interpreted from a sensor, it will convert it to a `0` before setting the node value.
=> 184186983 pressure sensor send 0 instead of NaN

src/plugins/dataflow/components/ui/dataflow-program-topbar.tsx
184186985-dataflow-serial-indicator
This changes the behavior of the serial connection button/indicator in the upper left corner of a Dataflow tile so that users of non-Arduino-manufactured boards do not get false error messages about the state of their physical connection, (but also do not get the intermediary prompt).  
**Known Arduino-manufactured board:**
1. flashes orange to warn for connection
2. physical connection made - flashes yellow, message to click to finish connection process
3. user clicks button to approve connection - turns green
**Unknown Arduino-manufactured board:**
1. flashes orange to warn for connection
2. physical connection made - continues flashing orange
3. user clicks button to approve connection - turns green
=> 184186985-dataflow-serial-indicator

src/components/tiles/link-indicator.tsx, src/components/tiles/table/use-geometry-linking.ts, src/models/document/shared-model-document-manager.ts, src/models/shared/shared-data-set-colors.ts, src/models/tiles/geometry/geometry-content.ts, src/models/tiles/geometry/jxg-point.ts, src/models/tiles/geometry/shared-model-color-map.ts, src/models/tiles/table/table-content.ts, src/plugins/data-card/data-card-content.ts
This restores some of the functionality of colored points representing cases in a table shared to a Geometry tile.  Now, points belonging to tables are colored according to an index stored as a volatile property on the shared model.  Row highlights on the corresponding table point also highlight. 
(stories #184187751 and #184187751)
**Changes**
- `shared-model-color-map.ts` instantiates a global map that stores entries that pair a given table id or shared model id with a `colorSet` - specifying how to color points and link symbols when they appear in the context of a Geometry tile. 
- This global map is accessed by `jxg-point` and the geometry model to set and maintain colors on load and through interactions
**Items still open + notes**
- Since this is only used in the context of the …
=> 176599280-shared-model-color-map

src/components/toolbar-button.test.tsx, src/components/toolbar-button.tsx, src/components/toolbar.tsx, src/public/curriculum/m2studio/m2studio.json
PT Story: https://www.pivotaltracker.com/story/show/184008021
Checks the number of existing diagram tiles and if there is already at least one, disables the diagram tile button.
=> feat: Restrict to One Diagram Tile (PT-184008021)

src/components/tiles/text/text-toolbar.tsx, src/plugins/shared-variables/dialog/use-edit-variable-dialog.tsx, src/plugins/shared-variables/dialog/use-insert-variable-dialog.tsx, src/plugins/shared-variables/dialog/use-new-variable-dialog.tsx, src/plugins/shared-variables/slate/variables-plugin.tsx
Pair-programmed with @tealefristoe 
Tries to set the edit caret (selection) when closing any of the variable dialogs to the spot immediately after the affected variable. Generally sets the position of the caret correctly but doesn't always successfully activate the blinking caret, but even in this case typing will usually put the new characters where they belong. Without this fix, the caret would sometimes jump to the beginning of the text and typing new characters wouldn't work correctly. Thus, the new behavior is better than the previous behavior even when it doesn't work completely correctly.
=> Fix selection after inserting/editing variables via dialogs

src/models/tiles/text/text-content.test.ts, src/models/tiles/text/text-content.ts
https://www.pivotaltracker.com/story/show/184366775
Stops adding "\n" between lines in text tiles specified via html in curriculum. This was causing slate to add text outside of paragraphs, which is illegal, and caused data loss and broken functionality when the tiles were copied and modified.
=> Stop adding new lines when creating text tiles from html specified in curriculum

package-lock.json, package.json
Updates diagram-view to the latest version.
[Release notes for diagram-view 0.0.26](https://github.com/concord-consortium/quantity-playground/releases/tag/diagram-view-0.0.26)
=> Update diagram-view to v0.0.26

package-lock.json, package.json
[Release notes for diagram-view 0.0.28](https://github.com/concord-consortium/quantity-playground/releases/tag/diagram-view-0.0.28)
=> Update diagram-view to latest version -- 0.0.28

README.md, docs/text-tile-plugins.md, package-lock.json, package.json, src/components/tiles/text/text-tile.tsx, src/components/tiles/text/text-toolbar.tsx, src/models/tiles/text/text-plugin-info.ts, src/plugins/shared-variables/slate/text-tile-buttons.tsx
Here is what I want to try to do here:
=> Clean up toolbar rendering

functions/src/get-network-document.ts, functions/src/parse-document-content.ts, functions/src/publish-support.ts, functions/test/parse-document-content.test.ts, functions/test/publish-support.test.ts, functions/test/test-utils.ts
This should fix part of the image issue that we've been seeing: PT-184215310
There are 2 more parts that need to fixed:
- there needs to be a migration which finds all of the images that were not "published" correctly.
- there is still the possibility that a document will be loaded by a teacher before the teacher's network is known by CLUE. And if the teacher can only access the images in the document because of this network, the images will not be loaded correctly.
For the migration, I think I can basically use the existing image migration script. It does more than necessary, but I think it will correctly find any unpublished images and publish them.
=> handle published image urls in new tile state

src/components/tiles/geometry/geometry-content.tsx
This restores functionality in which polygons, comments, and vertex angle markers made from shared data persist after page reload.  
This restores functionality in which the graph axes rescale as shared points are added and changed, and also accounts for native points so that all points remain in view as data changes and rescales. 
1. `syncLinkedPoints` becomes `syncLinkedGeometry`.  
2. I left in place the functionality that deletes and recreate shared points, but compartmentalized it into a function `recreateSharedPoints`.  I was not able to easily pick out and reconstitute the change objects for cases when one of a set of shared points changes.  
3. It uses `checkCleanJXG` to see if there are any objects in model state that are not in JXG state (and also checks for duplicates, though I …
=> 183053771 shared data polygon and axis rescale

package-lock.json, package.json, src/hooks/custom-modal.scss, src/plugins/shared-variables/dialog/use-edit-variable-dialog.tsx, src/plugins/shared-variables/dialog/use-new-variable-dialog.tsx
PT Story: https://www.pivotaltracker.com/story/show/183974159
These changes will need to be made in light of [these changes](https://github.com/concord-consortium/quantity-playground/pull/58) to the diagram-view variable edit form.
=> feat: Edit Variable dialog displays read-only expressions (PT-183974159)

src/components/tiles/text/text-tile.tsx
This PR fixes a problem where the first text tile to load in curriculum would not have markup.
The issue was that the content was being deserialized before the editor had been set up, so no node types were registered and they were therefore all being ignored.
=> 184366884 Fix First Text Tile Bug

src/hooks/use-custom-modal.tsx, src/plugins/shared-variables/dialog/use-edit-variable-dialog.tsx
PT Story: https://www.pivotaltracker.com/story/show/183974159
This fixes two issues related to [this previous PR](https://github.com/concord-consortium/collaborative-learning/pull/1566)
1) If changes were made in the edit dialog form but not saved, the changed values could reappear in the edit form.
2) Hitting the Return/Enter key while typing in a textarea in the edit dialog would cause the dialog to close.
=> fix: Edit Variable dialog displays read only expressions (PT-183974159)

src/components/tiles/text/text-tile.tsx
A recent change prevented the toolbar from disappearing when a text tile loses focus. This PR forces a rerender on focus and blur, ensuring that the toolbar is displayed properly.
=> Fix Text Toolbar

docs/images.md, scripts/README.md, scripts/update-supports-images.ts
- this uses a more generic regex to find images in both the old and new tile states
- handle non-networked published docs better
Add documentation on:
- running scripts in a shell.
- how published images are handled
PT-184215310
=> fix some previously published images

src/plugins/shared-variables/dialog/use-new-variable-dialog.tsx, src/plugins/shared-variables/shared-variables.ts, src/plugins/shared-variables/slate/text-tile-buttons.tsx
PT Story: https://www.pivotaltracker.com/story/show/184406182
Adds a `noUndo` option to SharedVariable's `addAndInsertVariable` action. The new option is used to determine if `withoutUndo` should be called for the action.
In some cases (e.g., adding a new variable to a text tile), using the `addAndInsertVariable` action can result in two undoable actions being added to the undo history which can lead to confusing and unexpected behavior. Passing `true` for the `noUndo` option ensures that only one undo action is added to the undo history, preventing the unexpected behavior.
=> fix: New variable dialog creates two undoable actions (PT-184406182)

cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js, src/plugins/diagram-viewer/diagram-tile.tsx, src/plugins/shared-variables/shared-variables.ts
PT Story: https://www.pivotaltracker.com/story/show/184375871
Per comments in the PT story, although recent work fixed the crash caused by undoing adding a new variable to a diagram tile using the New Variable dialog, the diagram tile's drag-and-drop monitor was still using the `addVariable` action which can cause problems when using the Undo feature. These changes update the drag-and-drop monitor to use the `addAndInsertVariable` action instead like the New Variable dialog does.
=> fix: Undo of diagram tile variable card creation crashes CLUE (PT-184375871)

cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js, src/components/document/canvas.tsx
PT Story: https://www.pivotaltracker.com/story/show/184280949
This problem could happen with other tile/action combinations. For example, if you typed text into a text tile, then changed a drawing, undoing the drawing change would also undo the text tile change.
The reason for that was we were still allowing the browser's default handling of cmd+z and cmd+shift+z to occur in addition to our custom undo and redo handlers. These changes make sure we prevent the default.
=> fix: Undo in drawing tile undoes action in diagram tile (PT-184280949)

src/plugins/shared-variables/dialog/use-edit-variable-dialog.tsx
PT Story: https://www.pivotaltracker.com/story/show/184474083
These changes fix a problem with creating `variableClone` from `variable` that was causing the edit dialog to contain stale values. `variable` is included in the dependency array of the call to useMemo used for `variableClone`, but because useMemo only does a shallow comparison of objects, changes to `variable`'s properties in the variable cards were not triggering an update of `variableClone`.
To fix that, we modified the solution included in [these changes to fix how edited values in the dialog remained after the dialog's Cancel button was clicked](https://github.com/concord-consortium/collaborative-learning/pull/1576). The main change is to increment `count` when the modal is opened instead of when it's closed. This can …
=> fix: Changes to variable cards not saved unless click away (PT-184474083)

package-lock.json, package.json
[Release notes for diagram-view 0.0.34](https://github.com/concord-consortium/quantity-playground/releases/tag/diagram-view-0.0.34)
=> Update diagram-view to latest version -- 0.0.34

src/clue/components/teacher/teacher-group-six-pack-fourup.sass, src/clue/components/teacher/teacher-group-six-pack-fourup.tsx
This removes the teacher support button and associated styles and click handler as described in pivotal story #183368003.
=> removes teacher dashboard group header support button

src/lib/logger-utils.ts, src/models/document/document-content.ts, src/models/tiles/log/log-comment-event.ts, src/models/tiles/log/log-tile-base-event.ts, src/models/tiles/log/log-tile-change-event.ts, src/models/tiles/log/log-tile-copy-event.ts, src/models/tiles/log/log-tile-document-event.ts, src/models/tiles/table/table-content.ts
PT Story: https://www.pivotaltracker.com/story/show/184428587
Add tile titles to tile event logs for easier reference by researchers. If a tile has no title, use `<no title>` as a placeholder.
=> feat: Log tile titles (PT-#184428587)

src/lib/logger.ts
PT Story: https://www.pivotaltracker.com/story/show/184068699
The `portal` property of `user` is initially empty when the app first loads, so `sendToLoggingService` was defaulting to using the QA URL. The `portal` property in `data.parameters` seems to contain the expected value (i.e., learn.concord.org) from the start, so these changes include an additional check for `data.parameters.portal` in case `user.portal` is empty.
Included is a change to the `console.log` statement when `DEBUG_LOGGER` is true. We were previously outputting the full `logManagerUrl` object instead of the specific log-ingester URL being used. Seems like we would want the specific URL, but I want to double check that.
=> fix: Initial load from production portal using qa log ingester (PT-184068699)

src/models/tiles/text/text-content.ts, src/utilities/string-utils.ts
Turns out we did need to escape double quotes after all! In my recent tests, I was only checking quotes in the actual text field, which were automatically being converted to `& quot ;`. However, double quotes within html tags (like the href of a link) were not being converted automatically.
=> 182820037 Fix link exports

src/models/tiles/geometry/jxg-point.ts
PT Story: https://www.pivotaltracker.com/story/show/184609260
BUG: While a teacher is viewing a student's work in the 4-up view, if the student links a graph and a table, the data from the table does not appear in the graph in the teacher's view (it does appear for the student). If the teacher reloads the page and navigates back to the view of the student's work, the graph is then populated.
When the link is first made, an error appears in the teacher's browser console: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fill')`.
These changes prevent that error by checking if `colorMapEntry.colorset` is defined instead of just checking for `colorMapEntry` since `colorMapEntry` can exist with an undefined `colorSet`. With that error prevented, the graph is …
=> fix: Table and Graph do not synchronize in 4-up view (PT-184609260)

src/models/curriculum/problem.test.ts, src/models/curriculum/problem.ts, src/models/curriculum/section.ts, src/models/curriculum/unit.ts, src/public/curriculum/example-curriculum/example-shared-data.json, src/public/curriculum/m2studio/m2studio.json, src/public/curriculum/mothed/mothed.json
This is a simplified approach to supporting shared models in curriculum sections.
Ideally we wouldn't have duplicate shared model manager initialization code, but the approach in this PR is miminal and solves the problem.
As usual trying to avoid circular dependencies makes the code harder to read. 
PT-184583797
=> feat: support shared  models in sections

cypress/e2e/clue/branch/student_tests/canvas_test_spec.js
This feature (shift+click and drag multiple tables from left to right) is not working until we handle dragging of multiple shared-model-backed tiles.  The test has been adjusted to only handle a single-table drag.
=> Disable (temporarily) test of dragging a group of multiple table tiles

src/hooks/use-custom-modal.tsx, src/plugins/diagram-viewer/diagram-tile.tsx, src/plugins/shared-variables/dialog/use-edit-variable-dialog.tsx, src/plugins/shared-variables/dialog/use-new-variable-dialog.tsx
PT Story: https://www.pivotaltracker.com/story/show/184616625
BUG: When a variable card is selected in a diagram tile and the Edit Variable dialog is opened but none of its fields are in focus, hitting the keyboard Delete key results in the selected variable card being deleted.
This change prevents the bug by disabling the default Delete key behavior for variable cards when a dialog is present.
These changes build on [these related changes to diagram-view](https://github.com/concord-consortium/quantity-playground/pull/69).
=> fix: Expression variable behaviour (PT-184616625)

cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js, cypress/e2e/clue/branch/student_tests/text_tool_spec.js, cypress/support/elements/clue/DataCardToolTile.js, src/plugins/data-card/components/case-attribute.tsx, src/plugins/data-card/components/sort-area.tsx, src/plugins/data-card/components/sort-select.tsx, src/plugins/data-card/data-card-content.ts, src/plugins/data-card/data-card-tile.scss, src/plugins/data-card/data-card-tile.tsx
This implements a basic select menu for Data Card sorting, as described in  [PT #184552058](https://www.pivotaltracker.com/n/projects/2441242/stories/184552058)
- A sort selector includes all fields added by the user to the deck
- When fields are added to a card, the new field shows up on the sort in alphabetical order
- When a field is removed from the deck, the field name is removed from the list
- The sort by selection persists in the model (across reloads)
=> 184552058 sort deck control

cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js, cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, cypress/e2e/clue/branch/student_tests/table_tool_spec.js, cypress/support/elements/clue/DataCardToolTile.js, src/plugins/data-card/components/data-card-rows.tsx, src/plugins/data-card/components/sort-area.scss, src/plugins/data-card/components/sort-area.tsx, src/plugins/data-card/components/sort-card-attribute.tsx, src/plugins/data-card/components/sort-card.tsx, src/plugins/data-card/components/sort-select.tsx, src/plugins/data-card/components/sort-stack.tsx, src/plugins/data-card/data-card-content.ts
This implements a display for sorted data cards.   Cards appear in their sorted-by-attribute-value category, and can be individually toggled open or closed.  
`SortCard` now displays a styled card, and can toggle open and closed.  `SortCardAttribute` displays an individual attribute name/value pair.  Styling was cleaned up and consolidated a little bit.  
I also added a little more cypress test coverage.  Randomly the linter brought to the surface some small issues in some unrelated cypress tests, and those are in this PR as well. 
PT #184524377 should be updated to reflect the fact that the PIs now prefer the toggle-any-card view deployed here.
=> 184524377 sort card display

src/components/document/canvas.tsx, src/models/document/document-content.test.ts, src/models/document/document-content.ts, src/models/tiles/table/table-export.ts, src/models/tiles/text/text-content.ts, src/models/tiles/tile-content-info.ts, src/models/tiles/tile-model.ts, src/utilities/hot-keys.ts, src/utilities/string-utils.ts
Fulfills this PT story: https://www.pivotaltracker.com/story/show/184755026
Allows a user to press cmd+option+shift+e to save the current document's contents as files representing sections.
Also fixes these bugs:
- Commas between tiles in exported json no longer include an extra newline.
- Text tiles that contained carriage returns from pasted content would include those line breaks in exported json. These are now removed when exporting sections into files.
- Table tile json now include a comma when a table name is present.
=> 184755026 Export Sections

src/models/stores/app-config-model.test.ts, src/models/stores/app-config-model.ts
PT Story: https://www.pivotaltracker.com/story/show/184606497
Fixes AppConfigModel's `getUnitBasePath` view so that exports contain relative paths for images instead of full URLs.
=> fix: Separate Content Repo Images (PT-184606497)

cypress/e2e/clue/branch/student_tests/data_card_tool_spec.js, cypress/support/elements/clue/DataCardToolTile.js, src/plugins/data-card/components/sort-area.scss, src/plugins/data-card/components/sort-area.tsx, src/plugins/data-card/components/sort-card.tsx, src/plugins/data-card/components/sort-stack.tsx
Implements drag and drop of data cards between sort categories as described in PT story: https://www.pivotaltracker.com/n/projects/2441242/stories/184717210
- Dragging a card from one column to another in the sort view will change the value of the attribute and the card will appear in the new stack
- Drop zones appear at the top of sort stacks when any card is dragged
- Leverages `dnd-kit`: `useDraggable`, `useDroppable`, and `useDndMonitor`
=> #184717210 drag and drop of data cards between sort stacks

src/models/tiles/geometry/geometry-content.ts, src/models/tiles/geometry/geometry-import.ts, src/models/tiles/geometry/geometry-migrate.ts, src/models/tiles/geometry/jxg-board.ts
This PR fixes a bug introduced in a previous fix. The issue is that a single function, `defaultGeometryBoardChange`, is used in two contexts, when initializing the board and when exporting json. But there are slight differences in requirements for these cases. Originally they were both doing the same thing, which caused the geometry view to shift when loading from exported json. But part of the fix for this was no longer including the units when converting the model to changes. However, this broke the case when we needed to initialize the board. The fix is to conditionally include the units, so they are present when initializing the board but absent when exporting json.
=> 18477441 Fix geometry tile display

cypress/e2e/clue/branch/student_tests/table_tool_spec.js, cypress/support/elements/clue/TableToolTile.js, src/components/tiles/table/table-tile.tsx, src/components/tiles/table/table-toolbar-buttons.tsx, src/components/tiles/table/table-toolbar.scss, src/components/tiles/table/table-toolbar.tsx, src/components/tiles/table/use-data-set.ts
PT Story: https://www.pivotaltracker.com/story/show/183570161
This PR adds a new delete button to the table toolbar, which clears the contents of the currently selected cell. It also makes the table toolbar buttons configurable in curriculum json: `[unit].config.settings.table.tools = ["set-expression", "delete"]`, remove a button string from the array to remove the button from that unit.
Note on tests: I added a simple cypress test for the delete button, which works as expected. However, code coverage claims that many lines involved in this test are not being covered for some reason. So the code coverage percentage is misleadingly low. I didn't add tests for configuring the table toolbar.
=> 183570161 Table Toolbar Configuration and Delete Button

src/models/document/document-content.test.ts, src/models/tiles/table/table-content.test.ts, src/models/tiles/table/table-export.ts, src/models/tiles/table/table-import.ts
PT story: https://www.pivotaltracker.com/story/show/184679541
Previously, column width information was included with other column information when exporting/importing tables. A recent change moved the column information out of the tile json, and into shared model json. However, the column widths are a property of the table, not the shared model, so this information was lost in the transition. This PR addresses that issue by reintroducing the column widths into exported tables.
=> 184679541 Export and Import Table Column Widths

docs/cms.md, src/cms/clue-control.tsx, src/components/app.tsx, src/components/doc-editor-app.tsx, src/doc-editor.tsx, src/index.tsx, src/initialize-app.tsx
- move document handling into ClueControl
- keep DocEditorApp just for the doc editor entry point
- extract some parts of the initializeApp which are
only needed by the runtime (index.tsx)
- unify the ModalProvider and QueryClientProvider for all 3 entry points
=> refactor app initialization

src/models/tiles/text/text-content.ts, src/utilities/string-utils.ts
PT Story: https://www.pivotaltracker.com/story/show/184755026
When exporting text tiles, new line characters sometimes sneak into the final output, breaking the json. The source of these line breaks are unknown, but probably result from hidden characters pasted into the text tiles from Word. This PR attempts to address the issue by more aggressively removing newlines and carriage returns, and doing so before escaping backslashes.
These solutions seem to solve the problem, but I'm still not sure why previous solutions didn't work. I'm guessing that the issue is Windows line breaks, `\r\n`, are considered a single character, so splitting on `\n` did not leave the `\r`, which I was trying to filter out previously. The new reg expression I'm using covers all combinations of `\r` and `\n`, so …
=> 184755026 Remove new lines when exporting text

src/cms/clue-control.tsx, src/components/doc-editor-app.tsx
PT Story: https://www.pivotaltracker.com/story/show/184824070
=> 184824070 Include Tile Ids when Exporting JSON from CMS Widget and Doc Editor

src/components/document/editable-document-content.scss, src/components/document/editable-document-content.tsx
PT Story: https://www.pivotaltracker.com/story/show/184836795
The recent document editor and CMS update required adjusting the css for `EditableDocumentContent`. This added an additional layer of classes that differentiated contained and full screen components, because the CMS component had to be contained within a widget. This broke some other css (`.document-tabs .editable-document-content`) that was previously overriding the single `.editable-document-content` class, but was no longer overriding the double `.editable-document-content.full-screen` pair of classes. This fix moves `.full-screen-editable-document-content` and `.contained-editable-document-content` to the top level, so as single classes they will be overridden by the pair of classes as was happening previously.
=> 184836795 Fix editable document content css.

cypress/e2e/clue/full/student_tests/group_chooser_spec.js, src/clue/components/clue-app-header.tsx, src/components/app.tsx, src/components/document/document.tsx, src/lib/db-listeners/db-doc-content-listener.ts, src/lib/db-listeners/db-groups-listener.ts, src/lib/db-listeners/db-problem-documents-listener.ts, src/lib/db.ts, src/lib/logger.ts, src/models/stores/groups.test.ts, src/models/stores/groups.ts, src/models/stores/user.test.ts, src/models/stores/user.ts
The current user's group was not being computed correctly so the documents of other members of their group were not monitored. The `latestGroupId` is stored in firebase on the user object. It is updated to represent the last group that a user has joined. When the user launches a different assignment/problem from when they joined that last group they might be a in a different group in this different assignment/problem.
This change was done by adding a `currentGroupId` property to the `User` model.  This is property is set whenever the groups are updated.
The `latestGroupId` is still used in order to automatically join the user to a group when they start a new assignment in the class. 
Because it is hard to test this, I also tried to change all of the places that were finding the user's …
=> Fix 4-up monitoring

cypress.config.ts, cypress/e2e/clue/branch/student_tests/canvas_test_spec.js, cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js, cypress/e2e/clue/branch/student_tests/graph_tool_spec.js, cypress/e2e/clue/branch/student_tests/image_tool_spec.js, cypress/e2e/clue/branch/student_tests/text_tool_spec.js, cypress/support/elements/clue/ImageToolTile.js, cypress/support/elements/clue/cCanvas.js, src/components/tiles/geometry/geometry-content.tsx, src/components/tiles/image/image-tile.tsx, src/models/image-map.ts, src/plugins/drawing/components/drawing-tile.tsx, src/utilities/clipboard-utils.test.ts, src/utilities/clipboard-utils.ts
PT Story: https://www.pivotaltracker.com/story/show/184755020
Adds support for pasting image URLs copied from the CMS media library into the Image, Drawing, and Geometry tiles. When pasted into a tile, the image URLs are automatically converted to a rendered image, or background image in the case of the Geometry tile.
=> feat: Author/upload images (PT-184755020)

src/cms/custom-control.scss
PT Story: https://www.pivotaltracker.com/story/show/184851232
Decap CMS sets styling for unordered and ordered lists that adversely affects their appearance in CLUE text tiles that appear in the CMS content editor (no bullets or indentation, seemingly arbitrary text color change and size). There doesn't appear to be an option to get Decap to not apply styling to certain elements in the editor section, so this fix adds a section to custom-control.scss where Decap's stye rules can be overridden or reverted when necessary.
=> fix: Text tiles should display bulleted lists (PT-184851232)

README.md, docs/cms.md, src/cms/clue-control.tsx, src/lib/debug.ts
PT Story: https://www.pivotaltracker.com/story/show/184824215
Adds a `cms` debug flag for tracking content changes in the CMS.
=> feat: Loading unchanged image tiles should not register as change (PT-184824215)

README.md, src/components/document/document-content.tsx, src/components/tiles/tile-component.tsx, src/lib/debug.ts, src/models/document/document-content-import-types.ts, src/models/document/document-content-import.ts, src/models/document/document-content.ts, src/models/document/drag-tiles.test.ts, src/models/document/drag-tiles.ts, src/models/shared/shared-data-set.ts
This is Part 1 of hopefully a set of 3 PRs to address this story: PT-184869601
- It pulls the drag code out of `tile-component.tsx` and adds tests for the extracted code.
- It includes some type changes to the document content import.
Those types are not used much so didn't expose the issues.
- It adds a new debug flag `drop` which prints the dataTransfer of the drop event. This turned out to be more tricky than just logging the object because of how the dataTransfer object is only fully available during the event itself.
The second PR will be https://github.com/concord-consortium/collaborative-learning/pull/1611, that had minimal changes on the drag side of the code that was refactored here, so there should be minial merge conflicts.
The third PR will be to refactor the drop side of the …
=> refactor tile drag code and add tests

src/cms/clue-control.scss, src/cms/clue-control.tsx, src/cms/custom-control.scss
PT Story: https://www.pivotaltracker.com/story/show/184882521
In the CMS, links are rendered in dark gray text and do not have an underline, which makes them difficult to see. These changes revert the color and text-decoration CSS rules for links within the CLUE canvas part of the CMS so links within tiles are more visible.
=> fix: Styling missing on links (PT-184882521)

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, cypress/support/elements/clue/DataflowToolTile.js, src/models/stores/serial.ts, src/plugins/dataflow-tool/microbit/communicator.md, src/plugins/dataflow-tool/microbit/hub.md, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/model/utilities/channel.ts, src/plugins/dataflow/model/utilities/node.ts, src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx, src/plugins/dataflow/nodes/controls/sensor-value-control.tsx, src/plugins/dataflow/nodes/factories/live-output-rete-node-factory.tsx
Functionality is here for [PT#184916018](https://www.pivotaltracker.com/n/projects/2441242/stories/184916018)
- Relays send their aggregated state back to Dataflow
- Live output node indicates (sent) if the state of the selected relay does not match the state of the relay in the report
- Live sensors will no longer accept `NaN` values coming up from failed parse of serial stream.  They retain the last set value until a new, valid, positive number is read from sensor. 
There are a few to-do items that are potentially keeping this in draft for the moment
Changes above are made below.  I also added some cypress tests that touch:
- Dragging nodes
- Connecting nodes
- The modal serial connection warning
- Data flowing from one node to the next
=> 184916018 live output node matches sent state with received state

cypress/e2e/clue/branch/student_tests/canvas_test_spec.js, cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/support/elements/common/Canvas.js, src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-shared-models.test.ts, src/models/document/document-content-types.ts, src/models/shared/shared-data-set.ts, src/models/shared/shared-model.ts, src/models/tiles/geometry/geometry-content.ts, src/models/tiles/table/table-content.ts, src/models/tiles/table/table-registration.ts, src/models/tiles/tile-content-info.ts, src/plugins/data-card/data-card-content.ts, src/plugins/data-card/data-card-registration.ts, src/plugins/dataflow/model/dataflow-content.ts
PT Story: https://www.pivotaltracker.com/story/show/184812191
This PR builds off of the tile duplicate code to make copying tiles by dragging them from another document also duplicate the tiles' shared models. It also better structures that code by breaking it into multiple functions and moving code related to specific tiles and shared models into their files rather than the generic document content file.
This code still involves a lot of hard coded references to specific tiles and shared models. It also only addresses shared data sets and the table, datacard, geometry, and dataflow tiles; it doesn't support shared variables or diagram, drawing, or text tiles.
I'm requesting a review now even though I'm hoping to add a couple of cypress tests that deal with dragging linked tables and …
=> 184812191 Drag to Copy Table and Data Card Tiles with Shared Data Sets

src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/components/ui/dataflow-program-zoom.tsx
PT Story: https://www.pivotaltracker.com/story/show/182890335
This PR allows the user to scroll the document when wheeling over the dataflow tile. This event is usually captured by Rete, preventing scrolling.
=> Dataflow scroll

src/models/tiles/table/table-content.ts, src/models/tiles/table/table-registration.ts
PT Story: https://www.pivotaltracker.com/story/show/185046082
The immediate reason for this work is that it's now possible to switch a table tile's dataset ((un)linking with a dataflow tile). Previously, the displayed title was the dataset's name, but that changes when switching datasets. This work prevents that by using the tile's title instead of the dataset's name. Additionally:
- The dataset's name no longer changes when the user changes the tile's title, so I don't think it's possible to change a dataset's name through CLUE any longer.
- An imported table tile will take its dataset's name if it doesn't have a title specified. This was required to make certain legacy units load properly for testing.
Unless there are requests for changes, this PR is ready to merge after the 4.0 …
=> 185046082 Use Table Tile Title Over Dataset Name

src/plugins/dataflow/components/dataflow-program.tsx
Zombie components were being left around with these actions:
- when the programEditor is re-initialized in read-only DataflowProgram
- when the DataflowProgram was unmounted
- when a rete node was removed
Really this fix should be integrated into react-render-plugin,
but doing that would require changes in more places.
=> cleanup zombie components

src/plugins/dataflow/nodes/controls/demo-output-control.tsx, src/plugins/expression/README.md, src/plugins/expression/expression-content.test.ts, src/plugins/expression/expression-content.ts, src/plugins/expression/expression-icon.svg, src/plugins/expression/expression-registration.ts, src/plugins/expression/expression-tile.scss, src/plugins/expression/expression-tile.test.tsx, src/plugins/expression/expression-tile.tsx, src/plugins/expression/expression-types.ts, src/register-tile-types.ts
This comprises 
[PT#184851423 expression tile](https://www.pivotaltracker.com/story/show/184851423)
- Uses the starter tile template to create an expression tile
- Adds icon
[PT#184851445 expression tile title](https://www.pivotaltracker.com/story/show/184851445)
- Adds title edit/save functionality
- One unrelated, unused import removed from Demo Output
=> 184851423 expression tile

cms/src/iframe-control.tsx
PT Story: https://www.pivotaltracker.com/story/show/184919981
Fixes the iframe src path value so the CMS editor is loaded correctly on branch URLs. This is a follow up to https://github.com/concord-consortium/collaborative-learning/pull/1688 which can't be tested at master branch URLs because the path `/cms-editor.html` returns a 404 when you try to access the CMS at URLs like https://collaborative-learning.concord.org/branch/master/admin.html.
=> fix: Use iframe for CMS (PT-184919981)

cms/src/iframe-control.tsx
PT Story: https://www.pivotaltracker.com/story/show/184919981
Adds the `unit` URL param to the iframed CMS editor. This corrects a problem where the editor wasn't displaying the correct toolbar items specified in a unit's settings.
=> fix: Use iframe for CMS

src/models/document/shared-model-document-manager.ts, src/models/history/tree.ts, src/models/shared/shared-model-manager.ts, src/models/tiles/text/text-content.test.ts, src/models/tiles/text/text-content.ts, src/models/tiles/tile-content.ts, src/plugins/diagram-viewer/diagram-content.test.ts
Some tiles may need to respond specially to linking to or unlinking from a shared model. This PR adds a second argument to the `updateAfterSharedModelChanges()` callback indicating the type of change that is occurring.
Note: I was sorely tempted to rename the `updateAfterSharedModelChanges()` function to something more conventional like `handleSharedModelChange()` but decided to refrain from the function rename in the interest of keeping this PR simpler. I'd still be in favor of a rename, but perhaps that should be left for a subsequent PR. One additional reason for the change is that in the case of `unlink`, the call happens _before_ the unlink, so that the tile has a chance to make use of the shared model before the unlink occurs. I also considered having three separate callbacks, …
=> refactor: add `type` argument to handleAfterSharedModelChange() callback

package.json, src/app-config.ts, src/components/tiles/table/data-table.tsx, src/components/tiles/table/linked-table-cell-editor.tsx, src/models/tiles/geometry/jxg-changes.ts, src/test/setupTests.test.ts, src/utilities/dom-utils.ts, tsconfig.json
- Enabling `isolatedModules` in the jest configuration should speed up the jest tests
- Enabling `isolatedModules` in the `tsconfig.json` just issues an error if there's any code that wouldn't work with `isolatedModules`
=> chore: enable isolatedModules in tsconfig.json and ts-jest configuration

.eslintrc.js, cypress/e2e/clue/branch/student_tests/expression_tool_spec.js, cypress/fixtures/teacher-dash-data-CLUE-test.json, cypress/fixtures/teacher-dash-data-msa-test.json, cypress/fixtures/teacher-dash-data.json, cypress/support/elements/clue/ExpressionToolTile.js, package-lock.json, package.json, src/components/tiles/custom-editable-tile-title.tsx, src/plugins/data-card/data-card-tile.scss, src/plugins/data-card/data-card-tile.tsx, src/plugins/expression/expression-content.test.ts, src/plugins/expression/expression-content.ts, src/plugins/expression/expression-registration.ts, src/plugins/expression/expression-tile.disable-test.tsx, src/plugins/expression/expression-tile.scss, src/plugins/expression/expression-tile.test.tsx, src/plugins/expression/expression-tile.tsx, src/plugins/expression/expression-types.ts, src/test/jest-resolver.js, src/test/setupTests.ts, src/utilities/title-utils.ts
Updates the implementation for this PT story:
- [184851445](https://www.pivotaltracker.com/story/show/184851445): **Expression title default and editing** (This is reimplemented with a reusable component that is also swapped in to the Data Card tile).  
Adds functionality from these PT stories: 
- [184851442](https://www.pivotaltracker.com/story/show/184851442): **Expression saves and restores**
- [184851427](https://www.pivotaltracker.com/story/show/184851427): **Expression tile allows expression editing from Cortex**:
2. I'm leaving this in draft at the moment until a resolution of an issue with resolving mathlive in jest test.  
3. We got mathlive module into Jest environment, and I was able to get a few basic tests going.  However, I was not able to get the shadow dom to render in the …
=> Expression Tile Editing, Save, Title

src/models/image-map.ts
PT Story: https://www.pivotaltracker.com/story/show/185149154
In the context of authoring, `db.stores` is undefined. This change adds a check for that, and in the case `db.stores` is undefined, skips the attempt to store an image when it's added to a data card. (The original image URL will be saved instead.)
=> fix: Images do not appear in data cards (PT-185149154)

cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_4_quadrants_spec.js
@scytacki , I have re-enabled the 4-up view test in this PR; It didn't crash on my machine and it looks like it also din't crash in github.
=> Re-enabling 4-up cypress tests that were recently disabled

src/components/document/group-virtual-document.tsx, src/components/document/student-group-view.tsx, src/models/stores/groups.ts
PT Story: https://www.pivotaltracker.com/story/show/185159335
It looks like CLUE is supposed to only allow group numbers from 1 to 99. But somewhere, this is broken, and some teachers have enormous group numbers (greater than a million). This probably causes multiple problems, but one in particular is that the numbers overflow the buttons that allow a teacher to switch between groups, which makes it difficult to see and switch to groups.
Ideally, we should figure out how groups with absurdly large numbers are being created. I tried to look into it a bit, but I couldn't figure it out. Additionally, someone should go back and clean up existing groups in the database that have become absurdly large.
This PR addresses the issue in a short term, imperfect way by truncating group ids to only …
=> 185159335 Truncate Group Numbers

src/plugins/expression/expression-tile.scss, src/plugins/expression/expression-tile.tsx
This implements [PT#184930324](https://www.pivotaltracker.com/story/show/184930324)
- The title field already implements readOnly
- This adds the functionality to the math-field itself
- The math-field element has a `readonly` property that we can set to match the component readonly prop 
_- Note: I set the math field `readonly` in an effect.  I did try to pass it directly in the `math-field` attribute, but found that did not work, even with a function inline.  (I think because either updates were stale because the underlying object is a ref and/or the presence of the readonly property, though its value was undefined, was evaluating as "truthy"_
=> 184930324 expression read only

cypress/support/elements/clue/DataflowToolTile.js, src/plugins/expression/expression-content.ts
Expression Tile Export: [PT#185246854](https://www.pivotaltracker.com/n/projects/2441242/stories/185246854)
- This adds the latex field to the expression tile export format, with each backslash escaped for serialization
- I tested the results of the export commands on left-side and right-side content
=> Expression export 185246854

src/plugins/data-card/components/sort-area.tsx, src/plugins/data-card/components/sort-card-attribute.tsx
This fixes a crash reported in this story: https://www.pivotaltracker.com/story/show/184376222
However the error looks like it has been there a little while before. I suspect it is because merging datasets resulted in undefined values which then cause the problem. According to the dataset typing undefined values are valid so this change seems the best way to handle things.
=> convert dataset values to strings

cypress/e2e/clue/branch/student_tests/expression_tool_spec.js, src/plugins/expression/expression-tile.test.tsx, src/plugins/expression/expression-tile.tsx
Functionality described in [PT#185182713]:(https://www.pivotaltracker.com/n/projects/2441242/stories/185182713)
- Since clicks on the equation editor itself do not propagate past the boundary of the shadow dom, we have to explicitly set the expression tile as the active tile in the ui store
- This is not necessary for clicks within the expression tile that are not within the boundaries of the shadow dom
- _Note: the failing cy test is the one that I believe is expected to fail at the moment_
=> 185182713 expression focus synced with other tiles

src/components/tiles/geometry/geometry-content.tsx, src/plugins/data-card/data-card-tile.tsx
The linking dialog is using these titles
We could almost get rid of this `getTitle` on the API, and replace it with a `tileModel.title`. But the table tile has logic to support an unset `tileModel.title`. If it isn't set then it uses its `dataset.name`. So this makes it look like the `getTitle` API is still required. 
However there are places that set the tileModel.title on tile creation even if it is table. So it is probably inconsistent when table tiles do and don't have tileModel.titles
Also, I looked around and there are a few places that are currently assuming `tileModel.tile` has the right title:
- getTileTitleForLogging
- makeChatThreads
An intermediate step would be to change DocumentContent#getTileTitle so it falls back to `tileModel.title` if the tile doesn't implement its own …
=> add titles to geometry and data-card tiles

src/models/document/shared-model-document-manager.ts, src/plugins/graph/components/graph-wrapper-component.tsx, src/plugins/graph/graph-registration.ts, src/plugins/graph/models/graph-controller.ts, src/plugins/graph/models/graph-model.ts, src/utilities/shared-data-utils.ts
PT Story: https://www.pivotaltracker.com/story/show/184667373
These changes do two things:
1) Make it so Graph tiles can only be connected to one shared data set at a time. This fixes a bug where if you link a graph to a data provider, and then delete the data provider, the graph will continue to show the old data even if you try linking it to a new data provider.
2) Fix a small, unrelated issue where we were directly importing `appConfig` into the Graph model
=> fix: XYPlot - Link Table to XYPlot (PT-184667373)

README.md, src/components/doc-editor-app.tsx, src/components/document/canvas.tsx, src/models/document/document-content-import.ts, src/utilities/url-params.ts
- allow passing a document url as a param
- allow saving a document if the document wasn't opened
- allow loading basic documents, not section documents
- show the file name of the opened or saved document
- add new hot key for copying raw document content: non export document
raw document content works with shared models better
Note: this isn't covered well by tests. Here is some rational why: 
- It hasn't been requested as a feature for end users, currently it is just useful for developers and demo'ers
- It should be useful for writing CLUE tile tests since it is now possible to load a pre populated document that has been crafted for a specific test case.  If we start using it this way then more of it will be covered.
=> improve standalone doc editor

src/plugins/graph/axis/components/axis.tsx, src/plugins/graph/axis/hooks/use-axis.ts, src/plugins/graph/axis/models/axis-model.ts, src/plugins/graph/components/graph-axis.tsx, src/plugins/graph/graph-types.ts, src/plugins/graph/hooks/use-graph-model.ts, src/plugins/graph/models/graph-controller.ts, src/plugins/graph/models/graph-model.ts
PT Story: https://www.pivotaltracker.com/story/show/184867297
These changes fix a bug where connecting an XY Plot tile to an empty Table tile and then adding data to the table would lead to the XY Plot tile not placing the corresponding data dots properly. The GraphController's `setPrimaryRoleAndPlotType` function has been updated to use `numeric` as the default plot type instead of `empty` in the case that the `emptyPlotIsNumeric` setting is `true`.
=> fix: XYplot default axis limits and tick behavior

src/plugins/graph/components/attribute-label.tsx
PT Story: https://www.pivotaltracker.com/story/show/185317045
Move the `defaultAxisLabels` check within the `useClickHereCue` check in AttributeLabel so the default labels are only shown when there is no linked data source. This allows the axis label values to be updated when the associated attribute names are changed in a linked data source.
=> fix: Renaming Table attrs not showing in linked XYPlot (PT-185317045)

src/plugins/data-card/data-card-tile.tsx, src/plugins/expression/expression-tile.tsx
PT#185307242 bug: DataCard and Expression tile toolbars were not rendering in correct location in 4-up view.  
- This passes scale prop to DataCard and Expression toolbars so that they have the correct value in hand when their locations are calculated.  
- This also destructures the props at the top of the Expression Tile
=> 185307242 expression toolbar placement fix

cypress.config.ts, cypress/e2e/clue/branch/student_tests/expression_tool_spec.js, package-lock.json, package.json, src/plugins/expression/expression-buttons.tsx, src/plugins/expression/expression-tile.test.tsx, src/plugins/expression/expression-tile.tsx, src/plugins/expression/expression-toolbar.scss
This PR: 
1.  updates to the latest version of `mathlive`
2.  replaces `suppressChangeNotifications` with `silenceNotifications` to match the updated API and type in the library.
3.  adds a second ref to hold state for all readOnly instances of the `math-field` on the page
4. changes toolbar button to a `button`
This completes [PT#185246497](https://www.pivotaltracker.com/story/show/185246497). Editing in the CMS (within an iFrame) now works. 
This completes [PT#185315270](https://www.pivotaltracker.com/story/show/185315270). Denominator is no longer "stuck" in placeholder state when typing a fraction. 
This improves on the issue behind  [PT#185170012](https://www.pivotaltracker.com/story/show/185170012).  The "moving parens" is less likely to happen now as the "ghost" or "unconfirmed" …
=> 185246497 mathlive update 0 94 6

cypress/support/commands.js, src/components/tiles/table/editable-table-title.tsx, src/components/tiles/table/table-tile.tsx, src/components/tiles/table/table-toolbar-buttons.tsx, src/components/tiles/table/table-toolbar.scss, src/components/tiles/table/table-toolbar.tsx, src/components/tiles/table/use-content-change-handlers.ts, src/components/tiles/table/use-data-set.ts, src/models/document/shared-model-document-manager.ts, src/models/shared/shared-model-manager.ts, src/models/tiles/geometry/geometry-registration.ts, src/models/tiles/table/table-content.ts, src/models/tiles/tile-content-info.ts, src/plugins/dataflow/model/dataflow-content.ts, src/utilities/shared-data-utils.ts
PT Stories: 
- [Tables can link to other tables, data decks](https://www.pivotaltracker.com/story/show/185316977)
- [Data Sources with strings are linkable](https://www.pivotaltracker.com/story/show/185250327)
The two stories above have a lot of overlap so the work was combined in this one PR. 
These changes make it possible to link a Table tile to another Table tile, move the linking button from the Table tile's header to its toolbar, and remove the check/requirement for numerical data before allowing linking between tiles.
=> feat: Tables can link to other tables (PT-185316977)

src/plugins/expression/expression-tile.tsx
This PR addresses [#PT185394587](https://www.pivotaltracker.com/story/show/185394587)
Inline shortcuts such as `pi` and `th` get in the way when people are trying to type variable names that may include those strings, e.g. “pizza", or "moth" 
This disables all inline shortcuts.  
Note that this does not disable \ commands - e.g. a person can still type the π symbol by typing `\pi`.
=> disable inline shortcuts

cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js, cypress/support/elements/clue/DataflowToolTile.js, cypress/support/elements/clue/DiagramToolTile.js, src/components/tiles/basic-editable-tile-title.tsx, src/plugins/diagram-viewer/diagram-tile.tsx, src/plugins/drawing/components/drawing-tile.tsx, src/plugins/graph/components/graph-wrapper-component.tsx
PT Story: https://www.pivotaltracker.com/story/show/185415226
This PR adds a title component to the diagram tile. It also introduces a new basic title component that can be used by many tiles. In this PR it's only used for the diagram, drawing, and graph tiles.
=> 185415226 Add title to diagram tile

cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_workspace_spec.js
Over the weekend, two cypress tests started failing in master, both related to the overview tab in the teacher guide of the msa unit. I think this tab was changed in curriculum, which doesn't cause our tests to run any longer because it's in a separate repo. The fix was to change the "Overview" tab to "Unit Plan".
Note that two other tests in `teacher_chat_spec.js` are failing related to recent changes to comment colors. This PR does not address those failing tests.
=> Stop checking for overview tab in teacher guide section in cypress tests

src/plugins/expression/expression-tile.tsx
This fixes the math-live "slash mode". It was broken because typing `\` would cause an input event but not change the value. We'd then set the value of the math-live element which would mess up the "slash mode". So the fix is to identify input events that happen in slash mode and ignore them.
This also fixes the `%` which was broken when the shortcuts were blanked out.
And finally it fixes the `*` which was broken when shortcuts were blanked out, but instead of using the default `\cdot` it now uses `\times`.
PT-185428315
PT-184933384
PT-185356879
PT-185394587
=> fix percent and slash mode, change asterisk to create times

src/plugins/dataflow/model/utilities/simulated-channel.ts
PT Story: https://www.pivotaltracker.com/story/show/185309379
This follow up PR makes it so input variables will appear in a sensor node's bottom dropdown when the appropriate sensor type is selected. It does this by trying to match the input variable's name with a sensor type's name, then giving the simulated channel the corresponding type.
=> 185309379 Set a simulated channel's type based on its name.

cypress/e2e/clue/branch/teacher_tests/teacher_workspace_spec.js, cypress/support/commands.js, src/components/document/student-group-view.scss, src/components/document/student-group-view.tsx, src/components/four-up.tsx, src/models/document/document-utils.ts
Replaces the group name with the student name and document name of the currently open 1up view title bar in Student Workspaces tab. When user clicks on 4up button, title bar shows the group name again.
Also moved the student's name from the document title bar to the group buttons area. The student name buttons are currently none functional.
=> Student name and document name to 1up view title bar in Student Workspaces

src/components/document/student-group-view.scss, src/components/document/student-group-view.tsx, src/components/four-up.tsx, src/components/vars.sass
Adds functionality the the student name buttons in Student Workspaces tab.
When in 1up view of a student's document, teacher should be able to switch student documents by clicking on the student name.
Note that clicking on the group button does not do anything when in student 1up view. But should still switch groups when in 4up view.
=> 185382726 student button functionality

src/models/curriculum/problem.ts, src/plugins/dataflow/model/dataflow-program-model.ts
This is a change to address a bug that emerged when we updated mst to 5.1.8, as described in [PT#185453973](https://www.pivotaltracker.com/story/show/185453973) (Node values were not serializing). 
- In Dataflow, we make a copy of the snapshot before extracting the currentValues, rather than operating on it in place. 
- In the problem model, we no longer have to make the new copy
**leaving in draft until tests pass in cloud (already passed locally)**
=> 185453973 save node value fix

src/models/stores/groups.ts
PT Story: https://www.pivotaltracker.com/story/show/185484498
Fixes a bug where group numbers with two digits would only show their final digit.
=> Only truncate group ids when they are too long.

src/plugins/graph/components/graph-axis.tsx
PT Story: https://www.pivotaltracker.com/story/show/185532784
This PR prevents the graph from recomputing its axes ranges when there are no points to plot. Previously, this was resulting in null values being assigned to the axes' mins and maxes, which resulted in corrupted documents.
=> 185532784 Prevent graphs from corrupting documents when all points are removed from a linked dataset.

README.md, functions/dependencies-notes.md, functions/src/get-network-document.ts, functions/src/parse-document-content.ts, functions/src/publish-support.ts, functions/src/shared.ts, functions/test/parse-document-content.test.ts, functions/test/shared-dataset-example.ts
these datacard images are stored in the data set, so the
parseDocumentContent function needed to be updated to handle this.
It would be better to make this more generic so we don't have
to update with new tiles or shared models. However there is
still support to avoid publishing multiple images from legacy content.
So until we migrate the legacy content (or give up on the optimization)
we can't make this fully generic.
I also tried to update the README to help others get the tests running.
PT-185502029
=> FIX: publishing images added via a datacard tile

src/components/thumbnail/decorated-document-thumbnail-item.tsx, src/components/thumbnail/thumbnail-document-item.tsx
Previously we only showed stars if the current user starred the documents. But documents that have been starred by a co-teacher are still shown in the Starred documents list for a class in Class Work tab, though they are shown "unstarred". We are changing the behavior so that any document that has been starred, regardless of who starred them, will show them "starred" in the Class Work tab.
This removes the logic that shows stars on documents only starred by current user. We now show stars for all the starred documents for a class that have been starred by anyone in the class.
Added a data attribute to document thumbnail with document id to aid in debugging.
=> Shows stars on all starred documents

src/plugins/dataflow/nodes/dataflow-node-plot.tsx
This rounds the tick values on the y axis of the Dataflow minigraph to one decimal point, as described in [PT#184623254](https://www.pivotaltracker.com/story/show/184623254)
=> 184623254-minigraph-tick-decimal-fix

firebase.json
I'm not sure how this worked before, but when firebase now deploys
a function, it will compile it locally and then again in the cloud.
In order to compile it in the cloud the src folder is needed,
and the tsconfig files are needed.
PT-185502029
=> need src and tsconig for functions deploy

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/nodes/dataflow-node-plot.tsx, src/plugins/dataflow/nodes/dataflow-node.tsx, src/plugins/dataflow/utilities/playback-utils.ts
This adds minigraph rendering to Dataflow recorded program playback, as described in [PT#184873706](https://www.pivotaltracker.com/story/show/184873706) and [PT#184873784](https://www.pivotaltracker.com/story/show/184873784)
- Removes some logic to a utility function
- adds recorded value to nodes during playback.  For those nodes with a calculated output, the calculated value is displayed with an arrow before, indicating it's the result of an operation.
=> 184873706 dataflow minigraph playback

src/components/document/document-content.tsx, src/components/document/editable-document-content.tsx, src/components/navigation/nav-tab-panel.tsx
Reverting back so that student's cannot make comments anymore - only teachers can - per Leslie's request.
See this old PR for reference when I changed it last week - 
https://github.com/concord-consortium/collaborative-learning/pull/1812
=> 185638530-turn-off-student-chat-for-4.2.0

src/components/document/document-content.tsx, src/components/document/editable-document-content.tsx, src/components/navigation/nav-tab-panel.tsx
Previous PR - where we set isChatEnabled to equal `user.isNetworkedTeacher` .
https://github.com/concord-consortium/collaborative-learning/pull/1821
we actually want this to be `user.isTeacher` so lets say teacher 1 (who doesn't have a network) can see the chat, comment and edit.
=> 185638530-patch-fix

src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/components/dataflow-tile.tsx, src/plugins/dataflow/components/ui/dataflow-program-topbar.tsx, src/plugins/dataflow/components/ui/dataflow-rateselector-playback.tsx, src/plugins/dataflow/model/dataflow-content.ts
- remove redundant timers, and redundant state
- move end of playback and end of recording handling to the tick function
- group actions so there are single undo and history events for
clear, start, and adding cases
The redundant timers and state were removed by passing in existing state like playBackIndex, and computing the duration of the recording from the values in the dataset. The computing of the duration is in dataflow-content.ts.
The stopping of the playback and recording when they hit their limits was moved into the update functions in `dataflow-tile.tsx`. This way no extra points will be recorded or played back. And this control is closer to the tick function. This also means the handlers don't have to be passed into RateSelectorOrPlayBack. 
The actions for clear and start now …
=> clean up dataflow playback

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, src/plugins/dataflow/model/utilities/node.ts, src/plugins/dataflow/nodes/controls/value-control.tsx, src/plugins/dataflow/nodes/factories/control-rete-node-factory.tsx, src/plugins/dataflow/nodes/factories/logic-rete-node-factory.tsx, src/plugins/dataflow/nodes/factories/math-rete-node-factory.tsx, src/plugins/dataflow/nodes/factories/transform-rete-node-factory.tsx, src/plugins/dataflow/nodes/utilities/view-utilities.ts
This improves the display of decimal numbers in the Dataflow nodes that take in numbers and return new numbers (Math, Logic Transform, Hold).  [PT#185631814](https://www.pivotaltracker.com/story/show/185631814)
- a new number-to-string function is defined in a utility file, and used in the factory of each node
- small cypress test
=> 185631814 dataflow decimals

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, cypress/support/elements/clue/DataflowToolTile.js, src/plugins/dataflow/components/dataflow-tile.tsx
[PT#185477557](https://www.pivotaltracker.com/story/show/185477557) describes a number of features, most which are already implemented.  This PR addresses the only one not already implemented: 
-  Dataflow's existing tile link icon should not need to wait for recorded data to exist in order to be enabled. 
-  It should be enabled if there is an XY Plot or Table tile present in the document/
=> 185477557 dataflow link button display

cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, src/components/chat/comment-card.tsx, src/components/chat/comment-textbox.tsx, src/lib/firestore-schema.ts, src/public/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
CSS changes that enable the user to post an empty comment given that there are tags
Part of this ticket 
[ **[CLUEAI]** If Tags are enabled, able To Post Empty Comment and display with Tag.](https://www.pivotaltracker.com/n/projects/2441242/stories/185633009)
Changes to the firestore function `async function postDocumentComment` (that needs to be deployed) in `post-document-comment.ts `were in this previous PR (https://github.com/concord-consortium/collaborative-learning/pull/1803)
Timestamp: Jun 19th: 9:49AM PST: 
Currently in `master` there is no way the user can actually click the post button when there is an empty comment and tags, so this addresses that. 
Right now if you post an empty comment (where it has tags), it gives the following error
I'm assuming this will go away once Scott …
=> 185633009-if-tags-are-enabled-able-to-post-empty-comment-and-display-with-tag

functions/src/post-document-comment.ts, src/components/chat/chat-thread.tsx, src/components/chat/comment-card.tsx, src/components/chat/comment-textbox.tsx, src/plugins/dataflow/nodes/dataflow-node.tsx
Deployed link - 
https://collaborative-learning.concord.org/branch/fix-aitag-crashing/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=teacher:2&problem=2.2&unit=https://collaborative-learning.concord.org/branch/master/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______
- Fixed issue where opening comments panel would crash CLUE 
(see below)
This was because in Firestore, `tags` was not being written as an array but rather a string. 
- Added capability to have multiple tags for a comment in the database schema (although our UI currently doesn't support it) 
- Fixed bug reported where when you select a non `tagPrompt` option (in our example "Select Student …
=> fix-ai-tag-crashing

cypress/e2e/clue/branch/student_tests/numberline_tool_spec.js, cypress/support/elements/clue/NumberlineTile.js, src/plugins/numberline/README.md, src/plugins/numberline/assets/numberline-icon-2.svg, src/plugins/numberline/assets/numberline-icon.svg, src/plugins/numberline/numberline-content.test.ts, src/plugins/numberline/numberline-content.ts, src/plugins/numberline/numberline-registration.ts, src/plugins/numberline/numberline-tile.scss, src/plugins/numberline/numberline-tile.test.tsx, src/plugins/numberline/numberline-tile.tsx, src/plugins/numberline/numberline-types.ts, src/register-tile-types.ts
Fulfills [Numberline Tile ticket](https://www.pivotaltracker.com/n/projects/2441242/stories/185477179)
[LocalHost Link](http://localhost:8080/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=teacher:2&problem=1.1&appMode=demo&unit=example)
[Deployment Link
](https://collaborative-learning.concord.org/branch/numberline-tile/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=teacher:2&problem=2.2&unit=example)
I've merged line 46 (see below) to the [clue-curriculum repo](https://github.com/concord-consortium/clue-curriculum), into example > `content.json  ` so that Numberline tile will show up a deployed url where the `unit=example`
=> 185477179 numberline tile

cypress/e2e/clue/branch/student_tests/nav_panel_test_spec.js, cypress/support/commands.js, src/components/navigation/problem-tab-content.tsx, src/components/navigation/section-document-or-browser.tsx
The left side components get recreated each time the resources panel is collapsed and expanded. 
So without this code change, the open subTab was getting reset each time the resource panel was collapsed and expanded.
https://www.pivotaltracker.com/story/show/185800396
Also one of the Cypress functions for collapsing the resource panel was updated. It was flakey before. Below are some notes from a slack conversation about it https://concord-consortium.slack.com/archives/CCHKYUW3S/p1691763253308029
Fix for collapseResourceTabs() is to use cy.get('.drag-thumbnail').trigger('mouseover'). The drag-thumbnail is the 3 vertical dots. It is ontop of everything and it's mouse handler does not have a delay.
There were a few issues with using `.divider-container`:
- one is that the center point is on …
=> only set the subTab if one isn't already set

src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/model/drawing-content.test.ts, src/plugins/drawing/objects/drawing-object.ts, src/plugins/drawing/objects/ellipse.tsx, src/plugins/drawing/objects/image.tsx, src/plugins/drawing/objects/line.tsx, src/plugins/drawing/objects/rectangle.tsx, src/plugins/drawing/objects/vector.tsx
Since action names in the draw tile are used directly as the "operation" field of log entries, they have to be understandable out of context.  This PR changes the names of two new actions to be more clear:
adoptDragBounds --> resizeObject
adoptDragPosition --> repositionObject
=> 185520282-clean-up-draw-action-names

src/components/document/annotation-layer.tsx, src/components/tiles/table/use-tile-api.ts, src/components/tiles/tile-api.tsx, src/models/annotations/clue-object.ts
PT Story: https://www.pivotaltracker.com/story/show/185539001
This PR addresses feedback related to the positioning of sparrows for table cells.
- It's now possible to specify default offsets for different target objects.
- Default offsets for table cells have been changed to the top center of the cell.
=> 185539001 Sparrow Default Offsets

cypress.config.ts, package-lock.json, package.json, src/models/data/attribute.test.ts, src/models/data/attribute.ts, src/models/data/data-set-types.ts, src/models/data/data-set.ts, src/models/data/data-types.test.ts, src/models/data/data-types.ts, src/plugins/data-card/components/case-attribute.tsx, src/plugins/data-card/data-card-tile.scss
This also increases the tests of the attribute model.
It introduces the `dayjs` dependency to help with date parsing.
To visualize the types it adds a type icon to the data card tile.
=> Identify data set types, add new image type

src/plugins/drawing/components/drawing-tile.tsx, src/plugins/drawing/components/drawing-toolbar.tsx, src/plugins/drawing/model/drawing-content.ts, src/plugins/drawing/objects/drawing-object.ts, src/plugins/shared-variables/drawing/drawing-utils.test.ts, src/plugins/shared-variables/drawing/drawing-utils.ts, src/plugins/shared-variables/drawing/variable-object.tsx
Adds an algorithm that finds a location that is not already occupied when inserting variables into a drawing.
Can be tested in units that include shared variables, such as m2s.  A diagram tile as well as a drawing tile is necessary in order to create variables and test this.
I would be interested in feedback on whether there is a more elegant way to get the drawing toolbar button access to know the actual size of the visible drawing area.  I did this by passing a `getVisibleCanvasSize` method down from the tile level to the toolbar and then the individual button.
=> Offset positions when inserting variable chips in drawing (PT #183927775)

src/components/navigation/nav-tab-panel.sass, src/components/workspace/resize-panel-divider.scss
Add some min-width properties so wide content doesn't cause the left side to take extra width.
Also remove some flex containers which were just being used to set the height of a single child.
There is a separate PR for this change on master: https://github.com/concord-consortium/collaborative-learning/pull/1903
=> 185903129-limit-resource-panel-width-4.5.x

src/components/navigation/nav-tab-panel.sass, src/components/workspace/resize-panel-divider.scss
Add some min-width properties so wide content doesn't cause the left side to take extra width.
Also remove some flex containers which were just being used to set the height of a single child.
=> 185903129-limit-resource-panel-width

src/models/document/document.test.ts, src/models/document/document.ts, src/models/history/undo-store-test-utils.ts, src/models/history/undo-store.test.ts, src/models/history/undo-store.ts
Adding logging of undo and redo operations.
Ideally one would log what operation was undone or redone. However, I don't see any simple way to do that, since at best all we have access to would be the tree diffs.  Unless I'm missing something?  If it's not possible, I do think just logging that an undo happened is better than nothing.
I tried to add a test, to which I was going to add testing that the log messages actually get sent, but for some reason undo does not seem to be available in the test environment.  Again, I am probably missing some simple thing.
So I need a little help here. This task goes pretty deep into the internals that I don't yet understand.
=> Add log calls to undo & redo (PT #185847005)

src/models/data/attribute.test.ts, src/models/data/data-types.test.ts, src/models/data/data-types.ts
this now uses strict date parsing, which means invalid
dates will also not be considered dates. For example
if the day or month is too large.
It also means the separator character is strict only `/` and `-` are supported.
I'm about to submit another PR that updates this slightly. That PR will remove all of the single `/` date formats since those are going to be identified as fractions in this next PR.
=> fix image being identified as date

src/plugins/drawing/objects/line.tsx
Fix a symptom of a drawing tool bug (PT-186002744)  that is leaving nulls in line drawings. 
This adds a preprocessor to detect and remove the offending points.
It is a bandaid fix until the root cause can be found and fixed.
=> Preprocess to remove stray null values in drawing

src/plugins/drawing/components/drawing-tile.tsx, src/plugins/drawing/objects/group.tsx, src/utilities/hot-keys.ts
Adds keyboard shortcuts for 'group' and 'ungroup' operations in the drawing tile.
Added a liveness check in the group getBoundingBox call, since it apparently gets called via some observer after it has been detached and throws an error into the console.
=> Group and ungroup keyboard shortcuts (PT-185994631)

src/plugins/drawing/objects/line.tsx
These are the same changes as PR #1929.
Fix a drawing tool bug ([PT-186002744](https://pivotaltracker.com/story/show/186002744)) that was leaving nulls in line drawings.
This PR targets the 4.6.x branch so that it can be more quickly deployed.
=> 186002744 avoid drawing nulls 4.6.x

src/components/tiles/geometry/geometry-content.tsx
PT Story: https://www.pivotaltracker.com/story/show/186036945
This PR fixes a bug where geometry sparrow functions were not checking to make sure a polygon existed before accessing its points, causing a crash when the polygon had been deleted.
=> 186036945 Fix Deleted Geometry Polygons with Sparrows

.github/workflows/ci.yml
This adds support for a `run regression` label.
If the `run regression` label is added to a PR it will trigger a new build that includes the cypress regression tests.
Any further pushes to the PR's branch will also run the cypress regression tests, unless the `run regression` label is removed.
When a branch is pushed that doesn't have a PR yet, the regression tests will not run.
When a PR is created for the branch that doesn't have the `run regression` label the regression tests will not run.
When the PR is merged to master the regression tests should run. 
**Notes:** 
When any label is added to the PR it will now start a build. The first job of the build will only run if the label is `run regression`. 
When a label is added to the PR the list of checks will be updated to include ones …
=> run regression tests only with 'run regression'

src/models/curriculum/unit.ts
There is better `cause` support in the JS standard but Chrome
still doesn't support it:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
https://bugs.chromium.org/p/chromium/issues/detail?id=1211260
This was used to help track down a recent syntax error in the moth unit.
I don't have a simple way to test it. One approach is to check out the clue-curriculum repo. Then add an syntax error to one of the problem files, and then load that unit.
=> print the urls of the files that fail to load

src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-general.test.ts
the non-random ids were causing problems when content was loaded
in the authoring system and then saved again.
PT-186179174
=> assign random unique ids to tiles without them

cypress/e2e/clue/branch/student_tests/simulator_tile_spec.js
This adjusts the sim tile cypress test to match the expected behavior of the sim tile.  Since we no longer have an option of hard-coded data stream without a sim tile, we have one less menu item.
=> adjust cy tests - we no longer have simulated data streams in the menu

src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-general.test.ts
The id change broke comments on curriculum tiles.
With this id change, if a tile doesn't have an id then one was randomly assigned when it is loaded. There are several curriculum files that do not have ids on all of their tiles, so each time one of these was loaded the tile would get a different id. When a comment is made on a tile it is associated with this id. So comments on these id-less tiles would not match any tile when viewed on a new instance of CLUE.
With this reversion PR, the tile ids will again be set deterministically based on their type and index in the section. This means that comments will continue to match up with the tile in the curriculum. However this approach is fragile, if a new tile is inserted into the curriculum the indexes of tiles after it will change so their …
=> 186208247-revert-id-change

src/models/curriculum/problem.test.ts, src/models/curriculum/problem.ts, src/models/curriculum/section.ts, src/models/mst.test.ts
Before this change if a unit had content with duplicate ids across sections, the content would
crash CLUE. With this change the ids only need to be unique within the section itself.
This can be tested with an old version of the seeit unit. You can use this unit by passing this argument to CLUE:
`unit=https://models-resources.concord.org/clue-curriculum/version/seeit-duplicate-ids/seeit/content.json`
So this should work:
https://collaborative-learning.concord.org/branch/section-scoped-ids/?appMode=dev&unit=https://models-resources.concord.org/clue-curriculum/version/seeit-duplicate-ids/seeit/content.json
And this should fail:
https://collaborative-learning.concord.org/version/v4.7.0/?appMode=dev&unit=https://models-resources.concord.org/clue-curriculum/version/seeit-duplicate-ids/seeit/cont …
=> prevent MST from validating ids in sections

src/plugins/drawing/components/drawing-tile.scss
This is a (partial) fix for PT-186082444.  It just updates the CSS.
There are still 1-2 pixel differences between exactly where the different icons align vertically.  To fix this detail we would need to make a matching set of icon images for this context -- the current ones are scavenged from other places that used similar icons.  Not sure if it is worth doing that extra work.
=> Align icons in drawing tile Show/sort panel

src/plugins/graph/components/graph.tsx, src/plugins/graph/models/data-configuration-model.ts, src/plugins/graph/models/graph-model.ts
In PR #1983 I stated that the first question to ask in the case of point filtering issues in the graph code is:
>1. Is `matchCirclesToData()` being called in the relevant path?
a. if so, there may be a bug in `matchCirclesToData()` itself
b. if not, why not?
In the case of these multiple Y filtering bugs, `matchCirclesToData()` was not being called. The reason is that one of the main ways `matchCirclesToData()` is called is that `GraphModel.setAttributeID()` triggers a reaction in the `Graph` component which calls `GraphController.handleAttributeAssignment()`, which calls `matchCirclesToData()` (among other plot configuration). PR #1966 added several methods to the `DataConfigurationModel` for updating the attribute configuration, but they don't trigger the above cycle. With this PR, …
=> fix: issues with filtering points on multiple-y plots

src/components/tiles/geometry/geometry-content.tsx, src/components/tiles/image/image-tile.tsx, src/models/image-map.test.ts, src/models/image-map.ts, src/plugins/drawing/components/drawing-layer-legacy.test.tsx, src/utilities/clipboard-utils.test.ts, src/utilities/clipboard-utils.ts, src/utilities/image-utils.ts
Switch the image map to a MobX class instead of an MST model.
This change is a for few reasons:
- it will make it safer to use the image map within our tile models. There is a known issue with MST where action tracking fails when an action from one tree runs an action in another tree which then triggers an action back in the first tree. This issue doesn't happen when MobX objects are used.
- it hopefully makes the code a little easier to read without all `action` and `view` sections.
- it also makes it possible to mark members as private. Unfortunately this can't be used much since the tests need access to these members. 
When looking at image-map.ts it is useful to hide whitespace changes.  There are still lots of changes, but they match up better.
The image map has a mix of flow and …
=> switch image map from MST to MobX

cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js, src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/components/drawing-tile.tsx, src/plugins/drawing/objects/drawing-object.tsx, src/plugins/drawing/objects/image.tsx, src/plugins/drawing/objects/line.tsx
Implementation of PT-186304442.
Changes the behavior of the "freehand line" and "stamp" tools in the drawing tile to stay selected after a line/stamp is added to the canvas.  Other tools, for example "rectangle", maintain the previous behavior of selecting the object just drawn and activating the select tool.
The drawing tile Cypress test is extended to test this behavior and simplified by putting `{scrollBehavior: false}` as a global preference on each test suite, not on the individual `click()` commands.
=> Customize switch to select tool after drawing

src/models/document/tile-row.ts, src/models/history/without-undo.ts
This fixes warnings that happened when the resizing of a row was being triggered by parent action.
In these cases it seems to make sense to just go ahead and record the resizing. The reason we didn't record it before because it could happen on document load and would result in a weird undo history.
The change really should just remove a warning that is printed in some cases. The adding of undo history events should behave exactly the same as when the warning was there.
=> withoutUndo with opt out

src/plugins/data-card/components/case-attribute.tsx, src/plugins/graph/components/attribute-label.tsx, src/plugins/graph/components/simple-attribute-label.tsx, src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
Fixes: first issue of [[#186234669]](https://www.pivotaltracker.com/story/show/186234669)
The bug was caused by previous rows (above the row with the graph) resizing. The bug occurred because the button used to trigger the menu was being rendered relative to the document rather than to the tile. This, in turn, was because the component was being portaled to the document so that the displayed menu wouldn't be clipped by the tile. The fix is to separately portal the button that triggers the menu (relative to the tile) and the displayed menu itself (relative to the document).
=> fix: graph axis menus after resizing earlier rows

cypress/support/elements/clue/cCanvas.js, src/components/toolbar/tile-toolbar.tsx, src/components/toolbar/use-tile-toolbar-positioning.tsx, src/models/stores/configuration-manager.test.ts, src/models/stores/configuration-manager.ts
Followup work for PT-186143201.
Fix settings merge so that keys inside settings.table from base app config and unit, lesson configs will still be merged, lists of toolbar buttons will not attempt to be merged (only the more specific config that is defined will be used).
Moved toolbars floating elements to be inside the document "canvas", and add "hide" middleware that makes sure the toolbar is hidden when the tile it is attached to is scrolled out of view.
=> Avoid toolbar overflow and extra buttons

cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js, src/components/document/annotation-layer.tsx
PT Story: https://www.pivotaltracker.com/story/show/186419478
This PR fixes a bug where the document size limiting placement of sparrow parts (especially the text field) was inaccurate, causing the sparrows to acquire really awkward shapes. The underlying problem was that the annotation layer was determining document height by summing `TileRowModel.height`, but this number was not always accurate. In particular, rows with text tiles were often incorrect.
The solution was to look at the DOM elements of the rows and use their bounding boxes to determine height.
I don't think these changes should impact any cypress tests. The tests that are failing are timing out, so it's tough to tell what's going on, but before they were timing out it was just the usual suspects that were failing.
I'm …
=> 186419478 Fix Sparrow Document Limits

firebase-test/src/documents-rules.test.ts, firebase-test/src/setup-rules-tests.ts, firestore.rules
This uses the class_hash in the current user's token and compares it with the context_id in the document. 
The list of teachers in the documents is not updated when a co-teacher is added to the class, so this approach seems better. 
It would be better if the use of the list of teachers on a document was removed from these rules to keep them more simple. However there might be a use case which requires that. I can't think of one. Since it isn't currently possible to test these rules on QA before deploying them, it seems best to stay conservative and continue supporting both.
=> co-teachers can view documents, history, comments

cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/e2e/clue/branch/student_tests/shared_dataset_spec.js, cypress/support/elements/clue/DataCardToolTile.js, cypress/support/elements/clue/TableToolTile.js, src/components/tiles/table/table-tile.scss, src/components/tiles/table/table-tile.tsx, src/components/tiles/table/use-column-extensions.ts, src/components/tiles/table/use-columns-from-data-set.ts, src/components/tiles/table/use-grid-context.ts, src/components/tiles/table/use-rows-from-data-set.ts, src/components/vars.sass, src/models/data/data-set.ts, src/plugins/data-card/components/case-attribute.tsx, src/plugins/data-card/components/sort-area.scss, src/plugins/data-card/components/sort-card-attribute.tsx, src/plugins/data-card/components/sort-card.tsx, src/plugins/data-card/data-card-tile.scss, src/plugins/graph/components/background.tsx, src/plugins/graph/models/data-configuration-model.test.ts, src/plugins/graph/models/data-configuration-model.ts
PT Stories:
https://www.pivotaltracker.com/story/show/186170880
https://www.pivotaltracker.com/story/show/186170898
This PR adds the ability to synchronously highlight attributes between tables and datacard tiles.
- In tables, column selection is now handled in the dataSet.
- Because of this, it's now possible to deselect columns when cases are selected in other tiles.
A lot of styling has been improved, especially in the datacard tile, where editing now follows the design spec.
- I wasn't able to get table header cell edit styling quite right. The colored outline is reduced at the bottom. I spent some time trying to fix this but gave up. I think it would make sense to split this into a separate bug story. We might want to just have a styling cleanup story after all these highlight …
=> 186170880 Attribute Highlighting

.vscode/launch.json
This adds a configuration so that in the VSCode "Run and Debug" view, you can easily choose to launch the debugger on the Jest test that is in the editor window.
To do so, while the test  file is displayed in the editor, go to `View - Run`, set the pulldown menu at the top to `Debug test`, and click the 'Start debugger' button next to the pulldown menu.
If the editor is displaying a regular source file, it will try to find a similarly-named .test file.
=> Add a "Debug Jest test" launch config

src/models/mobx.test.ts, src/models/mst.test.ts
We are not using these features yet.
The flow test is useful for some planned changes to the ImageMap. The mobx flow and mst flow are different functions. But I believe they should work the same as what this test is checking. 
The scheduler test is useful for some planned changes to updateAfterSharedModelChanges, so it can use MobX tracking and still be paused during undo/redo.
=> tests of mobx scheduler and mst flow

src/clue/app-config.json, src/plugins/graph/components/attribute-label.tsx, src/plugins/graph/components/graph-axis.tsx, src/plugins/graph/components/graph-wrapper-component.tsx, src/plugins/graph/components/graph.tsx, src/plugins/graph/components/legend/legend.tsx, src/plugins/graph/hooks/use-graph-settings-context.ts, src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
This disables the drag-and-drop functionality within the graph, as described in PT-186472583
- A new setting is created `"attributeDnD": false` (default)
In the default state:
- Droppable zones do not render
- The draggable attributes and listeners are not passed to the AxisOrAttributeMenu
=> 186472583 disable xy dnd

src/plugins/graph/models/graph-model.ts
Fix for PT-186506561
Run the auto-assign method `configureLinkedLayer` after all dataset changes. This will catch cases where attributes are removed and re-created, and automatically assign the first two attributes after such events.
This restores the previous behavior from before multi-dataset changes, which was removed in error since it is important for tracking incoming data from Dataflow tile.
=> Do re-autoassignment of graph X & Y when needed

src/hooks/document-comment-hooks.test.ts, src/hooks/document-comment-hooks.ts
This removes the basically unused `useValidateCommentableDocument` hook. It was called, which did cause it to be warmed up. But the code in the onError was not being called so the document was not being created here.
This also removes an unused useDocumentHistory hook. The document history handling was moved into the model (tree-manager.ts) after this initial hook was added a while ago.
=> handle non-existing firestore documents

cypress/e2e/functional/teacher_tests/teacher_scrolling_spec.js, cypress/e2e/functional/tile_tests/shared_dataset_spec.js, src/components/tiles/table/table-tile.tsx, src/models/data/data-types.ts, src/plugins/graph/components/casedots.tsx, src/plugins/graph/components/dotplotdots.tsx, src/plugins/graph/components/scatterdots.tsx, src/plugins/graph/utilities/graph-utils.ts
PT Story: https://www.pivotaltracker.com/story/show/186386406
This PR adds cell highlighting in the graph tile.
- Cells highlighted in tables and values highlighted in datadecks will now cause the corresponding dots to highlight in linked xy plot tiles.
- Note that selecting an x axis cell will select all dots in the case, because all dots share that cell as their x values.
- Clicking a dot in an xy plot will now highlight that dot's y cell rather than the entire case.
- The exception to this rule is for units with the `dataset.cellsSelectCases` option set (currently only true for the `moth` unit). In this case, clicking a dot will still select the entire case.
=> 186386406 Graph Cell Highlighting

src/plugins/graph/components/graph.tsx
This makes it so the axis scale controls are only visible on numeric axes.
=> Only render EditableGraphValue if the axis is numeric

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/XYPlotToolTile.js, src/plugins/graph/components/editable-graph-value.tsx
This PR includes:
1. Adding `data-testid` for editable-box so that these elements can be accessed from the cypress tests in a straight-forward way.
2. Included tests to check for integer, decimal and string values in the edit boxes.
=> Added cypress tests for edit box in xy-plot axes

src/lib/db.ts
If we did this it would probably take care of some console errors which are probably reported by rollbar.
=> suggested improved document error handling

cypress/e2e/functional/tile_tests/tile_error_spec.js, package-lock.json, package.json, src/components/document/canvas.tsx, src/components/document/document-error.tsx, src/lib/db-listeners/db-other-docs-listener.ts, src/lib/db-listeners/db-problem-documents-listener.ts, src/lib/db.ts, src/lib/firebase.ts, src/plugins/error-test/README.md, src/plugins/error-test/error-test-content.ts, src/plugins/error-test/error-test-icon.svg, src/plugins/error-test/error-test-registration.ts, src/plugins/error-test/error-test-tile.scss, src/plugins/error-test/error-test-tile.tsx, src/plugins/error-test/error-test-types.ts, src/public/curriculum/example-curriculum/error-document.json, src/public/curriculum/example-curriculum/error-unit.json, src/register-tile-types.ts
We were getting CLUE crashes when tiles had rendering errors. Since these errors can happen in the thumbnails, without error handling it is hard to find them. 
A React error boundary is used to catch these errors at the document level. We could add an additional error boundary at the tile level so then the document could still be rendered and just the specific tile would show the error. However the whole document approach seems better to start.
Also a new ErrorTest tile is added to make it easier to demo and test this error handling.
You can see the error page with this with this link:
https://collaborative-learning.concord.org/branch/improve-error-handling/doc-editor.html?unit=./curriculum/example-curriculum/error-unit.json&document=curriculum/example-curriculum/error-document.json
=> Handle tile render errors

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/XYPlotToolTile.js, src/plugins/graph/adornments/plotted-function/plotted-variables/plotted-variables-adornment-component.tsx, src/plugins/graph/components/legend/multi-legend.scss, src/plugins/graph/components/legend/multi-legend.tsx, src/plugins/graph/components/legend/variable-function-legend.tsx, src/plugins/graph/components/legend/variable-selection.tsx
PT Story: https://www.pivotaltracker.com/story/show/186507040
This PR allows the user to plot multiple variable traces in a graph tile.
- Adds an "Add variables" button to the variables part of the graph legend, which adds another trace to the graph. There is no limit to the number of traces that can be graphed, including repeats.
- When there are at least two traces, an X button appears in the legend for each trace, which deletes that trace. No button appears when there is only one trace to ensure that each linked graph has at least one trace.
Implementation details:
- The new buttons reuse css used elsewhere in the graph legend, which required moving the css around a bit.
- The calculation for the height of the legend is improved a bit with this work, but it's still not great. I think …
=> 186507040 Multiple Variable Plots

cypress/e2e/cleanup/remove_teacher_comment_spec.js
Added wait to fix remove teacher comment failure in portal report.
This wait is required because of https://www.pivotaltracker.com/story/show/186702606. With the recent save and restore documents work, there is an intermediate screen that appears before the past state is restored which also causes the chat panel to not show up for the first second or two and then to show up. 
So, the code found the chat panel element length at that time and it was > 0 but after that chat panel was displayed in open mode by default. At that time, the chat panel element would not be available to click so the test was failing.
Error message in Cypress: “We initially found matching element(s), but while waiting for them to become actionable, they disappeared from the page.”
Adding this wait gives cypress time …
=> Added wait to fix failure

.vscode/settings.json, src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx, src/plugins/graph/components/casedots.tsx, src/plugins/graph/components/chartdots.tsx, src/plugins/graph/components/dotplotdots.tsx, src/plugins/graph/components/legend/layer-legend.tsx, src/plugins/graph/components/scatterdots.tsx, src/plugins/graph/components/simple-attribute-label.tsx, src/plugins/graph/hooks/use-point-locations.ts, src/plugins/graph/models/graph-model.test.ts, src/plugins/graph/models/graph-model.ts, src/plugins/graph/utilities/graph-utils.ts, src/utilities/color-utils.ts
PT Story: https://www.pivotaltracker.com/story/show/186487775
This PR updates how colors are handled in the graph tile.
- Colors from the design spec are now used rather than kelly colors.
- Within a graph, colors are assigned to attributes rather than the index of a plot. This means that an attribute's color won't change if you remove a plot above it, for example.
Implementation notes:
- I basically followed @bgoldowsky's suggested strategy for this work. The `GraphModel` manages colors via ids (which can be any type of ids, so will work for variable as well as data plots).
- However, the colors are not consistent between graphs.
- Right now, deleting a plot will not remove it from the list of colors, so the color will not be reused until going through all other colors, and if you bring …
=> 186487775 Graph Colors

src/plugins/graph/components/attribute-label.tsx, src/plugins/graph/components/legend/variable-selection.tsx, src/plugins/graph/components/simple-attribute-label.tsx, src/plugins/graph/graph-types.ts
PT Story: https://www.pivotaltracker.com/story/show/186569351
This PR fixes an issue identified while testing the above PT story. Previously, the chakra portals used for dropdowns in the graph tile would render below the tile's toolbar. Now these portals render above the toolbar.
=> 186569351 Make Graph Dropdowns Render Over Tile Toolbar

src/components/document/canvas.test.tsx, src/lib/auth.ts
Also fix an error thrown in the canvas test.
In some cases strings are thrown instead of Error objects. I think this makes the new code consistent with the old code. In that case it was rejecting the promise with a string. 
If you hide whitespace changes you can see the essence of the conversion to await.
=> switch to using await

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
The xy_plot_tool_spec needs to look for the newly configured buttons when testing runs on example-config-subtabs unit
=> xy_plot_tool_spec should test for link multiple dataset button

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, src/plugins/graph/models/graph-controller.ts
Fixes PT-186740258.
Testing notes:
- This bug is hard to replicate.  It seemed to happen most often in a brand new session - any cached or already-rendered content would avoid it.  With a brand new session, follow the replication instructions in the bug report.  It may take many tries before the bug can be observed.
Implementation notes:
- in the `GraphController`, there is a `handleAttributeAssignment` method that is called when attributes are assigned to a place on the graph, and also for all `autoAssignedAttributes` at graph initialization time.  This method previously had code that checked whether the attribute was in fact assigned to the given place, and if not, assigned it. This code did not account for the possibility of multiple Y attributes and would set the given attribute as …
=> autoassign fix

cypress/e2e/functional/tile_tests/data_card_tool_spec.js, cypress/e2e/functional/tile_tests/table_tool_spec.js, cypress/support/commands.js, cypress/support/elements/tile/XYPlotToolTile.js, src/hooks/use-link-consumer-tile-dialog.tsx, src/hooks/use-link-provider-tile-dialog.tsx
As requested in the latest designs and in PT-186566168, revises the wording in the dialog of the graph's "Add data" button, and in all of the linking buttons changes the "Unlink" button to "Clear It!".
=> Dialog wording changes

src/plugins/graph/adornments/plotted-function/plotted-function-adornment-model.ts
Addresses performance problems detailed in PT-186719712.
Makes `computePoints` and action which seems to avoid problems with extraneous reactions and history wrangling bogging down the response.
=> Variables plotting performance improvement

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/XYPlotToolTile.js, src/plugins/graph/adornments/plotted-function/plotted-function-adornment-component.scss, src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-component.tsx, src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables.scss
Implements PT-186610304.
A point is drawn on the trace of each variable pair added to a graph, showing the current value of those variables (if the variables both have a value). 
On mouseover, the trace and the point are highlighted, and a label showing the current values (rounded off) is shown.
=> Add variable-value readout point to graph

docs/unit-configuration.md
Attempting to address the lack of documentation of how toolbars (and other properties) of tiles can be configured, which ones have been updated to the new toolbar framework, etc.
Doc is viewable at: https://github.com/concord-consortium/collaborative-learning/blob/737f4aafd2af408779b83e28f8b2e92ab09b18ba/docs/unit-configuration.md
=> Tiles settings documentation

src/lib/db-listeners/db-student-personal-docs-listener.ts
This makes it so we only start listening to offering users' personal doc changes if a sort-work tab is specified for the unit we are in, as described in PT-186811130
=> 186811130 enable sort work listeners

package-lock.json, package.json, src/plugins/diagram-viewer/diagram-types.ts
PT Story: https://www.pivotaltracker.com/story/show/185855379
This PR updates the version of diagram-view used by CLUE. The updated version of diagram-view allows the user to zoom out more and also prevents the tile from panning when dragging nodes, which should prevent most cases where nodes are separated very far from each other.
=> 185855379 Increase Allowed Zoom Out and Prevent Panning while Dragging Nodes

README.md, src/components/document/doc-list-debug.scss, src/components/document/doc-list-debug.tsx, src/components/document/sort-work-view.scss, src/components/document/sort-work-view.tsx, src/components/thumbnail/thumbnail-document-item.tsx, src/lib/debug.ts, src/models/document/document.ts
PT-186631894 _Draft_
For units with Sort Work tab enabled for students, this will apply the privacy "eyeball"  as needed according to user role, and the type and share setting of each document. 
It also moves the `sortWork` debug render function to its own component, changing the debug flag to the more general `DEBUG_DOC_LIST` and the key to `docList`
(It used to be `DEBUG_SORT_VIEW` and the key was `sortView`)
=> 186631894 sort work for students with isPrivate calc

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, src/plugins/graph/graph-types.ts, src/plugins/graph/models/graph-model.ts, src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-model.ts
Adjust autoscaling rules as per PT-186819809.
* x variable default range changed to 0 to 10 (when there are no data points or variables)
* 'Fit all' button behavior adjusted to match autoscaling behavior - clicking 'Fit' should not change how the graph is scaled if the graph has already been auto-scaled.  The new behavior always shows the range `[0 - 2*value]` for all variable values
=> autoscale adjustments

cypress/e2e/functional/tile_tests/dataflow_tool_spec.js, cypress/e2e/functional/tile_tests/simulator_tile_spec.js, src/plugins/dataflow/model/utilities/virtual-channel.ts
PT-186872441
This brings the hard coded `fastBoil` temp series back into the Sensor block as an option.  This data was created originally for this purpose, and was then taken out of the temperature sensor directly, (and eventually used instead in the Sim tile).  Now it is available in both places.
=> bring demo temperature data back in as an option on temp sensor

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, src/plugins/graph/components/legend/layer-legend.tsx, src/plugins/graph/components/simple-attribute-label.tsx, src/plugins/graph/imports/components/axis/components/axis-or-legend-attribute-menu.tsx
PT Story: https://www.pivotaltracker.com/story/show/186472564
This story prevents the user from removing the attribute from the x axis or only y axis of an xy plot tile (y attributes can be removed until there's only one left). It's also now possible to assign the same attribute to the x and y axes, which will make it easier for the user to switch axes.
Please note that this story only applies to the CLUE style legend. This story does not impact units that use the old CODAP style axis labels (like `moth`).
=> 186472564 XY Plots Always have Both Axes

cypress/e2e/functional/portal_user_tests/teacher_report_spec.js, src/lib/auth.ts, src/utilities/auth-utils.test.ts, src/utilities/auth-utils.ts
This way the student or teacher can reload the page even after the token has expired.
This also changes the OAuth2 code to use replaceState instead of pushState
=> Rewrite URL with OAuth2 params

src/utilities/loading-utils.ts
The authoring system and standalone document editor do not
initialize the loadingMeasurements object.
It seems like there is no need for them to record these measurements anyhow.
=> ignore loading measurements in standalone documents

src/models/document/base-document-content.ts, src/models/document/document-content-import.ts, src/models/document/document-content-tests/dc-shared-models.test.ts, src/models/document/drag-tiles.test.ts, src/plugins/diagram-viewer/diagram-content.test.ts, src/plugins/diagram-viewer/diagram-content.ts
There were 2 issues with old approach:
1. the shared models were added to the document after the tiles
2. the tiles were created independently from the document
The core problem with both issues is that references in the tiles to shared model objects could not be resolved.  The solution for `#1` was to first add the content of the shared models to the doc, then the tiles, and then the tile references.  The solution for `#2` required refactoring the import code so the tiles would be created within the content by passing the snapshot of the tile to `tileMap.put`.
The refactored import code replaces some deeply nested calls to `add*` methods in BaseDocumentContent. These `add*` methods could not be removed because they are still be used in other places. This does mean there is some …
=> fix importing tiles with shared model refs

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, cypress/support/elements/tile/DiagramToolTile.js, src/plugins/graph/adornments/adornment-models.ts, src/plugins/graph/components/graph-wrapper-component.tsx, src/plugins/graph/models/data-configuration-model.ts, src/plugins/graph/models/graph-layout.ts, src/plugins/graph/models/graph-model.ts, src/plugins/shared-variables/graph/plotted-variables-adornment/plotted-variables-adornment-model.ts
Per PT-186266962, allows all data and variable traces on the graph tile to participate in Sparrow annotation.
In addition, fixes a bug where changing the axis scale would not correctly adjust the sparrow endpoints.
- This was accomplished by adding `graph-wrapper-component` lines 52--57.  I'm not thrilled with this solution, let me know if you have a better suggestion.
=> Sparrows can connect to all graph traces

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js
This change fixes a test failure noticed on master due to the test attempting to click a toolbar button (`link-tile`) that is not configured in the unit it's currently pointing to.
This changes it to use `link-tile-multiple`, and then updates some values in the test since that button operates differently and leaves the table connected.
=> Update name of toolbar button to fix test

docs/launch-sequence.md, src/cms/document-editor.tsx, src/components/app.tsx, src/doc-editor.tsx, src/index.tsx, src/initialize-app.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/lib/db.ts, src/lib/misc.ts, src/lib/portal-api.ts, src/models/curriculum/unit.test.ts, src/models/curriculum/unit.ts, src/models/stores/stores.ts, src/models/stores/ui.ts
This includes several changes:
- make sure that loadUnitAndProblem is only called once. This replaces the logic that was checking if the portal offering had a different unit than the initial unit.
- make initializeApp synchronous. It no longer needed to be async, with this change some code could be simplified
- move the code that needed the problem to be loaded into `loadUnitAndProblem`. Including initializing the logger, configuring rollbar, and setting the page tile. Now that `loadUnitAndProblem` is only called once, moving this code simplified things.
- improve error handling by showing stack of original error
- require a unit and problem to be set on CLUE URLs in the portal
- add tests for the fake offering ids, this identified a case which might cause problems. I didn't want grow the …
=> on teacher launch, don't load default unit

src/plugins/data-card/components/sort-area.tsx
This addresses the bug described in PT-187055825.  Dragging a Data Card off its current stack and on to "nothing" was causing the card to take on an empty string value for the current sort attribute.  This prevents that from happening.
=> only complete attribute change if there is a draggedToValue defined

src/models/stores/persistent-ui.ts, src/models/stores/workspace.ts
[[PT-187087979]](https://www.pivotaltracker.com/story/show/187087979)
Shows the bug:
https://collaborative-learning.concord.org/branch/master/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=student:2&unit=example-config-subtabs&problem=1.1
Shows the fix:
https://collaborative-learning.concord.org/branch/fix-comparison-mode/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=student:2&unit=example-config-subtabs&problem=1.1
Note that the fix is only applied on initial load of the `PersistentUI` from firebase, so it shouldn't affect the behavior of bookmarks mode or comparison mode beyond that.
=> fix: clear comparison mode on initial load of `PersistentUI` to fix layout bug

src/models/stores/sorted-documents.ts
Fulfills this ticket
[**[Exemplar]** Multiple Teachers should show with different names in name sort](https://www.pivotaltracker.com/n/projects/2441242/stories/187042217)
________________________________________________________________________
Deployed Link
https://collaborative-learning.concord.org/branch/exemplar-multiple-teachers-should-show-2/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=teacher:1&unit=example-config-subtabs&problem=1.1
=> 187042217-exemplar-multiple-teachers-should-show

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/XYPlotToolTile.js
Added a test to cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, for duplication of a graph that was linked to a Data Card, rather than to a Table (as in a previous test).
Added a very simple 'linkDataCard' method, which is used by that test, to cypress/support/elements/tile/XYPlotToolTile.js.
=> Added test of duplicating a graph associated with a Data Card, not a Table

cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, cypress/support/elements/common/ResourcesPanel.js, cypress/support/elements/common/SortedWork.js
This PR expands on the Sort Work tab tests that were previously written. There were a few TODOs (added as a comment in the spec) in the spec file that @dennisrcao had added when he initially wrote the tests. This PR addresses some of those TODOs (and removed the TODO comment pertaining to those). 
Specifically, this PR addresses the tests for the teacher Sort Work view updationss when students join and leave groups. It also checks student problem and personal documents in the sort work view, where they show up and when opened, whether or not they're editable.
=> Added Sort Work tab cypress tests for testing student groups

src/hooks/use-document-caption.tsx
PT-187080552
- adds the display of the teacher name to the title under thumbnails in my work for teacher support publications published to all classes.  
- this is achieved by removing the special casing for rendering the "caption" when the document is a `SupportPublication` (the type created when publishing to all classes)
=> 187080552 teacher name prefix

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Merge of #2206 broke a Cypress test that was added on another branch - default naming of data cards changed.
This fixes the error and allows the tests to pass again.
=> Fix cypress test failure due to merge

src/plugins/graph/utilities/graph-utils.ts
We were seeing rollbars errors from `setPositions`. From the docs about `end()`, it looks like it is legitimate for the resulting promise to be rejected if the transition is canceled or interrupted. My guess was that some animation was getting interrupted during loading because something in the graph state was changing. 
We were able to reproduce the error only by switching to the teacher from the rollbar error and running the teacher report for this particular assignment. The error did reproduce when running CLUE on localhost. We noticed that the number of errors generated locally would vary from reload to reload. From the error information we could tell that the errors were coming from multiple instances of the graph tile. And it seemed like they were coming from multiple documents …
=> fix rollbar errors from setPositions

.github/workflows/ci.yml
This change tells GitHub the branch was deployed, and it adds a new deployment section to the PR. If you click the "Show environments" link you'll find a "View deployment" button which will open the CLUE demo page for the PR's branch. 
More info can be found in this PR:
https://github.com/concord-consortium/starter-projects/pull/72
=> add deployment url

src/models/image-map.test.ts, src/models/image-map.ts
PT-187179232
This approach is still fragile. It would be better to only allow localAssets in specific cases. And then we could require the image urls have a protocol which will make the pattern even less likely to be falsely identified.
Also there are two different tests for image urls. One is in the image map. The other is in data-types.ts. The test in data-types.ts is much more strict, but it likely prevent cases where an image is dragged from another page into CLUE.
=> make image url match more strict

cypress/e2e/functional/tile_tests/dataflow_tool_spec.js, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/components/ui/dataflow-drop-zone.tsx, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/nodes/dataflow-node-plot.tsx, src/plugins/dataflow/nodes/node-editor-mst.ts, src/plugins/dataflow/nodes/utilities/view-utilities.ts
- when a node is dragged and dropped from the toolbar, create it in the drop location
- when a node item on the toolbar is clicked, add it to a unique position
- when a node is dragged update the position in its MST model
- when the tile is loaded translate the nodes into the position based on the MST model
- update the origin of the Rete canvas so it starts at 0,0 instead of the center of the diagram
- remove an extraneous console log
=> handle node positions

src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/nodes/base-node.ts, src/plugins/dataflow/nodes/control-node.ts, src/plugins/dataflow/nodes/controls/demo-outputs/humidifier-animation.tsx, src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx, src/plugins/dataflow/nodes/controls/input-value-control.tsx, src/plugins/dataflow/nodes/controls/num-control.tsx, src/plugins/dataflow/nodes/controls/num-units-control.tsx, src/plugins/dataflow/nodes/controls/value-control.tsx, src/plugins/dataflow/nodes/counter-node.ts, src/plugins/dataflow/nodes/demo-output-node.ts, src/plugins/dataflow/nodes/generator-node.ts, src/plugins/dataflow/nodes/live-output-node.ts, src/plugins/dataflow/nodes/logic-node.ts, src/plugins/dataflow/nodes/math-node.ts, src/plugins/dataflow/nodes/node-editor-mst.ts, src/plugins/dataflow/nodes/service-types.ts, src/plugins/dataflow/nodes/timer-node.ts, src/plugins/dataflow/nodes/transform-node.ts, src/plugins/dataflow/nodes/utilities/view-utilities.ts
Making readOnly mode work required several changes
`tick` and `process` were stopped from running in readOnly mode, this way only the editable tile should be updating the state of the tile model. This is a change from Rete v1. In that old approach we were ticking and processing the nodes even in readOnly mode.
With `process` it means all nodes and controls needed to be updated so the controls can display the right thing even without the node's `data` method being called. The approach is to save more information in the Node's MST model and update the controls and control components so they can observe this state and update appropriately.  For simple nodes like the Math and Logic nodes, this means they needed to store their two input values into their MST model. This way the readOnly view …
=> readOnly Data flow support

cypress/e2e/functional/tile_tests/dataflow_tool_spec.js, cypress/e2e/functional/tile_tests/simulator_tile_spec.js, src/plugins/dataflow/nodes/base-node.ts, src/plugins/dataflow/nodes/controls/value-with-units-control.sass, src/plugins/dataflow/nodes/controls/value-with-units-control.tsx, src/plugins/dataflow/nodes/generator-node.ts, src/plugins/dataflow/nodes/rete-manager.tsx, src/plugins/dataflow/nodes/rete-scheme.ts, src/plugins/dataflow/nodes/sensor-node.ts
PT-187382896
Changes:
- add ValueWithUnitsControl
- use ValueWithUnitsControl in sensor node
- reset the graph when the sensor or sensorType changes
- lookup the decimal places and units from the NodeSensorType instance
- re-enable the cypress tests that are looking at the sensor value
- remove valueControl instance variable from generator node
=> add value and plot to sensor

src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/nodes/engine/dataflow-engine.ts, src/plugins/dataflow/nodes/engine/dataflow.ts, src/plugins/dataflow/nodes/engine/readme.md, src/plugins/dataflow/nodes/engine/utils/cache.ts, src/plugins/dataflow/nodes/node-editor-mst.ts, src/plugins/dataflow/nodes/rete-manager.tsx
This combines all of the changes made during the onTick and data methods of each node into a single MST action.
It was necessary to fork our own version of the rete dataflow engine which runs synchronously to make this work properly.
The multiple changes per tick caused several negative effects:
- multiple history events were created each tick. The history code gets slower the more history events there are, so this caused a slow down.
- multiple react renders were triggered one for each MST change was completed.  This caused a lot of overhead for each change.
- more storage was needed since there is a wrapper around each of the history events
- the snapshot changes triggered network updates to store the document content.
=> optimize Dataflow tick

src/lib/debug.ts, src/models/tiles/tile-model.ts, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/nodes/base-node.ts, src/plugins/dataflow/nodes/control-node.ts, src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx, src/plugins/dataflow/nodes/controls/input-value-control.tsx, src/plugins/dataflow/nodes/controls/num-control.tsx, src/plugins/dataflow/nodes/controls/num-units-control.tsx, src/plugins/dataflow/nodes/dataflow-node-plot-types.ts, src/plugins/dataflow/nodes/dataflow-node-plot.tsx, src/plugins/dataflow/nodes/demo-output-node.ts, src/plugins/dataflow/nodes/generator-node.ts, src/plugins/dataflow/nodes/live-output-node.ts, src/plugins/dataflow/nodes/logic-node.ts, src/plugins/dataflow/nodes/math-node.ts, src/plugins/dataflow/nodes/number-node.ts, src/plugins/dataflow/nodes/rete-manager.tsx, src/plugins/dataflow/nodes/sensor-node.ts, src/plugins/dataflow/nodes/service-types.ts, src/plugins/dataflow/nodes/timer-node.ts, src/plugins/dataflow/nodes/transform-node.ts
- replace the onTick method on nodes with an inTick flag in services. This way nodes have access to the most recent input values during their tick code. This is because the data code is called in the order of input nodes to output nodes while the onTick was called in the insertion order of the nodes. Additional output nodes needed to make sure their data method was called first before the tick code, and previously this was not the case.
- now process is called on every tick so it isn't necessary for nodes to indicate if a tick should be trigger a reprocess
- add dataflow debug option which includes warnings when state might be changed incorrectly
- have the playback always run in readOnly mode, this way the code in node data functions should not update any state in the snapshot copy
- add …
=> process in read only mode too

docs/dataflow.md, src/plugins/dataflow/model/utilities/node.ts, src/plugins/dataflow/nodes/control-node.ts, src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx, src/plugins/dataflow/nodes/demo-output-node.ts, src/plugins/dataflow/nodes/generator-node.ts, src/plugins/dataflow/nodes/live-output-node.ts, src/plugins/dataflow/nodes/logic-node.ts, src/plugins/dataflow/nodes/math-node.ts, src/plugins/dataflow/nodes/sensor-node.ts, src/plugins/dataflow/nodes/transform-node.ts
- switch to passing the setter to the DropdownListControl instead of having it figure it out automatically
- the live output now:
- updates its hubSelect value when the user changes the liveOutputType
- uses the deviceFamily and sharedVariable when updating the hubSelect
- updates the hub select options when the liveOutputType is changed
- the requiresSerial check now takes into account the hubSelect value
- the "Physical Gripper" value of the hubSelect has both a device and noDevice view. This way the hubSelect value doesn't have to be changed when an arduino is connected or disconnected, instead just the view changes.
=> update live output node to not update state on tick

README.md, src/components/doc-editor-app.tsx, src/models/mst.test.ts, src/models/stores/stores.ts, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/components/dataflow-tile.tsx, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/nodes/live-output-node.ts, src/plugins/dataflow/nodes/rete-manager.tsx, src/plugins/dataflow/nodes/service-types.ts, src/utilities/url-params.test.ts, src/utilities/url-params.ts
- remove `runnable` flag that was used for curriculum mode, now they behave the same as a readOnly document
- add `readOnly` param to doc-editor for testing
- update url params to handle booleans more generically
- a false value for a url param is now treated as false
- fix a error thrown when a problem doesn't have a teacher guide
=> handle curriculum mode better

src/models/stores/serial.ts, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/model/utilities/channel.ts, src/plugins/dataflow/model/utilities/simulated-channel.ts, src/plugins/dataflow/nodes/rete-manager.tsx, src/plugins/dataflow/nodes/sensor-node.ts
- add new sensorDisplayName prop to sensor nodes so readOnly views can show the correct option in the sensor dropdown menu
- add code to compute a nice looking name when we don't have a displayName
- only show the extra sensor option as missing if we are not readOnly
- move updateChannels to rete manager
- add back missing code which updates channel status on each tick
- fix a spelling mistake of lastMessageRecievedAt
=> handle readOnly sensor names

src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/nodes/rete-manager.tsx
- This make sure the playbackReteManager is created even if the program component is never updated.
- Also deletes extra console.log
=> create playbackReteManager on load too

src/plugins/dataflow/model/dataflow-content.ts, src/plugins/simulator/model/simulator-content.ts
PT-187558259
This makes it so a user's Sim will always connect attach to the first local shared program model that is connected to an existing Dataflow title.  This allows a user to reconnect a sim to a new dataflow tile if its original program's tile is deleted.
=> 187558259-reconnect-sim-to-program

src/cms/document-editor.tsx, src/components/doc-editor-app.tsx, src/components/document/document-annotation-toolbar.tsx, src/models/stores/app-config-model.ts
- the controls will only be shown if they are enabled in the unit.
- the doc editor's dom elements were updated so the existing css for the annotation controls would apply
- the logic for determining if the controls should be shown was moved so it could be shared.
=> show annotation controls in doc editors

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, cypress/support/elements/tile/DataflowToolTile.js, src/components/doc-editor-app.tsx, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/components/dataflow-tile.tsx, src/plugins/dataflow/model/dataflow-content-test-constants.ts, src/plugins/dataflow/model/dataflow-content.test.ts, src/plugins/dataflow/model/dataflow-content.ts, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/model/utilities/recording-utilities.ts, src/plugins/dataflow/nodes/rete-manager.tsx
This also fixes the translation of the dataflow canvas. Previously the translation of the canvas was not saved in state unless the user also zoomed the program canvas. With this change the translation is now saved even if the user doesn't zoom the program canvas.
PT-186813616
PT-187581801
=> add sparrows to dataflow tile

src/plugins/dataflow/components/dataflow-tile.tsx, src/plugins/dataflow/dataflow-registration.ts
This fixes an issue that was happening with the latest version of Chrome.
When a block within a Dataflow tile was dragged it would move a couple of pixels and then the whole Dataflow tile would start to be dragged.
CLUE has a mechanism for saying that drag events should be ignored unless they are on the specific drag handle of the tile. Dataflow was trying to use this mechanism, however it was not working. The main issue only showed up in the latest Chrome, however it was possible to see that drag events which should have been ignored were causing tile dragging in older versions of Chrome.
The mechanism CLUE uses for tiles to say only their drag handle should be draggable, is by adding the `disable-tile-content-drag` class to an element. The tile dragging code listens for drag events on …
=> move disabled tile content dragging to tile element

cypress/e2e/functional/tile_tests/drawing_tool_spec.js, src/lib/logger.ts
This demonstrates how to drive the UI with Cypress and then verify that a log event is recorded.
I don't find the code very nice looking though. There are a lot of strings that will be easy to type wrong. So probably this should be moved into a helper function which can encapsulate all of the strings. 
However, it is probably good to merge this as is so it is available when someone wants to check log messages. And we can refactor it once we have a few more examples.
=> A demo of testing for a log event

.github/workflows/ci.yml
This uses the new `concord-consortium/s3-deploy-action/deploy-path@v1` action which was added here:
https://github.com/concord-consortium/s3-deploy-action/pull/403
Readme doc on it is here: https://github.com/concord-consortium/s3-deploy-action?tab=readme-ov-file#deploy-path-only-action
The basic changes are:
- the build job now figures out the deployPath first
- the build job then passes this deployPath as the DEPLOY_PATH environment variable when running the webpack builds. 
- after the build is completed the whole `dist/` folder is uploaded as an "artifact"
- the s3-deploy job now downloads this artifact.
- the s3-deploy job no longer needs to install any dependencies or build anything.
- by default the s3-deploy-action will try to run `npm run build` so this is overridden with no op …
=> build with the new deploy-path action

src/models/mst.test.ts, src/plugins/graph/adornments/adornment-models.test.ts, src/plugins/graph/adornments/adornment-models.ts
In the process of this change I also found that preProcessSnapshot has some nuance on how it works.
When `prop: types.maybe(Model)` is used, then it undefined is passed to preProcessSnapshot.
To respect the `types.maybe`, preProcessSnapshot has to return undefined.
=> convert null to NaN in the graph Point model

docs/document-types.md, src/models/document/base-document-content.ts, src/models/document/document-content-import.ts, src/models/document/document-content-tests/dc-general.test.ts, src/models/document/document-content-tests/dc-shared-models.test.ts, src/models/document/document-content-tests/dc-test-utils.ts, src/models/document/document-content-with-annotations.ts, src/models/document/document.ts, src/models/document/drag-tiles.test.ts, src/models/document/tile-row.ts
- This changes the loading to manipulate the snapshot instead of a temporary MST document
- It also updates the general document loading to run `typecheck` if there is an error while
loading the document. This results in better error messages when the document is corrupt.
- It updates the dc-general.test.ts to check the structure of the document using a
representation of all of the rows of the document instead of a collection of methods.
A side effect of the loading change is that fewer ids are created, so the tests which compare
snapshots with ids had to be updated.
=> improve exported content loading

.vscode/launch.json, docs/cms.md
Updates `launch.json` to have the default for starting the VSCode debugger be the standalone document editor. This is a very convenient way to debug since a document can be stashed in local storage and the read-only views can be configured either on or off as needed.
Updates `cms.md` to fix lint complaints and provide more explicit guidance on testing the authoring environment with the Git proxy.
=> Doc & debug updates

cypress/e2e/functional/tile_tests/datacard_merge_spec.js, src/plugins/data-card/data-card-tile.tsx
[#187848992](https://www.pivotaltracker.com/story/show/187848992)
We determined that simply dropping the drag-to-merge data cards feature was the solution for this. These changes:
- Remove all code related to dragging and dropping data cards into one another
- Update the data card tests to use the "Add Data from..." button instead of dragging to merge data cards. Note that the ability to drag-to-merge a data card from another document will be lost, so I removed the test related to that. (Students will still be able to drag a data card into their document from another document, and then merge it with other data cards by using the "Add Data from..." button.)
=> fix: Issue with combining  data card stacks via drag and drop (PT-187848992)

.github/workflows/ci-regression.yml, .github/workflows/ci.yml, .github/workflows/manual-regression.yml, .github/workflows/regression-daily.yml, cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, cypress/support/elements/common/cHeader.js, dependencies-notes.md, package-lock.json, package.json
This has two changes:
1. This is to fix this failure that has happened a few times now:
https://github.com/concord-consortium/collaborative-learning/actions/runs/9720002467/job/26830753417
The fix is to make the test retry-able by clearing the data at the beginning of the test, and also add a short delay to give more time for firebase to store the change of the group. 
2. add the user arg to all of the other containers used in the cypress github jobs. This arg was added to one a little while ago, but I forgot to add it to all of them.
=> Cypress updates

cypress/e2e/functional/document_tests/canvas_test_spec.js, cypress/e2e/functional/document_tests/copy_doc_test_spec.js, cypress/e2e/functional/document_tests/student_teacher_4up_readonly_spec.js, cypress/e2e/functional/document_tests/tiles_copy_test_spec.js, cypress/e2e/functional/tile_tests/geometry_table_integraton_test_spec.js, cypress/e2e/functional/tile_tests/geometry_tool_spec.js, src/components/document/document-content.tsx, src/components/toolbar.tsx, src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-general.test.ts, src/models/document/document-content-types.ts, src/models/document/document.test.ts, src/models/tiles/geometry/geometry-registration.ts, src/models/tiles/tile-content-info.ts
PT-185538860
When a Geometry tile is created, it will no longer create a text tile.
Since we're not planning to bring this functionality back for any tile type, simplify the code by removing the concept of 'sidecar' tile creation entirely.
=> No sidecar tile for geometry

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, src/plugins/graph/models/graph-controller.ts
[187934814](https://www.pivotaltracker.com/story/show/187934814)
Adds an additional check when determining if the axis bounds should be automatically reset to the defaults when `setupAxis` is called in the graph controller's `handleAttributeAssignment` function. If the current layer is editable, the bounds are not changed.
=> fix: Adding manual points causes axes to autoscale (PT-187934814)

docs/bookmarks.md
While working on the design for the new sort work tab UI, I needed to review how bookmarks (stars) work in CLUE. So I took the time to update the docs a bit. 
PT-187943086
=> update bookmark documentation

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, cypress/support/elements/tile/ArrowAnnotation.js, src/components/document/annotation-layer.tsx, src/components/document/document-annotation-toolbar.tsx, src/components/toolbar.tsx, src/public/demo/units/qa-config-subtabs/content.json
Exit annotation mode when user clicks the 'select' toolbar button (in addition to other toolbar buttons which already did so); uses the ESC key; or double-clicks anywhere that is not an active annotation button.
=> Add ways to exit annotation mode

src/components/tiles/geometry/geometry-content.tsx, src/components/tiles/geometry/geometry-toolbar-registration.tsx, src/models/tiles/geometry/geometry-content.ts
PT-187995444
Consider circles as well as points when scaling to fit in the geometry tile.
Also fit 2 lint errors in geometry tile
=> Geometry scale to fit circles

cypress/e2e/functional/document_tests/canvas_test_spec.js, cypress/e2e/functional/document_tests/tiles_copy_test_spec.js, cypress/e2e/functional/tile_tests/diagram_tool_spec.js, cypress/e2e/functional/tile_tests/geometry_table_integraton_test_spec.js, src/assets/icons/drag-tile/move.svg, src/assets/icons/resize-tile/expand-handle.svg, src/components/document/tile-row.tsx, src/components/tiles/tile-component.scss, src/components/tiles/tile-component.test.tsx, src/components/tiles/tile-component.tsx, src/models/tiles/text/text-registration.ts, src/plugins/dataflow/dataflow-registration.ts, src/plugins/diagram-viewer/diagram-registration.ts, src/plugins/drawing/drawing-registration.ts, src/plugins/graph/graph-registration.ts, src/plugins/simulator/simulator-registration.ts
This is "option 2" as described in the comments of PT-187924942.  As part of fixing resizing for touch devices, It removes the ability for any tiles to be dragged except by their drag handles.
Previously, "drag tile from anywhere" was supported on _Data Deck, Expression, Geometry, Image, Numberline, and Table_, but not supported (only dragging the handle would work) on _Text, Dataflow, Diagram, Drawing, Graph, or Simulator_.  Handlers were at the tile level but optionally checked whether the event target was the drag handle.  After this PR, only the handle is supported and it has the event handlers specified directly on it. This avoids overlapping with the 'resize' drag handlers.
Drag and resize handles are increased in size so that they are easier to use on touch devices, visual feedback …
=> Make tile resizing work on touch devices

cypress/e2e/functional/document_tests/copy_doc_test_spec.js, cypress/e2e/functional/document_tests/exemplar_test_spec.js, cypress/e2e/functional/document_tests/student_teacher_4up_readonly_spec.js, cypress/e2e/functional/document_tests/tiles_copy_test_spec.js, cypress/e2e/functional/teacher_tests/history_playback_spec.js, cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, cypress/e2e/functional/tile_tests/drawing_tool_spec.js, cypress/support/elements/tile/DrawToolTile.js, src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/components/selection-drawing-tool.tsx, src/plugins/drawing/objects/drawing-object.tsx, src/plugins/drawing/objects/ellipse.tsx, src/plugins/drawing/objects/group.tsx, src/plugins/drawing/objects/image.tsx, src/plugins/drawing/objects/line.tsx, src/plugins/drawing/objects/rectangle.tsx, src/plugins/drawing/objects/text.tsx, src/plugins/drawing/objects/vector.tsx, src/plugins/shared-variables/drawing/variable-object.tsx
This PR is mostly a big search-and-replace that uses `PointerEvent`s rather than `MouseEvent`s to draw, thus allowing drawing on touch devices like the iPad and touchscreen Chromebooks.
Some mild refactoring in Cypress tests so that the events used are not in so many different places.
One slight complication is the need to separately `stopPropagation` on `touchStart` and `mouseDown` in order to prevent the `TileComponent` from interpreting these as tile selection.  It listens for both of these rather than Pointer events, and if propagation is not stopped, as you use shift-click to select multiple drawing objects, the tile keeps switching between selected and deselected.
=> Allow drawing with touch events

src/components/document/canvas.scss, src/plugins/graph/models/graph-model.ts
Adds the manual resizing option to graphs as per PT-186813262 .
This caused a Cypress test to fail due to the resizing border of the tile having a higher z-index than a Chakra portal dialog. Addressed this by following  @kswenson 's suggestion to introduce a stacking context.
=> Allow user resizing of graph

scripts/ai/download-documents-with-info.ts, scripts/ai/update-metadata.ts
[#188001508](https://www.pivotaltracker.com/story/show/188001508)
Documents downloaded using download-documents-with-info.ts will now get a visibility property set, and update-metadata.ts will add this property when updating metadata. This will allow us to get the information we need to identify documents as private in the new sort views.
=> feat: add visibility property and values to metadata (PT-188001508)

cypress.config.ts, cypress/e2e/functional/document_tests/student_test_spec.js, cypress/support/elements/common/SortedWork.js, functions/src/shared.ts, src/components/thumbnail/simple-document-item.scss, src/components/thumbnail/simple-document-item.tsx, src/models/document/document-utils.ts, src/models/document/document.test.ts, src/models/document/document.ts
[#188001508](https://www.pivotaltracker.com/story/show/188001508)
Use metadata documents' new `visibility` property to render private documents differently than public documents in the sort work UI.
=> feat: Filter All retains Shared State (PT-188001508)

src/clue/clue.sass, src/components/document/document.scss
Fixes PT-188092179.
When space is narrow, the second button wrapped under the first and was not displayed.
=> Avoid row of buttons in toolbar wrapping

functions/src/shared.ts, src/lib/db-types.ts, src/lib/db.ts, src/models/document/document.ts, src/models/history/tree-manager.ts
[#188066940](https://www.pivotaltracker.com/story/show/188066940)
Create a new Firestore metadata document for any new document when that document is created.
Metadata for certain document types (planning, problem, published problems, and published supports) will have investigation, problem, and unit information included.
=> feat: Create Firestore metadata document when users create new documents (PT-188066940)

firebase-test/src/documents-rules.test.ts, firestore.rules
There are cases in the code where a teacher tries to read comments on a document that doesn't have a metadata document. This was causing an Firestore access error.
Also this fixes an issue where the built in `exists` function from Firestore rules was being overwritten by our own function.
=> fix reading of comments when there are none

firebase-test/src/class-rules.test.ts, firestore.rules
- the network field is optional now
- if a teacher wants to update the network field we'll just let them now since it is being phased out
- when reading a class doc its allowed to request an non-existent doc
- when reading a class doc the list of teachers in the existing doc is checked not the list of teachers in the request (which doesn't exist for a read).
this last bug looks like it has been there since the beginning
=> fix issues in class rules

scripts/ai/clean-docs-without-metadata.ts, scripts/ai/download-documents-with-info.ts, scripts/ai/update-class-metadata.ts, scripts/ai/update-metadata.ts, scripts/lib/script-utils.ts
Handle production doc issues
- url parsing didn't work with certain characters, need to use `new URL` instead
-  handle missing offerings in documents
- handle missing metadata which meant a missing type
- do a single update call instead of 3 to speed things up
- only read offering info one time to speed things up
- don't add teachers array to new documents. This array isn't needed anymore and it contained the wrong data.
Find and delete docs without general metadata
=> 188192669-update-migration-scripts

cypress/e2e/functional/tile_tests/geometry_tool_spec.js
Reverts concord-consortium/collaborative-learning#2360
Oh no! It looks like when the code was merged into master, the length of one of the polygons defaulted to 4.9 instead of 5.0. I’ve always been concerned about something like this happening in CLUE and am wondering if it’s possible to test on the Cloud before merging. In the meantime I'll ask John for help on how to resolve these kinds of issues.
=> Revert "Automation for Creating Polygons from Existing Points"

functions-v2/src/at-midnight.ts
According to the FB docs a schedule function like this is triggered by
an http request. And http request functions can run up to 60 minutes.
=> try to increase timeout to 30 minutes

firestore.rules, src/clue/components/clue-app-header.tsx, src/lib/db.ts, src/lib/firebase.test.ts, src/lib/firebase.ts, src/lib/firestore.test.ts, src/lib/firestore.ts, src/lib/root-id.ts, src/models/stores/user-context-provider.ts
This PR started as a change to use a random id in local storage for the root id when the appMode is dev. However that approach couldn't be finished because the Firebase functions needed to be updated. That incomplete work was split out into its own PR: https://github.com/concord-consortium/collaborative-learning/pull/2407
What remains in this PR is:
- a refactoring of the code to get the root id which is used in both Firestore and the Realtime database.
- relaxing the Firestore rules so we can implement the random id behavior in the future. The Realtime database have been relaxed like this since the beginning. 
**Historical Options**
When this PR included the local random id, the following options were considered for dealing with the problem of the broken functions.  See …
=> refactor firebase root id computation

cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, src/components/document/doc-list-debug.tsx, src/components/document/document-group.tsx, src/components/document/sort-work-view.tsx, src/components/document/sorted-section.tsx, src/components/thumbnail/simple-document-item.tsx, src/models/stores/document-group.test.ts, src/models/stores/document-group.ts, src/models/stores/sorted-documents.test.ts, src/models/stores/sorted-documents.ts, src/utilities/sort-document-utils.ts
- remove unnecessary DocumentContext around SimpleDocumentItem
- switch usage of IDocumentMetadata to IDocumentMetadataModel (the MST model)
- add disposer for the metadata docs watcher
- make SimpleDocumentItem an observing component so it updates when the visibility changes.
- update tests to work with the new metadataDocsFiltered property
- update sorted-documents to have two MST models for the filtered and withoutUnit metadata docs. These models are kept in sync with the Firestore query results.
- update the queries to use Firebase `onSnapshot` listeners instead of just calling `get`
- have the `onSnapshot` listeners merge the exemplar docs and then apply the new query results to the MST models
- turn firestoreMetadataDocs into a view that combines all of the documents together.
=> live update sorted documents

src/models/history/tree-manager.test.ts, src/models/history/tree-manager.ts, src/models/history/tree-monitor.ts, src/models/history/undo-store.test.ts, src/models/history/undo-store.ts, src/plugins/data-card/components/case-attribute.tsx, src/plugins/data-card/components/data-card-toolbar-buttons.tsx, src/plugins/data-card/data-card-content.ts, src/plugins/data-card/data-card-tile.tsx, src/plugins/data-card/data-card-toolbar.tsx
As noted in PT-188129121 , a bar graph created with the "Bar Graph It!" button from a table did not have its history recorded in a way that could play back without errors.  In fact this was failing for other tiles (data cards, graph) created with shared models pre-attached; changes made in response to the shared model were recorded in history _before_ the creation of the tile, and thus would fail on replay.
This PR is more careful about the order in which these events are recorded in history.  In addition, some deeper issues with the Data Card tile are addressed so that undo, redo, and history playback should now work for the "Data Card It!" case.
=> Make history playback work for "X It!"

cypress.config.ts, cypress/e2e/functional/document_tests/student_test_spec.js, cypress/e2e/functional/teacher_tests/teacher_share_spec.js, cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, cypress/support/visit_params.js, src/components/app.tsx
- fix teacher share test:
- the teacher was added to a group (teachers aren't supposed to be in groups
- the sort group sections weren't loaded before being expanded
- fix student test, it was using demo space for testing which made it unpredictable
- enable sort filter persistence test, it was using demo space for testing which made it unpredictable
- added a new helper visitQaSubtabsUnit to improve readability
=> Fix Cypress tests around sorted documents

scripts/ai/download-documents-with-info.ts, scripts/ai/update-metadata.ts
- documentMetadata is undefined sometimes
- some comment docs had tags as an empty string
=> handle invalid data when running scripts

src/hooks/use-document-sync-to-firebase.test.ts, src/hooks/use-document-sync-to-firebase.ts, src/lib/firebase.ts
PT-188320636
Adds a `lastEditedAt` metadata property for documents. After a document is modified by a user, this is set to the time when either:
* The document is unloaded from the editing workspace (eg, user opens a different document) or
* The user's database session ends (tab closed, browser closed, WiFi connection lost, etc)
=> Track end of document edit session

cypress/support/elements/common/SortedWork.js, cypress/support/elements/tile/DataflowToolTile.js, src/models/stores/sorted-documents.ts
The code for opening a specific section was opening all of the currently visible sections. The actual section that should be opened might not be visible yet.
There were extraneous MobX warnings showing up in the tests. These were fixed by wrapping the change in a runInAction.
When running locally the default timeout is now 5s which is was too short for the dataflow timer waiting.
=> Fix Cypress Tests

shared/shared.ts, src/components/document/document-group.tsx, src/components/document/document.tsx, src/components/document/sort-work-document-area.tsx, src/components/document/sorted-section.tsx, src/components/navigation/document-view.tsx, src/components/thumbnail/simple-document-item.tsx, src/hooks/use-document-caption.tsx, src/lib/db.ts, src/models/document/document-types.ts, src/models/document/document-utils.test.ts, src/models/document/document-utils.ts, src/models/document/document.ts, src/models/document/log-document-event.ts, src/models/history/tree-manager.ts, src/models/stores/sorted-documents.ts
Specifically this unifies the way the simple document items (the boxes in the sorted documents view), and the thumbnail captions are computed. It also improves the titling when the unit or problem is not known or found for the current document.
Additionally it takes care of an issue with the creation of the metadata documents. Before we started using them for the sort work view they were created by the history system so the history entries could be stored underneath the metadata document. When we added the sort work view we started creating these metadata documents immediately when any document was created.  The new spot that created these documents makes sure to set the unit, investigation, and problem when necessary. The original spot in the history system was not doing this. So if the …
=> unify more the titles displayed for documents

cypress/e2e/functional/document_tests/group_chooser_spec.js, src/clue/components/clue-app-header.tsx, src/clue/components/teacher/teacher-student-tab.tsx, src/components/app.tsx, src/components/four-up.test.tsx, src/components/four-up.tsx, src/components/group/group-chooser.tsx, src/initialize-app.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/lib/db-listeners/db-groups-listener.ts, src/lib/db.ts, src/lib/firebase.ts, src/models/stores/base-stores-types.ts, src/models/stores/class.test.ts, src/models/stores/class.ts, src/models/stores/create-exemplar-docs.ts, src/models/stores/document-group.test.ts, src/models/stores/groups.test.ts, src/models/stores/groups.ts, src/models/stores/portal.ts, src/models/stores/sorted-documents.test.ts, src/models/stores/stores.ts, src/models/stores/ui.ts
If a student is added to the class after CLUE has already launched, and then this new student runs CLUE and joins a group. The first student should see this new student.
To support this several changes were made:
- when the class store is updated from the portal data, it is done "in place" now with applySnapshot.
- the groups store was updated to use the MST environment system instead of handling this itself. Originally the MST system was avoided because we planning to drop MST for the Groups store. Now that we are syncing groups using MST is the best option.
- the groups store is now sync'd "in place" using applySnapshot
- the groups store now looks up the users in the class store instead of copying their initials and name. This way when a new student is in the groups and not the class …
=> Refresh class roster plus refactor

src/components/tiles/geometry/geometry-content.tsx, src/components/tiles/tile-component.tsx
- some linked tiles had empty string ids, so this caused react to complain about duplicate keys
- the geometry board couldn't be destroyed, the uncaught exception prevented React from re-rendering the sort work tab
PT-188339926
=> fixing thrown errors fixed the closing problem

cypress/e2e/functional/tile_tests/shared_variables_test_spec.js, package-lock.json, package.json, src/plugins/shared-variables/shared-variables.ts
This brings in:
- a rounding change that was missing before.
- a fix so the units are not shared between different diagrams in the same browser window
- a fix for units like "S" that crashed documents
=> use diagram-view 1.0.0

cypress/e2e/functional/tile_tests/drawing_tool_spec.js, cypress/e2e/functional/tile_tests/tile_navigator_spec.js, cypress/support/elements/tile/DrawToolTile.js, cypress/support/elements/tile/TileNavigator.js, src/components/tiles/tile-navigator.scss, src/components/tiles/tile-navigator.tsx, src/models/tiles/navigatable-tile-model.ts, src/plugins/drawing/components/__snapshots__/drawing-layer-legacy.test.tsx.snap, src/plugins/drawing/components/__snapshots__/drawing-layer.test.tsx.snap, src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/components/drawing-tile.tsx, src/plugins/drawing/model/drawing-content.ts, src/plugins/drawing/objects/ellipse.tsx, src/plugins/drawing/toolbar-buttons/zoom-buttons.tsx
[#187924987](https://www.pivotaltracker.com/story/show/187924987)
Adds up, down, left, and right panning buttons to the tile navigator. The buttons only appear when drawing content extends beyond the boundaries of the main tile's viewable content area. Clicking a button pans the tile navigator viewport's and main tile's content area's view in that direction.
=> feat: Drawing tile panning controls (PT-187924987)

functions-v2/src/index.ts, functions-v2/src/on-analysis-document-imaged.ts, functions-v2/src/on-analysis-document-pending.ts, functions-v2/src/on-analyzable-doc-written.ts, functions-v2/src/utils.ts, functions-v2/test/on-analysis-document-imaged.test.ts, functions-v2/test/on-analysis-document-pending.test.ts, functions-v2/test/on-analyzable-doc-written.test.ts, src/lib/firebase.ts, src/public/demo/units/qa/content.json
Followup work on PT-188092997
* Allow creation of multiple comments by the AI evaluation. A new comment will be added each time the evaluator runs, as per request in Slack.
* Remove restriction to the `AI` demo space.
=> Create multiple ai comments

src/components/document/tile-row.tsx
[#188449969](https://www.pivotaltracker.com/story/show/188449969)
Removes `e.dataTransfer.effectAllowed = "none"` from `handleStartResizeRow` which was preventing `handleDrop` from being called. Setting `effectAllowed` means the [item may not be dropped](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed#none). Removing the line results in a tile resize being maintained when a document is reloaded, and doesn't appear to break anything.
=> fix: tiles don't retain their vertical size (PT-188449969)

src/plugins/drawing/components/drawing-layer.test.tsx, src/plugins/drawing/model/drawing-content.test.ts, src/plugins/drawing/model/drawing-content.ts
PT-185893761
- Removes logging for a couple of model actions that do not represent user actions (reset, afterCreate) or are just precursors to actions (setEditing, setOpenPalette).
- Removes methods only called by tests: `moveObjects`, `updateImageUrl`
- Updates tests to use `setDragPosition` / `repositionObject` which is how the UI does it, rather than calling `setPosition` directly,.
I did not attempt to create a `dontLog` annotation; wasn't quite sure how & there was already a list of actions not to log in the code so I just added to that.
=> Image logging cleanup

cypress/e2e/functional/document_tests/tiles_copy_test_spec.js, src/models/document/document-content-with-annotations.ts
When dragging to copy a tile, previously straight sparrows on that tile were not copied.  This was because the logic of `getAnnotationsUsedByTiles` did not include them.  This PR fixes that.  It also adds a simple Cypress test of this to the tile copy spec.
=> Fix copying of straight sparrows with tile copy

functions-v2/.gitignore, functions-v2/README.md, functions-v2/package.json, functions-v2/src/index.ts, functions-v2/src/on-document-tagged.ts, functions-v2/test/on-document-tagged.test.ts, src/hooks/document-comment-hooks.ts
[#188476611](https://www.pivotaltracker.com/story/show/188476611)
Adds a Cloud Function that will watch for comments and update the related document's strategies array with tag values in the comment. The function will also delete values from the document's strategies array if a comment containing tags is deleted and no other comments contain the same tags.
Also included is a small change to the `emulator` script in `functions-v2`. It will now save and load data from the new `functions-v2/emulator-data` directory so that state will persist between emulator runs.
=> feat: AI-categorized docs show in strategy sorts (PT-188476611)

src/components/tiles/geometry/geometry-content.tsx, src/models/tiles/geometry/geometry-content.ts
Fixes bug where after copying a Geometry tile, not all linked datasets were being displayed.
Changes the return value of getLinkedPointsData, which was previously a hash indexed by the `providerId` of each linked SharedDataSet.  After a tile copy operation, the newly-created SharedDataSet copies have no providerId any more, so this was being indexed by `undefined`.
Change this to using the SharedDataSet id as the hash key, and include the providerId in each point's properties.
=> Fix bug in copying multi-dataset Coordinate Grid tiles.

cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, functions-v2/src/on-document-tagged.ts, functions-v2/test/on-document-tagged.test.ts, src/hooks/document-comment-hooks.ts
[#188476611](https://www.pivotaltracker.com/story/show/188476611)
The functionality provided by the removed code is now handled by a [new Cloud Function](https://github.com/concord-consortium/collaborative-learning/pull/2433). Also included is a small modification to the teacher sort work view tests in light of deleted comments now being supported.
=> chore: remove existing tag-handling code (PT-188476611)

src/components/tiles/geometry/geometry-content.tsx
Fixes a regression introduced by the navigator panel in the Geometry tile.
The navigator-internal `GeometryContentComponent` was re-registering the tileAPI and returning incorrect position information for objects (based on where they are shown in the navigator view, rather than the main tile view).
=> Fix positioning of sparrow buttons in Geometry

scripts/shutterbug.ts
This creates images that match the height of the content.
So far only staging shutterbug has been updated with this support, but it
should be on production soon.
=> use the fullPage option of shutterbug

src/lib/auth.ts, src/lib/logger.ts, src/lib/portal-api.test.ts, src/lib/portal-api.ts, src/models/document/log-document-event.ts, src/models/tiles/geometry/geometry-utils.ts
This adds three elements to the information that is logged with events.
- A new `documentHistoryId` entry is added inside the `parameters` of document-related events. 
- When launched from the portal, the `offeringId` is included with _all_ events. It should get added to `extras` by the log ingester.
- When launched from the portal, the `activity` URL should now be included for students; it was already being sent for teachers. This is one of the top-level elements in the log schema.
I included one TODO comment that is unrealated to this change, but was in my local copy & I didn't want it to get lost.
=> Logging additions to enable linking to historical documents

README.md, docs/unit-configuration.md, shared/shared.ts, src/clue/components/clue-app-header.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/lib/portal-types.ts, src/models/curriculum/unit.ts, src/models/stores/portal.ts, src/models/stores/unit-configuration.ts, src/models/stores/user-types.ts, src/models/stores/user.ts, src/utilities/url-params.ts
This adds a "researcher" url param to CLUE that, when present, is passed to the requests for the portal and Firebase JWTs.  When the researcher param is set to "true" the portal JWT will mint a JWT with the user_type set to "researcher" for any user.  When it is set to "true" for the Firebase JWT the user must be a researcher for the provided class_hash param.
The portal store was also updated to allow for researcher authentication.  However, once authenticated the user won't be able to currently read any data from Firestore.  There is a follow on PT story for updating the Firestore rules to allow researchers access to the data.
=> feat: Add requests for researcher portal and Firebase JWTs [PT-188754102]

cypress/e2e/functional/tile_tests/bar_graph_tile_spec.js, cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/BarGraphTile.js, cypress/support/elements/tile/TableToolTile.js, cypress/support/utils/data-display.js, src/clue/data-colors.scss, src/clue/data-colors.scss.d.ts, src/plugins/bar-graph/bar-graph-content.test.ts, src/plugins/bar-graph/bar-graph-content.ts, src/plugins/bar-graph/bar-graph.scss, src/plugins/bar-graph/chart-area.tsx, src/plugins/bar-graph/legend-secondary-row.tsx, src/utilities/color-utils.ts
[#188212464](https://www.pivotaltracker.com/story/show/188212464)
Adds a color picker option to the Bar Graph component's color legend. Clicking a legend color brings up a color palette from which the user can change the associated bars' color.
The menu placement differs from the spec in that it's automatically placed so it isn't cropped by the container, which would happen if the menu was always placed below its associated button. Also, offline discussion determined that it's desirable to allow a color to be used more than once. However, when automatically adding new colors, we should try to avoid duplication.
Also adds an `exportJson` view to `BarGraphContentModel` for export/authoring.
=> feat: bar graph color picker (PT-188212464)

src/components/playback/playback-control.tsx
This fixes a bug in the playback control that showed "0" instead of "Jan" when the edit date was in January.
=> fix: History is showing "0" for January dates [PT-188788349]

src/components/document/sort-work-document-area.tsx
This enables the history feedback for researchers regardless of the history role setup in the configuration.
=> fix: Enable history playback for researchers [PT-188754125]

README.md, cypress/e2e/functional/teacher_tests/teacher_student_work_spec.js, docs/oauth2.md, src/components/document/document-content.tsx, src/initialize-app.tsx, src/models/stores/app-config-model.ts, src/models/stores/nav-tabs.ts, src/models/stores/sorted-documents.ts, src/models/stores/stores.ts, src/utilities/url-params.ts
PT-188754089
Adds support for a `studentDocument` URL parameter for teacher/researcher users. This will load the referenced document into the resource area after startup.
Related changes:
- Fix some markdownlint warnings in doc files touched
- Add a `data-document-key` attribute to HTML for convenience in testing
- Adds a test of the URL parameter. We don't have a "researcher" setup for Cypress tests, and it didn't seem worth creating one just for this single test, so it's running as teacher for now.
=> URL param to load a student document

package.json, src/models/json-number.test.ts, src/models/json-number.ts, src/plugins/graph/adornments/movable-line/movable-line-model.test.ts, src/plugins/graph/adornments/movable-line/movable-line-model.ts
This adds a JsonNumber type which serializes NaN, Infinity, and -Infinity as strings.
This makes the javascript number type safe to serialize with MST.
It fixes a bug where vertical lines with Infinity slope were not round tripping.
=> handle special numbers

README.md, cypress/e2e/functional/teacher_tests/teacher_student_work_spec.js, docs/firestore-schema.md, src/components/document/canvas.tsx, src/components/playback/playback.tsx, src/initialize-app.tsx, src/models/document/log-document-event.ts, src/models/history/tree-manager.ts, src/models/stores/sorted-documents.ts, src/models/stores/stores.ts, src/utilities/url-params.ts
PT-188754092
Adds a `studentDocumentHistoryId` URL param that works in concert with `studentDocument`.
Adds a test for this.
Cleans up a few things from the studentDocument PR.
=> Add URL param that links to point in document history

docs/oauth2.md, src/lib/auth.ts, src/lib/portal-api.ts, src/models/stores/portal.ts, src/utilities/researcher-param.ts, src/utilities/url-params.ts
A utility function called maybeAddResearcherParam was added to add the researcher=true query param to portal api urls if it is set in the CLUE query parameters.  This ensures the portal anonymizes the student info even if the user has higher privileges than a researcher.
The target_user_id is also passed to the portal JWT and Firebase JWT calles if the targetUserId parameter is set in the CLUE query parameters.  This is needed for researchers to check if they have access to the user's information.
=> fix: Add missing researcher and target_user_id params to portal requests [PT-188754125]

scripts/README.md, scripts/find-documents-missing-metadata.ts
PT-188784006
Script to address the symptom of this bug, which created (or perhaps still creates) documents without the unit, investigation, and problem fields. In at least some cases, there is another metadata doc with the same key, so we can copy these fields over.
Also fixes some lint warnings in the README.
=> Script to add missing metadata to docs

src/components/annotations/annotation-arrow.scss, src/components/document/annotation-layer.tsx
PT-188582563
Disable interaction with the sparrows when not in sparrow mode.
When you _are_ in sparrow mode, also tweak CSS so that curved sparrow does not consider mouseover event for the area inside its curve - just the actual stroke path.
These changes make it much easier to interact with the content that is underneath the sparrow.
=> Prevent any interaction with Sparrows when not in Sparrow mode.

.github/workflows/release-production.yml, .github/workflows/release-staging.yml, .github/workflows/release.yml
We are already creating GitHub deployments when branches and versions are deployed by the s3-deploy-action.
Before this PR we were not creating GitHub deployments for staging and production releases.
The first release run with this code was `5.20.0`. It did create a deployment:
https://github.com/concord-consortium/collaborative-learning/deployments
The versions and branches deployments are created with a simple `environment` section in the workflow:
https://github.com/concord-consortium/collaborative-learning/blob/81632f12fe9ae69ee5cd85e3a68699e389d3ea42/.github/workflows/ci.yml#L135-L137
This environment section was not used for the release for two reasons:
1. As far as I know it would require checking out the tag that is being deployed. Our deployment process just copies some s3 files …
=> create github deployment during release

cypress/e2e/functional/document_tests/workspace_test_spec.js, cypress/e2e/smoke/single_student_canvas_test.js, cypress/support/commands.js, cypress/support/elements/common/ResourcesPanel.js, src/clue/app-config.json, src/clue/app-icons.tsx, src/components/delete-button.test.tsx, src/components/document/document-toolbar.tsx, src/components/document/document.tsx, src/components/document/editable-document-content.scss, src/components/document/editable-document-content.tsx, src/components/document/section-toolbar.tsx, src/components/document/sort-work-document-area.tsx, src/components/document/sort-work-view.scss, src/components/navigation/document-view.tsx, src/components/navigation/problem-panel.scss, src/components/navigation/problem-panel.tsx, src/components/navigation/section-document-or-browser.scss, src/components/toolbar-button.tsx, src/components/toolbar.tsx, src/models/stores/app-config-model.ts, src/models/stores/configuration-manager.ts, src/models/stores/problem-configuration.ts, src/models/tiles/toolbar-button.ts
This adds a separate toolbar to all document views on the left of the workspace.
The toolbar has options set by the caller to show individual buttons.
For now the edit button can be shown and a placeholder for the playback button is in the code but forced to be hidden until we get to that story.  The playback option was added just to test the filtering.
=> feat: Add My Resources Toolbar [CLUE-1]

src/components/document/document-toolbar.tsx, src/components/toolbar.tsx
This will allow the root copy PRs to remain unmerged by rebasing the later PRs that are not related to copy but need these toolbar changes.
=> fix: Pick toolbar changes picked from earlier copy stories

src/components/document/editable-document-content.scss, src/components/document/sort-work-view.scss
This ensures the primary toolbar tool svg path colors stay the same.
=> fix: Ensure correct svg path fill for primary tools [CLUE-42]

src/components/toolbar.tsx, src/models/document/base-document-content.ts, src/models/document/document-content.ts
This converts the copy spec to use the existing drag copy tile code to avoid duplicating code and to handle shared models and annotations.
=> fix: Use existing drag copy tile code to for copy specs [CLUE-3]

cypress/e2e/functional/document_tests/nav_panel_test_spec.js, src/components/document/tile-row.tsx
This fix hides the resizing icon when the tile is in a readonly document.
=> fix: Remove tile expand icon when tile rendered on left side [CLUE-68]

cypress/e2e/functional/document_tests/tiles_copy_test_spec.js, src/components/tiles/geometry/geometry-tile.tsx, src/components/tiles/geometry/use-tile-selection-pointer-events.ts, src/components/tiles/tile-component.tsx, src/components/toolbar.tsx, src/models/document/document-content.ts, src/models/stores/ui.ts
- select the copied tiles when copying to workspace or other document
- when all tiles are selected (or when more than one tile is selected), clicking on a single selected tile will deselect all the other tiles but keep the one tile selected
=> fix: Update tile select/deselect pattern [CLUE-66]

src/components/toolbar.scss
This adds a css rule to not update the copy to workspace and copy to document icon svg path fills to gray and instead leave them blue as in the original svg.
=> fix: Keep copy icon path fill [CLUE-4]

.github/workflows/manual-regression.yml, cypress/e2e/functional/standalone_tests/standalone_load_spec.js, src/clue/components/clue-app-header.tsx, src/components/app.tsx, src/components/navigation/problem-panel.scss, src/components/navigation/problem-panel.tsx, src/components/network-status.tsx, src/components/workspace/workspace.tsx, src/hooks/use-last-support-view-timestamp.ts, src/models/stores/stores.ts, src/models/stores/ui.ts, src/models/stores/user.ts, src/standalone.tsx, webpack.config.js
This adds a new top level page called "standalone".  For now standalone mode shows the curriculum on the left and a TBD panel on the right.
When the login UI is added in the next PR the "STANDALONE FIXME" comments will be addressed, probably with additional or modified model state.
=> feat: Add standalone app page [CLUE-72]

cypress/e2e/functional/tile_tests/drawing_tool_spec.js, cypress/support/elements/tile/DrawToolTile.js, src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/components/selection-drawing-tool.tsx, src/plugins/drawing/objects/ellipse.tsx, src/plugins/drawing/objects/image.tsx, src/plugins/drawing/objects/line.tsx, src/plugins/drawing/objects/rectangle.tsx, src/plugins/drawing/objects/text.tsx, src/plugins/drawing/objects/vector.tsx
CLUE-24
Pointer events include an `isPrimary` attribute. For touch events where the user may have multiple body parts touching the screen, whatever registers the first touch is considered primary. This set of changes makes sure that only that initial touch point gets tracked so that you don't end up following `pointerMove` events from all of the touchpoints interleaved with each other.
=> Drawing tools only respond to primary pointer

src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-shared-models.test.ts
Send required rowId for insertion into existing row
Update the test to send a correct row ID.
=> Fix failure to copy tiles

src/components/document/document-content.tsx, src/components/document/locked-container-context.tsx, src/components/tiles/question/question-tile.tsx, src/components/tiles/text/text-tile.tsx, src/components/tiles/tile-component.tsx, src/components/toolbar.tsx, src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-question-tile-move-copy.test.ts, src/models/document/document-content.ts, src/models/document/drag-tiles.ts, src/models/document/row-list.ts, src/models/tiles/question/question-registration.ts, src/models/tiles/question/question-utils.test.ts, src/models/tiles/question/question-utils.ts, src/models/tiles/tile-content-info.ts, src/models/tiles/tile-model.ts
CLUE-80.  Make copying work properly for tiles including Question tile and the tiles within it.
Make sure that when copying, all tiles embedded within a Question tile are copied properly as well.
Get the order right when multiple tiles are copied (there were some pre-existing bugs here).
Question tiles are locked when copying across documents, but unlocked copies are made for within-document copies.
Set proper read-only, unselectable behavior for prompts when in locked tiles.
=> Copying question tiles

src/clue/components/app-mode-indicator.scss, src/clue/components/app-mode-indicator.tsx, src/clue/components/clue-app-header.sass, src/clue/components/clue-app-header.tsx, src/components/network-status.scss
This commit introduces a new design for the online indicator and version number display in the header.
The changes include:
- Stacked the online indicator and version number to save horizontal space.
- Updated the online indicator to use the spec'ed font color and size.
- Adjusted the version number be "CLUE v{version}" to match the design spec
Also fixed the icon spacing of the preview warning icon in the app header - it was being clipped.
Before update:
After update:
=> feat: Restyle Online Indicator & Version Number [CLUE-101]

cypress/e2e/functional/standalone_tests/standalone_load_spec.js, src/components/utilities/dialog.sass, src/components/utilities/use-error-alert.tsx, src/hooks/use-custom-modal.tsx
- Added height: auto to standard dialog input container so that inner input/select padding addition worked when container had a set height
- Fixed missing unit parameter in standalone test
=> fix: Daily regression test breaks

src/components/utilities/dialog.sass
Adding the inner padding on the input elements conflicted with the outer padding in the standard prompt dialog causing two borders.
=> fix: Double border on dialog input [CLUE-81]

cypress/e2e/functional/document_tests/copy_doc_test_spec.js, cypress/support/elements/tile/QuestionToolTile.js, src/models/document/base-document-content.ts, src/models/document/document-content.ts, src/models/document/drag-tiles.ts, src/models/tiles/tile-model.ts
CLUE-99
This fixes three bugs that were found in the Question tile implementation:
- the method to copy an entire document, used in the "Make a Copy" menu item, did not recursively update nested rows.
- exporting JSON (as used in authoring) did not include the "fixedPosition" annotation that prompts need.
- placeholder tiles were not properly created at the end of question tiles in all cases.
=> Copying Question tile from other users

src/plugins/bar-graph/bar-graph.scss
[CLUE-110](https://concord-consortium.atlassian.net/browse/CLUE-110)
Previously, bars only had an outline when there was a secondary sort. That worked fine before we allowed users to change the bar colors from the default blue when there is no sort. Now that the user can change the color to white, though, bars can become essentially invisible. This change would ensure bars always have an outline to prevent that. (I checked with @mtirenin who confirmed bars should always have an outline.)
[CLUE-110]: https://concord-consortium.atlassian.net/browse/CLUE-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: white bar on bar graph disappears (CLUE-110)

cypress/e2e/functional/document_tests/student_test_spec.js, cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, src/components/document/sort-work-view.tsx, src/components/document/sorted-section.tsx, src/components/thumbnail/decorated-document-thumbnail-item.tsx, src/components/thumbnail/document-type-collection.scss, src/components/thumbnail/simple-document-item.scss, src/components/thumbnail/simple-document-item.tsx, src/models/stores/persistent-ui/persistent-ui.ts, src/models/stores/ui.ts
[CLUE-86](https://concord-consortium.atlassian.net/browse/CLUE-86?atlOrigin=eyJpIjoiYTA2NTM3ZjA4ZmIxNDc0NmFhMTc5NjUxNTk2ZDA4ODQiLCJwIjoiaiJ9)
When a user expands a section in the Sort Work overview, clicks on a thumbnail within a section to view a document, and then exits that view to return to the Sort Work overview, any previously expanded sections remain open, and the previously opened document remains visibly highlighted. 
When a user switches the 'Secondary Sort' option or the 'Filter', if a section is expanded, the section remains expanded, and if a document is highlighted, it remains highlighted. 
When a user switches the 'Primary Sort' option, everything resets -- expanded sections are no longer remembered, and neither is the previously highlighted document.
[CLUE-86]: …
=> [CLUE-86] Return to Sort View retains state

cypress/e2e/functional/teacher_tests/teacher_sort_work_view_7_spec.js, cypress/support/elements/common/SortedWork.js, src/components/document/document-scroller.tsx, src/models/stores/sorted-documents.ts
[CLUE-56](https://concord-consortium.atlassian.net/browse/CLUE-56?atlOrigin=eyJpIjoiOTRlMDhiNTFiOGI5NDI2ZWIzNDJkYzU5MDYzNzc5YjgiLCJwIjoiaiJ9)
Updates the scroll view header so that it contains the primary / secondary sort labels relevant to the document group.
[CLUE-56]: https://concord-consortium.atlassian.net/browse/CLUE-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLUE-56]: Scroller list header shows document group labels

src/clue/components/clue-app-header.sass, src/clue/components/clue-app-header.tsx, src/clue/components/custom-select.sass, src/clue/components/custom-select.tsx, src/components/class-menu-container.tsx
This adds the functionality to share a link to the current standalone app instance in the teacher dropdown.
This does not update the dropdown styling to match the new spec.  That will be done in a follow on PR as there are a couple of styling issues that need to be resolved first and the current header styling is a bit of a mess.
This commit also updates the version output in the teacher app header to match the student app header and adds a gap between the version and teacher dropdown.
=> feat: Add shareable link to teacher dropdown [CLUE-91]

src/clue/components/clue-app-header.tsx, src/components/problem-menu-container.tsx, src/components/standalone/auth.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/lib/portal-api.test.ts, src/lib/portal-api.ts, src/test-fixtures/sample-portal-offerings.ts
This allows students to navigate between units in the app.  Before only teachers could navigate between units.  This change requires the portal API to be updated to allow students to request their own offerings.
This also updates unrelated code in the standalone auth component to change a variable name and update a comment based on an earlier PR comment.
=> feat: Add unit navigation for students [CLUE-76]

src/initialize-app.tsx
When launched from the portal the domain parameter becomes the "authDomain".
=> fix: Support student standalone launches from the portal [CLUE-126]

src/components/problem-menu-container.tsx
The code was updating a portal offering in the state tree outside of an action.  The update was not necessary so a temp variable is now used.
=> fix: Bug violating mobx update of state tree

src/utilities/auth-utils.ts
This updates the login and auth url generation to just use the modern URL class and removes all manual string interpolation to build the url.
=> fix: Escaping of login_url parameter in standalone auth

src/clue/components/clue-app-header.sass
The header creates a stacking context the the dropdown uses and that stacking context needs to be above the nav tabs z-index.  Before this change it was below it so the selected nav tab rendered above the header menus when they were opened.
=> fix: Header menus rendering under selected nav tabs

src/components/chat/comment-card.scss, src/components/document/publish-dialog.scss, src/components/network-status.scss, src/components/tiles/table/expressions-dialog.scss, src/components/utilities/single-string-dialog.scss, src/hooks/link-tile-dialog.scss, src/plugins/drawing/components/variable-dialog.scss, src/plugins/shared-variables/dialog/variable-dialog.scss
This removes all the explicit heights from the custom modals as they are not needed anymore as the custom modal was updated in CLUE-90 to add default padding to the modal content which accomplishes the same effect as the height setting but without having to determine and set the height.
This also updates the select styling in the link tile dialog to match the spec'ed padding.
=> fix: Remove heights from custom modals [CLUE-113]

src/clue/components/custom-select.sass, src/clue/components/custom-select.tsx, src/components/class-menu-container.tsx
This removes the italicized text and replaces it with a dashed underline.
Before change:
After change:
=> fix: Update copy shareable link styling [CLUE-91]

src/utilities/auth-utils.test.ts, src/utilities/auth-utils.ts
Early in the standalone development I used "class" for the class word as that what was used in the tech design document but that conflicted with an existing class param so it was changed to classWord but I failed to change this instance.
=> fix: Wrong param name for class word passed to portal [CLUE-135]

src/components/tiles/placeholder/placeholder-tile.tsx, src/models/document/sectioned-content.ts
CLUE-120
In some pre-existing content no "containerType" was getting initialized for placeholders, leading to a "No placeholder content is configured" message. This PR makes sure to always use the configured default placeholder content even in that case.
=> Fix default placeholder content

src/initialize-app.tsx, src/models/stores/portal.ts, src/utilities/auth-utils.test.ts, src/utilities/auth-utils.ts
This fix shortens the url sent to the portal during login/registration.  This is url saved in the database and is used to redirect after registration is successful on the portal.  The database has a current limit of 255 characters for the url and the url used by CLUE just exceeded that.
The url we were sending had a long authDomain url, it has been replaced by a much shorter sentinel value.
A more future proof solution would be to extend the size of the sign_up_path column in the portal from a varchar(255) to varchar(512) but that would require a migration over the nearly 2 million existing user accounts.
=> fix: CLUE registration crash due to sign_up_path to long on the portal [CLUE-135]

src/components/standalone/auth.tsx
If the users cancels the logout on the portal this will automatically log the user back in when they get redirected back to CLUE from the logout page.
=> feat: Detect a canceled logout and then auto login [CLUE-132]

src/clue/components/clue-app-header.tsx
This updates the app header to only show the problem switcher to students in standalone mode.
Before standalone mode was added the students had no access to the switcher.  While standalone mode was being developed it was changed to show for all students, however we only added support to switching classes for students while they were in standalone mode so now the original non-dropdown is shown unless the student is in standalone mode.
=> fix: Only show students the problem switcher in standalone mode [CLUE-143]

.github/workflows/regression-daily.yml
This is a patch for the CLUE standalone Cypress check. Apparently the github actions were configured in the CI Regression and Regression label, but not in the Daily Regression label.
=> chore: patch for checking CLUE standalone

cypress/e2e/functional/standalone_tests/standalone_load_spec.js, cypress/support/elements/common/standalone-helper.js
[CLUE-154](https://concord-consortium.atlassian.net/browse/CLUE-154)
This PR improves the Cypress test coverage for the standalone CLUE application by:
- Adding a logout test that verifies a user can log out and is returned to the welcome screen.
- Improving the StandaloneHelper and test logic to handle conditional UI states so that the dialog text is less brittle
[CLUE-154]: https://concord-consortium.atlassian.net/browse/CLUE-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLUE-154 added test for log out and return to welcome screen

src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/components/drawing-tile.scss, src/plugins/drawing/model/drawing-types.ts
CLUE-67.
- Add offset to read-only view so that content that is centered under the title when edited is still centered in read-only view.
- Clicking read-only tile should select it.
=> Add read-only offset & click handler.

docs/tile-creation.md, src/lib/logger.test.ts, src/models/document/base-document-content.ts, src/models/document/document-content-tests/dc-tile-move-copy.test.ts, src/models/document/document-content-tests/multiple-tiles-example.json, src/models/document/document-content.ts
CLUE-83
Skips making tile titles & dataset names unique when copying a tile from one document to another.
Updates `tile-creation` documentation with the document toolbar -> "copy with spec" alternate pathway.
=> Don't make names unique when copying across documents

.github/workflows/ci.yml, .github/workflows/release.yml, package-lock.json, package.json, scripts/write-version.js, src/index.html, src/initialize-app.tsx, src/lib/misc.ts, src/models/stores/base-stores-types.ts, src/models/stores/stores.ts, version.json
CLUE-184
Rollbar package updated
Increase stacktrace depth
Limit to 100 error reports per page view
Add event log items to Rollbar "telemetry"
Notify Rollbar of releases in Github Actions
The "version"/"code_version" field was changed to use Github SHA since that seems to be what's recommended.
The sementic version is sent as an extra "version_tag" payload property.
=> Update rollbar config

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, src/plugins/drawing/components/drawing-layer.tsx, src/plugins/drawing/components/drawing-tile.scss, src/plugins/drawing/components/drawing-tile.test.tsx, src/plugins/drawing/components/drawing-tile.tsx, src/plugins/drawing/components/object-list-view.tsx, src/plugins/drawing/model/drawing-content.ts, src/plugins/drawing/model/drawing-types.ts, src/plugins/drawing/model/drawing-utils.ts, src/plugins/drawing/objects/drawing-object.tsx, src/plugins/drawing/objects/group.tsx
CLUE-172
Updates the `getObjectBoundingBox` method of the drawing tile to find correct bounding boxes for objects that are in groups. One method was moved from the `actions` section to the `views` section of the model since the incorrect placement was preventing mobx reactivity from working. 
Updates the `annotatableObjects` method to list objects inside groups, but not the groups themselves (matches requested UX where groups are not themselves considered annotatable).
Also fixes Sparrow endpoints when the "Show/Sort" panel is opened. To enable this reaction, the state variable representing whether the panel is open was moved to a volatile property of the drawing content. The width of the open panel was also previously determined dynamically but is now stored as a constant, which …
=> Sparrows in groups

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, cypress/e2e/functional/tile_tests/table_tool_spec.js, cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/TableToolTile.js, src/components/tiles/table/row-divider.tsx, src/components/tiles/table/row-drag-overlay.tsx, src/components/tiles/table/use-row-label-column.tsx, src/components/tiles/text/toolbar/highlight-button.tsx
[CLUE-202](https://concord-consortium.atlassian.net/browse/CLUE-202)
- Added comprehensive Cypress tests for table row reordering UI elements
- Added data-testid attributes to row drag indicators for better testability
- Fixed lint warnings in related files
✅ All tests pass
✅ Lint warnings resolved
✅ UI elements verified: drag indicators, row dividers, persistence
[CLUE-202]: https://concord-consortium.atlassian.net/browse/CLUE-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Cypress tests for table row reordering functionality

cypress/e2e/functional/document_tests/student_chat_spec.js, docs/unit-configuration.md, firebase-test/src/documents-rules.test.ts, firebase-test/src/setup-rules-tests.ts, firestore.rules, src/clue/app-config.json, src/components/document/document-content.tsx, src/components/document/editable-document-content.tsx, src/components/navigation/nav-tab-panel.tsx, src/models/stores/app-config-model.ts, src/models/stores/configuration-manager.ts, src/models/stores/unit-configuration.ts, src/public/demo/units/qa/content.json
CLUE-163
Adds an app-config setting to enable the comment panel based on the user's role.
Add database rules to allow students access to comments (enables read/write access, which goes beyond this story to enable the later stories in this epic).
Add tests at the database-rules level and Cypress tests.
Update the documentation (including some reformatting)
=> Allow students access to document comments

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js, cypress/support/elements/tile/TableToolTile.js
Makes some test changes that should improve the reliability of several cypress tests:
- Add `scrollBehavior: false` to the click events to minimize the chance of the table cell editor rendering in the wrong place. If it renders outside the table cell the edit cannot be completed.
- Do not depend on chaining or caching of DOM elements while doing table edits, since the table tile can get re-rendered and cause those DOM elements to be detached.
Optimistically removes the `skip` from the most problematic tests.
=> Make table tests less flaky

src/models/document/document-content.ts
CLUE-191
When copying Question tiles via the `copyTilesWithSpec` [pathway](https://github.com/concord-consortium/collaborative-learning/blob/master/docs/tile-creation.md), make sure that tiles embedded within those Question tiles are also brought along. 
Tweak the logic so that extra rows are not inadvertently created for them.
Add a TODO comment about the tile ordering issue.
=> Copy Questions tiles correctly via toolbar button

package-lock.json, package.json, src/components/tiles/geometry/geometry-content.tsx, src/components/tiles/table/use-editable-expressions.ts, src/models/data/data-set.ts, src/models/document/row-list.ts, src/models/document/tile-row.ts, src/models/mst.test.ts, src/models/stores/curriculum-config.ts, src/models/stores/groups.ts, src/models/stores/selection.ts, src/models/tiles/geometry/geometry-content.ts, src/models/tiles/table/table-content.ts, src/models/tiles/text/text-content.ts, src/models/tiles/tile-content.ts, src/models/tiles/tile-environment.ts, src/models/tiles/tile-model.ts, src/models/tiles/toolbar-button.ts, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/graph/adornments/movable-line/movable-line-model.ts, src/plugins/graph/adornments/movable-line/movable-line.tsx
- keys of forEach of MST maps have changed to be `string|number` type so this required changing parts of the code. This is probably a bug in MST, but its easier to change our code rather than fix it.
- `getEnv` now throws an error if the MST node has no environment, so now we use `hasEnv` to check for the environment first, this is mostly needed when the models are being tested without environments
- the typing of MST arrays now prevents  assignment of a simple array, but by using MST's cast function it fixes the problem
- A types.union of MST model types can't be simply coerced to a super type so now it is coerced to unknown first
=> upgrade MST

src/hooks/use-document-sync-to-firebase.ts, src/models/document/document.test.ts, src/models/document/shared-model-document-manager.test.ts, src/models/history/create-action-tracking-middleware-3.test.ts, src/models/history/create-action-tracking-middleware-3.ts, src/models/history/history.ts, src/models/history/tree-manager-api.ts, src/models/history/tree-manager-history.test.ts, src/models/history/tree-manager.test.ts, src/models/history/tree-manager.ts, src/models/history/tree-monitor.ts, src/models/history/tree-types.ts, src/models/history/tree.ts, src/models/history/undo-store-test-utils.ts, src/models/history/undo-store.test.ts, src/models/history/undo-store.ts, src/models/history/without-undo.ts
-  add enableMonitoring disableMonitoring actions
- fix some syntax and indenting differences
- use an object to pass arguments when there are a lot of arguments
- add a model name to HistoryEntries to make debugging easier
- add a document revisionId which CODAP uses for integration with the CFM
- add isValidCallEnv to simply and clarify code
- remove a FIXME that has already been addressed
- update tests to match the new runtime code
- reuse test helper function expectEntryToBeComplete
CLUE-226
=> sync history changes from CODAP

.firebaserc, cypress/e2e/functional/document_tests/ai_evaluation_test_spec.js, functions-v2/src/on-analysis-document-imaged.ts, functions-v2/src/on-analysis-document-pending.ts, functions-v2/src/utils.ts, functions-v2/test/on-analysis-document-imaged.test.ts, src/public/demo/units/qa/content.json
Add a "mock" option to the configuration of AI analysis, for testing purposes.  When a unit specifies `aiEvaluation: "mock"`, an AI comment will be created, but without calling any LLM.
=> New "mock" value for aiEvaluation for testing

src/components/tiles/geometry/color-palette.scss, src/components/tiles/geometry/color-palette.tsx, src/components/tiles/geometry/geometry-toolbar-registration.tsx, src/models/tiles/geometry/geometry-model.ts, src/models/tiles/geometry/geometry-utils.ts, src/utilities/color-utils.ts
Previously the Coordinate Grid, Graph, and Bar Graph were programmed to use the same set of colors; at some point 4 new colors were added to the set to make the bar graph more flexible, but they were neither properly added nor excluded from Coordinate Grid, making the color menu display oddly.  This PR restricts it to the subset of 8 colors.
=> Define 8 colors for geometry tile

src/lib/firebase.test.ts, src/lib/firebase.ts
[CLUE-214](https://concord-consortium.atlassian.net/browse/CLUE-214)
Copilot-generated summary:
This PR fixes an issue where custom AI prompt values were not being stored in analysis queue documents when users disconnect. The fix introduces a shared method to handle timestamp and AI prompt storage consistently across both immediate edits and disconnect scenarios.
- Extracted duplicated logic for storing timestamps and AI prompts into a reusable private method
- Updated disconnect handling to use the same logic as immediate edits for consistent data storage
- Updated test comments to reflect the corrected behavior
[CLUE-214]: https://concord-consortium.atlassian.net/browse/CLUE-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: custom ai prompt not stored on disconnect (CLUE-214)

cypress/e2e/functional/tile_tests/drawing_tool_spec.js, cypress/support/elements/common/cCanvas.js, cypress/support/elements/tile/DrawToolTile.js, src/clue/app-config.json, src/plugins/drawing/assets/align-bottom-icon.svg, src/plugins/drawing/assets/align-center-icon.svg, src/plugins/drawing/assets/align-left-icon.svg, src/plugins/drawing/assets/align-middle-icon.svg, src/plugins/drawing/assets/align-right-icon.svg, src/plugins/drawing/assets/align-top-icon.svg, src/plugins/drawing/components/align-palette.tsx, src/plugins/drawing/components/align-type-button.tsx, src/plugins/drawing/components/vector-type-button.tsx, src/plugins/drawing/drawing-registration.ts, src/plugins/drawing/drawing-toolbar.scss, src/plugins/drawing/model/drawing-basic-types.ts, src/plugins/drawing/model/drawing-content.test.ts, src/plugins/drawing/model/drawing-content.ts, src/plugins/drawing/model/drawing-utils.ts, src/plugins/drawing/objects/group.tsx, src/plugins/drawing/toolbar-buttons/align-button.tsx, src/plugins/drawing/toolbar-buttons/vector-button.tsx
Adds an "align" button with a tool palette to the Sketch tile toolbar.
* Requested alignment type is persisted in the model
* Implements align behavior
* Fixes console error with other palette buttons due to nesting of <button> within <button>
* Adds Jest and Cypress tests
=> Sketch tool align buttons

src/plugins/graph/adornments/movable-line/movable-line-model.test.ts, src/plugins/graph/adornments/movable-line/movable-line-model.ts, src/plugins/graph/utilities/graph-utils.ts
This fix ensures that the movable line model and graph utilities handle cases where the slope is infinite or the intercept is null,
which is caused when the x axis is categorical and not numeric.
CLUE-268
(cherry picked from commit f6338e7aaae5db094a2976a1d05f8b5925ebe47e)
=> fix: Default adornments on categorical a-axis causes null intercepts [CLUE-268]

cms/README.md, cms/webpack.config.js, docs/cms.md
This adds a README.md to the cms folder that points to the existing cms.md folder and also includes other info.
This also sets the default port of the cms to 8082 to reduce the complexity of the order of startup of the app, the git proxy and the cms.
=> build: Update default CMS port to 8082 and add README

src/components/annotations/annotation-utilities.ts, src/components/annotations/arrow-annotation.tsx, src/components/document/annotation-layer.tsx, src/models/annotations/arrow-annotation.ts, src/models/document/row-list.ts
Straight arrows now maintain their relative position on source tiles when those tiles are resized.
This is achieved by storing a normalized offset based on the source tile's dimensions.
NOTE: as part of this change the trigger for re-rendering the annotation layer was modified from when the row order changed to when the tile order changed across all rows.  This is to ensure that the annotation layer is re-rendered when tiles are moved between rows.
=> fix: Straight arrows scale with tiles [CLUE-247]

src/assets/icons/deleted-tile-icon.svg, src/components/chat/chat-comment-thread.test.ts, src/components/chat/chat-comment-thread.ts, src/components/chat/chat-panel.test.tsx, src/components/chat/chat-panel.tsx, src/components/chat/chat-thread.scss, src/components/chat/chat-thread.test.tsx, src/components/chat/chat-thread.tsx, src/components/chat/comment-card.scss, src/components/navigation/nav-tab-panel.tsx, src/components/playback/comment-marker.scss, src/components/playback/comment-marker.tsx, src/components/playback/playback-control.scss, src/components/playback/playback-control.tsx, src/components/vars.scss, src/hooks/use-nav-tab-panel-info.tsx
This changes the playback control to show markers for comments along the playback slider. The slider positions are now a combination of history entries and comments.  As the playback position changes, the comment thread updates to show comments relevant to the current position.
A few notes:
1. The playback will still show there is no history when there are only comments. We may want to change this in the future.
2. The comment thread header for deleted tiles has been updated to show a deleted icon along with the title "Deleted Tile".  Before the title was empty.  Since the tile name is not available after deletion, this is the best we can do.
=> feat: Sync comments with history [CLUE-276]

src/components/playback/comment-marker.tsx, src/components/playback/playback-control.tsx
This was causing the avatar's background color not to be set correctly.
=> fix: Added missing isMe prop to playback control ChatAvatar [CLUE-276]

src/components/playback/playback-control.tsx
This change ensures that when a user clicks on a comment marker in the playback slider, the canvas updates to reflect the document state at the time of the comment. This is done by navigating to the most recent history entry prior to the comment's creation time.
=> fix: Keep canvas in sync with document history when comment markers are clicked [CLUE-279]

scripts/consolidate-metadata-docs.ts, scripts/lib/script-utils.ts
- improve logging and error logging
- reduce number of writes needed when there are multiple prefixed documents
- don't delete top level document or its collections until all of its data has been merged into the unprefixed document
- allow subcollection documents to already exist at the unprefixed location
- retry if a resource exhausted error is reported by firestore, the bulk writer should wait 1 minute before retrying.
- if we get more than 10 resource exhausted errors then just exit the script.
- don't completely bail if there are merge errors, report all of them and then skip the document
- fix count of documents so the status matches up
- record curriculum metadata docs
- during a dryRun actually process the subcollections
- log how many documents are in each subcollection
- don't …
=> CLUE-249 use a global BulkWriter

firebase.json, src/authoring/components/app.scss, src/authoring/components/app.tsx, src/authoring/hooks/use-auth.ts, src/lib/db.ts, src/lib/firebase-config.ts, src/utilities/url-params.ts
This adds Firebase email/password authentication to the authoring tool.
It includes sign-in, sign-out, and user state management.  A custom hook is used as the FirebaseUI package is not compatible with Firebase 8.
This may be extended in the future to support Gmail OAuth to allow CC Google Workspace users to sign in with their Google accounts and automatically be granted access.
To enable local testing, the Firebase Auth emulator is now supported via the `?auth=emulator` URL parameter.
NOTE: this also centralizes Firebase initialization to avoid duplicating code in the main app.
=> feat: Add auth to authoring [CLUE-292]

authoring-api/src/helpers/express.ts, authoring-api/src/helpers/github.ts, authoring-api/src/index.ts, authoring-api/src/routes/get-remote-branches.ts, authoring-api/src/routes/get-remote-units.ts, authoring-api/src/routes/pull-unit.ts, src/authoring/components/app.tsx, src/authoring/hooks/use-auth.ts, src/authoring/hooks/use-authoring-api.ts, src/authoring/hooks/use-curriculum.ts
This commit updates the authoring API and frontend to use Firebase GitHub authentication instead of the Firebase username/password system.
Users can now authenticate using their GitHub accounts, and the system checks if they are collaborators on the CLUE curriculum repository.  Each call to the authoring API must include a valid GitHub token in the query parameters.
Further checks are in place to ensure that only users with email addresses from the concord.org domain can perform admin-only operations, such as pulling units.
=> ffeat: Replace authoring username/password with GitHub Auth [CLUE-297]

src/authoring/components/editors/raw-settings-control.scss, src/authoring/components/left-nav.tsx, src/authoring/components/workspace.scss, src/authoring/components/workspace.tsx, src/authoring/components/workspace/curriculum-tabs.tsx, src/authoring/components/workspace/nav-tabs.tsx, src/authoring/types.ts, src/models/stores/nav-tabs.ts, src/models/stores/stores.ts, src/models/view/nav-tabs.ts
This commit allows authors to customize the navigation tabs in the workspace.
Authors can now set which tabs are visible, their labels, and whether they are teacher-only.
The implementation includes a new component for managing nav tabs, updates to the unit configuration, and necessary styling adjustments.
Since the nav tabs are defined using an array in the unit configuration, a new `hidden` property has been added to each tab specification to manage visibility. This approach maintains the order of tabs as defined by the author and keeps any customizations intact.
=> feat: Add nav tab authoring [CLUE-269]

README.md, authoring-api/src/helpers/github.ts, authoring-api/src/index.ts, authoring-api/src/routes/get-raw-content.ts, authoring-api/src/routes/get-remote-branches.ts, authoring-api/src/routes/get-remote-units.ts, authoring-api/src/routes/pull-unit.ts, authoring-api/src/routes/put-image.ts, src/authoring/components/app.scss, src/authoring/components/app.tsx, src/authoring/components/editors/iframe-control.tsx, src/authoring/components/media-library.tsx, src/authoring/components/workspace.tsx, src/authoring/components/workspace/curriculum-tabs.tsx, src/authoring/hooks/use-authoring-api.ts, src/authoring/hooks/use-authoring-preview.ts, src/authoring/hooks/use-curriculum.ts, src/authoring/utils/authoring-api.ts, src/components/app-content.tsx, src/models/curriculum/problem.ts, src/models/curriculum/unit-utils.ts, src/models/image-map.ts, src/models/stores/create-exemplar-docs.ts, src/utilities/get-content.ts, src/utilities/url-params.ts
This commit introduces a new authoring mode preview feature that allows users to see real-time updates of their content changes.
A new url param, `authoringBranch`, has been added to enable this feature. When present, the runtime will fetch raw content from the authoring branch instead of the published branch, allowing authors to preview their edits. This also sets the base curriculum url to use the authoring branch so that images are also loaded from the raw authoring branch url.
This same param is also passed to the content iframe in the authoring workspace so that the iframe can also load content from the authoring branch.
A new hook, `useAuthoringPreview`, has been added to encapsulate the logic for determining if the preview mode is active.  It is used both in authoring to launch …
=> feat: Add authoring mode preview [CLUE-298]
