- .travis.yml
- s3_deploy.sh
- s3_website.yml
Set up Travis CI and S3 deployment [#160077604]
Improvements
- strips PT story ID from deployed branch names for ease of use
- supports tagged builds on production branch (deployment document discussion)
Testable at https://collaborative-learning.concord.org/branch/travis-ci/ (note the absence of the PT story ID in the deployed branch name).
> Set up Travis CI and S3 deployment

- package.json
- src/components/app-container.tsx
- src/components/app.tsx
- src/components/base.ts
- src/components/header.tsx
- src/components/learning-log.tsx
- src/components/left-nav.tsx
- src/components/my-work.tsx
- src/components/workspace.tsx
- src/index.tsx
- src/lib/auth.ts
- src/models/curriculum.ts
- src/models/problem.ts
- src/models/stores.test.ts
- src/models/stores.ts
- src/models/user.ts
- src/utilities/url-params.ts
- tslint.json
- yarn.lock
Refactor stores [#160188594]
- moves `stores` into separate module
- @inject stores into all components that need them
@ekosmin The API has changed a bit since we reviewed it together, so you may want to take another glance. Also, I added the unit test we talked about.
@dougmartin I ended up not going with the special derived/base class approach. It seemed like we could get enough of our boilerplate reduction and testing benefits without it.
@dougmartin @ekosmin I made some changes based on code review in case you want to take another look. I'm going to do a quick test of `tslint-no-unused-expression-chai` to see if it drops in as easily as it's supposed to. If it does I'll update the PR. -- Well that was easy. It dropped right in.
> Refactor stores

- package.json
- src/components/app.tsx
- src/index.tsx
- src/lib/auth.test.ts
- src/lib/auth.ts
- src/models/user.test.ts
- src/utilities/url-params.ts
- tslint.json
- yarn.lock
I added a handful of tests that use `Nock` to test authentication. Not 100% coverage of the `auth` file, but the main method is covered quite well.
I wanted to add tests for the logic in `index` that calculates `devMode` as well, but I couldn't manage to test anything in that file. Does it not get loaded by Mocha?
Also, I suspect I'll have some conflicts with Kirk's PR, but I'll resolve those once it's merged in.
> Authorization tests

- package.json
- src/models/data/attribute.test.ts
- src/models/data/attribute.ts
- src/models/data/data-set.test.ts
- src/models/data/data-set.ts
- yarn.lock
- update to MobX-State-Tree 3 and TypeScript 3
- port/extend unit tests as well
I anticipate storing the data shared between components/tiles (e.g. between the table and the geometry/graph) in a DataSet.
> Add DataSet and Attribute models from Workspaces/NeoCODAP

- src/components/canvas-tools/text-tool.tsx
- src/lib/db-types.ts
- src/lib/db.test.ts
- src/lib/db.ts
- src/models/document.ts
- src/models/tools/text/text-content.test.ts
- src/models/tools/text/text-content.ts
User work is saved based on the "whole doc" storage, for now. Parses Slate correctly now, too!
I realized there was a bug when I demo'd this morning - documents were only saved if they were just opened, so returning to an opened tab broke saving. Now, I'm monitoring all user documents at the same time. The alternative would be to listen for changes to the UI to figure out what to listen to, but I'd be surprised if the performance cost of a few extra listeners was noticeable.
> Save user work

- src/components/canvas.tsx
- src/components/four-up.sass
- src/components/four-up.tsx
- src/components/workspace.sass
- src/components/workspace.tsx
- src/lib/db.ts
- src/models/workspaces.test.ts
- src/models/workspaces.ts
This PR includes the synced 4-up view and the hide/show button. For each workspace, listeners watch group mate section documents and the content of those documents for changes, which are persisted to the workspace model. The listeners are updated whenever a workspace is created or loaded, or whenever the group makeup changes.
Tests are still needed, but I'm hoping to get this merged for tomorrow's demo.
> 4-up Text View

- src/components/canvas-tools/text-tool.tsx
- src/components/document-content.tsx
- src/models/tools/text/text-content.test.ts
- src/models/tools/text/text-content.ts
- remove Slate model from MST model
- don't serialize Slate selection to MST
- always keep Slate model in React component state
- only synchronize changes from Slate to MST in editable views
Separately, disable dropping tools into read-only documents
> Fix text tool issues after drag/drop

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/text-tool.tsx
- src/components/canvas-tools/tool-tile.sass
- src/components/canvas-tools/tool-tile.tsx
- src/components/document-content.sass
- src/components/workspace.tsx
- src/models/document-content.ts
- src/models/tools/tool-tile.ts
- src/models/ui.ts
- src/models/workspaces.ts
The work in this PR has been spear-headed by @DALove1025 with input from @ekosmin and me, much of it achieved during pair- and trio-programming episodes. After sixteen commits and multiple merges from master in the original PR branch I was having a hard time reviewing the changes so I cherry-picked the changes into a new branch that makes it easier to understand. In doing so I also tweaked a few things.
Support tool selection [#160300212]
- the current "styling" is a pink border around the selected tile; true styling awaits
Add delete tool which deletes the currently selected tile [#160407213]
Parse Slate operations for more fine-grained control of tool selection
- allows clicking outside any tile to deselect a text tile
> Support tool tile selection and deletion

- src/components/canvas-tools/tool-tile.sass
Fix bleed-through of geometry labels onto other layers (e.g. learning log) [#160686040]
- create stacking context in tool-tile such that tool-specific z-indexes are contained
- "what happens in tool tiles, stays in tools tiles"
> Fix bleed-through of geometry labels onto other layers

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/text-tool.tsx
- src/components/document-content.tsx
- Fix delete of text tool [[#160702405]]
- text tool no longer deselects tile on loss of focus
- text tool still selects on tile on focus
- Clicking on document background deselects currently selected tool
- works for both text and geometry (and future) tools
- First click on geometry tile selects it; subsequent clicks on selected tile create points
> Fix text tool delete & tile selection issues

- src/components/canvas.sass
- src/components/workspace.sass
This is a trivial addition to the css for the canvas style. Played around with it for about a 1/2 hour and could find no visual anomalies or odd behavior -- that is, in the 1-up view.
However, in 4-up, all 4 documents and the splitter(s) are inside the scrolling area. And there is still some strange visual behavior with overflow.
Resolving this is a bit more work as it may go to the heart how the canvases and sub-canvases interact.
I suggest this quickie fix for 1-up be merged, for the moment, and the 4-up scrolling be addressed in a more lengthy user-story.
> Added scrolling overflow to canvas

- package-lock.json
- package.json
- src/components/canvas-tools/geometry-tool.sass
- src/components/canvas-tools/geometry-tool.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg.ts
- src/typings.d.ts
- webpack.config.js
- GeometryTool renders in 4-up view [#160686176]
- GeometryTool resizes when appropriate [#160688141]
- the 4-up issue turned out to be a resize issue
- Guarantee unique DOM element IDs
- the 2-up issue turned out to be a problem with redundant IDs
Notes:
- Webpack is now loading the JSXGraph library source rather than the minified/built library. This makes it _much_ easier to debug but also slows down the build.
- I'm not sure why npm insisted on making so many changes to the `package-lock.json` file.
> GeometryTool works in all views

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas.tsx
- src/components/four-up.tsx
Fix new point creation on scaled canvases (e.g. 4-up view)
- must account for scale factor in mouse coordinate conversions
- scale factor is passed down as prop through canvas
> Fix new point creation on scaled canvases (e.g. 4-up view)

- src/components/canvas-tools/geometry-tool.tsx
- src/components/four-up.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
In read-only views, e.g. other group members in 4-up view, points cannot be created or dragged.
Note: This PR is build on top of PR #60, which should be reviewed/merged first after which this PR can be rebased to master if desired.
> Geometry tool supports read only

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/tool-tile.tsx
- src/utilities/browser.ts
- tslint.json
After originally settling for an unsatisfactory workaround, it occurred to me that the problem might be related to the additional dom layer provided by the SizeMe component. It turns out that by using an appropriate child node for the drag image, reasonable drag image behavior can be achieved for the geometry tool.
> Fix geometry tool drag image bug

- src/components/canvas-tools/geometry-tool.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-point.ts
- src/models/tools/geometry/jxg-polygon.ts
Implement double-click on free point to connect free points into polygon [#160575042]
It occurred to me that I could bypass the issue of needing a selection model by having a double-click on a free point automatically connect all free points, i.e. all points not otherwise connected to anything. Polygons for the win!
Note: this PR is built on the previous PR #69, which should be reviewed/merged first, after which this PR can be rebased to master.
> Connect free points to form polygon (no selection)

- src/components/learning-log.sass
- src/components/learning-log.tsx
- src/components/workspace.sass
Fixed title wrapping looks like this now (with right nav tabs hidden to show the titlebar fully):
> Fixed learning log title wrapping [#160797339]

- src/components/header.tsx
- src/index.tsx
- src/lib/auth.ts
- src/lib/db.ts
- src/utilities/url-params.ts
Previously dev mode would use a constant offeringId of "1" which caused the section documents to be persistent across problems.
This change generates a unique offeringId based on the problem in the urlParams.
This change also adds a debug helper: in non-authed mode when you hover over the username you will now see the firebase uid.
> Fixed non-unique offeringId per problem in dev mode [#160796641]

- package.json
- src/models/data/attribute.ts
- src/models/data/data-set.test.ts
- src/models/data/data-set.ts
- src/models/four-up-grid.test.ts
- src/models/groups.test.ts
- src/models/groups.ts
- src/models/supports.test.ts
- src/models/ui.test.ts
Add `lint:unused` script
- eliminate unused variables from a number of model files
I made this a separate script so unused variables don't necessarily break the build, but the script can be run when desired to identify unused variables for subsequent removal.
Note: I didn't remove unused variables from `db.ts` or a number of React components because I didn't want to risk introducing merge conflicts in files that might be part of current in-progress PRs.
> Add lint:unused script

- src/lib/auth.test.ts
- src/lib/auth.ts
Previously, we were passing an offering ID in through the URL parameters, and it was always the same. Now we convert the problem ID into a unique offering ID, as we do for dev mode.
> Creating fake offering IDs in QA and demo modes

- src/components/canvas-tools/geometry-tool.tsx
- src/components/learning-log.tsx
- src/components/my-work.tsx
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-board.ts
Fix geometry resizing [#160688141]
- fix geometry scaling in My Work and Learning Log thumbnails
- maintain consistent grid size and tick spacing
- default grid spacing matches curriculum images
> Fix geometry resizing and scaling issues

- src/components/canvas-tools/geometry-tool.tsx
- src/models/tools/geometry/jsxgraph.d.ts
A previous PR (#92) enabled dragging of polygons, but didn't save the updated location(s) to the model. This PR corrects that oversight.
> Save dragged polygon location

- src/components/document-content.tsx
- src/components/document/tile-row.sass
- src/components/document/tile-row.tsx
- src/models/document/tile-row.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/tool-tile.ts
- infrastructure supports drag-resize of any tile row
- tiles opt-in to user-resizability -- only geometry tool supports it for now
- row can only be resized when all tiles within it support resize
- fix computational error in geometry scaling calculations
Note: image tool is the obvious next candidate to support resize, but will require some additional work. The `<img>` tag doesn't by default provide the kind of resize behavior I think we want. Switching to `background-image` provides better resize behavior but would require a different default size implementation. @dstrawberrygirl I'm tagging you for review since you're in the middle of image tool work.
> Support drag-resize of geometry tile rows

- src/components/class-work.tsx
- src/models/documents.test.ts
- src/models/documents.ts
- src/models/workspaces.ts
Now we show the most recent work published by each *student*, rather than each *group*. This didn't require any changes to the way publications are stored, just the way they're retrieved.
> View published work by student

- package-lock.json
- package.json
- src/components/document-content.tsx
- src/index.tsx
- src/lib/logger.test.ts
- src/lib/logger.ts
- src/models/document-content.ts
- src/models/documents.ts
- src/models/stores.ts
This is an initial implementation of logging to the Log Manager, for the create, copy and delete tile actions.
This logs the fields checked off on the list in https://docs.google.com/document/d/1hPvRfBCtg0j5B8fvp9nHm6D4jonXunpyeMS5pltaWjA/edit#
One property that I know we will want to fix soon is to add the server skew to the time field, to get an accurate time, but it seemed like packaging this up as-is for the initial PR made sense. I will be following this up directly with some more action logging (UI changes, such as switching to the 4-up view, etc, as requested at a meeting earlier today).
This can be demo'd by non dev users by running the branch at http://collaborative-learning.concord.org/branch/logging-actions/?demo and looking at the network tab.
One feature that would probably …
> Add logging of actions

- src/components/canvas-tools/geometry-tool.sass
- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/image-tool.sass
- src/components/canvas-tools/text-tool.sass
- src/components/canvas-tools/tool-tile.sass
- src/components/canvas-tools/tool-tile.tsx
- src/components/canvas.sass
- src/components/document-content.sass
- src/components/document-content.tsx
- src/components/document/tile-row.sass
- src/components/document/tile-row.tsx
- src/models/document-content.ts
- src/models/document/tile-row.ts
- src/models/tools/image/image-content.ts
Support multiple tiles per row [#160634560]
- drop tile at left or right edge of row (w/in 20px) to add tile to row
- sized components (e.g. geometry tool) carry their size with them
- deleting/removing a tile from a row resizes if there are no more sized components
- tiles in row stretch to fill vertical height of row
- drag handlers revert to using `clientY` rather than `pageY` since `pageY` reflects page scroll not element scroll
Note: tiles copied from other documents always go into new row for now. Workaround is to copy them from their new row to the desired row as a second step.
> Support multiple tiles per row

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/tool-tile.tsx
Support dragging image tool to geometry to overlay image [#160604676]
- image drop zone is central area more than 25 pixels from edge (to avoid conflict with tile drop zones)
- only works for simple URLs (e.g. curriculum images) - no image upload support yet
Note: I cribbed the `getImageDimensions()` routine from @dstrawberrygirl 's image upload PR, but haven't tried to integrate the image upload itself.
> Support dragging image tool to geometry to overlay image

- src/components/canvas-tools/geometry-tool.tsx
Disable dragging to read-only geometry tool instances [#161272097]
> Disable dragging to read-only geometry tool instances (e.g. four-up)

- src/lib/logger.ts
- src/models/user.ts
Small addition to the logs to add the property `run_remote_endpoint`, which is used by our standard log-filtering systems.
This first adds it to the user model, from the Firebase JWT Token, and then adds it to each log message if it exists.
[#161299394]
> Adds remote endpoint to log messages

- src/components/canvas-tools/geometry-tool.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-image.ts
- Add null test before handleCreatePolygon() [#161349320]
- Prevent geometry background images from being dragged [#161343613]
- Remove previous image when dropping image on geometry [#161343613]
The first two were trivial. The last one required adding the ability to batch multiple changes.
> Fix geometry bugs

- .travis.yml
- package-lock.json
- package.json
- src/lib/db-listeners/db-groups-listener.ts
- src/lib/db.ts
- src/lib/firebase.ts
- src/models/tools/geometry/jxg.ts
For reasons that we still don't understand, our Travis builds started failing last night for reasons that didn't have anything to do with the contents of our project. The failures revolved around a set of packages that contain natively compiled code modules, specifically [node-canvas](https://www.npmjs.com/package/canvas) (an optional dependency of JSXGraph), [grpc](https://www.npmjs.com/package/grpc) (a dependency of firebase/firestore, which we don't use), and [node-sass](https://www.npmjs.com/package/node-sass) (which we use as our CSS preprocessor). My best guess is that something changed about the Travis/npm build environment such that the matching algorithm npm uses to select prebuilt binaries for natively compiled code modules began failing to find suitable matches, requiring that …
> Fix Travis builds; eliminate optional dependencies

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/tool-tile.tsx
- src/components/canvas.tsx
- src/components/document-content.tsx
- src/components/document.tsx
- src/components/document/tile-row.tsx
- src/components/four-up.tsx
- src/components/toolbar.tsx
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-point.ts
- src/models/tools/tool-tile.ts
- src/models/tools/tool-types.ts
Implement selection of points [#160969495]
- points are gray by default, red when selected
- clicking on a single point selects it
- ctrl/shift/cmd-click to select/deselect multiple points
- click on background deselects all points
- backspace/delete keys delete selected points [#161272021]
- first click on the interior of a polygon selects all its vertices
- click on interior of polygon with all vertices selected creates a new point
- click on red-X in toolbar to delete selected points [#161272021]
Implementing this required several pieces of new architecture.
- pass `tabIndex` to rows/tiles
- `tabIndex` is required for keyboard focus
- tile-specific metadata objects are created and passed to tiles that require them (currently only the geometry tool) for storage of tile-related data that …
> Geometry tool supports selecting points

- .travis.yml
This PR is a follow-up to #126. The solution to the mystery is that on October 23, 2018 node.js 11.0 was released as the latest stable version of node.js. Following some recommendation from somewhere, our `.travis.yml` included the following:
```
language: node_js
node_js: node
```
which is interpreted as a request for the latest stable version of node.js. Thus, immediately upon release of node.js 11.0 as the latest stable release, Travis started executing our builds in node.js 11.0. Unfortunately, several of the libraries we use that require native binaries do not yet provide pre-built native binaries for node.js 11.0, which means that they must resort to building those binaries from source, a process which frequently fails.
With this PR, we change our `.travis.yml` to the following:
``` …
```
> Specify latest lts version of node.js rather than latest stable version

- src/components/canvas-tools/geometry-tool.tsx
- src/models/clipboard.ts
- src/models/stores.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/utilities/hot-keys.ts
- src/utilities/js-utils.ts
Geometry clipboard operations [#160604580]
- support cut/copy of selected objects
- can paste objects into same or another geometry tile
- multiple pastes are offset slightly and get new labels
- uses new HotKeys modules to manage/dispatch keyboard shortcuts
- uses new Clipboard object in stores rather than global clipboard
We use a local Clipboard object in stores rather than the system clipboard because we aren't copying anything that would be understood outside the CLUE application and because the system clipboard has security protections that make it less convenient to deal with. I considered making it a global module like the `Logging` module, but decided that because some UI elements might one day depend on the state of the clipboard (e.g. enabling/disabling the paste button or menu …
> Geometry clipboard operations

- src/components/canvas-tools/drawing-tool/drawing-tool.tsx
The crash occurred in `DrawingToolComponent.componentDidMount()` when attempting to reset the current tool for the document displayed in the My Work panel. I believe what's happening is that there are two React components attempting to write to the same model in their `componentDidMount()` functions -- the one in the user's workspace and the one in the My Work tab. The first write succeeds, but triggers the firebase handler which triggers a document reload, which causes the second write to fail because the model in question has been replaced. The quick-fix here is to only try to reset the current tool in writable components, of which there should only ever be one. Ultimately, we should consider whether the currently selected tool should be in the model at all or whether it should be in …
> Fix draw tool crash

- src/components/canvas-tools/drawing-tool/drawing-layer.tsx
- src/components/canvas-tools/drawing-tool/drawing-tool.tsx
- src/models/tools/drawing/drawing-content.ts
Also, unrelated, unbind `reset` method in `drawing-content`. (Eventually we should put selected button in the metadata object instead.)
> Use scale prop to scale mouse interaction

- src/components/canvas-tools/geometry-tool.tsx
cleaning up a lingering geometry selection issue
> Geometry: background click in read-only view (e.g. 2-up) deselects

- package-lock.json
- package.json
- src/components/canvas-tools/tool-tile.tsx
- src/components/document.sass
- src/components/document.tsx
- src/models/clipboard.ts
- cmd-shift-c or ctrl-shift-c in supported component (e.g. geometry) copies json content to internal clipboard
- when internal clipboard contains json tile content, download icon appears in title bar (next to publish icon)
- clicking download icon downloads json tile content as local file named `tile-content.json`
- disabled in `authed` mode
This is primarily for @lbondaryk , who needs to embed authored geometry into the curriculum.
> Implements hidden copy/download tile content as json

- src/components/canvas-tools/geometry-tool.tsx
> Disable snapToGrid during drag to avoid point jitter

- src/lib/db.ts
- src/models/document-content.ts
- src/models/document/tile-row.ts
- src/models/tools/tool-tile.ts
Published documents should not share row/tile IDs with their source documents.
> Generate new row and tile IDs on publish

- cypress/integration/workspace.test.ts
This should remove the collisions we saw with manual groups today...not a good long-term solution but I think it will help.
> Use a unique class/offering for Cypress tests

- src/components/canvas-tools/drawing-tool/drawing-layer.tsx
- src/components/canvas-tools/drawing-tool/drawing-tool.tsx
- src/models/tools/drawing/drawing-objects.ts
Drag/drop from image tool (same as geometry)
Background image appears behind all other objects
Subsequent drops replace earlier images (only one image at a time)
Note: this is an initial implementation using the current (firebase storage) image storage implementation. It will need to be reworked a bit (along with the geometry tool) to support the upcoming image storage rearchitecture.
> Sketch background image

- src/models/tools/drawing/drawing-content.test.ts
- src/models/tools/drawing/drawing-content.ts
This is another variant of the bug fixed in #145. The fix here is to follow the suggestion made in that PR by moving the `selectedButton` out of the content model and into the metadata model.
> Fix draw tool crash switching to four-up view with non-default tool selected

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/geometry-tool/geometry-utils.ts
- src/models/tools/geometry/jsxgraph.d.ts
Fix selection/deselection in four-up view [#162287919]
- as usual, need to scale coordinates
The bug is actually in a JSXGraph function (Board.getAllObjectsUnderMouse()) which doesn't take scaling into account. The fix is to replace it with our own version that does.
> Fix selection/deselection in four-up view [#162287919]

- src/components/canvas-tools/geometry-tool.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
Fix bugs which prevented dragged points from saving/restoring properly [#162356359]
1. Incorrect coordinate reference resulted in Y-only drags not being saved
2. Make sure axis extents are set properly on board creation
- If axis extents are off, JSXGraph's default snap-to-grid behavior restricts points to be visible, which prevents them from restoring correctly in some circumstances because they are incorrectly determined to be out-of-bounds.
> Fix bugs which prevented dragged points from saving/restoring properly

- src/components/canvas-tools/geometry-tool.tsx
The code assumed that only the dragged polygon would receive pointerDown/pointerUp messages. In fact, JSXGraph dispatches pointerDown/pointerUp messages to all objects at the given location. If the "wrong" polygon received the events first, it would clear the intermediate drag cache so that the changed location of the dragged polygon would not be saved. The short-term fix is to have each polygon only clear the portion of the drag cache that it is responsible for. In the long-term it might be better to not have other polygons responding at all. Dragging of overlapped polygons is most likely to occur after copy/paste operations which intentionally overlap polygons.
> Fix drag of overlapped polygons [#162456045]

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/geometry-tool/geometry-utils.ts
- src/models/tools/geometry/jsxgraph.d.ts
Fix bug reported by @sfentress  in which clicking on overlapping polygons could result in selecting one polygon but dragging another.
The fix is to synchronize our notion of draggable/selectable polygon with JSXGraph's.
Note: @sfentress found this while testing one of the previous bug-fixes. I don't believe it's implicated in the recent classroom issue, so it may make sense to hold off on this one until the others are released to production.
> Fix another overlapping polygons drag bug

- src/components/canvas-tools/geometry-tool.tsx
- src/components/canvas-tools/geometry-tool/geometry-utils.ts
Tweak overlapping polygons bug-fix to preserve selection in read-only views [#162513469]
> Tweak overlapping polygons bug-fix

- src/curriculum/moving-straight-ahead/moving-straight-ahead.json
- src/curriculum/unit-template.json
- src/index.tsx
- src/utilities/url-params.ts
Support multiple unit files with url parameter to select desired unit [#162777044]
- add template for `moving-straight-ahead.json`
Add URL parameter `unit=msa` to specify Moving Straight Ahead, `unit=s&s` or no unit parameter at all for Stretching and Shrinking.
> Support multiple unit files with url parameter to select desired unit [#162777044]

- cypress/integration/image_tool_spec.js
- cypress/integration/workspace_test_spec.js
- package.json
- src/components/tools/drawing-tool/drawing-layer.tsx
- src/components/tools/geometry-tool/geometry-tool.tsx
- src/components/tools/image-tool.sass
- src/components/tools/image-tool.tsx
- src/index.tsx
- src/lib/db-types.ts
- src/lib/db.ts
- src/lib/firebase.ts
- src/models/image-map.test.ts
- src/models/image-map.ts
- src/models/image.ts
- src/models/stores/stores.ts
- src/models/tools/drawing/drawing-content.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-image.ts
- src/models/tools/image/image-content.ts
- src/utilities/image-utils.ts
- webpack.config.js
These changes will change our image storage mechanism from using Firebase Storage to storing the images as base64 strings in the realtime database.
**Important safety note** Testing this code on this branch in demo mode will add images that can only be retrieved if the users are using the same branch. The URL scheme will not be recognized if you add an image while testing on http://collaborative-learning.concord.org/branch/image-storage/?demo then view the same user's documents on Master, for example. 
Additional refactor notes: Goals of the refactor beyond what @dstrawberrygirl had done:
- Fix lingering content synchronization issues (e.g. images not appearing in My Work thumbnails).
- Consolidate as much of the functionality as possible in common/utility code to simplify adding support …
> Image storage change to Realtime Database

- src/components/tools/geometry-tool/geometry-tool.tsx
- src/models/tools/geometry/geometry-utils.ts
- src/models/tools/geometry/jxg-polygon.ts
- prevent selection of points/edges under polygons
- newly pasted objects/points are automatically selected
- increase offset of multiple pasted polygons
> Geometry: fix layered selection issues

- src/components/tools/geometry-tool/geometry-tool.tsx
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
- delay before calling `freeBoard()` in `componentWillUnmount()`
- let JSXGraph generate unique board IDs
The error occurred because we call JSXGraph's `freeBoard()` function to dispose of the board in the `componentWillUnmount()` method of the `GeometryToolComponent`. The problem is that JSXGraph invokes some asynchronous functions via `setTimeout(..., 0)` which were completing after our call to `freeBoard()`. The solution here is to use `setTimeout(freeBoard(), 100)` to delay until after the asynchronous JSXGraph operations have completed.
The second issue, which was confirmed while debug the first, is that we were specifying UUIDs for each board in our content. However, since multiple React components can use a single content object, this resulted in the creation of duplicate board …
> Fix updateText() rollbar error

- src/components/navigation/right-nav.sass
Adjust CSS so right nav has proper height which allows all content to be displayed onscreen when scrollbars are present.  A more concise, less intrusive way to handle right nav scrolling.
[#163036885]
> Allow all right nav content to display when scrolling

- cypress/integration/learning_log_test_spec.js
- src/components/navigation/bottom-nav.sass
- src/components/navigation/bottom-nav.tsx
- src/components/navigation/right-nav.sass
- src/components/navigation/right-nav.tsx
- src/components/thumbnail/class-logs.tsx
Keep tab components loaded after they are initially displayed to prevent the component from reloading its content everytime the user clicks on a tab button.  Prevent initial loading of content until transition is complete.
[#163028478]
> Make rightnav more responsive when loading content

- cypress/integration/teacher_test_spec.js
- src/components/document/document.tsx
- src/components/teacher/teacher-dashboard.sass
- src/components/teacher/teacher-dashboard.tsx
- src/components/teacher/teacher-group-tab.sass
- src/components/teacher/teacher-group-tab.tsx
- src/components/teacher/teacher-student-tab.sass
- src/components/teacher/teacher-student-tab.tsx
- src/components/teacher/teacher-support.sass
- src/components/teacher/teacher-support.tsx
- src/components/teacher/teacher-supports.sass
- src/components/teacher/teacher-supports.tsx
- src/components/vars.sass
- src/lib/db-listeners/db-supports-listener.ts
- src/lib/db-types.ts
- src/lib/db.ts
- src/lib/firebase.ts
- src/models/curriculum/section.ts
- src/models/stores/groups.ts
- src/models/stores/supports.test.ts
- src/models/stores/supports.ts
In addition to class supports, teachers can now author supports for a specific group or user through the dashboard. On top of that, supports can target a specific problem section in addition to targeting an entire problem.
The overall implementation looks something like this:
- When a support is created, note its target section + audience. Audience consists of an enum value (class, group or user) and an identifier (undefined, groupId or userId respectively). 
- Store the support in Firebase, using the target section and audience to create the correct path
- Listen to the supports path. When a change is received, the audience type (class/group/user) will be at the root, and all supports of that type for the offering will be beneath it
- Loop through the supports in the change and construct …
> Group + User Supports by Section

- cypress/integration/canvas_test_spec.js
- cypress/integration/left_nav_test_spec.js
- cypress/integration/workspace_test_spec.js
- cypress/support/commands.js
- cypress/support/elements/LeftNav.js
- cypress/support/elements/Workspace.js
- src/components/navigation/left-nav.sass
- src/components/navigation/left-nav.tsx
Once a tab is clicked on the left nav panel, the tab contents will now stay loaded.  This is to prevent lag caused by reloading content every time a tab is clicked.  
As a result, the Cypress tests needed to be updated to accommodate this new structure.  Previously, we loaded a single tab at a time, so there was always a single "open" button to load the workspace.  If, for example, you wanted to load the Initial Challenge workspace, you simply clicked on the Initial Challenge tab and then clicked on the Open button.  Now, however, multiple tabs, each with their own Open button, might be loaded at the same time.  Hence we need to be more explicit when loading a workspace to ensure that we target the correct open button.  @kevinsantos-cc @eireland I'm open to suggestions when it comes to …
> 163028478 load left nav improvements

- src/components/tools/geometry-tool/geometry-tool.tsx
Waiting too long to call freeBoard() in componentWillUnmount() confuses JSXGraph.
The previous fix added a setTimeout() call to allow any JSXGraph asynchronous operations to complete. An arbitrary timeout of 100ms was chosen. This had adverse side effects that were visible when switching between views (for instance), and so the timeout was reduced to the minimum value, which still is sufficient to eliminate the original bug without introducing the new issues.
> Re-fix rollbar updateText() bug

- src/components/document/document-content.tsx
- src/components/toolbar.tsx
- src/components/tools/tool-tile.tsx
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/document.ts
This adds the ability to drag in toolbar buttons in order to insert tools at specified locations. The ability to click to add tools to the bottom is retained.
The bulk of this work is simply refactoring existing code in order to support the ability for the `document-content` to easily create a new tile of a type, and then move that tile to a new location.
A little bit of verbose code was added to the moving of the newly-created tiles, to support the moving sidecar text tiles alongside the geometry tiles.
The only real new code is 4fa4082, which makes the tool buttons draggable, and adds a data field that tells `document-content.tsx` which new tile to create.
> Drag toolbar buttons to create tools; and create in visible canvas

- s3_deploy.sh
Whitespace error was causing a problem moving files in tag builds such as this: https://travis-ci.org/concord-consortium/collaborative-learning/builds/476702027
> Fix tagged deployment on Travis

- src/components/tools/geometry-tool/geometry-tool.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-dispatcher.ts
In his movable line PR (#224) @ekosmin encountered the need for some geometry improvements that I had already made as part of my linked table-geometry work. This PR extracts those pieces for common use.
- setElementColor() supports clientFillColor and clientStrokeColor
- applyChange() can return multiple new elements
- applyChange() dispatches delete/object by object type
> Common geometry improvements

- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-changes.ts
Copy properties from change history to clipboard on copy [#163629494]
In addition to the basic properties like label and position, we need to copy any other properties that were set for the point (or any copied object).  To do so, we walk the changes array gathering properties relevant to the objects being copied.
> Fix snap behavior of copied points

- src/components/tools/geometry-tool/rotate-polygon-icon.tsx
Note: this is also apparently the source of some of our rollbar error reports.
> Fix rotate polygon crash logged by @sfentress [#163803381]

- src/models/tools/geometry/geometry-content.ts
Fix copy polygon behavior after selection changes introduced by annotation feature [#163922781]
Prior to the annotation feature polygons were not explicitly selected at the model layer; they were simply assumed to be selected if all of their vertices were selected. Code that assumed that polygons would not be among the selected objects must be updated to account for that possibility. In this case, the copy code ends up copying the same polygon twice -- once because it's now selected and once because all of its vertices are selected.
Note that polygons that were copied in this way retain this "corruption", so it may still be possible to find polygons that can't be rotated (or duplicated) if they were copied/pasted by the affected version of the code.
> Fix copy polygon behavior after selection changes introduced by annotation feature

- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-changes.ts
- src/utilities/graph-utils.test.ts
- src/utilities/graph-utils.ts
- uses CODAP tick/label heuristic
This adds support for a new `axisRange` field in the import schema for geometry tiles:
```json
"board": {
"axisMin": [-3, -3],
"axisRange": [60, 40]
}
```
The `axisRange` property specifies a desired total axis range given a prototypical tile of size 480x320. (These round numbers approximate the default size of a tile on a laptop screen.) Since the ratio of the sizes is 3x2, any `axisRange` values in a 3x2 ratio correspond to a 1:1 aspect ratio, i.e. the same scale factor on each axis and a perfectly square grid. Tiles larger or smaller than 480x320 will show more or less range as appropriate. Note that the `axisRange` is the total axis range, so the expected maximum value will be affected by the `axisMin` value as well as the size of the tile. As a …
> Support arbitrary axis scales in curriculum authoring [#163750284]

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/jxg-movable-line.ts
This allows the line slope to be changed even after a line is selected during movement.
> Moving a control point deselects the line

- src/components/document/document.sass
- src/components/document/document.tsx
- src/components/header.sass
- src/components/header.tsx
- src/components/toolbar.sass
- src/components/tools/drawing-tool/drawing-tool.sass
- src/components/tools/geometry-tool/geometry-tool.sass
- src/components/tools/tool-tile.sass
- src/components/vars.sass
Buttons, icons, toolbars should match UI specs [#163635414]
- Adjust appearance of document toolbar to match UI specs
- Adjust title bar and status bar
- Adjust geometry widgets
- Adjust drawing tool height
The introduction of blueprint.js follows the general CSS best-practice of defaulting to `box-sizing: border-box` rather than the browser default of `box-sizing: content-box`. This has the effect of making buttons, icons, etc. smaller because any borders, padding, margins are included in the size.
[* { Box-sizing: Border-box } FTW](https://www.paulirish.com/2012/box-sizing-border-box-ftw/)
[Inheriting box-sizing Probably Slightly Better Best-Practice](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/)
[International box-sizing Awareness …
> Buttons, icons, toolbars should match UI specs [#163635414]

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-object.ts
- src/models/tools/geometry/jxg-point.ts
- src/models/tools/geometry/jxg-polygon.ts
- src/models/tools/geometry/jxg-vertex-angle.ts
- src/utilities/js-utils.ts
Fix several bugs with polygons created from linked table points
- user should not be able to rotate them (rotate button should not appear)
- deleting them can orphan angle labels [#163930085]
- after deleting a linked polygon with an angle label, cannot make another polygon with those points
> Fix several bugs with polygons created from linked table points

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
Due to content lifetime issues, the code could occasionally generate duplicate IDs for JSXGraph DOM elements, which justifiably confused JSXGraph.
In this scenario, moving the tile causes a new JSXGraph instance to be generated and the original JSXGraph instance to be destroyed. In the process of removing the DOM elements of the board being destroyed, the duplicate IDs could result in the corresponding elements being removed from the new board rather than the old one.
> Fix disappearing geometry bug [#163994734]

- src/components/tools/table-tool/table-tool.tsx
- src/models/tools/table/table-content.ts
- can't access content from `indexValueGetter()`
> Fix use-after-delete error from MST

- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-table-link.ts
Copies of linked points should snap to grid, even though linked points do not [#164122904]
> Copies of linked points should snap to grid [#164122904]

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-dispatcher.ts
This fixes two separate bugs:
First, listeners were not added to axes after they were redrawn during an undo. This was fixed by returning the axes along with the board during the call to `create`. This was complicated slightly by the fact that some code expected a board to be returned by board creation, so that code needed to be updated to accommodate an array containing a board.
The next issue was that undo axis rescaling was broken. Basically, the issue was that the bounding box was not being updated when the board was "created" during an undo.
There is some tech debt touched by this fix, but it is not made worse by it, so I opted to leave it alone. I'll point out where that happened, let me know if you think it's worth addressing
> Fixing Scaling + Undo

- cypress/integration/table_tool_spec.js
- src/components/tools/table-tool/data-table.tsx
- src/components/tools/table-tool/table-tool.tsx
- the basic behavior of completing cell edits is simply a flag passed to ag-grid
- the harder part is making sure that completion of edits of the local/input row result in addition of the new row to the table
> Complete cell edits when table loses focus [#164152746]

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/document/document-content.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-table-link.ts
- src/models/tools/table/table-content.ts
There were several related issues at work here:
- During publication tile IDs are mapped to new IDs. Since linked actions contain tile IDs, linked actions need to be updated during publication.
- When processing linked actions, table must validate that the corresponding geometry tile is present.
- When processing linked actions, the geometry tile must validate that the corresponding table tile is present.
With these changes, publication of a document should retain any table-geometry links, but copying a linked table or graph to a new document (that doesn't contain the other end of the link) should result in an unlinked table or graph.
> Fix publication of documents with linked tables/geometries

- CHANGELOG.md
- package-lock.json
- package.json
- Log table changes
- More cypress test coverage
- Bug fixes
|---|---|---|
| index.css | 476,805 bytes | 0.0% |
| index.js | 3,899,990 bytes | 0.0% |
> Release 0.5.1

- src/lib/auth.ts
- src/lib/db-listeners/db-groups-listener.ts
This is the fix we discussed for this rollbar error:
https://rollbar.com/concordconsortium/CLUE/items/63/
`self` was `undefined` for some reason, but we now use the ID we read from Firebase so we no longer depend on `self`.
There was one issue with the fix that took me some thinking to resolve. When we read `rawUsers` from the Firebase snapshot, it's normally a map e.g. `{1001: user, 1002: user}` etc. However, since Firebase doesn't have explicit array support, it can get interpreted as an array by accident for small user IDs! So if a group only has a single user with ID 1, `rawUsers` will instead be an array: `[empty, user]`. Previously, we were using `Object.keys` to get the IDs from that list, which interestingly enough works correctly i.e. it returns `[1]`. Special considerations …
> Fixed error reading uid from undefined "self" field on group user

- src/components/tools/geometry-tool/axis-settings-dialog.tsx
- src/components/tools/geometry-tool/comment-dialog.tsx
- src/components/tools/geometry-tool/movable-line-dialog.tsx
Last bug found by @eireland - key presses on dialogs were reaching the board, so backspace deleted highlighted elements, you could undo actions etc. Now I'm stopping key propagation in all geometry dialogs.
Of course, this is another PR that shows the need to eventually refactor all the dialog code...
> Preventing key presses in geometry dialogs from propagating to the board

- src/components/document/document-content.tsx
- src/components/document/tile-row.tsx
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/geometry-tool/geometry-shared.tsx
- src/components/tools/geometry-tool/geometry-tool.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/tool-tile.tsx
@ekosmin I think this is ready for re-review with an eye toward including it in the next build (0.5.2/0.6.0).
This is mostly elimination of tech debt based on a better understanding of how this is supposed to work. It's not a priority for the 0.5.1 release and would probably be better to wait until we get some more testing on it.
- Set `tabIndex` property to 0 or -1 as appropriate, rather than trying to assign unique `tabIndex` values
- Move responsibility for checking/setting tile selection from `GeometryContentComponent` to `GeometryToolComponent`
cf. https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#Building_keyboard_accessibility_back_in
> Improve tabbing behavior

- cypress/integration/group_chooser_spec.js
- src/components/app-content.sass
- src/components/app-content.tsx
- src/components/app.tsx
Minor code refactor of general interest to CLUE that simplifies the kind of application genericization required to support DataFlow.
- move files from `src/components/group` to `src/components`
- rename CSS class from `.group-view` to `.app-content`
- update cypress tests
> Rename `GroupViewComponent` to `AppContentComponent`

- src/models/tools/geometry/jxg-movable-line.test.ts
- src/models/tools/geometry/jxg-movable-line.ts
Graph control points are no longer snapped to the grid, and bounding boxes are calculated correctly during control point calculation.
> 166111125 simple slope fix

- src/lib/db-listeners/index.ts
Fix listeners when loading empty document -- caused data loss in classroom
> Fix load/reload of empty document prevents subsequent document saves

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-comment.ts
- src/models/tools/geometry/jxg-movable-line.ts
- src/models/tools/geometry/jxg-object.ts
- src/models/tools/geometry/jxg-point.ts
- src/models/tools/geometry/jxg-types.ts
Deal with potentially overlapping movable line labels by allowing the user to drag them to new locations. Attempting to re-layout movable line labels automatically is left as a potential (expensive) future improvement.
> Make movable line labels/equations draggable

- src/models/tools/geometry/jxg-object.ts
We no longer unsuspend when updating a text anchor, only before setting text positions. This allows for fewer unsuspend/suspends while updating comments and labels correctly.
> Only unsuspend the board before updating text object positions

- package-lock.json
- also updates version number
The updates fixed are related to nested dependencies on `tar` and `fstream`.
Note: I received an email from GitHub about a security vulnerability in js-yaml:
```
Known high severity security vulnerability detected in js-yaml < 3.13.1
defined in package-lock.json.
package-lock.json update suggested: js-yaml ~> 3.13.1.
```
but we're already using js-yaml 3.13.1 on every branch that matters (e.g. master/production). I don't know what branches GitHub would be looking at and the message doesn't say.
> Run `npm audit fix` to fix security vulnerabilities

- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-comment.ts
- src/models/tools/geometry/jxg-image.ts
- src/models/tools/geometry/jxg-object.ts
Note: I'm creating this PR for @ekosmin , who did the underlying work before he left for vacation.
This PR is based on PR #300 , which should be reviewed/merged first and then this PR rebased on top of master once the other has been merged to master. It eliminates several hacks/kludges introduced to deal with the consequences of the firebase rebound, which can now be eliminated thanks to the elimination of the rebound itself.
- Geometry: remove timeout for axis rescaling
- Geometry: remove timeout from `handleTableTileDrop()`
- Table: remove obsolete timeouts in data tables
> Remove gratuitous timeouts now that firebase rebound has been removed

- package-lock.json
- package.json
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/table-tool/data-table.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/text-tool.tsx
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-movable-line.ts
- src/models/tools/geometry/jxg-vertex-angle.ts
- src/models/tools/table/table-content.ts
- tsconfig.json
Update to TypeScript 3.5 [#167279884]{294}
- add explicit types where appropriate
- make `getTableContent()` a global function (rather than a view on `GeometryContentModel`)
- make `getGeometryContent()` a global function (rather than a view on `TableContentModel`)
- enable `noImplicitThis` in `tsconfig.json`
> Update to TypeScript 3.5

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/utilities/node.ts
Store sensor channel values in the `NodeChannelInfo` which is passed to each sensor node.  If a user changes a sensor node such that it has a new active sensor (via the sensor select dropdown), we can immediately set a sensor value from the `NodeChannelInfo` stored in the node rather than having to wait for a new sensor value to be received and the `hubStore` to be updated which in turn triggers a node value update (in the case where a sensor value is stable this could be a noticeable period of time).
> Store channel value in NodeChannelInfo so initial sensor node value is correct

- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
These changes are needed to ensure node controls (such as the sensor or relay selection dropdown controls) are properly created when restoring nodes from the program JSON representation.  In particular these changes have been tested against the Rete save and reload functions `editor.toJSON()` and `editor.fromJSON(data)` .  Extra checks have been added to verify if selected node hub channels are still valid when reloading nodes.  If a selected channel is no longer valid (e.g., hub is offline or sensor has been unplugged), set the selected channel to "none".
> Restore node controls if reloading a node, remove selected channel if unavailable

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/factories/generator-rete-node-factory.tsx
Update to use correct terminology on generator node.  User set the "period", not the "frequency."
> Use "period" in generator blocks

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/utilities/node.ts
Small changes in service of ensuring sensor nodes contain and restore proper values:
- uniquely identify each sensor node's relationship to a physical sensor by the component id alone (do not include hub id).  With this change the following will be permitted:
program contains sensor block connected to SensorA which is plugged into Hub1
user unplugs SensorA from Hub1 and plugs into Hub2
sensor block will still show values from SensorA (despite changing hubs)
- ensure we match sensor block to physical sensor based on a standardized type string which may not match the human readable sensor name.
- set initial value when setting sensor from dropdown
> Sensor node updates

- src/dataflow/components/nodes/controls/relay-select-control.tsx
Minor fix to ensure relay nodes stores relay value based on component id alone and do not use hub id.
> Fix relay selection

- src/dataflow/components/dataflow-program.tsx
Ensure that sensor and relay updates now occur on the program heartbeat.
- there is now a single autorun function that handles keeping track of new hubs and channels, removed hubs and channels, and updated sensor values
- the heartbeat function now updates sensors with new values, updates sensor and relays with channel info used in dropdown menus, updates generators based on functions, and updates recent node values used for 15 second plots
> Update sensors and relays on program editor heartbeat

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/hub-list.tsx
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/lib/iot.ts
- src/dataflow/models/stores/hub-store.ts
- src/dataflow/utilities/node.ts
Read and store sensor plug number.  If we have a hub with 2 sensors of the same type (e.g., 2 temperature sensors), display the plug number to help distinguish the sensors.  This is used in the control panel and the sensor/relay nodes.
> Add plug numbers to distinguish sensors of same type

- src/dataflow/components/nodes/controls/value-control.tsx
- src/dataflow/components/nodes/factories/math-rete-node-factory.tsx
- src/dataflow/utilities/node.ts
This adds rounding to displayed node values which prevents nodes from displaying values like (.3333333333....).  This is essentially the same rounding mechanism and equation used in Dataflow 2.0:
- no more than 3 decimal digits are shown for nodes other than the number node (where the user can enter a value such as 1.11111 and the entered value is displayed)
- internally stored node values are not changed - we only adjust the value that is displayed in the node (so raw values are still passed for further calculations downstream).
> Round numeric values computed by node functions

- src/dataflow/lib/iot.ts
- src/dataflow/models/stores/hub-store.ts
Request the array of thing groups for each thing that is registered on the AWS IoT server.  Store this information in  the HubStore.  Eventually this will be useful to organize and sort things (hubs) - particularly when filtering and displaying hubs to users.
> add thing groups to hub store

- src/dataflow/components/dataflow-program.tsx
Fix call to updateChannelInfo for relay nodes to prevent exceptions (I thought this was in the original PR but perhaps was squashed by a merge or rebase along the way).
> Fix updateChannelInfo function call

- src/dataflow/components/dataflow-program-toolbar.sass
- src/dataflow/components/dataflow-program-toolbar.tsx
- src/dataflow/components/dataflow-program.sass
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/utilities/node.ts
Add initial, unstyled Dataflow program toolbar.  Includes additional changes and updates to facilitate toolbar functionality:
- remove default program when creating program tile
- add styling to node selection
- add function to reset nodes (removes array of recent values and timing info)
- add function to clear nodes (remove all nodes)
- add function to delete a single node 
- remove the Rete context menu (right click to add nodes)
> Add dataflow program toolbar

- src/dataflow/components/dataflow-program.sass
- src/dataflow/components/nodes/controls/dropdown-list-control.sass
- src/dataflow/components/nodes/dataflow-node.sass
- src/dataflow/components/nodes/dataflow-node.tsx
- src/dataflow/components/nodes/factories/dataflow-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/generator-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/logic-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/math-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/number-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/relay-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/sensor-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/transform-rete-node-factory.tsx
Custom Rete node styling changes in service of adding the upcoming data storage node (which needs greater control over the layout of node controls).  I wanted to break these changes into their own PR to keep the size of the upcoming data storage PR to a minimum and to isolate a majority of the UI-specific changes so they're easier to review.  The big change here is adding `dataflow-node.tsx` which which exports `DataflowNode` which allows us to control the layout and display of the inputs, outputs, and controls of each node (instead of using the Rete defaults).  The constructor of each node factory sets `data.component = DataflowNode` to specify that we should use the layout and display specified in `DataflowNode`.  This code is lifted from the Rete example of how to make a custom node …
> Update node styling

- src/dataflow/components/dataflow-program.tsx
Small fix for bug found while testing.  Clear list of selected nodes after deleting selected nodes or subsequent deletion attempts might reference invalid node(s).
> Clear list of selected nodes after node deletion

- src/dataflow/lib/iot.ts
- When publishing MQTT topics messages, include quality of service parameter = 1 (at least once) allowing for consistent message delivery.  More reading on topic here:
https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/
- Change `SEND_INTERVAL` to 1 second, this allows sensor messages to be sent from the hub every second which is the desired interval for use in classrooms (we were using 2 seconds to cut back on message traffic during initial testing, but we're at the phase of the project where we need to be using and testing the interval which is required for actual classroom use).
> Update IoT QoS and send interval

- src/dataflow/components/nodes/controls/num-control.tsx
- call stopPropagation() for `pointerdown` events
Following the suggestion from [react-render-plugin #3](https://github.com/retejs/react-render-plugin/issues/3#issuecomment-517909448) we add a native event listener for the `pointerdown` event. In our case we use a hooks-based approach so that we can (theoretically) remove the native event listener when the `NumControl` is unmounted.
> Prevent NumControl clicks from dragging Rete nodes

- src/dataflow/components/dataflow-program-toolbar.tsx
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/dropdown-list-control.tsx
- src/dataflow/components/nodes/controls/num-control.tsx
- src/dataflow/components/nodes/controls/plot-control.tsx
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/components/nodes/controls/text-control.sass
- src/dataflow/components/nodes/controls/text-control.tsx
- src/dataflow/components/nodes/controls/value-control.tsx
- src/dataflow/components/nodes/factories/data-storage-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/generator-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/logic-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/math-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/number-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/relay-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/sensor-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/transform-rete-node-factory.tsx
- src/dataflow/utilities/node.ts
Adds a new data storage node with variable inputs (node adds a new input when user connects a node and removes input when input node is disconnected).  Data storage node contains a plot (like other nodes) that can display one or more graph traces for each current input (previous inputs that are no longer present but are contained in the 15 second node history are not shown).  
User can only have a single data storage block.  Toolbar button is disabled if data storage block is present.  
To facilitate these changes, the `plot-control` can now have multiple graph traces.  `recentValue` in node data is now stored as an object to allow storage of multiple node values needed for data storage node.  A new `text-control` Rete control is used in data storage node so user can enter sequence name …
> First pass data storage block

- src/components/tools/tool-tile.tsx
- src/utilities/dom-utils.ts
- adding `.disable-tile-drag` class disables all tile drags
- adding `.disable-tile-content-drag` class disables dragging tile from content, but allows dragging tile from drag handle in upper right corner
Will be used in `dataflow` branch to disable tile content drags.
> Provide mechanism for clients to disable tile drags

- src/curriculum/dataflow/dataflow.json
- src/dataflow/components/tools/dataflow-tool.tsx
- Configure right-nav tabs for Dataflow
- "Class Work" => "Shared Work"
- no "Class Logs" tab
- Prevent Dataflow tile content drags
> Configure dataflow branch

- src/dataflow/components/nodes/controls/custom-hooks.ts
- src/dataflow/components/nodes/controls/dropdown-list-control.tsx
- src/dataflow/components/nodes/controls/num-control.tsx
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/components/nodes/controls/text-control.tsx
Take changes to handle Rete node drag state that were originally implemented in the `NumControl` and extend them to the `DropdownListControl`, `RelaySelectControl`, `SensorSelectControl`, and `TextControl` to prevent errant node drags when user is working with node controls.  Minor change to make hand-rolled dropdowns respond to `mouseDown` instead of `click` so they more closely mimic the standard `select` controls.
> integrate rete node drag fixes into all control types

- src/dataflow/components/dataflow-program.tsx
Minor change to adjust initial node positions so there is less node overlap to facilitate automated testing.  I'm using the number node size for layout (some nodes are obviously bigger, but the goal is to shrink nodes down to sizes closer to the number node size as we restyle the nodes). @eireland can you check if this works for you?
> Update initial node positions

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
Use `react-sizeme` so we can monitor changes to the `DataflowProgram` component's height and width.  When changes are detected, signal to the Rete editor that its view needs to resize as well.  This eliminates cases where the program tile is resized, but the editor does not resize.  This caused cases where nodes were not properly displayed as the were moved (since they were outside of the editor view space.  Recommendation to call `editor.view.resize()` comes from this Rete issue:
https://github.com/retejs/rete/issues/108
> Update Rete editor size based on container resize to show editor content

- src/curriculum/dataflow/dataflow.json
- src/dataflow/components/dataflow-program-topbar.tsx
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
- src/dataflow/models/tools/dataflow/dataflow-content.ts
Add ability to save and restore a program tile contents including the Rete program (nodes, connections, positions, etc.), the program run time, and the editor zoom and position.  Also expand the use of read-only state on a program tile to hide and disable appropriate elements.
> 167243673 save reload program

- src/dataflow/components/dataflow-program.tsx
This will make it simpler to match the sensor values with the sensor ids listed in the network diagram.
> No need for hub ids in sensor ids

- src/dataflow/lib/iot.ts
Previous version of sensaurus esp32 hub program and the existing sensaurus hub simulator publish MQTT topic messages which contain current sensor values as a string (such as "1.1" or "5.6"). The newer version of the sensaurus esp32 hub program now sends sensor messages that contains sensor values as a number (such as 1.1 or 5.6). Our internal hub store expects a string. For safety and compatibility (and so that the newest sensaurus does not cause errors when we process a message from it), convert all sensor values to strings before storing.
> Support both string and numeric sensor values

- src/dataflow/components/nodes/controls/num-control.tsx
Minor changes to allow editing of numeric input fields on Rete nodes to be more user-friendly.  Rete examples used `onChange` event to validate input values which made it difficult to use delete or backspace keys, input negative values, etc.  Change to using `onBlur` for validation so user can enter text as they please and then validate input for invalid text when typing is complete and user exits input control.  Also need to maintain the current node value while the user is editing (since a heartbeat program update could request the value).  To do this we keep a node `value` and a node `inputValue`.
> 167638035 num input fixes

- src/dataflow/components/dataflow-program-cover.sass
- src/dataflow/components/dataflow-program-cover.tsx
- src/dataflow/components/dataflow-program-toolbar.tsx
- src/dataflow/components/dataflow-program-topbar.tsx
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
- src/dataflow/models/tools/dataflow/dataflow-content.ts
Modify the `DataflowContentModel` so that a program tile stores the following information about the currently running program: programId, programStartTime, programEndTime.  This is needed to set the program tile state (is a program running?) and to determine if we should show dataset data (does this program have a live or archived dataset?).  At present these values are being set on the tile within the document when the run button is pressed.  In the future, we will need to set these values in a newly created program document (that work is not completed yet).  However, to facilitate displaying dataset data, we will set these values for the current tile on the open document.
I also added some minor changes to set the UI state when running the program.  Left toolbar buttons are disabled and …
> Save program run state

- src/dataflow/utilities/node.ts
One-line change to fix the calculation of the sine generator.
This is what we currently see:
I believe this is what we should see:
> Fix sine period

- src/dataflow/components/dataflow-program-cover.sass
- src/dataflow/components/dataflow-program-cover.tsx
- src/dataflow/components/dataflow-program.tsx
Changes to program editor read-only tile state:
- topbar and toolbar are always shown
- if program is read-only or program is running topbar and toolbar are disabled
- if program is running or tile is read-only, transparent cover is placed over editor to prevent mouse interaction
- if program is running and tile is not read-only, stop button is shown
We will eventually need to handle 1 additional case.  We will need to disable the editor for both the case where a document contains a reference to a running program AND when it contains a reference to a previously run program.  We will need to bring in the personal document changes first and actually spawn new document when user runs program before making those changes.
> Set proper read-only state of program editor tile

- src/components/thumbnail/my-work.tsx
- src/dataflow/components/dataflow-program-cover.sass
- src/dataflow/components/dataflow-program-cover.tsx
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
- src/lib/db.ts
This pull request spawns a new document when a user starts a program. The new document is a copy of the currently open document with additional properties set in the Dataflow program tile to specify a program run id, start time, and end time.  This allows us to have a document with an editable program tile and a document with a read-only program tiles that can display saved data (the "dataset" which we will evenutally need to filter out and put into its own document category).
> Create new document when user runs a program

- src/components/document/document.tsx
When I refactored and consolidated `renderLearningLogTitleBar()` and `renderPersonalDocumentTitleBar()` to `renderOtherDocumentTitleBar()` in #386 I brought back the publishing button on the left hand side instead of the right hand side. This should fix it so it's back on the right hand side. At the moment in the UI the publishing button for `Learning Log` is being blocked by the right nav but it is working. This is fixed in #393 when Learning Log is moved to the main canvas and right nav.
> [#168230323] Display publish button on the right side for other documents

- src/curriculum/dataflow/dataflow.json
Update authored Dataflow unit JSON to use numeric rete node ids.  This prevents bug where node creation overwrites previously created node when saving/restoring.
> Fix authored ids in dataflow unit json

- src/dataflow/components/dataflow-program-cover.sass
- src/dataflow/components/dataflow-program-cover.tsx
- src/dataflow/components/dataflow-program-graph.sass
- src/dataflow/components/dataflow-program-graph.tsx
- src/dataflow/components/dataflow-program.sass
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/utilities/node.ts
This PR adds changes to how graphed data is displayed in the Dataflow program tile:
- allow user to toggle between a show-all and show-recent mode of the graph.  Show-all sets the min and max of the graph based on the program start and end time.  Show-recent sets the min and max based on the actual data points that we have currently acquired.
- show graph as type `time` with `linear` distribution so points are shown on the graph at their actual acquisition time based spacing in relation to one another
- allow user to toggle between mode where graph consumes the entire tile and a side-by-side mode where program and graph are shown together.  This feature is only available on documents containing a program run.
- revise state used to determine if we show program, graph, or both.  Add …
> 168198961 dataset graph updates

- src/dataflow/components/dataflow-program.tsx
This PR adds Dataflow program validation.  Programs are validated before sending them off for cloud execution.  A program must meet the following criteria to be run (if not, an error message is provided to the user and the program is NOT run):
- program must contain a relay node or data storage node (some form of output)
- if program only contains data storage node, then data storage node must have an input connection
- if program contains sensor or relay nodes with a selected relay or sensor (one with a channel id), then we must be able to find the sensor/relay on an active hub (so if the user has a node with a selected sensor that is unplugged/offline/broken/etc. we warn user and prevent program run)
We'll eventually want to get feedback from the DF team about error messaging, and I'm …
> validate program contents before running a program

- src/app-config.json
- src/components/document/document-workspace.tsx
- src/components/thumbnail/my-work.tsx
- src/lib/db-types.ts
- src/lib/db.ts
- src/lib/firebase.ts
- src/models/stores/app-config.ts
- src/models/stores/documents.ts
CLUE by default opens a problem-specific document on launch. In Dataflow, all user documents are non-problem-specific "Personal" documents, and so for Dataflow the application needs to open a Personal document by default. This PR allows this to be specified per application in the application configuration.
With the second commit we also allow the default document content to be specified so that, for instance, Dataflow can specify that a program tile and a text tile should be created by default.
> Default document type and content can be configured in app-config.json

- src/components/document/document-context.tsx
- src/components/document/document.tsx
- src/lib/db-listeners/index.ts
- src/lib/db-types.ts
- src/lib/db.ts
- src/models/document/document.test.ts
- src/models/document/document.ts
This is required for Dataflow to be able to filter documents based on program state, e.g. running, completed, etc. A React context implementation is provided so that clients (e.g. the DataflowProgramComponent) can access the properties.
> Support document properties in metadata for personal/learning log documents

- src/dataflow/components/dataflow-program.tsx
Previously, the `programRunState` could only be set to `Running` in `initProgramEditor()` which is called from `componentDidMount()`. This relied on the fact that switching from a ProblemDocument to a PersonalDocument required a complete reload of the component. Now that we're (correctly) using a PersonalDocument for the editable document, the `DataflowProgram` component is no longer unmounted/remounted, and so we must handle the state change internally.
> Set `programRunState` to `Running` in `runProgram()`

- src/dataflow/components/dataflow-program-toolbar.tsx
- src/dataflow/components/dataflow-program.tsx
These buttons are useful for developers and essential for QA. This just extends @mklewandowski 's earlier work and rebases it to latest Dataflow code.
> Show clear/reset buttons in Dataflow toolbar in Dev/QA modes

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
>Previously, the programRunState could only be set to Running in initProgramEditor() which is called from componentDidMount(). This relied on the fact that switching from a ProblemDocument to a PersonalDocument required a complete reload of the component. Now that we're (correctly) using a PersonalDocument for the editable document, the DataflowProgram component is no longer unmounted/remounted, and so we must handle the state change internally.
This PR handles switching documents for the same reason.
> Update editor state when switching documents

- src/dataflow/components/tools/dataflow-tool.tsx
Call `publish` on document content before creating new program run document to ensure unique tile ids.  Should take care of some of the program state issues that we've been seeing.
> Ensure new documents have unique tile ids

- src/models/document/document-content.ts
- src/models/stores/app-config-model.ts
Some clients were callign `DocumentContent.publish()` for this purpose, but `publish()` JSON.stringifies its return value, which meant that clients were then having to parse the result. Now clients can call the more-appropriately-named `cloneWithUniqueIds()` function and avoid the cost of gratuitously JSON.stringify()/JSON.parse()-ing the result.
> Add cloneWithUniqueIds() function

- src/assets/icons/copy/copy-active.svg
- src/assets/icons/copy/copy-disabled.svg
- src/assets/icons/copy/copy-hover.svg
- src/assets/icons/copy/copy.svg
- src/clue/clue.sass
- src/components/document/document-workspace.tsx
- src/components/document/document.sass
- src/components/document/document.tsx
- src/lib/db.ts
In the workspace title bars for Problem Documents, Personal Documents, and Learning Log Documents, users can now click on an icon to copy an existing document alongside its contents into a new document. Problem Documents and Personal Documents, when copied, become a Personal Document; Learning Log Documents, when copied, become a Learning Log Document.
> [#168011215] Copy Documents via Title Bar Icon 

- src/dataflow/app-config.json
- src/dataflow/components/dataflow-program.tsx
Changes to keep nodes in bounds when editor div changes by zooming program nodes.  As per story requirements:
- ensure program tile takes full vertical space when created
- ensure created nodes are not covered by zoom controls
- zoom nodes to keep them within the visible region when user resizes tile or toggles between graph/side-by-side view (note, this zoom is not saved but only used to aid in displaying the program).
> 167536596 nodes in view

- src/lib/db.ts
- fixes the bug seen in the demo meeting today (published datasets were being incorrectly categorized as published programs in the right nav tabs)
- properties were successfully being written to firebase, but weren't being restored from firebase correctly
- will need to be merged to the Dataflow branch to affect document organization there
> Fixes property propagation for personal publications

- src/dataflow/app-config.json
- src/dataflow/components/tools/dataflow-tool.tsx
Minor changes to facilitate running and complete program documents that do not have a data storage block:
- update the document title 
- show all running and completed programs that do not have a data storage block in the program list using a new `dfHasData` property that can be used to distinguish between programs (editable programs, running programs with no data storage, completed programs with no data storage) and data (all programs that have an associated dataset).
> Update relay program name and relay program document organization

- cypress/integration/full/my_work_test_spec.js
- src/assets/curriculum/moving-straight-ahead/moving-straight-ahead.json
- src/assets/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
- src/assets/curriculum/unit-template.json
- src/clue/app-config.json
- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/models/curriculum/section.ts
- src/models/stores/app-config-model.ts
Document titles for Personal, Problem, and Learning Log documents are configurable through `app-config.json`. This standardised the following new changes:
`My Work`
* `Workspaces I've Created` => `Extra Workspaces`
* `%abbrevInvestigation%` => `Problem Workspaces`
`Class Work`
* `Published Personal` => `Extra Workspaces`
* `Published` => `Problem Workspaces`
* `Published Logs` => `Learning Logs`
`Supports`
* `Just-in-time Supports` => `Problem Supports`
This also applied to the pop ups.
> Label CLUE documents consistently.

- src/assets/curriculum/moving-straight-ahead/moving-straight-ahead.json
- src/assets/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
- src/assets/curriculum/unit-template.json
- src/components/tools/text-tool.tsx
- src/index.tsx
- src/models/curriculum/unit.ts
Placeholder text can now be customised per unit and/or omitted by leaving an empty string.
> [#168771354] Placeholder Text in Text Regions from Units

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
Fixes to Dataflow editor tile to ensure that appropriate tile content heights are used.  Ensure the following:
- initial tile and content height consumes available vertical space
- user tile height changes are respected (for example, user grabs tile bottom bar and resizes tile)
- height is maintained when tile content state changes (program only, graph only, program and graph side-by-side)
Note: these are NOT meant to be long term solutions to handling the tile content height.  This is a simple fix to allow the Dataflow team to continue testing and use of Dataflow 3.0 without encountering glaring UI issues.
> Set height of editor tile content

- src/components/document/document-workspace.tsx
- src/lib/db-listeners/base-listener.ts
- src/lib/db-listeners/db-comments-listener.ts
- src/lib/db-listeners/db-groups-listener.ts
- src/lib/db-listeners/db-latest-group-id-listener.ts
- src/lib/db-listeners/db-other-docs-listener.ts
- src/lib/db-listeners/db-problem-documents-listener.ts
- src/lib/db-listeners/db-publications-listener.ts
- src/lib/db-listeners/db-stars-listener.ts
- src/lib/db-listeners/db-supports-listener.ts
- src/lib/db-listeners/index.ts
- src/lib/db.ts
- src/lib/debug.ts
- src/models/document/document.ts
- src/models/stores/groups.ts
With this change all problem document metadata is monitored but only the document content of those within a student's groups are monitored.
> Simplify group document listening to fix student 4-up view

- src/components/document/document-content.tsx
- src/components/document/document-workspace.sass
- src/components/document/document-workspace.tsx
- src/components/navigation/left-nav.tsx
- src/components/navigation/right-nav.tsx
- src/components/toolbar.tsx
- src/components/tools/image-tool.tsx
- src/components/utilities/image-drag-drop.ts
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/document.test.ts
- src/models/document/document.ts
- src/models/image-map.test.ts
- src/models/image-map.ts
- src/models/tools/image/image-content.ts
Extracted image drag/drop handling from image-tool component to utility library so it could also be used in the document workspace component.
In addition to extracting the existing code new code was added to handle drop/drops of image files and image data uris.
To enable drops anywhere in the workspace styling was added to the workspace component so that it overlays the entire page.
> Added desktop and data uri image drag/drop [#163658625]

- src/clue/app-config.json
- src/components/document/document-workspace.tsx
- src/lib/db.ts
- src/models/stores/app-config-model.ts
- src/models/stores/documents.ts
Users will now have a Learning Log created upon first use of the app with the title `My First Learning Log`. New Learning Logs increment with the default `Untitled` starting from `1` if users do not change their document titles. Create Learning Logs from the right nav has been removed but can be enabled again in the future via `app-config` (`"addDocument": true,`).
> [#168354940] Default One Learning Log

- src/components/document/document.tsx
Hide publish support button on other documents (personal documents and learning logs) for students
Use boolean short-circuit rendering consistently
> Hide publish support button when appropriate

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/dropdown-list-control.sass
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/utilities/node.ts
Small, miscellaneous Dataflow updates that I had stashed locally for a variety of reasons (waiting to bring in to avoid merge conflict, changes were partially complete, etc.).  Changes include the following:
- pass proper units to graph when unit is available (at present only if connection is directly to a sensor), units are not presently shown in graph but are shown in the exported CSV
- ensure proper text formatting is used on sensor and relay dropdown
- ensure proper capitalization is used in math, logic, transform, generator, and sensor node dropdowns
- use node name, not node type when displaying node to user (for example, a soil moisture sensor should present itself as "Soil Moisture" not "soil-moisture")
> Update node UI, ensure proper units are sent to graph component

- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/models/document/document.ts
- src/models/stores/app-config-model.ts
Properties is now supported for document labels through AppConfig in `documentLabelProperties`.
As an example this is necessary to support Dataflow's `Program` and `Data` which are both Personal Documents and needs to be merged to further work on labeling Dataflow documents.
> [#168917124] Support Properties for Document Labels in AppConfig

- src/components/document/tile-row.tsx
- src/components/tools/image-tool.sass
- src/components/tools/image-tool.tsx
- src/components/tools/tool-tile.tsx
Uses `contain` to ensure image is letterboxed and fully-visible, no matter how small the container, and adds ability for a tile to `requestRowHeight`, which sets the row to the desired height.
> Fit image in tile

- src/assets/curriculum/moving-straight-ahead/moving-straight-ahead.json
- src/assets/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
- src/clue/app-config.json
- src/clue/components/sixpack-right-controls.tsx
- src/components/demo/demo-creator.test.tsx
- src/components/document/document-workspace.tsx
- src/components/navigation/left-nav.tsx
- src/components/teacher/teacher-support.tsx
- src/lib/db-types.ts
- src/lib/db.ts
- src/lib/firebase.ts
- src/models/curriculum/problem.test.ts
- src/models/curriculum/section.test.ts
- src/models/curriculum/section.ts
- src/models/curriculum/unit.ts
- src/models/document/document-content.ts
- src/models/document/tile-row.ts
- src/models/stores/app-config-model.ts
- src/models/stores/supports.test.ts
- src/models/stores/supports.ts
- src/models/stores/ui.test.ts
- src/models/stores/workspace.ts
- src/models/tools/placeholder/placeholder-content.ts
- src/models/tools/tool-tile.test.ts
- src/models/tools/tool-tile.ts
- src/models/tools/tool-types.ts
Implements necessary infrastructure to support section headers, including code to automatically add section headers to newly created problem documents and to query the document for the number of tiles in a particular section.
@mklewandowski will be submitting a subsequent PR to attach the UI he's been working on to this infrastructure.
> Section headers infrastructure

- cypress/integration/full/graph_table_integraton_test_spec.js
- src/assets/curriculum/moving-straight-ahead/moving-straight-ahead.json
- src/assets/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/tool-tile.tsx
- src/models/curriculum/investigation.ts
- src/models/curriculum/problem.test.ts
- src/models/curriculum/problem.ts
- src/models/curriculum/section.ts
- src/models/curriculum/unit.ts
- src/models/stores/stores.test.ts
- src/models/stores/stores.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-movable-line.ts
- src/models/tools/tool-tile.ts
Add isFeatureSupported() and getDisabledFeaturesOfTile() functions
add `disabled` property to UnitModel, InvestigationModel, ProblemModel, and SectionModel
GeometryLinkedTables -- disables linking tables to geometry tiles
GeometryMovableLineEquation -- disables display of movable line equation
`disabled` features property propagated down to TileContentMetadata
> Support for selectively disabling tile features

- src/clue/clue.sass
- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/components/utilities/icon-button.tsx
This prevents users from deleting their last Personal and Learning Log documents via both an icon change and additionally as back-up a pop-up error alert message.
> [#168955293] Prevent Deleting Last Personal and Learning Log Documents

- src/components/document/document-content.tsx
- src/components/document/document-workspace.tsx
- src/components/document/tile-row.tsx
- src/components/tools/placeholder-tool/placeholder-tool.tsx
- src/components/tools/tool-tile.tsx
- src/lib/logger.test.ts
- src/models/curriculum/section.test.ts
- src/models/curriculum/section.ts
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/tile-row.ts
- src/models/tools/placeholder/placeholder-content.ts
Newly created CLUE problem documents have sections corresponding to the available sections in the corresponding curriculum content. Empty sections contain a placeholder tile that goes away when content tiles are added to that section.
Notes:
- @mklewandowski did all the UI work. I just refined the model architecture and fixed the bugs.
- this does not include the new heuristics for where new tiles are generated.
> Sectioned documents

- src/components/document/document-content.tsx
- src/components/document/document-workspace.tsx
- src/components/toolbar.tsx
- src/lib/logger.test.ts
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/document.ts
Implements the default tile placement heuristic suggested by @sfentress .
1. New tiles are placed immediately after the last visible non-placeholder/non-section-header row.
2. If there are no non-placeholder/non-section-header rows, then new tiles are placed after the first section header row.
The heuristic was straightforward to implement. The difficulties that arose were related to the fact that there are internal clients (e.g. unit tests) that were relying on the previous behavior so a fair amount of code needed to change to explicitly specify a row rather than relying on the defaulting mechanism.
Testable at https://collaborative-learning.concord.org/branch/default-tile-placement/?demo
Note: this PR is currently based on #490 . That should be merged first and then this can be rebased …
> Implement improved heuristic for placing new tiles

- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/tools/tool-tile.ts
Remember in #491 when I said:
>The difficulties that arose were related to the fact that there are internal clients (e.g. unit tests) that were relying on the previous behavior so a fair amount of code needed to change to explicitly specify a row rather than relying on the defaulting mechanism.
One of those internal clients that needed to change (but was not changed) is the one that handles importing curriculum content. The result was that only one placeholder row would appear (in the first section) in a document of multiple sections. I've added a unit test to test this case (and fixed the bug).
> Fix initial placeholders bug introduced with the change to default insert row

- src/lib/db.ts
Without signout the existing Firebase user seems to be cached by Firestore when signing in with another JWT which causes access errors when switching classes as the classHash in the new JWT is not the correct one.
> Add signout before auth to fix class switching issue

- src/components/document/document-workspace.tsx
- src/components/document/group-virtual-document.tsx
- src/components/teacher/teacher-group-six-pack.sass
- src/components/teacher/teacher-group-six-pack.tsx
- src/models/stores/workspace.ts
This PR adds a full-width document view for the four-up group comparison we have been working on.
It adds a split-panel button to the four-up comparison document for switching.
Its specified in this mockup:
> Add full sized workgroup view for four-up work groups

- src/dataflow/utilities/node.ts
We found this incorrect string today while testing that caused sensor blocks to prompt users with the wrong message.
> Fix sensor select message

- scripts/archive.py
- scripts/dedupe.py
Python scripts for archiving CLUE class contents in firebase. There are two scripts:
- `archive.py` copies the contents of each class in `authed/portals/learn_concord_org/classes` to a corresponding location in `archived/portals/learn_concord_org-{DATE}/classes`
- `dedupe.py` compares (via MD5 hash) the original class contents with the archived class contents and deletes the original as long as they match, with the option to retain specific classes if desired.
These scripts were used to archive the current contents of `authed/portals/learn_concord_org/classes` in preparation for a production release of new CLUE features.
It turns out that the JavaScript SDK for firebase has a maximum single-write size of 16MB, which is insufficient to write the contents of an entire class. In fact, there …
> Scripts for archiving CLUE class contents

- src/dataflow/components/nodes/controls/relay-select-control.tsx
This PR updates the relay block to behave in the same fashion as the sensor block.  If a specific relay is selected on a block, then we leave that relay selected even if we cannot immediately find it.  Relay was still using the old model that was changed for the sensor block over the summer.  This was actually causing a bug when the user refreshed the browser and the initially loaded program contained a relay.  The program would load before we finished communicating with the AWS IoT server, we couldn't find the selected relay for the block, and we set the relay block to "none."  This change will fix this bug and sync sensor and relay selection behavior.
> Remove code that sets selected relay to none if relay isn't immediately found

- .vscode/settings.json
- CHANGELOG.md
- package-lock.json
- package.json
- Release 0.8.0 (cherry-picked from `staging` branch)
- npm audit fix (eliminate `https-proxy-agent` vulnerability)
- `build:debug` script (like `build` but lint allows `console.log` & `debugger`)
- `.vscode/settings.json` simplification
- arguably shouldn't be in the repository at all
- since it is in the repository, it should only specify project-specific settings, not user preferences
> Miscellaneous project tweaks

- src/models/stores/supports.ts
Fix bug in which curricular supports for a single problem were considered multiple publications from the same source document and so only the last one would get displayed.
> Show all curricular supports [#169381641]

- src/models/stores/documents.ts
The teacher dashboard was not showing the latest publication but rather the first publication found for each group member.  This caused the starred publication not to show in the right nav as it filters by latest publication.
Also refactors the document model to use a common function for getting the latest publication from a list of publications and removes use of "this" in two of the model views.
> Fixed missing filter for latest publications in groups

- src/clue/clue.sass
- src/components/document/document.sass
This corrects the margins so that the Share button does not bump up directly next to the side of the toolbar in two-up view, additionally correcting the margins to match the rest of the styling of the toolbar in the single problem document view.
> [#169381657] Fixed Share Button in Two-Up View.

- src/components/link-switcher-menu.tsx
- src/lib/logger.ts
This othen caused a long wait before the page was refreshed.
The first attempt to mitigate this was to use `navigator.sendBeacon` to send a fire and forget log message that isn't cancelled like an AJAX request is when the page unloads.  However we need to be able to set the content-type on the log request and Chrome has disabled setting the content-type for now with `sendBeacon`.
> Removed wait for logging when switching classes or groups [#169345486]

- src/models/stores/supports.ts
>Batten down the hatches!
>I did!
>Well, batten them down again! We'll teach those hatches!
This bug was fixed in [PR #533](https://github.com/concord-consortium/collaborative-learning/pull/533) and then inadvertently unfixed in [PR  #527](https://github.com/concord-consortium/collaborative-learning/pull/527) (which was merged after #533).
> Show all curricular supports (again) [#169604919]

- cypress/fixtures/teacher-dash-data.json
The addition of Investigation 0 (the tutorial) changed the number of problems in the problem popup which broke the teacher dashboard cypress tests. @eireland
> Fix teacher dashboard cypress tests

- src/components/navigation/right-nav.tsx
- src/components/thumbnail/right-nav-tab-contents.tsx
Clear new supports badge when user interacts with supports tab by
- clicking on supports tab to open or close it
- clicking to expand/collapse a supports section within the supports tab
Previously, only switching from another tab to the supports tab would clear the badge
> Clear new supports badge when appropriate

- cypress/fixtures/teacher-dash-data.json
- cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js
- src/clue/components/teacher/sixpack-right-controls.sass
- src/clue/components/teacher/teacher-group-six-pack.sass
This PR is for a very simple tweak to the flex properties controlling the width of the teacher-dashboard's right controls. Without this fix, the width of those controls is a percentage of the browser window's width -- this change keeps the width fixed so the rendering of the controls and buttons don't get all messed up with wide browser settings.
No PT story is associated with this quickie change.
> Small tweak to flex settings for dashboard right-controls (fixed width)

- src/clue/app-config.json
- src/components/app.tsx
- src/components/demo/demo-creator.tsx
- src/components/document/document-workspace.tsx
- src/components/tools/image-tool.tsx
- eliminate use of deprecated `componentWillMount()`
- add redundant map entry for S&S since URL parameter is parsed as `s s` rather than `s+s`
> Eliminate console warnings

- src/models/tools/geometry/jxg-board.ts
- a recent change fixed this for 4-up view but thumbnail views need to be handled separately
> Scale geometry axes appropriately in thumbnail views [#169558066]

- src/clue/clue.sass
- src/components/document/document.tsx
Clicking on a Personal or Learning Log document title in the titlebar will now open up the Rename Workspace dialog for users.
> [#169612763] Edit Document Titles via Document Titles in Titlebar

- cypress/disabled/graph_table_integraton_test_spec.js
- cypress/integration/clue/full/student_tests/canvas_test_spec.js
- cypress/integration/clue/full/student_tests/graph_tool_spec.js
- cypress/integration/clue/full/student_tests/image_tool_spec.js
- cypress/integration/clue/full/student_tests/text_tool_spec.js
- cypress/integration/clue/smoke/single_student_canvas_test.js
- cypress/support/elements/common/Canvas.js
- src/components/document/document-workspace.tsx
From the PT story:
>User-created documents are always "Extra" workspaces. Currently, if you click the new document icon on the title bar of a problem document the dialog says "Create Problem Workspace".
> Fix new document dialog text [#169653637]

- cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js
- src/components/tools/geometry-tool/rotate-polygon-icon.tsx
- src/models/tools/geometry/geometry-utils.ts
In #550, the rotation algorithm was changed to operate in screen (pixel) coordinates rather than the coordinates of the plane (user coordinates in JSXGraph terminology) under the assumption that visual appearance of the geometry should be preserved under rotation. This assumption is incorrect -- in a non-cartesian coordinate system, the visual appearance of the shape must change under rotation if we are to maintain the mathematics of the underlying geometry. In a non-cartesian coordinate system, squares aren't square and circles aren't circular. If those things are important in any particular context, then a non-cartesian coordinate system should not be used in that context. This PR fixes [#169664263] by reverting #550, which reintroduces [#169557380], which is now recognized as the …
> Maintain lengths and angles during rotation [#169664263]

- cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js
- src/components/tools/table-tool/data-table.css
- src/components/tools/table-tool/table-tool.tsx
This PR addresses the table-highlight (also known as "the purple highlight"). With this change, as selections change in a graph, the matching purple highlight changes in the linked table.
Given where we are in the Clue release cycle, the most minimally invasive changes were made.
A few cypress tests were _skipped_, all in the `teacher_dashbaord_spec.js` file, to allow the build to complete and deploy.
See the PT story [169214220] for more context behind this fix.
> 169214220 match colors in links

- src/dataflow/components/dataflow-program.sass
For smaller screens on classroom Chromebooks add a default height. Testing this tomorrow in the office to verify this works on smaller screens!
> [#169654473] Add Program Container Default Height

- src/components/document/document-content.tsx
- src/components/document/document-workspace.tsx
- src/components/tools/tool-tile.tsx
- src/lib/logger.test.ts
- src/lib/logger.ts
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/document.ts
- src/models/tools/tool-tile.ts
Note: this PR is based on #530, which should be merged first and then this should be rebased to master before merging.
- add new `userAddTile`, `userDeleteTile`, `userMoveTiles`, `userCopyTiles` methods to `DocumentContentModel`
- move all logging into the new `user...` methods
- user-initiated actions call the `user...` methods so they are logged
- added logging of `MOVE_TILE` events
In addition
- moved some definitions (components should import definitions from models, not the other way around)
- cleaned up imports (eliminated unused imports, reordered imports, etc.)
- fixed some disabled Logger unit tests
- removed document `section` from log events since documents aren't associated with a particular section any more
- fixed a typo in log events (souceObjectId => sourceObjectId)
> Limit logging of tile events to user-initiated actions [#169490691]

- src/components/document/document.tsx
- src/components/navigation/left-nav.tsx
- src/components/navigation/right-nav.tsx
- src/components/thumbnail/right-nav-tab-contents.tsx
- src/lib/logger.ts
This PR addresses PT Story:
[169755093] logging updates
There are several items mentioned in the story and some of the work had be addressed with previous changes. Here is a list of the status of the numbered issues listed in the PT story.
1) serializedObject contents... **Not addressed; not in the CLUE codebase**
2) We need to log the group share/unshare event. I’d suggest calling the event something like SHOW_WORK, with an added parameter, like “visible” being set to True/False. We’d need to know the documentKey as well.
**When the learner clicks share or un-share, a `SHOW_WORK` event is logged. In additional to all the document parameters, an additional property, `"publishedVisibility"` with have either `"share"` or `"unshare"`.**
3) We need to log clicks to open the left-hand or …
> 169755093 logging updates

- cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js
- cypress/support/elements/clue/TeacherDashboard.js
- src/components/tools/geometry-tool/geometry-tool.tsx
An earlier commit as part of the multi-tile selection PR caused the click to be intercepted for tile selection. With this commit we reintroduce the prior behavior, which fixes the behavior within the geometry tool at the expense of the ability to cmd/shift-click to deselect the geometry tile.
Revert "Fix geometry tool deselection"
This reverts commit cb36316531f878481e7e1e5b82f5e8aa7b134b1a.
> Restore previous multi-select functionality in geometry tool [#169794619]

- src/components/tools/geometry-tool/geometry-content.tsx
- increase offset when pasting multiple polygons in succession
- offset is calculated in pixels, so it's not affected by axis scale
- clicking on a selected polygon no longer creates a new point
> Improve behavior of overlapping polygons [#169558267]

- src/components/document/document.sass
Increase z-index of the sticky note dialog close icon so it's above the drag/drop zones of the underlying document (z-index: 2)
> Fix sticky note dialog close icon weirdness

- CHANGELOG.md
- package-lock.json
- package.json
- Document supports selection of multiple tiles
- Drag/drop multiple tiles in document
- Teacher can publish document as support
- Teacher dashboard styling improvements
- Teacher can send "sticky notes" to individual students/groups
|---|---|---|
| index.css | 499,791 bytes | 1.8% |
| index.js | 4,365,192 bytes | 2.2% |
> Release 1.0

- src/models/document/document-content.ts
When all of the tiles of an existing row are being copied to another row that already has one or more tiles, the code merges the tiles from the source row with those of the destination row and then deletes the source row. In the bug scenario, the code attempts to merge a row with itself, after which it deletes the source (which is also the destination) resulting in the bug. The fix is simply to disallow merging a row with itself (or with a section header row, which has a similar effect).
> Fix `mergeRow()` bugs [#169909893]

- src/clue/components/clue-app-content.tsx
- src/clue/components/clue-app-header.sass
- src/clue/components/clue-app-header.tsx
- src/components/app-header.ts
This is the `master` side of the refactor done in the `dataflow` branch in #602.
> Refactor `AppHeaderComponent` to `ClueAppHeaderComponent`

- cypress/integration/dataflow/full/canvas_test_spec.js
- cypress/integration/dataflow/full/sensor_block_spec.js
- cypress/integration/dataflow/smoke/single_student_canvas_test.js
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/dropdown-list-control.sass
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/lib/iot.ts
- src/dataflow/utilities/node.ts
Improve handling of offline hubs, sensors, and relays so that we keep better track of offline hardware and properly inform user when hardware is offline.  Changes include the following:
- Vet program for missing sensors and relays before running.  If a sensor or relay cannot be found, notify the user of the missing device and give user the option to cancel or go ahead with program run.
- Unify and improve state of relay and sensor editor nodes when a currently selected device is unavailable.  Unify message on nodes and use selected device text box colored background to indicate to user that a device is unavailable.
- Keep track of the timestamp of the last known hub communication (communication occurs when we receive a devices or a sensors MQTT message).  If a hub does not communicate for …
> 168005513 offline sensor reporting

- cypress/integration/dataflow/full/logic_block_spec.js
- cypress/integration/dataflow/full/math_block_spec.js
- src/dataflow/components/dataflow-program.sass
- src/dataflow/components/nodes/controls/dropdown-list-control.sass
- src/dataflow/components/nodes/controls/num-control.sass
- src/dataflow/components/nodes/controls/plot-button-control.sass
- src/dataflow/components/nodes/controls/plot-button-control.tsx
- src/dataflow/components/nodes/controls/sensor-value-control.sass
- src/dataflow/components/nodes/controls/sensor-value-control.tsx
- src/dataflow/components/nodes/controls/text-control.sass
- src/dataflow/components/nodes/controls/value-control.sass
- src/dataflow/components/nodes/controls/value-control.tsx
- src/dataflow/components/nodes/dataflow-node.sass
- src/dataflow/components/nodes/dataflow-node.tsx
- src/dataflow/components/nodes/factories/data-storage-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/generator-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/logic-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/math-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/number-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/relay-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/sensor-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/transform-rete-node-factory.tsx
- src/dataflow/vars.sass
- src/index.html
This PR is primarily made up of CSS changes to update the Dataflow editor nodes to match the current UI spec.  The primary request was updating the portion of each node that displays its current value.  However, the node styling had drifted from the spec in several ways (or certain UI spec requests were never implemented) so a general styling pass was done here.  
The following changes are included:
-restructure order of components in node value output, move values closer to connection pins, move plot button to left
-add coloring to node value output
-update node fonts sizes and colors to match spec
-update node borders, padding, and margins to match spec
-improve handling of text overflow in nodes
-unify text case in text fields of each node
-update icon sizes to match spec
-update plot …
> Update UI of nodes to match spec

- src/dataflow/components/nodes/dataflow-node.sass
Small change to make the node x close button hit box larger so it is easier for the user to close/delete a node.
> Fix hitbox on node close button

- cypress/integration/dataflow/full/canvas_test_spec.js
- src/dataflow/components/dataflow-program-toolbar.sass
- src/dataflow/components/dataflow-program-toolbar.tsx
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/dropdown-list-control.sass
- src/dataflow/components/nodes/controls/num-control.sass
- src/dataflow/components/nodes/controls/num-control.tsx
- src/dataflow/components/nodes/controls/text-control.sass
- src/dataflow/components/nodes/dataflow-node.sass
- src/dataflow/components/nodes/dataflow-node.tsx
- src/dataflow/components/nodes/factories/timer-rete-node-factory.tsx
- src/dataflow/utilities/node.ts
- src/dataflow/vars.sass
This PR adds a new timer node to the dataflow editor.  The timer node outputs the values 1 and 0 over a user defined period.  The user can also specify the units of the period (sec, min, hours).  The timer, unlike other nodes, does not display a numeric value in its value output control, but instead displays `on` and `off` since it is intended to be fed into a relay.
> Add timer node

- cypress/integration/dataflow/full/control_panel_spec.js
- cypress/integration/dataflow/full/header_test_spec.js
- cypress/integration/dataflow/full/workspace_test_spec.js
- cypress/integration/dataflow/smoke/single_student_canvas_test.js
- cypress/support/elements/dataflow/dfHeader.js
- src/dataflow/app-config.json
- src/dataflow/components/dataflow-app-header.tsx
- No default text tile for Dataflow [#170144963]
- Only render Control Panel/Workspace buttons for teachers [#170140529]
Note that the elimination of the Control Panel/Workspace buttons for students required changing/disabling a number of cypress tests.
> Dataflow: No text tile; no control panel for students

- src/dataflow/components/nodes/controls/custom-hooks.ts
- src/dataflow/components/nodes/controls/dropdown-list-control.tsx
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
This PR adds changes to close node dropdown menus when clicks are detected outside of the dropdown list (previously the dropdown stayed open).  Essentially we listen for pointer down events and if we find one that isn't on the dropdown list (save a ref to the list and check if the event target is contained within the list ref), then we close to list (if it is open).
> 168205168 menu cleanup

- cypress/integration/dataflow/full/sensor_block_spec.js
- seems to fail if there's only one sensor of a specific type available
> Disable failing cypress test

- src/dataflow/components/tools/dataflow-tool.tsx
Running a program while comparison view is open now closes the comparison view and shows only the running "dataset" document
Fixes [[#169764811]](https://www.pivotaltracker.com/story/show/169764811)
> Fix running a program while comparison view is open

- src/components/tools/geometry-tool/geometry-content.tsx
The bug was that we were not clearing the drag state properly at the end of a drag, so a subsequent click on a polygon would be interpreted as a request to continue dragging the previously dragged points. The simple fix is to properly clear the drag state at the end of a drag.
> Clear drag state in `endDragSelectedPoints()` [#170243722]

- src/dataflow/components/nodes/controls/dropdown-list-control.sass
Limit dropdown menus on nodes from being shown offscreen (this happens when the list is very long or when using Dataflow on a small screen such as on a Chromebook) by adding a max-height and scrollbars.
> Add max-height and scrollbars to dropdown menus on nodes

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/num-control.tsx
- src/dataflow/components/nodes/factories/generator-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/timer-rete-node-factory.tsx
- src/dataflow/utilities/node.ts
This PR updates the timer and the generator nodes so that they store their period values in seconds rather than in the units specified on the node.  This will prevent the cloud execution from having to change to accommodate the new period units since the period stored in the node data will always be in seconds (e.g., 1 sec is stored as 1, 1 minute is stored as 60, 1 hours is stored as 3600, etc.).
> Update generator and timer to store period value with units as part of calculation

- package-lock.json
- src/dataflow/dataflow.sass
Fixes the PT story for Dataflow:
[170250390] Wherein the filter names don't maintain their height when their respective lists are collapsed.
This was fixed with minimal, surgical changes to the flex-box styling within dataflow's CSS and should have no impact on Clue. (At least, until we what it to have impact on Clue.)
> 170250390 filter names overlap

- src/dataflow/app-config.json
- src/dataflow/dataflow.sass
Adjusting some CSS to complete the problem with overlapping accordion titles. In particular, the PR includes changes to address:
* Sass changes to remove extra pixel of white space between closed accordions;
* Removal of the dataflow "Data Stories" accordions in both My Work and Shared tabs; and
* Sass changes to provide a bit more room on the last document in a scrolling accordion.
All changes are in dataflow files, only.
> 170250390 filter names overlap part 2

- package.json
- src/index.html
- webpack.config.js
Configure application-specific parts of `index.html` from `package.json` `config` property
When merged to Dataflow, will allow Dataflow to configure its `index.html` from its local `package.json` configuration.
> Configure application-specific parts of index.html from package.json

- src/models/document/document-content.ts
This shouldn't happen in theory, but it can result from bugs and it's easy to handle.
> Generalize `isPlaceholderRow()` to work when there are multiple placeholder tiles

- cypress/integration/dataflow/full/logic_block_spec.js
- cypress/integration/dataflow/full/math_block_spec.js
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-value-control.tsx
- src/dataflow/components/nodes/factories/dataflow-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/logic-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/math-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/relay-rete-node-factory.tsx
- src/dataflow/components/nodes/factories/transform-rete-node-factory.tsx
This sets sensor values to NaN (displayed as "__") when they are first initialized, when a sensor can't be found, and when data drops (once the 60-second timeout passes), and passes NaNs through the program, such that any node with a NaN input will have a NaN output.
https://www.pivotaltracker.com/story/show/169755170
https://www.pivotaltracker.com/story/show/168223544 (comes along for the ride)
> Allow NaN in Dataflow programs

- src/components/thumbnail/documents-section.tsx
- src/components/thumbnail/thumbnail-document-item.tsx
- src/dataflow/dataflow.sass
Listens for primary and comparison document changes and auto expands the accordion menu for the section that the document exists in and then scrolls to the item in the list.
NOTE: this uses React hooks as the `DocumentSection` component is a functional component.
> Added current document should be shown in the accordion [#170250414]

- src/components/tools/tool-tile.tsx
- src/dataflow/app-config.json
- src/dataflow/components/tools/dataflow-tool.tsx
- src/models/stores/app-config-model.ts
Note that there a common-code commit which should be cherry-picked to `master` and a Dataflow-specific commit which need not be.
> Disable tile drags for Dataflow [#170411493]

- cypress/integration/dataflow/smoke/single_student_canvas_test.js
- src/dataflow/dataflow.sass
Ultimately, the issue was that the `.list-container` was not accounting for the `.section-header` height, which meant that the last caption could end up underneath the next section header.
> Guarantee last document caption is visible [#170327009]

- cypress/integration/dataflow/smoke/single_student_canvas_test.js
- src/components/document/document.tsx
- src/dataflow/app-config.json
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
Add metadata to documents to allow identification of relay-only output documents [#170329486]
- sort relay-only output documents into the "Relay Programs" category
- hide program toolbar controls for relay programs
> Identify/support "Relay Programs" [#170329486]

- cypress/integration/dataflow/full/canvas_test_spec.js
- cypress/integration/dataflow/full/running-program-spec.js
- cypress/integration/dataflow/smoke/single_student_canvas_test.js
- src/dataflow/components/dataflow-program.tsx
Expand the program vetting in `hasValidOutputNodes` so check ensures the following:
- program must include at least 1 valid output
- a valid output can be either a valid relay node or a valid data storage node
- for a data storage node to be valid, it must have at least one input that has a numeric (non-NaN) value (other inputs can be NaN)
- for a relay to be valid, it must have an input that has a numeric (non-NaN) value and have a currently selected relay device
Note that we cannot simply check the `recentValues` in the `data` on the relay node because a relay must keep its state when the input node has a `NaN` value (and hence the `recentValues` are not an accurate reflection of if an input is valid).  Instead, we must examine the `inputs` to access the actual input node and determine …
> Vet program sensor and relay nodes for valid values

- src/dataflow/components/nodes/controls/value-control.tsx
- src/dataflow/components/nodes/factories/relay-rete-node-factory.tsx
This PR updates the rules regarding the current value of a relay node as follows:
- relays must hold on/off state (1/0)
- if a relay input is invalid, relay reverts to previous known value
- if new relay is created, it starts with value on/1 (this follows the previously defined rule that every relay value other than 0 is converted to on/true - so if the only known value is NaN, then we set the relay to on/1)
> Ensure relays maintains last valid state

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/tools/dataflow-tool.tsx
- src/dataflow/utilities/aws.ts
Pair-programmed with @mklewandowski .
Recent changes to remove the timestamp from the filename resulted in non-unique programRunIds because we were using the filename+timestamp as the runId. This adds the timestamp back when determining the programRunId.
> Append startTime to program title to create unique runId

- src/components/thumbnail/documents-section.tsx
- src/components/thumbnail/right-nav-tab-contents.tsx
Adjusts the implementation of the auto-expansion of the appropriate right-nav section when the user's primary document changes.
- auto-expands the "Data" section when a program is run (preexisting behavior)
- auto-expands the "Programs" section when the "Open Program" button is pressed
- should handle any other cases in which the primary document is changed by means other than selection of a right-nav element
- changes the logging behavior so that only user-initiated section expansion is logged
> Auto-expand appropriate section in right-nav on Open Program [#170460415]

- src/assets/dataflow/icons/one-up/one-up-active.svg
- src/assets/dataflow/icons/one-up/one-up-disabled.svg
- src/assets/dataflow/icons/one-up/one-up-hover.svg
- src/assets/dataflow/icons/one-up/one-up-selected.svg
- src/assets/dataflow/icons/one-up/one-up.svg
- src/assets/dataflow/icons/two-up-stacked/two-up-stacked-active.svg
- src/assets/dataflow/icons/two-up-stacked/two-up-stacked-disabled.svg
- src/assets/dataflow/icons/two-up-stacked/two-up-stacked-hover.svg
- src/assets/dataflow/icons/two-up-stacked/two-up-stacked-selected.svg
- src/assets/dataflow/icons/two-up-stacked/two-up-stacked.svg
- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/dataflow/app-config.json
- src/dataflow/components/dataflow-program.sass
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/dataflow.sass
- src/dataflow/vars.sass
- src/models/stores/app-config-model.ts
Adds a top-down two-up view for use in Dataflow.  
Some of the changes in `document-workspace.tsx` (text changes for DF) and `document.tsx` (adds a couple new buttons for DF) might need to be incorporated into the app config file.  For now, we can at least begin discussion.  Most of the other changes are DF specific styling and icons.
@kswenson Note, this has been condensed into a single commit, but if we need to slice it up, it will be pretty easy to do so on another branch (or whatever works best).  I wanted you to look first though.
> Add stacked two-up view for Dataflow

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/dropdown-list-control.sass
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/lib/iot.ts
- src/dataflow/models/stores/hub-store.ts
- src/dataflow/utilities/node.ts
Add two tiers of device timeout: after 30 seconds, mark the device as missing and update the UI accordingly.  After 5 minutes, remove the device entirely for the hub store and from the UI.
@kswenson Current changes are functional, but I want to review and test more carefully before submitting the final PR.  In the meantime, feel free to take a look.
> Update channel timeout mechanism

- src/dataflow/components/dataflow-program.tsx
Small fix to delete recent values from node data when loading a program.  Otherwise we show the stale recent values in the node mini-plot implying that they are part of the past 15 second worth of node values (even though these are actually old values from the previous time that the program was opened).
I chose to clear recent values on load rather than on save so that:
- loading existing programs created before the fix will not show stale recent values
- recent values retained in saved program data could be useful for debugging or research
> Delete node recent values on load

- src/dataflow/components/dataflow-program-cover.sass
The right edge of the program cover (used when program is disabled to prevent interaction) did not cover the program content.  This allowed the user to edit a read-only program.  This PR fixes the program editor cover size (no longer takes toolbar which is now hidden into account).
> Fix program cover sizing

- src/dataflow/components/dataflow-program.sass
Small fix to improve display of program editor content.  When the program editor tile height was shorter than the program toolbar height, we displayed the tile with scrollbars (this would occasionally happen in the 2-up display).  This resulted in the scrolled content being cut off due to an incorrect container height.  Enforce a min-height in the editor container so that in cases where the content is scrolled, we do not cut off editor content.
> Set min height of editor container

- src/dataflow/components/nodes/controls/plot-button-control.tsx
This PR adds back in a node update call that was recently removed.  We need to update the node to force a node re-render when the plot button is pressed.  Otherwise the plot is not shown/hidden until the next heartbeat hits and all nodes are updated.  This isn't a terrible bug, but without it, there is a noticeable delay when clicking the plot button (up to one second).
`(this as any).update();` is, as far as I can tell, not needed.
> Update node when plot button is pressed

- src/dataflow/components/dataflow-program-graph.tsx
This PR adds a new button to the dataset graph that allows the user to export the graph as a JPG image using a default filename modeled after the CSV export.  Exported image is WYSIWYG so any graph state (stacked, combined, line, scatter, etc.) should be exported to image as seen on the screen.
> Add tool to export graph as image

- src/dataflow/components/nodes/controls/value-control.sass
- src/dataflow/components/nodes/controls/value-control.tsx
Small improvements to how long node values are displayed in node value control (especially relevant in math, logic, and transform nodes where we tend to display longer strings than in other nodes):
- remove `height` from CSS so content is centered vertically
- add additional sizing tiers to better handle long strings
> Improve display of large string in value control

- src/dataflow/components/hub-list.sass
- src/dataflow/components/hub-list.tsx
This PR adds small changes to the control panel to communicate to the user when sensors or relays are in the `missing` state.
> Add hub channel timeout status to control panel

- cypress/integration/dataflow/full/control_panel_spec.js
- cypress/integration/dataflow/full/sensor_block_spec.js
- src/components/document/document.tsx
- src/components/thumbnail/class-logs.tsx
- src/components/thumbnail/right-nav-tab-contents.tsx
- src/dataflow/app-config.json
- src/dataflow/components/tools/dataflow-tool.tsx
- src/models/stores/app-config-model.ts
- src/models/stores/ui.ts
Continuing work begun by @mklewandowski .
1. published documents can be shown in the primary workspace (1-up) (in Dataflow)
2. show 1-up/2-up toggle buttons in the title bar of the primary workspace (in Dataflow)
3. these behaviors can be enabled for Dataflow via application configuration
Also, the Open Program button now selects the My Work tab if necessary. [#170523498]
> Support showing published documents in 1-up view for Dataflow

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/models/stores/hub-store.ts
This PR makes small changes to unify how we handle relays and sensors that are in the missing/finding state.  Specifically:
- highlight missing selected device on sensor and relay nodes and show "finding" message
- set sensor value to NaN as soon as we detect that it is missing
- warn user if the selected device on a sensor or relay node is missing
> Update node to show finding state as soon as device is marked missing

- src/lib/auth.ts
- src/lib/firebase.ts
- src/utilities/url-params.ts
When we detect a launch via the `Preview` button in the portal, we put the user in demo mode as the only student in their own personal class. FYI @scytacki .
> Support portal launch via Preview button [#170588779]

- src/dataflow/components/nodes/controls/relay-select-control.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
The message in the node dropdown list that reported the status of a missing sensor/relay was incorrect.  This PR fixes it for sensor and relay nodes.
> Fix sensor/relay message when device is missing

- scripts/patch-rete.js
- webpack.config.js
```
/*
* This script pre-processes the Rete module code to install simple code patches.
* We tried forking the Rete repository, making the changes there and then publishing
* the fork, but there are complicated dependencies with some of the other plugins
* (notably the rete-connection-plugin) that made it difficult to get the published
* forks working correctly with Dataflow. With this alternate approach, we process
* the Rete code before it is bundled by Webpack.
*/
```
```
/*
* The Zoom patch limits scroll-wheel zooming to when the mouse is over the
* white space of the Rete editor, i.e. not when over a node or other content
* that might want to handle the wheel event themselves. When the Zoom code
* swallows the wheel event, it prevents node menus from scrolling, etc.
*/
```
cf. …
> Patch Rete module in webpack.config.js before Webpack bundles it

- src/dataflow/app-config.json
Eliminate right-nav sections for published documents without data, since such documents cannot be published.
> Eliminate right-nav sections for published documents without data

- src/dataflow/utilities/node.ts
Update the default program run time.  Change from 10 minutes to 5 minutes.
> Update default run time

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/lib/iot.ts
Clear hub channels when user presses the refresh button - this guarantees that we update the full list of channels and remove and missing channels from hub stores.
> Remove all devices when user presses refresh button

- src/dataflow/components/dataflow-program-cover.sass
Fix top position of program cover.  Note, that I'm still leaving the `running` class on the cover div (even though it no longer modifies the div) since I have a hunch that it could end up being useful if there are future changes to how we display the program editor (which based on how many times we've changed this so far, I assume there will be more changes moving forward).
> Fix cover top position

- src/lib/db-listeners/db-problem-documents-listener.ts
- src/lib/db.ts
We recently encountered a situation in which users in `CLUE` `democlass1` were unable to open MSA problem 1.3 due to some offering-specific corruption. Specifically, user `1` was missing some required metadata (the `self` field) as was this user's problem document for this problem. When the code attempted to load this corrupted document it halted the application. The fix here is to simply ignore users and documents that lack required metadata.
> Add additional null tests in firebase document handling

- src/clue/components/teacher/teacher-supports.tsx
We had been reversing supports explicitly so that the most recent would be at the top. After recently changing it so that all documents are reversed to put the most recent at the top, the supports were being double-reversed into the wrong order.
> Show recent teacher supports at top [#171003815]

- src/models/tools/geometry/jxg-board.ts
Fixes [[#171010682]](https://www.pivotaltracker.com/story/show/171010682), in which linking a table to a geometry tool can reset user-set axis names.
> Preserve user-set axis names [#171010682]

- CHANGELOG.md
- package-lock.json
- package.json
- User-editable table title row
- User axis annotations
- Fix tile drags from curriculum
- Fix drawing tool stamps
- Fix preview button launch from portal
- Update dependencies
|---|---|---|
| index.css | 518,038 bytes | 3.5% |
| index.js | 4,114,798 bytes | -6.4% |
> CLUE Release 1.1.0

- src/lib/logger.test.ts
- src/lib/logger.ts
- log user role with each log message
- pull application name from configuration so CLUE logs as application `CLUE` and Dataflow logs as application `Dataflow`
> Uncontested logging improvements [#171218617]

- src/components/tools/link-indicator.scss.d.ts
- src/components/tools/link-indicator.tsx
- src/models/tools/table-links.scss.d.ts
- src/models/tools/table-links.ts
- src/typings.d.ts
Now that we've updated our TSConfig settings, we can implement type-safe sharing of values between SCSS and TS as described in [Use Sass Variables In TypeScript & JavaScript](https://mattferderer.com/use-sass-variables-in-typescript-and-javascript).
> Typesafe scss imports

- CHANGELOG.md
- Log user role
- Fix tile drags to existing row
- Fix table selection bug
- Fix geometry drag bug
- Fix representation of linked points in group view
|---|---|---|
| index.css | 518,038 bytes | 0.0% |
| index.js | 4,136,752 bytes | 0.0% |
> Release 1.1.1 take 2

- src/components/document/tile-row.tsx
- src/models/document/document-content.ts
- src/models/document/tile-row.ts
Ignore explicit height for section header rows (prevent glitchy box from showing)
> Prevent tile drops on section header rows [#171362427]

- CHANGELOG.md
- Log user role
- Fix tile drags to existing row
- Fix table selection bug
- Fix geometry drag bug
- Fix representation of linked points in group view
- Prevent tile drop on section headers
- Limit tile drags to a single source
|---|---|---|
| index.css | 518,038 bytes | 0.0% |
| index.js | 4,137,028 bytes | 0.0% |
> Release 1.1.1 take 3

- CHANGELOG.md
- package-lock.json
- package.json
- MSA tables format numbers to two decimal places
- Add infrastructure for authorable settings
|---|---|---|
| index.css | 518,038 bytes | 0.0% |
| index.js | 4,142,635 bytes | 0.1% |
> Release 1.1.2

- src/lib/db.ts
- use new credential with `appId`
- add referrer restrictions as well as API restrictions (firebase console)
- use `atob()` to lightly obfuscate the key
FYI: no nasty-gram from google so far, so maybe it worked. 😉
> Update firebase credential

- .firebaserc
- README.md
- database.rules.json
- firebase.json
- firestore.indexes.json
- firestore.rules
- package.json
- src/components/class-menu-container.tsx
- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/index.tsx
- src/lib/auth.ts
- src/lib/db-listeners/db-supports-listener.ts
- src/lib/db-listeners/index.ts
- src/lib/db-types.ts
- src/lib/db.ts
- src/lib/fire-utils.ts
- src/lib/firebase.ts
- src/lib/firestore.ts
- src/lib/portal-api.test.ts
- src/lib/portal-api.ts
- src/models/curriculum/support.ts
- src/models/document/document.ts
- src/models/stores/stores.ts
- src/models/stores/supports.test.ts
- src/models/stores/supports.ts
- src/models/stores/user.ts
- src/test-fixtures/sample-portal-offerings.ts
- src/utilities/js-utils.ts
Published teacher supports are now stored in firestore. For portal-authenticated users, only teachers can write supports and only teachers and students in a specified list of classes can read them. This allows teacher-published supports to be visible in multiple classes (all of a teacher's CLUE classes by default). This requires a brand-new firestore database instance which currently only has teacher-published (multi-class) supports.
This PR also introduces the [firebase-tools](https://www.npmjs.com/package/firebase-tools) to this project so that rules can be edited locally and deployed from the command-line rather than being edited via the google console GUI.
For demo use, supports are shared across three-class batches, e.g. [democlass1, democlass2, democlass3], etc.
For review purposes, …
> Store teacher supports as cross-class supports in firestore

- src/components/tools/drawing-tool/drawing-layer.tsx
[[#174431167]](https://www.pivotaltracker.com/story/show/174431167)
The bug occurs when loading a document that contains a drawing tool with multiple drawing objects. Calling `setState()` multiple times in succession can lose all but the last change given the asynchronous nature of `setState()`. The bug was introduced in the relatively recent TSLint => ESLint conversion which triggered a warning about the previous code which was modifying React state directly. The correct fix is to use the functional form of `setState()` so that each state update is guaranteed to be made to the correct previous state.
> Use functional form of setState() to make sure all changes get captured

- cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js
- src/lib/db-listeners/db-groups-listener.ts
[[#174479862]](https://www.pivotaltracker.com/story/show/174479862)
The code for responding to changes in group membership could remove the document model listener for a user's own documents but then fail to add it back. The fix here is to prevent addition or removal of listeners for a user's own documents in response to group membership changes. The bug was apparently introduced in #458.
> Fix monitoring of a student's own document(s) when group membership changes

- src/clue/app-config.json
- src/lib/portal-api.test.ts
- src/lib/portal-api.ts
- src/models/stores/app-config-model.ts
At various times, the "Stretching & Shrinking" unit has been abbreviated with "s+s", "s s", and now "sas". Since problem-matching is based on the unit code, we need to map to the current code ("sas") for matching purposes.
> Map legacy unit codes for teacher support problem matching

- CHANGELOG.md
- package-lock.json
- package.json
- Fix bug which affected class visibility of some teacher supports
|---|---|---|
| index.css | 502,710 bytes | 0.0% |
| index.js | 4,921,038 bytes | 0.0% |
> Release 1.2.1

- src/clue/components/clue-app-header.sass
- src/components/vars.sass
This PR makes small adjustments to the margins and account icon in the student header based on changes to the spec seen here:
https://app.zeplin.io/project/5d62a554d64a9e02dcad80de/screen/5f3adcf9b77c3129d28841ce
- icon size is 24x24
- component margin and padding sizing is 10 pixels (not 9)
> Update margins and user icon size to match spec

- src/components/document/document-workspace.tsx
Improve success message shown after publishing a support by adding the number of classes to which it was published.
It occurred to me while testing 1.2.1 that a more informative message would make it much easier to tell whether the publication of the support was working the way the user/teacher intended.
> Improve success message shown after publishing a support

- src/clue/components/clue-app-header.sass
- src/components/group/group-chooser.sass
Minor color changes so that the member blobs in the top header match the UI spec:
> Update member colors to match spec

- src/clue/components/clue-app-header.sass
- src/clue/components/clue-app-header.tsx
- src/clue/components/problem-select.sass
Update the hover and active colors of the header buttons to match the UI spec (dropdown is currently disabled, but colors have been updated).
> Update header button states

- src/clue/components/clue-app-header.sass
- src/clue/components/problem-select.sass
- src/clue/components/problem-select.tsx
Update app header so the handling of long text strings matches the UI spec.  Components expand to a max-width and then display long text with ellipsis.
> Handle text overflow in app header sections

- src/components/navigation/left-nav-panel.sass
- src/components/navigation/left-nav-panel.tsx
- src/components/navigation/left-tab-buttons.tsx
- src/components/navigation/left-tab-panel.sass
- src/components/navigation/left-tab-panel.tsx
- src/components/navigation/problem-tab-content.sass
- src/components/navigation/problem-tab-content.tsx
- src/components/vars.sass
This PR adds problem content to the slide out left tabs.  Problem sections are controlled by a second set of tabs beneath the main Problems/My Work/Class Work/etc. tabs.  Problem content scrolls vertically if the content is too long.  The bulk of the work is done in the new `ProblemTabContent` React component.  The `LeftNavPanelComponent` is reused (which displays the problem content) - although we might want to rename it to be better in sync with our new UI design.
> Add problem content in left tabs

- CHANGELOG.md
- package-lock.json
- package.json
- More informative message upon publishing a teacher support
- Improved image tile auto-sizing
|---|---|---|
| index.css | 502,710 bytes | 0.0% |
| index.js | 4,921,173 bytes | 0.0% |
> Release 1.2.2

- src/lib/db-listeners/index.ts
[[#174431947]](https://www.pivotaltracker.com/story/show/174431947)
It needs to be started after documents have been processed.
> Fix stars listener; it needs to be started after documents have been processed

- src/clue/components/clue-app-content.tsx
- src/clue/components/clue-app-header.tsx
- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/components/document/editable-document-content.tsx
- src/components/navigation/left-nav-panel.tsx
- src/components/navigation/left-nav.tsx
- src/components/navigation/left-tab-buttons.tsx
- src/components/navigation/left-tab-panel.tsx
- src/components/navigation/problem-tab-content.tsx
- src/models/stores/groups.ts
Prior to the development of the teacher dashboard, teachers could visit individual groups as a "ghost" user. With the development of the teacher dashboard, this notion became vestigial but was never removed.
> Eliminate vestigial notion of ghost user

- cypress/integration/clue/branch/student_tests/canvas_test_spec.js
- src/components/document/document-or-browser.tsx
- src/components/navigation/document-tab-content.sass
- src/components/navigation/document-tab-content.tsx
- src/components/navigation/document-tab-panel.sass
- src/components/navigation/document-tab-panel.tsx
- src/components/navigation/left-tab-panel.tsx
- src/components/navigation/problem-panel.sass
- src/components/navigation/problem-tab-content.sass
- src/components/thumbnail/tab-panel-documents-section.sass
- src/components/vars.sass
This PR displays a reference document in the left tab panel when a thumbnail is clicked.  Each primary tab section (my work, class work, supports) can display it's own reference document.  This work is not entirely complete (see note below), but I think it's worth putting the current progress in a PR so we can discuss the changes.
Changes include:
- rename existing `DocumentTabContent` component `DocumentTabPanel`
- additional props can be sent to `DocumentTabPanel` to specify callbacks for clicking on a thumbnail or a tab and an option document can be passed the component to be shown in place of the thumbnail content
- new `DocumentTabContent` manages the reference doc for a tab section
This does NOT complete the work on the reference doc.  There are still architectural considerations as …
> 174542553 reference document

- src/components/document/document-workspace.tsx
- src/components/navigation/document-tab-panel.tsx
- src/lib/db-listeners/db-supports-listener.ts
- src/lib/db.ts
- src/lib/logger.ts
- src/models/stores/stores.ts
- src/models/stores/ui.test.ts
- src/models/stores/ui.ts
[[#174789421]](https://www.pivotaltracker.com/story/show/174789421)
Log additional environment variables with every log message:
- problemPath (e.g. "SAS/1/1")
- navTabsOpen (whether the left-side navigation tabs are showing)
- selectedNavTab (the ID of the currently selected left-side navigation tab)
- workspaceMode ("1-up" or "4-up")
- teacherPanel (for teachers, "dashboard" or "workspace")
- selectedGroupId (for teachers, ID of group being viewed, if any)
Required changing the way the problemPath is determined since calling getProblemPath() from the logging function caused unit tests to fail.
Also eliminate unused/legacy UI fields.
> Log additional info with each log message

- src/components/document/document.sass
I know that this button will probably change once Michael gets to it in the updated UI spec, but since that probably won't happen in this iteration, I at least want to remove the gray/pea green that appear in the upper-right corner when this button is displayed in the document title bar.
> Use new UI spec colors on sticky note button

- src/components/utilities/dialog.sass
This PR make some simple changes based on the in-progress designs to move the dialog styling in the direction of the new UI work (I didn't touch button states since those categories are empty in the spec) in preparation for the upcoming release.  As with the sticky-note PR, the pop-up dialogs are not yet completed in the UI spec.  However, there is some preliminary work that we can follow to at least remove the pea green colors from the previous spec:
https://app.zeplin.io/project/5d62a554d64a9e02dcad80de/screen/5f3bbf9fe5e47135081b4439
> Update dialog styling

- src/components/navigation/problem-panel.sass
- src/components/navigation/problem-panel.tsx
This PR removes the problem titles in each problem section in the left tab panel (this was previously in the UI spec, but has since been removed).
> Remove problem title in left tab

- src/clue/components/clue-app-header.sass
- src/components/thumbnail/thumbnail-document-item.tsx
- starring a document no longer also opens the document
- added highlighting to the teacher dashboard/workspace toggle
> Fix bugs in upcoming 1.3.0 release

- src/components/four-up.tsx
Show full name when hovering over initials in four-up view in:
- student four-up view
- teacher student workspaces view
> Show full name when hovering over initials in four-up view

- cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js
- src/clue/components/clue-app-header.sass
- src/clue/components/custom-select.sass
- src/clue/components/custom-select.tsx
- src/components/class-menu-container.tsx
- src/index.tsx
- show correct item as selected
- show current class in class menu header
- clip long class names with ellipsis
- expand size of class menu to allow longer class names
Testable at https://collaborative-learning.concord.org/branch/teacher-menus/?demo, but note that the teacher menus don't really work when not launched from portal, so to test you really have to launch from portal and then manually change the URL.
> Fix teacher class/problem menus

- src/clue/components/custom-select.sass
> Fix File menu label

- CHANGELOG.md
- package-lock.json
- package.json
- New curriculum content
- Show tile drag border and drag icon on hover
- Tile drag border color reflects editability
- Add new teacher supports indicator badge
- Fix File menu rendering issue
- Fix text tile selection in curriculum content
- Fix bug which prevented dragging multiple tiles from curriculum content
- Fix table/geometry link icon appearance
|---|---|---|
| index.css | 503,854 bytes | -0.4% |
| index.js | 4,887,087 bytes | -1.3% |
> Release 1.4.0

- cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js
- package-lock.json
- package.json
- src/components/tools/link-indicator.test.tsx
- src/components/tools/link-indicator.tsx
Adds tests so that the build error that led to #843 would be caught by the cypress tests.
The `<LinkIndicatorComponent>` synchronizes values between `.scss` and `.tsx` files by importing SASS variables into the TypeScript code. It turns out that
1. If that import fails it doesn't fail the Webpack build.
2. There was a configuration change required with the latest version of `css-loader` which caused the import to fail after updating the dependency.
Moving forward, the new cypress test should trigger if that import process is ever broken again.
> Add unit and cypress tests for link indicator

- .eslintrc.js
- src/components/document/canvas.tsx
- src/components/document/document-content.tsx
- src/components/document/tile-row.tsx
- src/components/toolbar.tsx
- src/components/tools/hooks/use-floating-toolbar-location.ts
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/text-style-bar.sass
- src/components/tools/text-style-bar.tsx
- src/components/tools/text-tool.sass
- src/components/tools/text-tool.tsx
- src/components/tools/text-toolbar-button.tsx
- src/components/tools/text-toolbar.sass
- src/components/tools/text-toolbar.tsx
- src/components/tools/tile-comments.tsx
- src/components/tools/tool-tile.tsx
- src/components/utilities/tile-utils.ts
- src/hooks/use-tool-api-interface.ts
- src/utilities/event-utils.ts
[[#174930211]](https://www.pivotaltracker.com/story/show/174930211)
Implements a floating toolbar below the tile for the text tile. Toolbar is only visible/enabled when the text tile has focus. Toolbar scrolls with the document to stay pinned to bottom of tile. Toolbar is pinned to edge of window if bottom of tile extends off screen and is hidden if the entire tile is offscreen. Design changes are not included in this PR.
The core of the implementation is encapsulated in a custom hook which computes the location of the toolbar and updates the location as the document is scrolled or the tile is resized.
> Floating text toolbar

- cypress/integration/clue/branch/student_tests/canvas_test_spec.js
- src/components/document/tile-row.sass
- src/components/tools/drawing-tool/drawing-layer.tsx
- src/components/tools/drawing-tool/drawing-settings-view.tsx
- src/components/tools/drawing-tool/drawing-stamp-selection.tsx
- src/components/tools/drawing-tool/drawing-tool.sass
- src/components/tools/drawing-tool/drawing-tool.tsx
- src/components/tools/drawing-tool/drawing-toolbar-buttons.tsx
- src/components/tools/drawing-tool/drawing-toolbar.tsx
- src/components/tools/hooks/use-floating-toolbar-location.ts
- src/components/tools/hooks/use-force-update.ts
- src/components/tools/hooks/use-mobx-on-change.ts
- src/components/tools/hooks/use-toolbar-tool-api.ts
- src/components/tools/text-tool.tsx
- src/components/tools/text-toolbar.tsx
- src/components/tools/tool-tile.tsx
- src/components/utilities/tile-utils.ts
[[#174718210]](https://www.pivotaltracker.com/story/show/174718210)
As with the text toolbar, this doesn't update the draw toolbar to the latest specs, it just turns the existing toolbar horizontal and makes it float. To do so, the existing code was extensively refactored into functional components using hooks. Taking the implementation from the text tool one step further, the tool's responsibilities are now encapsulated in the `useToolbarToolApi()` hook function.
> Draw tool floating toolbar [#174718210]

- src/components/tools/hooks/use-mobx-on-change.ts
Realized this was missing in a recent PR and wanted to clear the decks before upcoming PRs.
> Dispose MobX reaction on unmount

- src/components/problem-menu-container.tsx
- src/components/tools/drawing-tool/drawing-tool.sass
- src/components/tools/geometry-tool/geometry-tool.tsx
- src/components/tools/geometry-tool/geometry-toolbar.sass
- src/components/tools/image/image-toolbar.scss
- src/components/tools/text-toolbar.sass
- src/components/tools/tool-tile.tsx
- src/components/vars.sass
- src/models/stores/ui.ts
- Row resize takes precedence over toolbars [[#175563814]](https://www.pivotaltracker.com/story/show/175563814)
- Geometry toolbar gets left behind after a drag [[#175550604]](https://www.pivotaltracker.com/story/show/175550604)
- Text tile deselects when typing modifier key combinations [[#175549435]](https://www.pivotaltracker.com/story/show/175549435)
- Dragging a tile should focus the tile and only drag that tile [[#175550381]](https://www.pivotaltracker.com/story/show/175550381)
- Show problem subtitle in teacher problem menu [[#175564025]](https://www.pivotaltracker.com/story/show/175564025)
@mklewandowski Each bug-fix is in a separate commit for review purposes.
> 1.5.0 bug fixes

- src/components/four-up.sass
- src/components/vars.sass
[[#175581201]](https://www.pivotaltracker.com/story/show/175581201)
Colors that label students make it nearly impossible to see the text, and associate it with editable and noneditable panes in 4up views. Update the teacher dashboard and student 4-up view with the new student ID colors and change font color.
> Update Student Identifier Colors and Font Color [#175581201]

- src/components/tools/hooks/use-force-update.ts
- src/components/tools/tool-tile.tsx
- src/components/utilities/tile-utils.ts
When clicking (not dragging) the corresponding icon in the document toolbar to create a geometry or draw tool, the initial toolbar location is often near the top of the document rather than at the bottom of the tile.
> Fix bug with initial toolbar location [##175587882]

- src/components/tools/text-tool.tsx
[[#175631464]](https://www.pivotaltracker.com/story/show/175631464)
The bug is essentially an order-of-initialization problem. During the initialization sequence the resize handler is called before the text toolbar has installed its handler, so it doesn't know the size of the tile when it comes time to determine the initial toolbar location. The fix here is to have the TextTool cache the size locally so that when the toolbar installs its handler the handler can be provided with the cached dimensions.
> Fix initial text toolbar location [#175631464]

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/tools/text-tool.tsx
- Fix text toolbar initial location bug
|---|---|---|
| index.css | 517,550 bytes | 0.0% |
| index.js | 4,950,629 bytes | 0.0% |
> Release 1.5.1

- src/assets/icons/add/add.nosvgo.svg
- src/assets/icons/remove/remove.nosvgo.svg
- src/components/tools/table-tool/grid-types.ts
- src/components/tools/table-tool/table-tool.scss
- src/components/tools/table-tool/use-columns-from-data-set.ts
- src/components/tools/table-tool/use-controls-column.tsx
- src/components/tools/table-tool/use-data-set.ts
- src/utilities/js-utils.ts
- webpack.config.js
[[#175773902]](https://www.pivotaltracker.com/story/show/175773902)
I was originally just going to implement Remove Row in this PR, but it turns out that supporting Add Column as well didn't add much to the degree of difficulty.
Note that for implementation reasons, the Add Column and Remove Row buttons are implemented as an additional column in the table. This makes rendering them straightforward using normal React mechanisms, guarantees proper alignment with the row, assures that they scroll properly when the table is scrolled vertically, etc. The downside to this approach, however, is that if the table is wider than the tile the buttons can be scrolled out of view horizontally. In the interest of moving on I propose we stick with this for now. If there is a desire to implement sticky …
> Table UI IV: Implement Add Column and Remove Row buttons [#175773902]

- src/assets/icons/text-input.svg
- src/components/tools/table-tool/use-set-expression-dialog.tsx
- src/components/utilities/single-string-dialog.scss
- src/components/utilities/single-string-dialog.tsx
- src/components/utilities/use-single-string-dialog.tsx
- src/hooks/custom-modal.scss
- src/hooks/use-custom-modal.tsx
As a further test of the new custom dialog infrastructure, we replace the existing `<SingleStringDialog>` component with an API-compatible version based on the new `useCustomModal` hook. One wrinkle is that the only existing client of the `<SingleStringDialog>` (the comment feature in the geometry tool) is a class component, which therefore can't use the `useSingleStringDialog` hook. Not to be deterred, however, with this PR we also implement a replacement `<SingleStringDialog>` as a functional component which wraps the `useSingleStringDialog` hook.
> Re-implement SingleStringDialog in terms of new useCustomModal()

- src/assets/icons/error.svg
- src/components/app.tsx
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/table-tool/use-set-expression-dialog.tsx
- src/components/utilities/error-alert.scss
- src/components/utilities/error-alert.tsx
- src/components/utilities/use-error-alert.tsx
- src/components/utilities/use-single-string-dialog.tsx
- src/hooks/custom-modal.scss
- src/hooks/use-custom-modal.tsx
The two uses of `<Alert>` being replaced are in `<AppComponent>` where it is used to show things like authentication failures:
and when attempting to link a table tile to a geometry tile with invalid data:
Note that the latter is cancelable via close box or escape key while the former is not.
Other improvements to the dialog infrastructure include:
- support `canCancel` option
- support `isDefault` button option with altered button appearance and handling of return/enter key
- use "close" instead of "cancel" in the button API since it's reasonable to apply it to the OK button as well as the Cancel button in some cases.
> Implement <ErrorAlert> to replace blueprint.js <Alert>

- src/components/tools/table-tool/editable-table-title.tsx
- src/components/tools/table-tool/header-cell-input.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/table-tool/use-columns-from-data-set.ts
- src/components/tools/table-tool/use-data-set.ts
- src/components/tools/table-tool/use-grid-context.ts
- src/components/tools/table-tool/use-model-data-set.ts
- src/components/tools/table-tool/use-row-label-column.tsx
- src/components/tools/table-tool/use-rows-from-data-set.ts
- src/components/tools/table-tool/use-table-title.ts
- src/models/tools/table/table-content.ts
Previously, table changes just affected the local `DataSet` instance but weren't writing changes to the content, which meant they weren't being written to firebase. Now, table changes are written to the content as before, i.e. the new table is "live".
In addition:
- fixed cell navigation so non-editable/non-visible cells are skipped in navigation
- prevent the input row from being selected
> Table changes written to content

- src/components/tools/table-tool/cell-text-editor.tsx
- src/components/tools/table-tool/table-tool.scss
- src/components/tools/table-tool/table-types.ts
- src/components/tools/table-tool/use-column-extensions.ts
- src/components/tools/table-tool/use-columns-from-data-set.ts
- src/components/tools/table-tool/use-controls-column.tsx
- src/components/tools/table-tool/use-grid-context.ts
- Clear row selection when editing a cell
- Show delete row icon when cell is selected in row as well as when row is selected [[#175959558]](https://www.pivotaltracker.com/story/show/175959558)
- Hide add colum/remove row buttons when tile isn't selected [[#175959577]](https://www.pivotaltracker.com/story/show/175959577)
Testable at https://collaborative-learning.concord.org/branch/table-selection/?demo.
> Improve cell selection and add column/remove row icon visibility issues [#175959558][#175959577]

- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/table-tool/table-types.ts
- src/components/tools/table-tool/use-grid-context.ts
- src/hooks/use-stores.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
Previously, row selection was stored in local React state. Initially, I tried synchronizing the shared selection state in the selection store with the local React state, which turned out to be trickier than expected. Ultimately, I realized that I could just use the selection store state directly and eliminate the local React state and any corresponding synchronization issues.
> Synchronize selection between table and geometry tiles [#176582684]

- src/components/document/document-content.tsx
- src/components/tools/drawing-tool/drawing-tool.tsx
- src/components/tools/drawing-tool/drawing-toolbar.tsx
- src/components/tools/geometry-tool/geometry-content-wrapper.tsx
- src/components/tools/geometry-tool/geometry-tool.tsx
- src/components/tools/hooks/use-floating-toolbar-location.ts
- src/components/tools/image-tool.tsx
- src/components/tools/table-tool/column-header-cell.tsx
- src/components/tools/table-tool/editable-table-title.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/table-tool/table-types.ts
- src/components/tools/table-tool/use-column-extensions.ts
- src/components/tools/table-tool/use-content-change-handlers.ts
- src/components/tools/table-tool/use-expressions-dialog.tsx
- src/components/tools/text-tool.tsx
- src/components/tools/text-toolbar.tsx
- src/components/utilities/tile-utils.ts
- src/models/document/document-content.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/table/table-content.ts
@mklewandowski The individual bug-fixes are each in their own commit, so you may want to review this commit-by-commit rather than reviewing all changes at once.
- Fix Clear button in expressions dialog [[#176602087]](https://www.pivotaltracker.com/story/show/176602087)
- The clear button needed to update the to-be-returned expressions as well as the currently edited expression.
- Fix axis labels for table-linked geometry tiles [[#176615381]](https://www.pivotaltracker.com/story/show/176615381)
- There were multiple paths for determining the axis labels which produced slightly different results. There is now a single `getAxisLabelsFromDataSet()` function in `TableContent` which is called from all other paths.
- Fix floating toolbar bugs with four-up view …
> Miscellaneous table-related bug-fixes

- src/models/curriculum/section.ts
Currently, there's a single global section map which was implemented when only one unit could be in use at a time. Now that we can have two units (the regular content unit and the teacher guide unit), we need to merge the section maps rather than simply replacing one with another.
> Fix section mapping between regular and teacher guide sections

- src/components/document/document-content.tsx
- src/components/document/editable-document-content.tsx
- src/components/toolbar.tsx
- src/components/tools/geometry-tool/editable-geometry-title.tsx
- src/components/tools/geometry-tool/geometry-content-wrapper.tsx
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/geometry-tool/geometry-label-input.tsx
- src/components/tools/geometry-tool/geometry-title.scss
- src/components/tools/geometry-tool/use-tile-selection-pointer-events.ts
- src/models/document/document-content.ts
- src/models/document/document.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-table-link.ts
- src/models/tools/table/table-content.ts
- src/models/tools/tool-content-info.ts
[[#174765909]](https://www.pivotaltracker.com/story/show/174765909)
Graphs (aka geometry tiles) now have user-editable titles that are rendered above the geometry content. Like tables, titles are initially auto-generated with numeric suffixes, i.e. "Graph 1", "Graph 2", etc.
New with this PR is that newly created geometry and table tiles are assigned their auto-generated title on creation. Previously, newly created tiles had no assigned title and were given a title at run time. Thus, if you created two tables, e.g. "Table 1" and "Table 2", and then deleted "Table 1", and then reloaded the page the table previously known as "Table 2" would appear as "Table 1" because it would receive a different auto-generated title on launch. Now that titles are assigned on creation, tiles should maintain …
> Support graph/geometry title [#174765909]

- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/table-tool/editable-table-title.tsx
- src/components/tools/table-tool/link-geometry-button.tsx
- src/components/tools/table-tool/table-tool.scss
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/table-tool/use-geometry-linking.ts
- src/components/tools/tool-tile.tsx
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/table-links.scss
- Fix drag bug which prevented row-resizing and linking tables to geometry tiles via drag/drop
- Fix polygon creation so that linked points can only be connected within a column
- Replace old-style link indicator icon with background-coloration of the new link button in tables.
- We don't have a complete design yet, so this is engineer-design that's just intended to get us through next week's classroom use.
> Miscellaneous bug-fixes

- src/components/document/document-content.tsx
- src/components/document/tile-row.tsx
Fix bug which prevented some rows from being resizable. Must use case-insensitive comparison when comparing ids that have been `toLowerCase()`d to fit within the key of the `DataTransfer` object.
> Fix row resize issue resulting from lower-case key limitation in DataTransfer

- package-lock.json
- package.json
- src/models/tools/text/text-content.test.ts
- src/models/tools/text/text-content.ts
Fixes import/export of `className` property
> Update to @concord-consortium/slate-editor 0.7.2

- CHANGELOG.md
- package-lock.json
- package.json
- Additional Moving Straight Ahead Teacher Content
- Uses @concord-consortium/slate-editor library
- Update `browserslist` configuration
|---|---|---|
| index.css | 389,494 bytes | 0.0% |
| index.js | 4,574,452 bytes | 10.3% |
> CLUE 1.7.0

- src/clue/components/teacher/teacher-class-info-button.sass
- src/clue/components/teacher/teacher-class-info-button.tsx
- src/lib/firebase.ts
This component was developed to generate a CSV-formatted report for teachers of the student groupings for each problem (offering) in a class. This was required at the time because early versions of CLUE did not log group information and so there was no easy way to determine student groupings from the existing logs. A student's `groupId` was added to the existing logs for CLUE 0.8.0 in [PR #451](https://github.com/concord-consortium/collaborative-learning/pull/451), obviating the need for this particular report component and its button. This component is left in the code base as an exemplar in case future need for CSV export of CLUE data arises. [[#172209086]](https://www.pivotaltracker.com/story/show/172209086)
> Archive code to export student groups [#172209086]

- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/table-tool/use-content-change-handlers.ts
- src/components/tools/table-tool/use-json-export.ts
- src/components/tools/table-tool/use-tool-api.ts
- src/lib/logger.ts
- src/models/data/data-set.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-object.ts
- src/models/tools/geometry/jxg-table-link.ts
- src/models/tools/table-links.ts
- src/models/tools/table/table-change.ts
- src/models/tools/table/table-content.test.ts
- src/models/tools/table/table-content.ts
- src/utilities/omit-deep.ts
- Extend table import format to support expressions
- Implement `exportContentAsTileJson()` to support JSON export
- Add unit tests
- Improve/refactor table types
[[#176874316]](https://www.pivotaltracker.com/story/show/176874316)
> Table: Support JSON export; improve import [#176874316]

- src/components/document/document-content.tsx
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/table-tool/use-content-change-handlers.ts
- src/components/tools/use-image-content-url.ts
- src/lib/db.ts
- src/models/tools/drawing/drawing-content.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/image/image-content.ts
- src/models/tools/table/table-content.ts
- src/utilities/image-utils.ts
- src/utilities/js-utils.ts
In working on the export capability for geometry tiles, I am frequently working with the changes array, which involves parsing JSON (because the changes are `JSON.stringify`ed). `JSON.parse()` is inherently not type-safe, as its return value is `any` and it throws an exception if it encounters anything it doesn't recognize. We have our own `safeJsonParse()` utility function which converts the exception into an `undefined` return value but doesn't do anything to address the lack of type-safety. A common usage pattern for `safeJsonParse()` looks something like:
```typescript
const foo = safeJsonParse(fooJson) as Foo;
```
This has the advantage of providing type information immediately, but unfortunately it loses the fact that `undefined` is a possible return value. Thus,
```typescript
const …
```
> Make `safeJsonParse()` type-safe

- cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js
- src/components/document/canvas.tsx
- src/components/document/editable-document-content.tsx
- src/components/toolbar.tsx
- src/components/tools/tool-api.tsx
[[#177273772]](https://www.pivotaltracker.com/story/show/177273772)
The unique titling is mediated by the document's `ToolApiInterface`, which is made available to clients via React context. In the original implementation, tiles were created without titles and then were given dynamically generated titles when instantiated. If users didn't explicitly edit the title, however, this dynamically generated title was not saved, which meant that the same tile might get a different dynamically generated title the next time the same document was opened.
Recently, this mechanism was enhanced so that newly created tiles would get a persistent unique title on creation (in theory) rather than waiting for it to be dynamically generated at instantiation time. As a result, a given tile would be able to …
> Fix table/graph title incrementing [#177273772]

- src/lib/db-listeners/index.ts
- src/lib/firebase.ts
- src/lib/logger.ts
This is primarily for debugging purposes. We have had two recent reports of users being able to work locally without incident while their efforts are not saved to firebase. The mechanism by which this is supposed to happen is that we monitor the user's document such that any changes trigger a save to firebase. The reported symptoms are consistent with a failure of this monitoring mechanism, so we log it in hopes of learning something.
> Add logging of monitoring/unmonitoring user documents

- src/components/tools/image-tool.tsx
- src/lib/db.ts
- src/models/image-map.ts
[[#175500575]](https://www.pivotaltracker.com/story/show/175500575)
This allows images copied from multi-class teacher supports to user documents to load successfully rather than showing the loading spinner indefinitely. I consider this to be a workaround rather than a proper fix because it doesn't prevent the initial error from occurring, which results in a console error and a Rollbar error report. It merely patches over the error from the user's perspective after the fact. But in the near term, it's an improvement in the user experience and so seems worth it until we find time to address the underlying issue.
> Temporary workaround for images copied from multi-class supports

- src/lib/logger.ts
While the 1.8.0 release is currently held up due to deploy issues, it occurred to me that logging the document `changeCount` could be useful. The `changeCount` is incremented by the same listener that is responsible for triggering a save to firebase, so we may be able to use the logging of events that should increment the `changeCount` to identify situations in which document changes aren't triggering a save.
> Log the document change count with log messages for use in debugging

- CHANGELOG.md
- Geometry: link/unlink table using dialog [#174765829](https://www.pivotaltracker.com/story/show/174765829) (#942)
- Geometry: add label line tool to toolbar [#175618736](https://www.pivotaltracker.com/story/show/175618736) (#940)
- Geometry: default axes accommodate larger Y values [#177087799](https://www.pivotaltracker.com/story/show/177087799) (#941)
- Table: unlink graph using link/unlink dialog [#176834983](https://www.pivotaltracker.com/story/show/176834983) (#933)
- Table: import/export improvements [#176874316](https://www.pivotaltracker.com/story/show/176874316) (#936)
- Can resize tile heights from corner of tile [#175081175](https://www.pivotaltracker.com/story/show/175081175) (#938)
- Switch to GitHub Actions for CI builds and deployment (#948)
- Fix table/graph title …
> Updated CHANGELOG with final 1.8.0 tweaks

- cypress/plugins/index.js
- cypress/support/index.js
- src/components/tools/geometry-tool/link-table-button.false.test.tsx
- src/components/tools/geometry-tool/link-table-button.true.test.tsx
- src/components/tools/geometry-tool/link-table-button.tsx
While working on unrelated cypress test issues I noticed that the buttons for linking geometry tiles to table tiles were appearing even when the linking feature was disabled. This fixes that and adds unit tests. The unit tests were a bit trickier to write than I expected because of the module-level nature of mocking in jest. I ended up writing tests in two separate modules so that I could mock the `useFeatureFlag()` function to return `true` in one module and `false` in the other.
Separately, following a suggestion from @scytacki with this PR we enable cypress tests to feed into the Codecov coverage reports.
> Don't show link button when linking is disabled

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/geometry-content.test.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/geometry-import.test.ts
- src/models/tools/geometry/geometry-import.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-types.ts
- separate geometry import code from GeometryContent
- add full unit test suite for geometry import code
Reviewer note: mostly the import code just moved but there were a few changes:
- added support for comments on any object
- fixed a bug which caused empty `vertexAngle` changes (effectively NOPs) to be generated for polygon vertices without vertex angles (i.e. most of them).
> Add unit test for geometry import

- cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js
- src/components/tools/text-toolbar.tsx
There are no keyboard shortcuts to support super/subscript so remove the tooltips associated with them.
> Removes tool tips for subscript and superscript in text toolbar

- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/tool-tile.tsx
- src/models/tools/geometry/geometry-export.test.ts
- src/models/tools/geometry/geometry-export.ts
- src/models/tools/geometry/geometry-import.test.ts
- src/models/tools/geometry/geometry-import.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-changes.ts
- src/models/tools/geometry/jxg-movable-line.ts
- src/models/tools/geometry/jxg-types.ts
[[#176874271]](https://www.pivotaltracker.com/story/show/176874271)
The exported content is copied to the clipboard on `[cmd/ctrl]-[option]-e`. (It was `[cmd/ctrl]-[option]-c` previously but that conflicts with a hard-coded Chrome shortcut.)
> Add export for geometry tile content

- .gitignore
- cypress/integration/clue/branch/student_tests/image_tool_spec.js
- package-lock.json
- package.json
- src/components/tools/image-component.tsx
- src/components/tools/image-tool.tsx
- src/components/tools/tool-tile.tsx
- src/components/tools/use-image-content-url.ts
- src/models/image-map.test.ts
- src/models/image-map.ts
- src/models/image.ts
- src/models/stores/app-config-model.ts
- src/models/tools/image/image-change.ts
- src/models/tools/image/image-content.test.ts
- src/models/tools/image/image-content.ts
- src/models/tools/image/image-import-export.test.ts
- src/models/tools/image/image-import-export.ts
- src/utilities/image-utils.ts
[[#176874262]](https://www.pivotaltracker.com/story/show/176874262)
Implements export for image tile via keyboard shortcut (`cmd-option-e`). To simplify authoring, also adds tracking of filename for images imported from local files and then export uses the default filename when exporting. Also adds jest tests for much of the model code and a cypress test for the export via keyboard shortcut.
> Image tile import/export

- src/components/document/canvas.test.tsx
- src/components/document/canvas.tsx
- src/components/document/tile-row.tsx
- src/components/tools/drawing-tool/drawing-layer.tsx
- src/components/tools/drawing-tool/drawing-tool.tsx
- src/components/tools/geometry-tool/geometry-content.tsx
- src/components/tools/image-tool.tsx
- src/components/tools/tool-api.tsx
- src/components/tools/tool-tile.tsx
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/tile-row.ts
- src/models/tools/drawing/drawing-content.ts
- src/models/tools/drawing/drawing-export.test.ts
- src/models/tools/drawing/drawing-export.ts
- src/models/tools/drawing/drawing-objects.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/geometry-export.ts
- src/models/tools/image/image-content.ts
- src/models/tools/image/image-import-export.test.ts
- src/models/tools/image/image-import-export.ts
- src/models/tools/tool-content-info.ts
[[#178747097]](https://www.pivotaltracker.com/story/show/178747097)
Two main issues were identified and reproducible:
1. Export of image urls
- The goal is to replace internal firebase urls for images imported from files on the assumption that those file would be added to the curriculum assets.
- This transformation was sometimes happening for image tiles but the implementation was buggy so it didn't work consistently.
- It wasn't happening at all for geometry tiles with background images or for drawing tiles with imported images.
- The new implementation centralizes the code as much as possible so that it can be shared between tiles.
2. Tile/row heights weren't being exported and appropriate defaults weren't being respected so that exported content would often be displayed with odd …
> Fix import/export issues [#178747097]

- src/lib/db.ts
This PR changes which document is autoloaded when Dataflow is first loaded in the browser.  Instead of loading the newest document, we first try to load the newest program document.  If there are no programs, then we load the newest document of any type.  If there are no documents, then we create a new document.
> Load first program rather than dataset

- cypress/integration/dataflow/branch/sensor_block_spec.js
- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/utilities/node.ts
This PR adds 6 virtual sensors that always appear in the sensor block.  There is one sensor for all of the sensor types other than soil moisture (which is intentionally ignored since we don't know enough about the sensor's expected values).  These virtual sensors display predefined data from an array of values (we will try to make this more sophisticated in later work tied to this story) and update on the program heartbeat (similar to the generators).  A user can select any of these sensors and see the values in the program block.  
This work DOES NOT include allowing the user to run a program and record the sensor data - that will be in a subsequent PR.
> Program editor virtual sensors

- cypress/integration/dataflow/branch/sensor_block_spec.js
Minor tweaks to Dataflow Cypress tests so that the tests succeed regardless of what sensors are on and running.  In the future, however, we should avoid tests like this that relay on the state of physical devices or external software that change from test to test.
> Fix sensor Cypress test

- src/dataflow/components/dataflow-program.tsx
- src/dataflow/components/nodes/controls/sensor-select-control.tsx
- src/dataflow/utilities/node.ts
This PR adds the ability for virtual sensors to be run in the lambda program executor (these are the "demo data" entries in the sensor list).  A `virtual` flag is included in the program node data section which indicates that a virtual value creation method should be used instead of attempting to get sensor values from a live sensor.
The changes in this PR only work with related changes in the dataflow-execution-framework repo.
> Allow virtual sensors blocks to function correctly when a program is running

- src/lib/db-listeners/index.ts
- src/lib/logger.debug.test.ts
- src/lib/logger.test.ts
- src/lib/logger.ts
- Disable logging in dev/qa/test modes
- @eireland reported that excessive logging was interfering with her cypress test debugging. We take this opportunity to disable logging in dev/qa/test modes.
- Enhance jest tests
- Improve coverage of logging code.
- Comment out logging of `INTERNAL_MONITOR_DOCUMENT` and `INTERNAL_UNMONITOR_DOCUMENT`
- These log messages were added to diagnose a potential cause of users losing data. Since adding them there has been no evidence that monitoring logic is at fault and they generate a boatload of spurious log messages so we simply comment them out for now.
> Logging improvements

- src/lib/auth.ts
- src/models/stores/store-types.ts
- src/models/stores/stores.test.ts
- src/models/stores/stores.ts
- src/models/stores/user.ts
- src/models/tools/text/text-content.test.ts
- src/setupTests.ts
- src/utilities/url-params.test.ts
- src/utilities/url-params.ts
plus:
- general improvements to url handling
- add jest tests
- add jestSpyConsole() utility function
- use it to suppress console warning during tests
> Support `network` and `chat` url parameters

- src/assets/left-drag.svg
- src/assets/right-drag.svg
- src/components/document/collapsed-workspace-tab.scss
- src/components/document/resize-panel-divider.scss
- src/components/document/resize-panel-divider.tsx
- src/components/navigation/collapsed-resources-tab.scss
When divider is on the side of a collapsed tab, the drag handler that collapses that side is hidden so that the tab captures the mouse event.
> Fixes the overlapping click control between the collapsed tabs and te drag handles

- cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js
- src/components/chat/chat-panel-header.tsx
- src/components/chat/chat-panel.test.tsx
- src/components/chat/chat-panel.tsx
- src/components/chat/comment-card.test.tsx
- src/components/chat/comment-card.tsx
- src/components/navigation/document-tab-content.tsx
- src/components/navigation/nav-tab-panel.tsx
- src/hooks/document-comment-hooks.ts
- src/hooks/use-stores.ts
- src/lib/auth.test.ts
- src/lib/auth.ts
- src/lib/firestore-schema.ts
- src/models/document/document.test.ts
- src/models/document/document.ts
- src/models/stores/ui.test.ts
- src/models/stores/ui.ts
These are the front-end changes required to hook up to the back-end work I've been doing to support posting new document comments and reading posted document comments. @eireland will take over further front-end refinements while I ready another PR with the back-end changes. The actual code for posting/reading comments has been stubbed out in this PR and will be part of the next PR.
Also with this PR, I took the opportunity to enable `dev`-mode users to be teachers. Previously, teacher-only features were only available in `authed`, `demo`, or `qa` modes. The same `fakeUser` url parameter that can be used to configure the current user in other modes is now also supported in `dev` mode, so `fakeUser=teacher` makes the current user a teacher and `fakeUser=teacher:2222` makes the current user …
> Comment UI synchronization

- cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js
- src/components/document/editable-document-content.tsx
- src/components/navigation/document-tab-content.tsx
- src/components/navigation/document-tab-panel.tsx
- src/components/navigation/focus-document-tracker.tsx
- src/components/navigation/nav-tab-panel.tsx
- src/components/navigation/problem-tab-content.tsx
- src/hooks/document-comment-hooks.ts
- src/models/stores/ui.test.ts
- src/models/stores/ui.ts
In #1014, we introduced a global notion of `referenceDocument` so that the comment panel would know which document to target. In doing so, we also removed the `DocumentTabPanel`'s local notion of `referenceDocument` under the assumption that the global instance could replace the local one. This assumption was incorrect. There are multiple `DocumentTabPanel`s and they each need to keep track of their own independent `referenceDocument`s. To fix the bug we simply restore the `referenceDocument` state to the `DocumentTabPanel` component and simply synchronize it with the global `referenceDocument` when appropriate. For clarity, we also rename the global to be the `focusDocument`.
> Fix tab switch bug introduced recently

- cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js
- src/clue/app-config.json
- src/components/document/document-workspace.tsx
- src/components/thumbnail/tab-panel-documents-section.tsx
- src/lib/auth.ts
- src/lib/db-listeners/db-problem-documents-listener.ts
- src/lib/db-types.ts
- src/lib/db.ts
- src/lib/firebase.ts
- src/models/curriculum/section.test.ts
- src/models/curriculum/section.ts
- src/models/curriculum/unit.ts
- src/models/document/document-content.ts
- src/models/document/document-types.ts
- src/models/stores/documents.ts
- src/public/curriculum/moving-straight-ahead/moving-straight-ahead.json
- src/public/curriculum/moving-straight-ahead/msa-teacher-guide.json
- src/public/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
This PR creates a default planning document (if one doesn't already exist) for each of a teacher's problems in a planning-document-enabled curriculum unit. ~~There is no UI for viewing or interacting with the planning document at this point, however. That will be provided in a subsequent PR.~~ The planning document shows in the document browser next to the problem document. There are still some issues, for instance the document header doesn't render when editing the planning document, but it basically functions like a normal document at this point.
> Support planning document

- functions/src/post-document-comment.ts
- functions/src/shared.ts
- functions/test/post-document-comment.test.ts
- functions/test/shared.test.ts
- src/hooks/use-stores.ts
- src/lib/firestore-schema.ts
- add uid field for curriculum documents
- include uid in path for non-networked teachers
To support different non-networked teachers ability to comment on individual curriculum "documents" without seeing each others' comments, we need to include the user id in the curriculum "document" path. Likewise, for non-networked teachers to have access to their own commented curriculum "documents" but not to those of other teachers, we need to associate each curriculum "document" with the teacher that created it.
> Update postDocumentComment firebase function

- firebase-test/package-lock.json
- firebase-test/package.json
- firebase-test/src/curriculum-rules.test.ts
- firebase-test/src/documents-rules.test.ts
- firebase-test/src/setup-rules-tests.ts
- firebase-test/src/user-rules.test.ts
- firestore.rules
- src/lib/firestore-schema.ts
Note: as written these rules only work for curriculum "documents". Firebase documents will require some additional attention, including potentially sharing some code between the two.
> Update security rules to support networked teachers commenting on curriculum "documents" [#179361057]

- src/components/demo/demo-creator.tsx
The need to add `&chat` for the networked demo teachers continues to be a source of confusion, so we eliminate it.
> Add `&chat` url parameter automatically for demo teachers 2 and 3

- cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js
- cypress/support/commands.js
- src/components/chat/chat-panel.test.tsx
- src/components/chat/chat-panel.tsx
- src/components/chat/comment-card.test.tsx
- src/components/chat/comment-textbox.test.tsx
- src/components/chat/comment-textbox.tsx
- src/components/document/canvas.tsx
- src/components/document/document-content.tsx
- src/components/document/editable-document-content.tsx
- src/components/navigation/document-tab-content.sass
- src/components/navigation/document-tab-content.tsx
- src/components/navigation/nav-tab-panel.tsx
- src/components/navigation/problem-panel.tsx
- src/components/navigation/problem-tab-content.tsx
- src/components/tools/tool-tile.sass
- src/components/tools/tool-tile.tsx
- src/models/stores/ui.ts
Adds ability to select a tile for comment. 
When user selects a tile with chat panel open, user can comment on selected tile. 
When user changes tile selection, chat panel updates to show comments for the new selection.
When user deselects tile, document is selected by default, and chat panel updates to show document comments only.
When user has selected a tile, and changes to a different tab, the tile is deselected, and the currently selected tab document is selected.
Moved chat panel state to ui stores.
> 179458436 tile comment highlight

- functions/package.json
- functions/src/index.ts
- functions/src/post-document-comment.ts
- functions/src/shared.ts
- functions/src/validate-commentable-document.ts
- functions/test/validate-commentable-document.test.ts
- src/hooks/document-comment-hooks.test.ts
- src/hooks/document-comment-hooks.ts
- src/lib/firestore-schema.ts
Previously, we only created the entry for a given document in Firestore when the first comment was added. This seemed to make sense since there's currently no other reason to have the document entry beyond providing a place to store comments. Unfortunately, when attempting to read the comments for a document this led to an attempt to add Firestore listeners to a non-existent document, which Firestore didn't take too kindly to.
The new approach is to create the document entry in Firestore (if it doesn't already exist) before the first read attempt, so that when the time comes to install the comment listener the document already exists. To accomplish this, there is a new Firebase Function, `validateCommentableDocument`, which checks whether the specified document exists in Firestore and …
> Ensure existence of document before requesting comments for it [#179540693]

- tool-tiles.md
This PR adds `tool-tiles.md` which includes a starting point for documenting tool tiles in CLUE.
> document tool tiles

- src/clue/app-config.json
This PR changes the order of the teacher document preview so that in the document thumbnails under My Work > Workspaces, the planning document is shown after the problem document.  Changes include:
- change section ordering in `app-config` file so original order is used and the planning document is shown after the problem document
PT Story: 
https://www.pivotaltracker.com/story/show/179427590
https://collaborative-learning.concord.org/branch/planning-doc-order/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=teacher:2&unit=sas&problem=0.1&chat
> Change thumbnail preview order of planning and problem docs

- src/components/chat/comment-card.test.tsx
- src/components/chat/comment-card.tsx
- src/hooks/firestore-hooks.ts
@eireland:
- you were right that simply removing the `any` didn't work
- I was right back when we added the `id` to the returned snapshot in `useCollectionOrderedRealTimeQuery` when I said that we were going to have to fix the types somewhere down the road.
The issue is that the delete comment code relies on the fact that the query returns an `id` with each comment, but by declaring the `CommentCard` props to include `postedComments?: CommentDocument[]`, we were explicitly telling it that there would _not_ be an `id` property on the comments. The right fix is to have `useCollectionOrderedRealTimeQuery` type its return appropriately and then to change the type of `postedComments` to match.
> Eliminate `any` from delete comment code

- firebase-test/src/class-rules.test.ts
- firebase-test/src/offering-rules.test.ts
- firebase-test/src/setup-rules-tests.ts
- firestore.rules
- src/lib/firestore-schema.ts
[[#179154344]](https://www.pivotaltracker.com/story/show/179154344)
For those following along at home:
**class**: teacher's class created in learn portal
**activity**: an assignable/runnable interactive for student use defined in the learn portal (corresponds to a problem in CLUE)
**offering**: an assignment of an `activity` to a `class`. A given `activity` can be assigned to many classes and a `class` can have many assignments of different activities.
To implement the teacher network features, we need to get a list of the other classes available in the network that have assigned the same activity/problem, because individual documents are only generally relevant to a particular problem. Therefore, ultimately we want to be able to query for all `offerings` that are assignments of the …
> Update firestore schema and security rules for classes and offerings

- src/components/app.tsx
- src/index.tsx
- src/models/stores/groups.ts
- src/models/stores/stores.ts
This PR auto assigns users to groups when in preview mode.  In doing so, the group chooser dialog is not shown.  Changes include:
- determine in App component if we are in preview mode.  If we are, do not show group chooser dialog and auto assign user to a group
- modify group store to allow students who are not members of a class to be added to the store when we are in preview mode
PT Story: 
https://www.pivotaltracker.com/story/show/179152641
https://collaborative-learning.concord.org/branch/no-preview-group-dialog/?demo
Deployed branch with URL params that put us in preview mode:
https://collaborative-learning.concord.org/branch/no-preview-group-dialog/?unit=msa&problem=4.3&domain=https%3A%2F%2Flearn.staging.concord.org%2F&domain_uid=218
> 179152641 no preview group dialog

- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
[[#179680306]](https://www.pivotaltracker.com/story/show/179680306)
Assign predictable ids to tiles in imported curriculum content for use in tile commenting.
During import we keep track of the current section and the number of tiles of each type in the current section so that tiles can be given tile ids like `introduction_Text_1` and `what-if_Geometry_2`.
Along the way, also:
- improve the typing of the import code
- add a missing unit test for the `createDefaultSectionedContent()` function
> Fix commenting on individual tiles in curriculum content [#179680306]

- src/hooks/use-stores.test.ts
- src/hooks/use-stores.ts
- src/models/stores/documents.ts
[[#179661807]](https://www.pivotaltracker.com/story/show/179661807)
For the comment card to show the correct icon, there must be a mechanism for getting from a document key/id and tile id to the type of the tile. This provides that mechanism.
Usage would look something like the following:
```typescript
interface IProps {
documentKey?: string;
tileId?: string;
}
export const ToolIconComponent: React.FC<IProps> = ({ documentKey, tileId }) => {
const tileType = useTypeOfTileInDocumentOrCurriculum(documentKey, tileId);
const { appIcons } = useContext(AppConfigContext);
...
};
```
Note: the coding of tile type into the tile id of curriculum documents is implemented in #1048, so this won't work _in situ_ until that PR is merged.
> Add `useTypeOfTileInDocumentOrCurriculum()` hook

- src/components/navigation/document-tab-content.tsx
This PR unselects tiles when the document header is clicked.  If a teacher user is adding comments, this effectively selects the document for commenting.  This change applies to all document types (original request was for learning log).  Changes include:
- unselect tiles when document header is clicked
PT Story: 
https://www.pivotaltracker.com/story/show/179660736
https://collaborative-learning.concord.org/branch/document-selection-via-header/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=teacher:2&unit=sas&problem=0.1&chat
> unselect tiles when document header is clicked

- firebase-test/package-lock.json
- firebase-test/package.json
- firebase-test/src/class-rules.test.ts
- firestore.rules
- package-lock.json
- package.json
- src/components/app.tsx
- src/components/class-menu-container.tsx
- src/hooks/document-comment-hooks.ts
- src/hooks/firestore-hooks.test.ts
- src/hooks/firestore-hooks.ts
- src/lib/auth.test.ts
- src/lib/auth.ts
- src/lib/firestore-schema.ts
- src/lib/firestore.test.ts
- src/lib/firestore.ts
- src/lib/portal-api.test.ts
- src/lib/portal-api.ts
- src/lib/portal-types.ts
- src/lib/teacher-network.test.ts
- src/lib/teacher-network.ts
- src/models/stores/user.test.ts
- src/models/stores/user.ts
- src/setupTests.ts
[[#179154344]](https://www.pivotaltracker.com/story/show/179154344)
On launch by a teacher, we synchronize each of the teacher's CLUE offerings (assignments) and classes that have assigned those offerings to firestore so that they can be used for future network lookups. Currently, if a given class/offering is already in firestore we just leave it alone, assuming that it has already been synchronized. With a little more work we could actually update the information in firestore in case there have been changes to the set of teachers of the class or other non-static information, but those changes are likely to be infrequent at best and so we leave handling of updates for a future story. Most of the information we need was already available but for security rules purposes we need to request …
> Synchronize teacher's CLUE classes and offerings to firestore for network use [#179154344]

- src/components/navigation/document-tab-panel.sass
- src/components/thumbnail/collapsible-document-section.tsx
This PR improves content visibility by adding scrolling to the left panel containing document thumbnails and by defaulting network collapsible content to closed.  In effect, this makes it so we can see all of the panel content as we add more and more content to the panel.  Changes include:
- add vertical scrolling to left panel containing document thumbnails
- default network collapsible content to closed
PT Story: 
https://www.pivotaltracker.com/story/show/179746600
https://collaborative-learning.concord.org/branch/left-panel-scrolling/?demo
> 179746600 left panel scrolling

- src/lib/firestore.test.ts
Mocking was incomplete for the `getFirestoreUser()` test, leading to an exception being thrown which was an ignorable warning in node 14 but @Concord-Jim noted that it causes the test to fail in node 16.
> Fix `getFirestoreUser()` test so it doesn't throw an exception

- src/models/stores/stores.ts
Set the value of isPreviewing in our base store so that we can properly decide if we are in preview mode and need to show the group chooser dialog.
> Set isPreviewing in store

- cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js
- src/assets/icons/document-icon.svg
- src/components/chat/chat-panel.test.tsx
- src/components/chat/chat-panel.tsx
- src/components/chat/comment-card.scss
- src/components/chat/comment-card.test.tsx
- src/components/chat/comment-card.tsx
- src/components/chat/tool-icon-component.tsx
- src/components/document/document-file-menu.scss
In the chat panel, when a particular type of tile is selected, the icon corresponding to that type of tile is shown in the chat header area.
With a table tile selected:
With a text tile selected:
> 179661807 comment icon as with tile

- src/components/navigation/document-tab-content.tsx
- src/components/navigation/document-tab-panel.tsx
- src/components/navigation/network-documents-section.tsx
- src/components/thumbnail/collapsible-document-section.scss
- src/components/thumbnail/collapsible-document-section.tsx
- src/components/thumbnail/tab-panel-documents-section.sass
This PR displays thumbnails for the personal, problem, planning, and learning log teacher network docs for each class that appears in the My Classes and My Network sections in the left panel.  Changes include:
- display a thumbnail for teacher network docs
- thumbnail is in canned state when we do not have the document content, and in the normal thumb state when we have the document content
- load content when clicked (note we are NOT properly restoring the tile content, but I believe that can be handled in another story and is unrelated to the UI)
WARNING: we are NOT properly restoring the tile content when we call `fetchRemoteContent`.  The call is successful, the tile content appears to be retrieved from the DB, we add content to the document model, but the tile content is not being …
> Display network doc thumbs and load content when clicked

- src/hooks/network-resources.ts
This PR sets the proper type on a network planning document (was previously set to a problem doc).  In turn, this allows the proper thumbnail caption to be shown.
> Set proper document type on network planning document

- src/components/navigation/document-tab-content.tsx
This PR hides the edit button in the header of the reference doc when the loaded reference doc is a network doc.
> Hide edit button when showing network docs

- src/index.html
- src/index.sass
For ref., PT ticket: https://www.pivotaltracker.com/story/show/179843180
Please note the "Dashboard" caption in the toggle button, in the screen shot below:
I tested with the four characters specifically mentioned in the ticket, but rendering is NOT limited to just those four glyphs. 
See:
https://fonts.google.com/noto/specimen/Noto+Sans+Math
and:
https://fonts.google.com/noto/specimen/Noto+Sans+Symbols+2
Note that we're retrieving the glyphs once from Google's CDN, but after that they are cached in the user's Web browser. This is the _same_ mechanism that is already being used for the existing 'Lato' type face:
> Adds: "Noto Sans Math" and "Noto Sans Symbols 2" type faces to the font 'stack'

- functions/src/post-document-comment.ts
- functions/src/shared.ts
- functions/src/validate-commentable-document.ts
- functions/test/post-document-comment.test.ts
- functions/test/validate-commentable-document.test.ts
- src/hooks/use-stores.test.ts
- src/hooks/use-stores.ts
[[#179652167]](https://www.pivotaltracker.com/story/show/179652167)
- `useDocumentFromStore()`, `useDocumentMetadataFromStore()`, and `useTypeOfTileInDocumentOrCurriculum()` now consider network documents as well as local documents
- add `contextId` to `IDocumentMetadata`
With these changes, commenting on network documents or on tiles within network documents works like commenting on local documents.
@Concord-Jim Since Matt's not available today, sync review probably makes sense.
> Fix commenting on network documents

- src/lib/logger.ts
This PR updates the `logManagerUrl` to use proper staging and production urls based on the current user `portal` value.  We use the production URL only if the `portal` value is "learn.concord.org".
> update logging url to use dev or prod

- src/components/thumbnail/tab-panel-documents-section.sass
This PR prevents tiles from being selected when inside of a thumbnail.  Previously, when a user clicked a thumbnail to open a document, the thumbnail was also getting mouse events that permitted a tile to be selected with the same action.  This was resulting in a seemingly random tile being selected when a document was opened.  Changes include:
- use `pointer-events: none` on div around thumbnail to prevent mouse events from getting to the thumbnail
PT story:
https://www.pivotaltracker.com/story/show/179822339
https://collaborative-learning.concord.org/branch/clear-doc-selection-state/?demo
> Prevent tiles from being selected when displayed in thumbnail

- src/components/tools/tool-tile.tsx
Sample content, before:
```
{
"type": "Text",
"format": "html",
"text": [
"<p>S&amp;S 0.1 Teacher Support</p>"
]
}
```
After:
```
{
"content": {
"type": "Text",
"format": "html",
"text": [
"<p>S&amp;S 0.1 Teacher Support</p>"
]
}
}
```
> Tile copy to clipboard: put all exported content in a top-level object, under key: "content"

- cypress/support/elements/clue/cCanvas.js
I'm not sure this change will fix the flakey-ness, but it is my best guess.
Here is the dashboard run where it couldn't find the delete dialog
https://dashboard.cypress.io/projects/3pbqac/runs/2218/test-results/215e4e23-6f88-483f-ad02-3b5505cfaf20
The fix here is to confirm the element is selected before clicking the delete tool.
It seems possible that the click on the tile followed by the delete tool click happened too fast.
> try to fix a flakey test where delete dialog wasn't showing

- .github/workflows/ci.yml
We got some errors during uploading, that I think only happened when re-running the build.
The error message from codecov implied it would be fixed if we included the token.
In theory the token isn't required because this is an open source project, but it can't
hurt.
> update the codecov action version, and include token

- cypress/support/elements/clue/TextToolTile.js
This adds a wait after typing the text.
There doesn't seem to be any debouncing of the text so it should be saved quickly.
In most cases this seemed to be working, hopefully the wait will decrease the failures.
As the comment says, ideally there would be a way to make sure the data was actually
saved.
> a test failed because text was not saved before the page navigation

- src/lib/logger.test.ts
- src/models/document/document-content.test.ts
- src/models/document/document-content.ts
- src/models/document/document.ts
- src/models/tools/drawing/drawing-content.test.ts
- src/models/tools/drawing/drawing-content.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/image/image-content.test.ts
- src/models/tools/image/image-content.ts
- src/models/tools/placeholder/placeholder-content.ts
- src/models/tools/table/table-content.ts
- src/models/tools/text/text-content.ts
- src/models/tools/tool-content-info.ts
- tool-tiles.md
This is second in the series of PRs to extract the tool code from the core. The goal of these PRs it to make it possible to add a new tool to CLUE without changing the core code. The only thing that should be required is importing a javascript library including the tool, and adding a reference to it in the app-config.json
The first PR is here: https://github.com/concord-consortium/collaborative-learning/pull/1113
This PR builds on the first by changing the `addTile` action in the `DocumentContentModel` to work with any tool that has been registered.  However it is still limited by the `DocumentTool` type of its `tool` parameter. That will be addressed later.
Supporting this required the following changes:
- unified set of parameters passed to all defaultContent functions
- supporting …
> Dynamic add tile

- src/app-config.ts
- src/components/document/canvas.test.tsx
- src/components/toolbar.test.tsx
- src/components/tools/drawing-tool/drawing-tool.tsx
- src/components/tools/placeholder-tool/placeholder-tool.tsx
- src/components/tools/table-tool/table-tool.tsx
- src/components/tools/tool-tile.tsx
- src/lib/db.test.ts
- src/lib/logger.test.ts
- src/models/document/document-content.test.ts
- src/models/document/document.test.ts
- src/models/stores/ui.test.ts
- src/models/tools/drawing/drawing-content.ts
- src/models/tools/drawing/drawing-registration.ts
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/geometry-registration.ts
- src/models/tools/image/image-content.ts
- src/models/tools/image/image-registration.ts
- src/models/tools/placeholder/placeholder-content.ts
- src/models/tools/placeholder/placeholder-registration.ts
- src/models/tools/table/table-content.ts
- src/models/tools/table/table-registration.ts
- src/models/tools/text/text-content.ts
- src/models/tools/text/text-registration.ts
- src/models/tools/tool-content-info.ts
- src/models/tools/tool-tile.test.ts
- src/models/tools/tool-tile.ts
- src/models/tools/tool-types.test.ts
- src/models/tools/unknown-content.ts
- src/register-tools.ts
Part 3 of a series of PRs to extract the tool code from the core. The goal of these PRs it to make it possible to add a new tool to CLUE without changing the core code. The only thing that should be required is importing a javascript library including the tool, and adding a reference to it in the app-config.json
The previous PRs are:
- https://github.com/concord-consortium/collaborative-learning/pull/1113
- https://github.com/concord-consortium/collaborative-learning/pull/1115
The main feature of this PR is to use the tool content info registry to store and lookup the tool component and css class used by the tool component.  
Taking that approach resulted in a several other things that needed to be changed:
- the registration of tools with the tool content info registry needed to be split …
> Dynamic tool component

- src/components/chat/chat-panel.tsx
- src/lib/logger.test.ts
- src/lib/logger.ts
~~Putting this up as a draft PR in the interest of not losing it. This was discussed as a possible enhancement for #1102, but it was decided not to include it there. As such, this PR should remain in draft mode and not be merged until after the 2.0.0 release.~~
Now that 2.0.0 is out the door I believe the time has come.
> Support `action` as typed string when logging comment actions

- src/components/delete-button.test.tsx
- src/components/delete-button.tsx
- src/components/document/document-workspace.tsx
- src/components/document/document.tsx
- src/components/document/editable-document-content.tsx
- src/components/tool-button.test.tsx
- src/components/tool-button.tsx
- src/components/toolbar.test.tsx
- src/components/toolbar.tsx
- src/models/stores/app-config-model.ts
- src/models/tools/tool-button.ts
- src/models/tools/tool-types.ts
- src/utilities/mst-utils.test.ts
The main change here is to pass a MST model of the toolbar button instead of a plan JS object.
The reason to try doing this is because I'm trying to get rid of the usage of `DocumentTool` where possible.  By passing the ToolButtonModel instance to the ToolButton component it can use this model instead of the `DocumentTool` type.
This also made it possible to move the logic of figuring out the Icon component of a tool button into the model itself. So now the code using these models just uses `model.Icon`. 
Some specific changes:
- the toolbar prop passed to DocumentComponent is now just `appConfig.toolbar` instead of its snapshot
- the toolbar prop of DocumentToolbar is never undefined, this was the case before but the types didn't reflect it
- when the DocumentToolbar is first rendered it …
> Mst toolbar

- dependencies-notes.md
- package-lock.json
- package.json
- src/components/tools/table-tool/cell-text-editor.tsx
- src/components/tools/table-tool/column-header-cell.scss
- src/components/tools/table-tool/editable-header-cell.tsx
- src/components/tools/table-tool/header-cell-input.tsx
- src/components/tools/table-tool/table-tool.scss
- src/components/tools/table-tool/table-tool.tsx
For some time now we've been stuck on version `7.0.0-canary.34` because of some styling changes introduced in `7.0.0-canary.35` that broke the styling of our inline cell editors. With this PR we introduce a fix for those styling changes which allows us to update to `7.0.0-canary.46`. Unfortunately, `7.0.0-canary.47` introduces some API changes for the `RowFormatter` classes that will require some refactoring of our code. Therefore, discretion being the better part of valor and all that, we'll leave the `RowFormatter` refactoring for another day. Along the way we also have to deal with some row-height-handling changes introduced in `7.0.0-canary.44` that required some changes to the way we handle the layout of column header cells with formulas.
The fixes introduce some uncomfortably tight …
> Update ReactDataGrid library

- src/components/navigation/document-tab-content.tsx
- src/components/thumbnail/tab-panel-documents-subsection-panel.tsx
- src/models/document/document-utils.ts
[[#180463778]](https://www.pivotaltracker.com/story/show/180463778) Show planning document title in Resources
[[#180484449]](https://www.pivotaltracker.com/story/show/180484449) Show "Network User" for caption of published documents viewed via teacher network
Demo: https://collaborative-learning.concord.org/branch/planning-title/?demo
For the planning document title, this is a classic case of redundant code in two different places where one was updated to account for the possibility of planning documents while the other wasn't. The fix here is to consolidate the two usages into one utility function to avoid this from happening in the future.
For the "Network User", we just need to test whether the document is a remote document (i.e. loaded over the network). Note that the original request …
> Fix planning document title and "Network User" in resources

- src/models/tools/geometry/geometry-content.ts
[[#180496888]](https://www.pivotaltracker.com/story/show/180496888) Extra points on a graph are created on duplication of a figure created from a linked table
Odd that this wasn't discovered before now. For implementation reasons we maintain a hidden internal `__label__` attribute to store the label of each linked point. When we made the transition from only supporting two columns (one y-attribute) to supporting multiple columns, the code for creating the linked points expanded from creating a single point for each row of the table to a loop which creates a single point for each y-attribute of the table. Unfortunately, this loop failed to account for the `__label__` attribute, and so we end up creating extraneous hidden points in JSXGraph, which then become visible on copy. The fix is to …
> Ignore __label__ attribute when linking table to geometry

- src/lib/db-listeners/index.ts
- src/lib/logger.test.ts
- src/models/document/document.test.ts
- src/models/document/document.ts
In debugging a separate issue, I encountered (again) the fact that the model objects used by our tile components frequently seem to get destroyed out from under them and then subsequently recreated. After looking into this further it appears that there is a relatively straightforward fix. Historically, our firebase listeners have essentially done the following upon receipt of a new document snapshot from firebase:
```typescript
documentModel.setContent(DocumentContentModel.create(snapshot));
```
i.e. every firebase snapshot gets turned into a new `DocumentContentModel` which then replaces the existing content model along with all of its internal tile models.
The simple fix here is to replace `DocumentModel.setContent()` with the following:
```typescript
if (self.content) { …
```
> Use applySnapshot() in DocumentModel.setContent()

- src/models/curriculum/unit.test.ts
- src/models/curriculum/unit.ts
- src/models/stores/stores.ts
@lbondaryk recently asked about the performance implications of the tremendous amount of content that is built into CLUE, i.e. does having JSON for many different units present in the application, each of which contains references to many different images have any performance implications. The answer to both of those questions is no, thankfully, because we only load JSON files for the active unit and we only load images for displayed content. This investigation led me to discover one inefficiency, however, which can also be viewed as a security concern, namely that we were previously loading the teacher guide content for the unit unconditionally. We were only _displaying_ it for teachers, but the teacher guide content was still being loaded for students, which is both a performance issue …
> Only load teacher guide content for teachers

- src/public/curriculum/stretching-and-shrinking/sas-teacher-guide.json
While investigating the same set of issues that led to #1138 and #1139, I noticed that even after fixing those two issues there was still an image tile being destroyed/recreated. It turns out that the authored content for the SAS teacher's guide included two image tiles with the same id, which meant that the second one replaced the first. The practical consequence of this was that only the left-handed image was shown rather than both the left- and right-handed images which presumably was the intent. The fix here is simply to remove the ids, as they will be assigned automatically if they're not present.
This is in the SAS teacher guide, problem 1.2, Launch section.
> Eliminate duplicate image tile ids in SAS teacher's guide

- src/components/document/tile-row.tsx
- src/public/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
When a text tile is next to an image tile in curriculum content, the height of the image tile was overriding the height of the row regardless of the height of the text tile. With this change, we no longer allow image tiles in multi-tile rows to override an authored height. The fix is narrow enough that it seems safe to make this change close to the upcoming release.
This is used in this case to fix the height of a "Text" tile in the `Initial Challenge` section of SAS 0.1 ("When you click into a text tile...") and a "Text" tile in the `What If...?` section of SAS 0.1 ("The Share slider makes your work...").
Testable at https://collaborative-learning.concord.org/branch/row-height-fix/?demo.
> Don't let image tile override row height of multi-tile rows

- cypress/integration/clue/branch/student_tests/workspace_test_spec.js
- src/hooks/network-resources.test.ts
- src/hooks/network-resources.ts
- src/lib/db-listeners/db-other-docs-listener.ts
- src/lib/db-listeners/db-problem-documents-listener.ts
- src/lib/db-listeners/index.test.ts
- src/lib/db-listeners/index.ts
- src/lib/db.test.ts
- src/lib/db.ts
- src/models/stores/documents.test.ts
- src/models/stores/documents.ts
- src/models/stores/stores.ts
- src/setupTests.ts
- Use onPatch() and throttledSaveDocument() for local document monitoring rather than onSnapshot()
- Fix several race conditions and redundant document instances
In my investigation of recent data loss reports, I did some experimenting with MST's `onPatch` and `onSnapshot` handlers. During this investigation, I encountered some situations in which the `onSnapshot` handler did not fire but the `onPatch` handler did. In fact, the `onPatch` handler often fires multiple times for a single change in situations when the `onSnapshot` handler doesn't fire at all. Therefore, we replace the `onSnapshot` handler we were using previously for detecting document content changes with an `onPatch` handler and we then throttle the saving so that multiple patches in succession will only trigger a single …
> Multiple document monitoring/saving-related improvements

- docs/document-types.md
- src/lib/db-types.ts
@scytacki was asking about the different document types in CLUE, which reminded me that I had started this documentation a while back but then got distracted before finishing it.
> Add documentation for CLUE document types

- src/lib/db.ts
Now that #1148 has normalized the process of loading/creating required documents, the code paths for opening an existing document after the corresponding `requiredDocuments` promise has resolved to null are no longer necessary.
> Simplify required document creation code paths

- src/lib/db-listeners/db-other-docs-listener.ts
- src/lib/db-listeners/db-problem-documents-listener.ts
- src/lib/db-listeners/db-publications-listener.ts
- src/lib/db.ts
In investigating #1148, I came across a demo user with a number of documents with correctly saved metadata but no document contents. The change in this PR turns that error condition into a warning.
> More robust handling of errors when opening an invalid or corrupted firebase document

- src/clue/components/progress-widget.tsx
This is another realization stemming from the investigation into #1148. At some point I encountered a failing cypress teacher dashboard test which turned out to be because some of the demo users in the demo class used for the teacher dashboard test had spurious invalid problem documents in addition to the expected problem document, presumably as the result of a prior bug. It is trivial to handle this case in the teacher dashboard code and seems worth doing given the likelihood that other such bugs may be encountered in the future. In this particular case, I also took the liberty of deleting the extraneous problem documents from the affected users, but I tested this code before doing so.
> Improve handling of invalid problem documents in teacher dashboard

- src/components/navigation/document-tab-panel.sass
PT: [[#180731966]](https://www.pivotaltracker.com/story/show/180731966) (again)
Fix issues with CSS contention between learning-logs and class-work for published learning logs.
Learning logs tabs are colored learning-log-green _unless_ they're published learning logs shown under the class work tab, in which case they should be class-work-purple. Need to adjust the CSS so the class-work-purple overrides appropriately.
Thx to Saravanan for pointing out the problem.
Demo: https://collaborative-learning.concord.org/branch/subtab-colors/?demo
> Tweak sub-tab color fix [#180731966]

- src/components/document/resize-panel-divider.scss
- src/components/document/resize-panel-divider.tsx
PT: [[#180731992]](https://www.pivotaltracker.com/story/show/180731992)
Demo: https://collaborative-learning.concord.org/branch/fix-divider/?demo
The essence of the fix here is that instead of having the divider always be as wide as the two arrow buttons, even when only one of the buttons is showing, now we shrink the divider to be only wide enough to contain one arrow button when only one is showing. In other words, in the min and max positions, the divider container no longer overlaps the sidebars which contain their own arrow buttons. To accomplish this we add new `divider-min` and `divider-max` classes to the `resize-panel-divider` and use those to tweak the styles for the min/max positions. The styling feels fragile here, but a larger refactor didn't seem warranted in this case.
> Fix divider click behavior

- src/components/tools/geometry-tool/geometry-content.tsx
[[#180769939]](https://www.pivotaltracker.com/story/show/180769939)
Only present axis settings dialog when axis label is top-most clicked element.
> Geometry: fix axis dialog contention [#180769939]

- src/models/tools/geometry/jxg-board.ts
PT: [[#180805779]](https://www.pivotaltracker.com/story/show/180805779)
Demo: https://collaborative-learning.concord.org/branch/fix-axis-ticks/?demo
A teacher reported that one of her students had a problem in which CLUE would crash every time he visited the four-up view. The real problem turned out to be that another student in his group had a geometry tile which would hang when viewed. Drilling down into the offending geometry tile indicated that the second student had changed the bounds to be enormous and that for some reason the code was hanging while trying to process thousands of axis ticks. Several hours of debugging later, the source of the trouble turned out to be the fact that when resizing axes we were:
1. Setting the new axis bounds
2. Removing the old axes
3. Creating the new …
> Fix axis ticks crash [#180805779]

- src/lib/db-listeners/db-problem-documents-listener.ts
This shouldn't ever happen, but one demo user was encountered for which this was true.
> Handle numeric `uid` fields

- src/components/tools/geometry-tool/geometry-content.tsx
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/jsxgraph.d.ts
- src/models/tools/geometry/jxg-board.test.ts
- src/models/tools/geometry/jxg-board.ts
- src/models/tools/geometry/jxg-dispatcher.ts
- src/models/tools/geometry/jxg-table-link.ts
PT: arose from investigation of [[#180805779]](https://www.pivotaltracker.com/story/show/180805779)
Demo: https://collaborative-learning.concord.org/branch/nested-suspend/?demo
- suspend updates while handling axis bounds changes
- support nested suspension of updates
Note: this PR is _not_ expected to be merged for release 2.1.2. I think we should give it more time for testing and then release it in the _next_ release.
> Geometry: handle axis bounds changes more efficiently

- cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js
- cypress/integration/clue/branch/student_tests/graph_tool_spec.js
- cypress/support/elements/clue/GraphToolTile.js
- src/models/tools/geometry/geometry-content.ts
- src/models/tools/geometry/geometry-import.ts
- src/models/tools/geometry/jxg-board.ts
PT: [[#180817314]](https://www.pivotaltracker.com/story/show/180817314)
Demo: https://collaborative-learning.concord.org/branch/axis-bounds/?demo
Increases the amount of space to the left of the requested axis bounds for axis labels. This additional space will always be present. Dynamically adjusting the space to accommodate the actual size of the Y axis labels is left for another day.
> Adjust X axis bounds to leave room for Y axis labels [#180817314]

- src/models/tools/table/table-content.test.ts
- src/models/tools/table/table-content.ts
This expression evaluation exception was encountered in a user document in the field. The expression evaluator is documented as throwing exceptions if, for instance, an undefined variable is referenced in the expression. Given that, we should handle exceptions appropriately rather than letting them bubble up to callers.
> Table: Handle expression evaluation exceptions

- src/models/stores/stores.ts
In some paths, CLUE loads the default unit (S&S) before identifying and loading the actual desired unit. In this case we were not replacing the S&S teacher guide with the correct unit-specific teacher guide.
> Fix spurious references to S&S teacher guide

- src/models/stores/stores.ts
Previous fix was too narrow. We _always_ want to reset the teacher guide content when the unit/problem changes rather than trying to be clever about when we do or don't need to change it.
> Fix teacher guide content (again)

- .eslintrc.js
- .vscode/settings.json
- scripts/package.json
- scripts/update-supports-images.ts
This is the first big step in properly supporting multi-class images referenced from published multi-class supports. The fundamental limitation of the prior design is that while individual supports are published to firestore with rules for which classes should have access to those supports, image references in the content of those supports don't contain enough information to find the original images in cases in which the image data does not reside in the same class context as the document from which the support was published. This can happen either because teachers copy images from one support to another document in another class and then republish (the cause of the most recent issues encountered by some teachers) or because students copy images from published supports to their own …
> Add script for validating/migrating multi-class images [#180873340]

- functions/package-lock.json
- functions/package.json
- functions/src/get-image-data.ts
- functions/src/index.ts
- functions/src/shared.ts
- functions/test/get-image-data.test.ts
- functions/test/test-utils.ts
- src/components/tools/image-tool.tsx
- src/lib/db.ts
- src/models/image-map.test.ts
- src/models/image-map.ts
[[#180873340]](https://www.pivotaltracker.com/story/show/180873340)
This is part two of the work to support multi-class images in multi-class supports. In [part one](https://github.com/concord-consortium/collaborative-learning/pull/1174) we designed the firestore schema and implemented a script to migrate existing published supports to the new format. With this PR, we implement the firebase function that retrieves the image data making use of the new firestore collections where appropriate.
In addition to the jest tests, this has already been tested in the `demo` and `learn.staging.concord.org` contexts. Given that no existing clients call the new function, it can (and has) been deployed without affecting any existing clients. Once all phases of this work have been completed we can retire …
> Add getImageData_v1 firebase function for retrieving image data

- src/components/thumbnail/tab-panel-documents-subsection-panel.tsx
- src/lib/portal-api.ts
[[#180876987]](https://www.pivotaltracker.com/story/show/180876987)
When viewing the contents of networked classes, it can be confusing to see more than one personal or planning document with the same caption. This PR alleviates that by adding the user name and creation date (if known) to the caption shown for networked documents.
> Improve captions of network documents [#180876987]

- src/lib/db.test.ts
- src/lib/db.ts
[[#181124054]](https://www.pivotaltracker.com/story/show/181124054)
Fixes a copy/paste/logic bug in planning document promise-handling which likely explains the occurrence of extraneous planning documents in some circumstances.
@scytacki I also added tests that would have caught the bug, officially closing the barn door. Adding the tests required setting up offline mocking of firebase that should prove useful for writing additional tests down the road.
> Fix promise-handling bug in creation of planning documents

- cypress/fixtures/teacher-dash-data.json
- cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js
Recent portal changes mean that archived classes are no longer returned to clients. The teacher dashboard cypress test needs to be updated to accommodate the change.
> Fix teacher dashboard tests to only rely on active (not archived) classes

- functions/package-lock.json
- functions/package.json
- functions/src/get-image-data.ts
- functions/src/publish-support.ts
- functions/test/get-image-data.test.ts
- functions/test/publish-support.test.ts
- functions/tsconfig.json
- scripts/update-supports-images.ts
[[#181147217]](https://www.pivotaltracker.com/story/show/181147217)
In [[#180873340]](https://www.pivotaltracker.com/story/show/180873340), @tejal-shah pointed out that the existing solution for handling published supports/images doesn't work for networked teachers. In this PR we add the teacher's `network` to the properties written out for supports and images and then when determining whether a user has access to a particular image we check whether they're a teacher in the same network in addition to checking whether the requesting user is in a class to which the image has been published.
@tejal-shah For testing purposes, note that this solution does _not_ handle previously published supports. Handling those would require a migration that is probably not worth it. It should work for any …
> Extend multi-class supports/images to networked teachers [#181147217]

- src/components/thumbnail/tab-panel-documents-subsection-panel.tsx
- src/hooks/firestore-hooks.test.ts
- src/hooks/firestore-hooks.ts
Use mobx observable map to ensure that captions redraw when teacher names change. The previous approach which relied on React state didn't refresh all captions that needed refreshing.
> Refresh teacher names in network document captions when necessary

- README.md
- functions/jest.config.js
- functions/package-lock.json
- functions/package.json
- functions/src/canonicalize-url.ts
- functions/src/get-image-data.ts
- functions/src/get-network-document.ts
- functions/src/parse-document-content.ts
- functions/src/publish-support.ts
- functions/test/canonicalize-url.test.ts
- functions/test/get-image-data.test.ts
- functions/test/get-network-document.test.ts
- functions/test/parse-document-content.test.ts
- functions/test/publish-support.test.ts
Once more unto the breach...
In #1190 we extended the image access solution to images in supports _published_ to classes accessible via the teacher network. But, of course, images also reside in _unpublished_ documents, and for those we can't rely on `mcimages` entries in firestore. Instead, the `getNetworkDocument()` function uses our existing code for canonicalizing image urls in content to return canonicalized content and then the `getImageData()` function returns the image data if its class is accessible via a teacher's network.
> Networked teachers can access images in unpublished network documents

- src/clue/app-config.json
- src/components/delete-button.test.tsx
- src/components/delete-button.tsx
- src/components/document/document-content.tsx
- src/components/tool-button.test.tsx
- src/components/tool-button.tsx
- src/components/toolbar.test.tsx
- src/components/toolbar.tsx
- src/components/tools/tool-tile.tsx
- src/models/document/document-content.ts
- src/models/document/document-types.ts
- src/models/document/document.ts
- src/models/stores/configuration-manager.test.ts
- src/models/stores/configuration-manager.ts
- src/models/tools/drawing/drawing-registration.ts
- src/models/tools/geometry/geometry-registration.ts
- src/models/tools/image/image-registration.ts
- src/models/tools/placeholder/placeholder-registration.ts
- src/models/tools/table/table-registration.ts
- src/models/tools/text/text-registration.ts
- src/models/tools/tool-button.ts
- src/models/tools/tool-content-info.ts
- src/models/tools/tool-tile.test.ts
- src/models/tools/tool-types.ts
- src/models/tools/unknown-content.ts
- tool-tiles.md
now that tools added by calling the registerToolContentInfo method,
we cannot use static typing with the tool ids.
I'd also note that the places where the tool value is passed to the changed
methods it was just being casted from a string. So there wan't much type
safety here.
It was nice to know the type of the argument should be a tool id. And it would
be possible to just alias string as DocumentTool. But doing this kind of
creates a false sense of security. Typescript would take a string or a
DocumentTool in this case it would not even require it to be casted.
Because of this false security it seems better to just use string.
> Eliminate DocumentTool enumeration in favor of existing tool ids

- cypress/support/index.js
- scripts/delete-qa-user-data.ts
- src/lib/db.ts
- src/lib/firebase.ts
Previous code that runs when we run `qaClear=all` only clears the documents from `/{userNode}/portals/qa/{class}/{user}` node. This leaves orphaned test nodes in the `qa` node. This deletes the test node when user runs the qaClear=all, including after every Cypress test run.
Also adds a script to remove qa node from firebase if it ever gets overpopulated.
> Fixes qaClear=all to clear user node from qa node in firebase

- src/components/network-status.test.tsx
- src/components/network-status.tsx
- src/lib/firebase.ts
- src/lib/logger.test.ts
- src/lib/logger.ts
- src/models/stores/user.ts
Previously, if we detected a network failure we would log an `INTERNAL_FIREBASE_DISCONNECTED` event and then if we presented a network status alert we would log an `INTERNAL_NETWORK_STATUS_ALERTED` event. Unfortunately, these are both unreliable indicators. If the network goes down then log messages won't go out either, so the set of circumstances under which these events would actually be logged has never been entirely clear. Even when they did get sent, it was necessary to scan the log history for a given user to determine whether there had been any network interruptions in a given time period. For the purposes of determining whether network interruption could be a factor in a forensic data loss investigation (for instance), it would be most useful to know for a given user at a given …
> Improve network status logging
