src/components/app.tsx, src/index.tsx
This is so we can view production or a branch in devMode
=> Add devMode query param override

package.json, src/components/header.tsx, src/curriculum/stretching-and-shrinking.json, src/index.tsx, src/models/curriculum.ts, src/models/document-content.ts, src/models/investigation.ts, src/utilities/url-params.ts, yarn.lock
Add `problem` URL parameter for specifying initial problem [#159979340]
- show title and subtitle in header
- fill out curriculum unit to problem 2.3
=> Add `problem` URL parameter for specifying initial problem

package.json, src/components/app.tsx, src/components/header.tsx, src/index.tsx, src/lib/auth.ts, src/models/user.test.ts, src/models/user.ts, src/utilities/url-params.ts, tslint.json, yarn.lock
Here's the first part of authentication, just grabbing the user and class names from the Portal. I know it still needs test - I'll work on them before the demo in the morning.
@dougmartin, after a later conversation with @kswenson, I decided to handle unauthenticated users very simply for now. So, any user who isn't authenticated can use the app as an anonymous user. As a user is authenticating, you can see they're anonymous for a second, but it's not very noticeable. What do you think?
=> Portal Authentication

CHANGELOG.md, README.md
Added CHANGELOG.md and release notes in README.md
=> Release 0.0.2

__mocks__/fileMock.js, __mocks__/styleMock.js, package.json, src/curriculum/stretching-and-shrinking.test.ts, src/lib/auth.test.ts, src/models/four-up-grid.test.ts, src/models/problem.test.ts, src/models/section.test.ts, src/models/stores.test.ts, src/models/ui.test.ts, src/models/user.test.ts, src/models/workspace.test.ts, tslint.json, yarn.lock
Configure jest for unit tests instead of mocha/chai [#160203405]
@ekosmin I had to resolve some merge conflicts with the authentication tests. You may want to double-check that they're still behaving the way they're supposed to.
=> Configure jest for unit tests instead of mocha/chai

package.json, src/models/document-content.ts, src/models/document-row.ts, src/models/tools/geometry/geometry-tool.ts, src/models/tools/table/table-tool.ts, src/models/tools/text/text-tool.ts, src/models/tools/tool-tile.test.ts, src/models/tools/tool-tile.ts, src/models/tools/tool-types.ts, src/models/tools/unknown-tool.ts, yarn.lock
First pass at DocumentModel [#160175815]
=> First pass at DocumentModel

src/components/canvas.tsx, src/components/four-up.tsx, src/components/learning-log.sass, src/components/learning-log.tsx, src/components/left-nav-panel.sass, src/components/left-nav-panel.tsx, src/components/left-nav.sass, src/components/left-nav.tsx, src/components/my-work.sass, src/components/my-work.tsx, src/components/tab-set.tsx, src/components/tab.tsx, src/components/vars.sass, src/components/workspace.tsx, src/curriculum/stretching-and-shrinking.json, src/index.tsx, src/models/curriculum/problem.test.ts, src/models/curriculum/problem.ts, src/models/curriculum/section.test.ts, src/models/curriculum/section.ts, src/models/ui.test.ts, src/models/ui.ts
NOTE: to allow the UI model to have a reference to a section in the problem model I had to create an identifier for each section.  For the built in JSON the type doubles as the identifier for now.
=> Added active section and active LL tab [#160284706]

src/components/group-chooser.tsx, src/components/header.sass, src/components/header.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/lib/db.test.ts, src/lib/db.ts, src/models/class.test.ts, src/models/class.ts, src/models/groups.test.ts, src/models/groups.ts, src/models/user.test.ts, src/models/user.ts
Also fixed:
1. Switched to portalJWT uid instead of firebaseJWT uid
2. Added user name and status to group chooser and header
=> Added portal to firebase path

src/lib/db.ts
Earlier this morning, I was seeing errors from `authd` users about null `connectedTimestamp`s. This led me down a path of trying to make those timestamps optional, but ultimately deciding to set them in a promise so we can guarantee they are set/updated when we need them to be.
=> Getting connection timestamp in a promise

src/components/my-work.sass, src/components/my-work.tsx, src/lib/db.ts
Note: since the design is still in flux I left the tab at the bottom of the screen.
=> Added content for "My Work" tab [#160359729]

src/components/canvas-tools/tool-tile.tsx, src/components/document-content.tsx, src/models/document-content.ts
Pair programmed with Dave following example from Doug:
Add basic support for dragging tiles (tool instances)  [#159979496]
=> [With Dave] Support dragging tool tiles

src/components/canvas-tools/geometry-tool.tsx, src/components/canvas-tools/tool-tile.tsx, src/components/canvas.tsx, src/components/document-content.tsx, src/components/four-up.tsx, src/components/left-nav-panel.tsx, src/components/my-work.tsx, src/components/workspace.tsx, src/models/document-content.ts
- Fix handling of multiple geometry tiles connected to a single model (e.g. workspace and my work)
- Don't create point on drag of geometry tool
- create point on mouse up rather than mouse down
- only create point when mouse up occurs close to mouse down in space and time
=> Fix geometry tool issues

src/components/canvas-tools/text-tool.tsx, src/models/tools/text/text-content.ts
Add getDerivedStateFromProps() to update Slate Value when necessary
=> Handle text tool synchronization

src/lib/db.ts, src/models/workspaces.test.ts
Had a brief panic when I realized sharing wasn't working on master...until I realized the fixes @dougmartin and I made this morning never got merged 😅
=> Fixing four-up listeners

package-lock.json, package.json, src/components/four-up.test.tsx, yarn.lock
I got tired of waiting on Cypress, so I added enzyme and enzyme tests for components. The four up tests required setting up a lot of state, but I think they do test the new behaviors thoroughly.
@dougmartin @kswenson What do you think about adding component tests like this moving forward?
=> Enzyme Tests

src/lib/db.ts, src/models/workspaces.ts
Also generalized document listeners to model listeners and added backend support for delete - UI for delete is still needed.
=> Enabled rename of learning logs [#160073076]

src/models/groups.ts
Added guard when updating group users from Firebase to ensure that group users have not been partially deleted.
=> Fix TypeError: Cannot read property 'uid' of undefined [#160687074]

package.json, src/components/canvas.test.tsx, src/components/demo-creator.test.tsx, src/components/demo-creator.tsx, src/components/four-up.test.tsx, src/index.tsx, src/models/document.test.ts, src/models/four-up-grid.test.ts, src/models/ui.test.ts, src/models/ui.ts, src/models/user.test.ts, src/models/workspaces.test.ts, src/utilities/test-utils.ts
This does not include coverage of:
1. Geometry models as there is an existing story for that.
2. Window listeners as I'm not sure yet how to mock those.
3. Teacher authentication as there is a separate teacher auth story.
4. Firebase list monitoring - there needs to be another story to split db.ts up
=> Bring test code coverage back up [#160687173]

src/components/demo-creator.tsx, src/lib/auth.test.ts
Only 9 students are visible in the demo creator but 99 students are available in the url parameter for use in automated QA.
=> Allow up to 99 students in the demo via the url parameter

src/components/canvas-tools/geometry-tool.tsx
Update `syncedCount` when changes are synchronized so they don't get synced multiple times
=> Update `syncedCount` when changes are synchronized

src/components/canvas-tools/geometry-tool.tsx, src/models/document-content.ts
- Consistent grid every 1-unit on X and Y axes
- Points snap to 0.2 grid
=> Geometry: consistent grid; points snap to grid

src/components/canvas-tools/tool-tile.tsx
=> Simplify tile rendering code

src/components/canvas.tsx, src/components/four-up.test.tsx, src/components/four-up.tsx, src/lib/db.test.ts
Fix drop on empty canvas [#160767277]
=> Fix drop on empty canvas

src/components/app-container.tsx, src/components/class-work.tsx, src/components/right-nav.tsx, src/components/workspace.tsx, src/lib/db-types.ts, src/lib/db.ts, src/models/ui.ts, src/models/workspaces.test.ts, src/models/workspaces.ts
This isn't ready to merge yet, but I've finished the Firebase piece for publishing group documents. I ended up making a lot of changes to the types, and I'd appreciate a second opinion - I'll leave more specific comments below.
=> Publishing Class Work

src/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
- adding images using new image tool format
- adding some missing text from Introduction to 1.3 that has Unicode symbols in it for angles
- deleting some TEST supports
=> Images for the first two problem sections

src/components/canvas-tools/geometry-tool.tsx, src/models/tools/geometry/jxg-point.ts
Allow placing point at origin [#160993969]
- ignore hidden points when determining whether to place new point
=> Allow placing point at origin

src/components/canvas-tools/geometry-tool.tsx, src/components/document-content.tsx, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jsxgraph.d.ts, src/models/tools/geometry/jxg-polygon.ts
Refactor element creation; add onCreate callback
- set `hasInnerPoints` attribute to enable dragging of polygons [#161034052]
=> Support dragging polygons

.travis.yml, cypress.json, cypress/integration/workspace.test.ts, cypress/plugins/index.js, cypress/tsconfig.json, package-lock.json, package.json, tsconfig.json
Got Cypress tests up and running, and working in Travis! I'll make some comments about how it works below. Some series of upgrades seems to have solved the old type collision problem we had.
=> Adding Cypress test

.travis.yml, cypress.json
Seems like this has stopped the failures for the time being...what do you think?
=> Doubling default command timeout to reduce test failures

src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jsxgraph.d.ts, src/models/tools/geometry/jxg-board.ts, src/models/tools/geometry/jxg-changes.ts, src/models/tools/geometry/jxg-dispatcher.ts, src/models/tools/geometry/jxg-image.ts, src/models/tools/geometry/jxg-polygon.ts
Spike: add image to geometry in curriculum [#161137053]
- add support for images to geometry tool
=> Geometry tool: add background image support

src/components/canvas-tools/geometry-tool.tsx, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jsxgraph.d.ts
Fix scaled geometry clicks [#161234989]
- fixes clicks, drags, double-clicks in four-up and other scaled views
=> Fix scaled geometry clicks (e.g. four-up view)

src/models/ui.ts, src/models/workspace.ts
Fix comparison workspace [#161270806][#161270843]
Publications only show in comparison view [#161331884]
=> Fix comparison workspace bugs

src/components/document-content.tsx, src/components/document.tsx, src/components/group-view.tsx
- Published documents should be read-only
- Don't allow drops on read-only canvases [#161272097]
=> Fix read only bugs

src/components/canvas-tools/tool-tile.tsx, src/components/document-content.tsx, src/components/document.tsx, src/components/document/tile-row.tsx, src/models/document-content.ts, src/models/document.test.ts, src/models/ui.ts
Auto-select and scroll to new tile rows [#161151927]
=> Auto-select and scroll to new tile rows

package-lock.json, src/components/canvas-tools/image-tool.sass, src/components/canvas-tools/tool-tile.sass, src/components/canvas-tools/tool-tile.tsx
First part of improvements for drag and drop focussing entirely on drag, I've added a handle to the top left of the tile to give the user a larger area with which to start dragging. Drop target changes to facilitate side-by-side placement will be in a separate PR.
I do not feel comfortable that this is a mouse-specific solution - touch devices won't see the handle on hover, and I would like some UI feedback during testing if at all possible to determine a better solution.
=> Drag enhancements

src/components/document.sass, src/components/document.tsx, src/index.html, src/models/supports.test.ts, src/models/supports.ts
Minor updates to which supports we show and how we display their icons (more details in commit message)
=> Updating supports

src/components/group-view.tsx, src/components/left-nav-panel.sass, src/components/left-nav-panel.tsx
Updating left nav buttons - they don't match the mockup exactly, but they are an improvement.
Also changed the left nav closing behavior - it was really hard to open workspaces before.
=> Style buttons

src/components/canvas-tools/geometry-tool.tsx, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-content.ts
Geometry: Synchronize selection across multiple instances of same tile (e.g. two-up view)
=> Geometry: Synchronize selection (e.g. two-up view)

migrations/migrate.js, src/lib/auth.ts, src/lib/db-types.ts, src/lib/db.ts, src/lib/firebase.ts, src/utilities/url-params.ts
@kswenson After our discussion today, I believe this is what a PR for a migration should look like once the other migration prep PR is merged. It satisfies our criteria in that it is both safe to merge and requires minimal changes to be committed post-migration.
=> WIP: Adding migration (to be performed) to move users for updated security rules

src/components/canvas-tools/geometry-tool.tsx
- clicking on a polygon deselects other selected objects [#161666554]
- ctrl/cmd/shift-clicking on a polygon reverses its selection without deselecting others
- ctrl/cmd/shift-clicking on the background doesn't clear the selection and doesn't create new points
=> Fix polygon (and other) selection issues

src/components/canvas-tools/geometry-tool.tsx, src/utilities/event-utils.ts, src/utilities/hot-keys.ts
- Add `hasSelectionModifer()` and other event utility functions
- Support standard key names
=> Event-related improvements from code review comments

src/components/class-logs.tsx, src/components/document.sass, src/components/document.tsx, src/components/right-nav.tsx, src/lib/db-listeners/db-learning-logs-listener.ts, src/lib/db-types.ts, src/lib/db.ts, src/lib/firebase.ts, src/models/document.ts, src/models/documents.test.ts, src/models/documents.ts, src/models/ui.ts
Adds a new document type for published Learning Logs and stores them under class hash. Fair amount of copy-pasted code until we have a chance to refactor.
=> Publish Learning Logs

src/components/canvas-tools/geometry-tool.tsx, src/components/class-logs.tsx, src/components/class-work.tsx, src/components/my-work.tsx, src/components/right-nav.tsx
Fix geometry tiles in Class Work/Logs panels [#161857814]
Also, a minor tweak to previous drag/snap-to-grid fix
=> Fix geometry tiles in Class Work/Logs panels

src/components/canvas-tools/geometry-tool.tsx, src/components/canvas-tools/geometry-tool/rotate-polygon-icon.tsx
Factor `scale` into angle calculation to fix rotation in 4-up view [#160604593]
=> Fix rotation in four-up view

src/components/class-logs.tsx
Tiny PR to make @eireland's life testing CLUE a little easier...also makes more sense to show log names first since that's how we're sorting.
=> Class work and class logs now label documents the same way

CHANGELOG.md, package-lock.json, package.json
=> Release 0.1.1

src/models/tools/drawing/drawing-content.test.ts, src/models/tools/drawing/drawing-content.ts
The fix adversely affected other draw tool behaviors.
=> Revert to 0.1.0

src/components/canvas-tools/drawing-tool/drawing-layer.tsx, src/models/tools/drawing/drawing-content.test.ts, src/models/tools/drawing/drawing-content.ts
Use MobX reaction to synchronize selectedButton/currentTool properly.
=> Fix draw tool crash take 2

CHANGELOG.md, package-lock.json, package.json
Fix draw tool crash without breaking draw tool functionality
=> Release 0.1.2

CHANGELOG.md, package-lock.json, package.json
Ready and waiting on the results from QA...
=> Release 0.1.3

package-lock.json, package.json, src/blueprint.sass, src/blueprint.tsx, src/components/canvas-tools/geometry-tool.sass, src/components/canvas-tools/geometry-tool.tsx, src/components/canvas-tools/tool-tile.tsx, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jsxgraph.d.ts, src/models/tools/geometry/jxg-changes.ts, src/models/tools/geometry/jxg-dispatcher.ts, src/models/tools/geometry/jxg-object.ts, src/models/tools/geometry/jxg-polygon.ts, src/models/tools/geometry/jxg-vertex-angle.ts, src/models/tools/geometry/soft-surfer-sunday.ts
Interface is via a new hamburger menu in the upper right corner of the tile.
=> Implement labeled angles feature [#161272101]

src/models/tools/geometry/geometry-content.ts
- make sure parents are specified in proper order when copying angles
=> Fix angle copy bug encountered during testing

config/environments.json, cypress/integration/group_chooser_spec.js, cypress/integration/group_test_spec.js, cypress/integration/teacher_test_spec.js, cypress/integration/workspace_test_spec.js, cypress/support/commands.js, src/components/demo/demo-creator.test.tsx, src/components/demo/demo-creator.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/models/curriculum/unit.ts, src/utilities/url-params.ts
- dev/demo mode support for multiple units
- eliminate unused `fakeOffering` url parameter
=> Support Moving Straight Ahead unit

src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jsxgraph.d.ts, src/models/tools/geometry/jxg-dispatcher.ts
Improve document load performance by suspending updates during geometry tile initialization
=> Improve geometry tile initialization performance

CHANGELOG.md, package-lock.json, package.json
- Geometry: Improve initialization performance
|---|---|---|
| index.css | 318,477 bytes | 0.0% |
| index.js | 2,938,753 bytes | 0.0% |
=> Release 0.2.2

.travis.yml, rollbar_deploy.sh, src/components/app.tsx, src/components/header.tsx, src/index.tsx, src/models/stores/stores.ts
- add app version, user, class, unit, problem information to Rollbar error reports
- configure Travis to register deploys of master/production branches with Rollbar
=> Configure rollbar

src/models/tools/geometry/jxg-board.ts
Starting point for x and y axis labels using default labels provided by JSX graph.
[#162860392]
=> Add Geometry Tool graph axes labels

src/components/navigation/right-nav.tsx
This was the final requested change from the previous PR on this branch.  I restored the branch, added this final commit, and opened a new PR.  Not the most elegant path, but I had closed the previous PR, merged the branch into master, and deleted it before the comment was made.
=> Refactor set state of right nav

cypress/integration/canvas_test_spec.js, cypress/integration/learning_log_test_spec.js, cypress/integration/my_work_test_spec.js, cypress/support/elements/RightNav.js, src/components/navigation/right-nav.sass, src/components/thumbnail/class-logs.tsx, src/components/thumbnail/class-work.tsx, src/components/thumbnail/my-work.tsx, src/components/vars.sass, src/index.html
Add collapsable sections to the Class Work section of the right nav.  Includes UI changes based on latest spec updates from Michael.  Headers have been added to each tab.  Cypress tests have been updated accordingly.
=> 163131891 categories class work

src/components/tools/table-tool/rename-column-dialog.tsx
Completes last requirement for [#162227566](https://www.pivotaltracker.com/story/show/162227566).
=> Table: Restrict column name length to 20 characters

src/components/tools/geometry-tool/geometry-tool.sass, src/components/tools/geometry-tool/geometry-tool.tsx
@mklewandowski Should be a quick review.
=> Hide toolbar in curriculum (left-side) content

cypress/integration/canvas_test_spec.js, cypress/integration/graph_tool_spec.js, cypress/integration/group_test_spec.js, cypress/integration/image_tool_spec.js, cypress/integration/learning_log_test_spec.js, cypress/integration/left_nav_test_spec.js, cypress/integration/student_test_spec.js, cypress/integration/teacher_supports_all_section_spec.js, cypress/integration/teacher_supports_specific_section_spec.js, cypress/integration/teacher_test_spec.js, cypress/integration/workspace_test_spec.js, cypress/support/commands.js, cypress/support/elements/BottomNav.js, cypress/support/elements/Canvas.js, cypress/support/elements/DrawToolTile.js, cypress/support/elements/GraphToolTile.js, cypress/support/elements/Header.js, cypress/support/elements/ImageToolTile.js, cypress/support/elements/LearningLog.js, cypress/support/elements/LeftNav.js, cypress/support/elements/RightNav.js, cypress/support/elements/TeacherDashboard.js, cypress/support/elements/Workspace.js, package-lock.json, package.json, src/components/document/document.tsx, src/models/stores/supports.test.ts, src/models/stores/supports.ts
Also includes the teacher support tests
=> Abbr selectors

cypress/integration/graph_tool_spec.js, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jsxgraph.d.ts, src/models/tools/geometry/jxg-dispatcher.ts, src/models/tools/geometry/jxg-point.ts, src/models/tools/geometry/jxg-polygon.ts
- deleted points will be removed from polygons (rather then eliminating polygons) where possible
- fix bug in which deletion of points could result in deletion of polygons which could orphan vertex angles [#163631651]
Note: This bug is based on #230 . Only the last commit needs to be reviewed independently. Once #230 is merged to master, this PR should be rebased/merged to master as well.
=> Fix polygon vertex deletion

src/models/tools/geometry/jxg-movable-line.ts
=> Fix typo in setting id for movable line

src/components/tools/table-tool/table-tool.tsx, src/models/tools/geometry/jxg-table-link.ts, src/models/tools/table/table-content.ts
- Fix bug which prevented linked points added after link to remain after table was deleted [#163933441]
- Convert non-numeric table values to 0 when linking to geometry [#163957448], [#163929665]
=> Linked table geometry bugs

cypress/integration/canvas_test_spec.js, cypress/integration/group_test_spec.js, cypress/integration/learning_log_test_spec.js, cypress/integration/table_tool_spec.js, cypress/integration/text_tool_spec.js, cypress/integration/workspace_test_spec.js, cypress/support/commands.js, cypress/support/elements/Canvas.js, cypress/support/elements/DrawToolTile.js, cypress/support/elements/ImageToolTile.js, cypress/support/elements/LearningLog.js, cypress/support/elements/RightNav.js, cypress/support/elements/TableToolTile.js, cypress/support/elements/TextToolTile.js, src/components/tools/table-tool/table-header-menu.tsx
Cleaned up version of @eireland 's #241 with cherry-picked commits and merge commits eliminated.
Original PR description:
>Added basic table tests
>Refactored duplicate tests
Also includes some general cleanup in the form of elimination of redundant tests, elimination of unnecessary waits, etc.
=> Table tool tests

src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/table-tool/data-table.css, src/components/tools/table-tool/data-table.tsx, src/components/tools/table-tool/linked-table-cell-editor.tsx, src/components/tools/table-tool/table-tool.tsx, src/models/tools/table/table-content.ts
- Prevent linking table with non-numeric contents [#164039247]
- Validate user edits of table values so non-numeric data can't be introduced when table is linked to geometry [#164039269]
=> Validate linked table contents

src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/geometry-tool/line-dialog.tsx, src/components/tools/geometry-tool/movable-line-dialog.tsx, src/components/tools/table-tool/data-table.css, src/components/utilities/blueprint.sass, src/models/tools/geometry/jsxgraph.d.ts, src/models/tools/geometry/jxg-movable-line.test.ts, src/models/tools/geometry/jxg-movable-line.ts
Equations can now be clicked to edit lines. There's a lot of math related to finding control points along the visible portion of the line - I think the code is relatively self-documenting, but let me know if you think it would benefit from more comments.
=> Adding dialog to edit line slope and intercept

src/models/tools/geometry/jxg-board.ts
Introduced with the user axis scaling refactor.
=> Fix recently introduced geometry undo bug

src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/geometry-tool/geometry-shared.tsx, src/components/tools/geometry-tool/geometry-tool.tsx
Hoist keyboard handling from GeometryContentComponent to GeometryToolComponent [#164185497]
=> Fix keyboard shortcuts don't work after clicking on toolbar button

package-lock.json, package.json, src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/table-tool/data-table.css, src/components/tools/table-tool/data-table.tsx, src/components/tools/table-tool/table-header-menu.tsx, src/components/tools/table-tool/table-tool.sass, src/components/tools/table-tool/table-tool.tsx, src/components/tools/table-tool/update-expression-dialog.sass, src/components/tools/table-tool/update-expression-dialog.tsx, src/components/utilities/blueprint.sass, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/table/table-content.test.ts, src/models/tools/table/table-content.ts
Next steps are making an actual dialog for equation editing (instead of using the attribute renaming one) and parsing the real row values. Then, I think I need to go through similar steps as data validation - namely making sure equation columns are updated on equation creation, cell edit, and paste.
=> [#163482135] Data Generation

src/components/tools/geometry-tool/axis-settings-dialog.tsx, src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/table-tool/table-header-menu.tsx, src/components/tools/table-tool/table-tool.tsx, src/models/tools/geometry/jxg-board.ts
Last round of known fixes before 0.5.2
=> 0.5.2 fixes

.travis.yml, src/components/tools/drawing-tool/drawing-layer.tsx, src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/geometry-tool/geometry-tool.tsx, src/components/tools/image-tool.tsx, src/components/tools/table-tool/table-tool.tsx, src/components/tools/text-tool.tsx, src/lib/db-listeners/index.ts, src/lib/db.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jxg-board.ts, src/models/tools/geometry/jxg-changes.ts, src/models/tools/geometry/jxg-image.ts, src/models/tools/geometry/jxg-object.ts, src/models/tools/text/text-content.test.ts, src/models/tools/text/text-content.ts, src/utilities/js-utils.ts
Opening a PR just to look at @mklewandowski's changes to the text tool. Took me a while to wrap my head around what's going on - added a little documentation and fixed a missing line
=> Eliminate firebase rebound

src/components/demo/demo-creator.test.tsx, src/curriculum/dataflow/dataflow.json, src/curriculum/moving-straight-ahead/moving-straight-ahead.json, src/curriculum/stretching-and-shrinking/stretching-and-shrinking.json, src/index.tsx, src/lib/misc.ts, src/models/curriculum/unit.ts, src/utilities/url-params.ts
- Support `dataflow` curriculum unit [#167254016]{304}
- Support unit authoring of browser page title [#167150604]{294}
=> Support `dataflow` unit and configurable page title

src/components/document/document.tsx, src/components/toolbar.tsx, src/models/tools/tool-types.ts
Note: Ultimately the goal is to move the configuration into the unit authoring. For now, however, we leave it in code because actually moving it into unit authoring will involve changes to files that were refactored in the `dataflow` branch and so that work should be done in the `dataflow` branch to avoid unnecessary conflicts.
=> Make contents of toolbar configurable [#167377468]

src/dataflow/components/dataflow-program.tsx, src/dataflow/components/nodes/controls/num-control.sass, src/dataflow/components/nodes/controls/num-control.tsx, src/dataflow/components/nodes/factories/generator-rete-node-factory.tsx, src/dataflow/utilities/node.ts
Add new generator node that generates a signal (types sine, square, triangle, noise, random walk) every second using program heartbeat.
=> Add generator node type

src/dataflow/components/hub-list.sass
Add scrollbars to control panel to allow all hubs to be visible
=> Add scrolling in control panel

src/curriculum/dataflow/dataflow.json, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/tools/dataflow-tool.tsx, src/dataflow/models/tools/dataflow/dataflow-content.ts
Sample import:
```
{
"content": {
"type": "Dataflow",
"program": [
{
"id": "temp-id",
"name": "Sensor",
"data": { "type": "temperature" },
"outputs": [{ "num": [{ "add-id": "num1" }] }],
"position": [ 0, 0 ]
},
{
"id": "two-id",
"name": "Number",
"data": { "nodeValue": 2 },
"outputs": [{ "num": [{ "add-id": "num2" }] }],
"position": [ 0, 240 ]
},
{
"id": "add-id",
"name": "Math",
"data": { "mathOperator": "add" },
"outputs": [{ "num": [{ "compare-id": "num1" }] }],
"position": [ 250, 0 ]
},
{
"id": "compare-id",
"name": "Logic",
"data": { "logicalOperator": "equals" },
"inputs": [{ "num2": 5 }],
"position": [ 500, 0 ]
},
{
"id": "generator-id",
"name": "Generator",
"data": { "generatorType": "sine", "amplitude": 1, "period": 10 },
"outputs": [{ "num": [{ "transform-id": "num1" }] }], …
```
=> Support authoring of Dataflow tile content [#167503555]

src/components/header.tsx, src/dataflow/components/dataflow-app-content.tsx, src/dataflow/components/dataflow-header.tsx, src/dataflow/components/dataflow-types.ts
Since it's easy and it came up in Slack.
=> Dataflow defaults to Workspace tab

package-lock.json, package.json
cf. https://github.com/retejs/connection-plugin/pull/18
=> Update rete-connection-plugin to latest to include drag fix

.travis.yml, cypress/integration/full/canvas_test_spec.js, cypress/integration/full/graph_table_integraton_test_spec.js, cypress/integration/full/graph_tool_spec.js, cypress/integration/full/group_chooser_spec.js, cypress/integration/full/group_test_spec.js, cypress/integration/full/image_tool_spec.js, cypress/integration/full/learning_log_test_spec.js, cypress/integration/full/left_nav_test_spec.js, cypress/integration/full/my_work_test_spec.js, cypress/integration/full/student_test_spec.js, cypress/integration/full/table_tool_spec.js, cypress/integration/full/teacher_supports_all_section_spec.js, cypress/integration/full/teacher_supports_specific_section_spec.js, cypress/integration/full/teacher_test_spec.js, cypress/integration/full/text_tool_spec.js, cypress/integration/full/workspace_test_spec.js, cypress/integration/smoke/single_student_canvas_test.js, cypress/support/elements/Canvas.js, package.json, run_cypress_test.sh, run_test.sh
Created a cypress smoke test to shorten build time. Add '[dev-build]' to commit message to run just the cypress smoke test. Otherwise, full cypress test will run during build.
=> Smoke test3

src/dataflow/components/nodes/controls/dropdown-list-control.sass, src/dataflow/components/nodes/controls/sensor-select-control.sass, src/dataflow/components/nodes/controls/sensor-select-control.tsx, src/dataflow/components/nodes/dataflow-node.sass
Add more detailed class names to assist in automated testing as per request from @eireland.  Also add `flow-tool` parent class in CSS so node styling takes effect.
=> Sensor css class name changes

src/lib/db-listeners/db-section-documents-listener.ts
Teacher loads all documents into Documents store rather than just current user/group documents [#166391338]
=> Teacher loads all documents into Documents store

src/curriculum/dataflow/dataflow.json, src/dataflow/components/dataflow-program-toolbar.sass, src/dataflow/components/dataflow-program-topbar.sass, src/dataflow/components/dataflow-program-topbar.tsx, src/dataflow/components/dataflow-program.sass, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/tools/dataflow-tool.sass, src/dataflow/utilities/node.ts
Initial implementation of a program editor topbar.  Functionality and layout will most likely change, but this gives us a starting point to show team where program run/stop tools will exist and provide a path to implement the next phase of tile layout (clicking "run" button needs to switch tile to a side-by-side mode where we show a graph next to the program editor).
=> Initial implementation of program editor topbar

src/dataflow/components/dataflow-program.tsx, src/dataflow/utilities/aws.ts
Fixes to upload functionality to remove recent values, set the endTime correctly.
Added a fetchProgramData Lambda call that can be used to retrieve program data.
=> Improve upload

src/dataflow/lib/iot.ts
Small AWS updates:
- add a relay control function which can turn a relay on or off.  Function isn't called yet, but most likely will end up useful to have for testing or be used via some sort of admin tool (test relay using an on/off button).  Note, that I have tested this function locally with an actual relay to confirm it behaves as expected.
- add QoS = 1 to MQTT subscriptions.  After reading more on QoS, it is apparent that is needs to be set both by the publisher and the subscriber.  Ideally, we will need the Sensaurus hub software to also set a QoS of 1 on all of its pub/sub calls.
=> Add relay control, set QoS on subscriptions

src/dataflow/components/dataflow-program-toolbar.tsx, src/dataflow/components/dataflow-program.tsx, src/dataflow/utilities/node.ts
Minor changes to Dataflow editor toolbar and topbar.  Remove obsolete buttons and refine list of program run times based on input from the Dataflow team.
=> Update topbar and toolbar to remove obsolete options

src/components/vars.sass, src/curriculum/dataflow/dataflow.json, src/dataflow/components/dataflow-program-cover.sass, src/dataflow/components/dataflow-program-graph.sass, src/dataflow/components/dataflow-program-graph.tsx, src/dataflow/components/dataflow-program-toolbar.tsx, src/dataflow/components/dataflow-program-topbar.sass, src/dataflow/components/dataflow-program.sass, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/tools/dataflow-tool.tsx, src/dataflow/utilities/aws.ts
Add side-by-side graph view that is shown next to program editor when program is run.  Graphs show 15 second plot data from data storage block (this will most likely become obsolete as this view will probably show live data from the cloud or archived datasets).  Graph mode can be toggled between scatter/line and stacked/overlapped.
=> Dataflow exploded graph

src/dataflow/components/dataflow-program-zoom.sass, src/dataflow/components/dataflow-program-zoom.tsx, src/dataflow/components/dataflow-program.tsx
Replaces the scrollwheel zoom (which conflicts with other scrolling elements (like the tile container) and replace with floating UI button on the program editor.
=> Remove scrollwheel zoom, replace with editor buttons

src/lib/db.ts, src/lib/firebase.ts, src/models/stores/documents.ts
@llzes and I both encountered the need for this refactor independently.
=> Add `createOtherDocument()` method to DB

src/dataflow/components/dataflow-program-graph.sass, src/dataflow/components/dataflow-program-graph.tsx, src/dataflow/utilities/export.ts
This PR adds an export button to the graph panel and uses the current dataset from the chart to form the CSV export.
Adjusted css a bit to account for smaller screen widths. 
Also added a spinner to indicate that graphs are loading while we await our first data points from the server.
=> Export data

src/app-config.ts, src/components/app-content.tsx, src/components/app.tsx, src/components/demo/demo-creator.test.tsx, src/lib/db-listeners/index.ts
More application configuration
=> AppContentComponent configuration

cypress/integration/full/teacher_test_spec.js, cypress/support/elements/TeacherDashboard.js, src/components/app-header.sass, src/components/app-header.tsx, src/components/four-up.tsx, src/components/teacher/teacher-dashboard.sass, src/components/teacher/teacher-dashboard.tsx, src/components/teacher/teacher-group-six-pack.sass, src/components/teacher/teacher-group-six-pack.tsx, src/components/teacher/teacher-group-tab.tsx, src/index.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/models/stores/stores.ts, src/models/stores/user.ts
This is the same set of changes as in `167585781-switch-problems` which @DALove1025 worked on last week or so.
Because this branch was in danger of getting stale, I rebased off of master as of this afternoon (2019-09-06 11:28:37 AM EDT. 1b3d016 )
Nobody loves the complexity of the `getPortalJWTWithBearerToken` promise chains in `auth.tx` but I think I would like to get what we have hear reviewed before this commit gets too large.
Not sure who should do this @DALove1025 and I have been looking at it together for a while.
It might be nice to have @llzes or @kswenson to give it a passing nod since its my first time here.
Thank you
NB: Probably the strangest commit here is 2bc561a which is decidedly off topic for this PR.  I would pull it out, but it would be its own one-line PR.
This PR is a …
=> Restructuring commits from 167585781-switch-problems

src/components/demo/demo-creator.sass, src/components/demo/demo-creator.tsx, src/lib/firebase.ts, src/models/stores/demo.ts, src/models/stores/stores.ts, src/utilities/url-params.ts
Adds a demo name field to the demo creator that, when set, adds a namespace under the demo to allow for multiple simultaneous demos.
=> Allow for multiple simultaneous demos [#168436849]

README.md, src/components/document/canvas.sass, src/components/document/canvas.tsx, src/lib/debug.ts
Extensible flag with first use being to show the document key over the canvas displaying the document.
=> Added debug localstorage flag [#168439774]

src/components/document/document.sass, src/components/utilities/icon-button.tsx
The `IconButton` takes in multiple props and renders a React Component for a requested SVG icon.
=> [#168347561] IconButton

src/dataflow/components/dataflow-program.tsx
When a program is running and not yet complete, set the display state to show the program and graph in a side by side mode.
=> Set proper state when program is running

src/dataflow/components/dataflow-program-graph.sass, src/dataflow/components/dataflow-program-graph.tsx
Minor change to improve the dataset graph min-height so stacked graphs display better in a program tile.  Also includes some minor changes from the UI spec to adjust graph fonts and legends.
=> Update graph legend and min-height for better display

src/clue/clue.sass, src/components/document/document.tsx
This came up at the demo meeting today.
=> Color document header (title bar) and footer (status bar)

src/clue/components/clue-app-content.tsx, src/components/four-up.tsx, src/lib/debug.ts, src/lib/logger.ts
This adds all the currently required messages to the logger but adds TODO items to add the log messages when the functionality is implemented for some of the messages.
This also adds a localStorage debug option to write the log messages to the console.
=> Added start of teacher dashboard logging [#167320274]

src/components/thumbnail/documents-section.tsx
This aspect of the filtering behavior was lost in the recent refactor.
=> Only show most recent publication for each document

src/lib/logger.ts
Adds student's group id to all log messages
=> Log group with all student actions [#167794669]

src/assets/program-icon-running.svg, src/dataflow/components/dataflow-app-content.sass, src/dataflow/components/dataflow-app-content.tsx, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/tools/dataflow-tool.tsx, src/dataflow/models/tools/dataflow/dataflow-content.ts
Show indicators next to currently running programs, and update the visibility of those indicators once a program completes.
If a program is completed while the browser is closed, the process of loading the page will also check on running status by comparing the program end time.
[#167387953]
=> Run indicators

src/lib/auth.ts, src/lib/firebase.ts, src/lib/logger.ts
Add logging of successful non-demo/dev authentication and Firebase disconnects.
=> Added logging for debugging purposes [#166383283]

src/dataflow/lib/iot.ts
Increase max number of things when requesting thing list from AWS
=> Increase max number of things when requesting thing list from AWS

src/components/app.tsx, src/components/class-menu-container.tsx, src/index.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/lib/firebase.ts, src/lib/portal-api.test.ts, src/lib/portal-api.ts, src/models/curriculum/unit.ts
Use `AppConfigModel` where appropriate
References to `../clue/app-config.json` don't work on the `dataflow` branch. I should have noticed this on initial code review.
=> Eliminate common code references to `clue/app-config.json`

src/lib/auth.ts, src/lib/db.ts
Fixed missing return of promise in db#connect which caused a race condition between the user being signed into Firebase and the initial Firebase read.
Also formatted authentication function and adding some missing catches.
=> Fix authentication race condition [#168881534]

src/clue/app-config.json, src/components/document/tile-row.tsx, src/components/tools/placeholder-tool/placeholder-tool.sass, src/components/tools/placeholder-tool/placeholder-tool.tsx, src/components/tools/section-header.sass, src/components/tools/section-header.tsx, src/components/tools/tool-tile.tsx, src/models/document/document-content.ts, src/models/document/document.ts, src/models/document/tile-row.ts, src/models/tools/placeholder/placeholder-content.ts
Add Placeholder tile and SectionHeader component that are created in appropriate tile rows.  Add some simple rules around workspace dragging based on these new types of row content.
=> Placeholder and header ui

src/components/app.tsx, src/lib/portal-api.ts, src/models/curriculum/unit.ts
- recent teacher dashboard changes inadvertently broke problem specification for student launch
=> Fix student launch from portal

src/clue/app-config.json, src/components/thumbnail/documents-section.tsx, src/components/thumbnail/right-nav-tab-contents.tsx, src/lib/db-listeners/db-other-docs-listener.ts, src/lib/db-listeners/db-problem-documents-listener.ts, src/lib/db-listeners/db-publications-listener.ts, src/lib/db-listeners/sync-stars.ts, src/models/view/right-nav.ts
This feature is for both students and teachers
=> Added bookmarking in my work tab [#168962987]

src/models/curriculum/unit.test.ts, src/models/curriculum/unit.ts
Fixed logic error introduced in #501. Added unit tests (now that the barn door is closed).
=> Fix problem-switching broken in a previous PR

src/components/tools/table-tool/data-table.tsx, src/components/tools/table-tool/rename-column-dialog.tsx
Note: this work was begun by @llzes .
=> Auto-size table columns on rename

src/lib/db.ts
These changes were added to Dataflow while merging `master` into `dataflow` .  We want these changes in CLUE as well.
=> Prevent loading of a deleted document

src/components/class-menu-container.tsx, src/components/document/group-virtual-document.tsx, src/components/link-switcher-menu.tsx, src/components/problem-menu-container.tsx, src/components/teacher/teacher-group-six-pack.tsx, src/components/thumbnail/right-nav-tab-contents.tsx, src/lib/logger.ts, src/models/document/group-virtual-document.ts
Since switching the class and problem involve reloading the page optional callback functionality was added to the logger to ensure the XHR log request was finished before the reload (otherwise the browser will cancel the pending XHR request).
=> Added class and problem switch logging [#167320274]

src/clue/components/clue-app-content.tsx, src/clue/components/teacher/sixpack-right-controls.sass, src/clue/components/teacher/sixpack-right-controls.tsx, src/clue/components/teacher/teacher-dashboard.sass, src/clue/components/teacher/teacher-dashboard.tsx, src/clue/components/teacher/teacher-group-six-pack.sass, src/clue/components/teacher/teacher-group-six-pack.tsx, src/clue/components/teacher/teacher-group-tab.sass, src/clue/components/teacher/teacher-group-tab.tsx, src/clue/components/teacher/teacher-student-tab.sass, src/clue/components/teacher/teacher-student-tab.tsx, src/clue/components/teacher/teacher-support.sass, src/clue/components/teacher/teacher-support.tsx, src/clue/components/teacher/teacher-supports.sass, src/clue/components/teacher/teacher-supports.tsx, src/components/app-header.tsx, src/components/document/document.tsx, src/components/four-up-overlay.tsx, src/components/four-up.tsx, src/components/thumbnail/right-nav-tab-contents.tsx
- move CLUE-specific files into `src/clue` folder
- eliminate references to CLUE-specific files from common code files
@knowuh @DALove1025 I've assigned both of you for review. I don't think it needs two reviews, I just don't know which one of you has more bandwidth.
=> Refactor teacher dashboard work to simplify `dataflow` merge

src/models/tools/geometry/jxg-board.ts
Fixes [#169188285](https://www.pivotaltracker.com/story/show/169188285)
=> Scale board axes to zoom-level, e.g. for four-up view [#169188285]

package-lock.json, src/index.html
This PR addresses PT Stories:
[#169210909] make bold bolder
It is a simple, one-line change in index.html to adjust how the google fonts are specified.
=> Adjust google font link to support native Lato bold font.

CHANGELOG.md, package-lock.json, package.json
- User documents associated with problems rather than sections
- Users can create personal document workspaces
- Uesrs can rename/delete personal documents and learning logs
- Teacher dashboard
- Teacher switch classes & problems
- Teacher workspace
- Rich-content supports
- Support Dataflow application
|---|---|---|
| index.css | 421,764 bytes | -15% |
| index.js | 4,124,348 bytes | 2% |
=> Release 0.8.0

CHANGELOG.md, package-lock.json, package.json
- Workspace documents for each problem have separate sections with section headers
- Improved tile placement heuristic for documents with sections
- Teacher dashboard shows student progress through sections
- Styled text in authored curriculum content
- Stretching & Shrinking curriculum updates
- Auto-size table columns on column label changes
- Auto-scale geometry tile axes when a table is linked
- Request taller geometry row on image drag if necessary
- Geometry: arrow keys nudge selected points
- Linked geometry/table icons
=> Release 0.9.0

cypress/fixtures/teacher-dash-data.json, cypress/integration/clue/full/student_tests/canvas_test_spec.js, cypress/integration/clue/full/student_tests/graph_tool_spec.js, cypress/integration/clue/full/student_tests/group_chooser_spec.js, cypress/integration/clue/full/student_tests/group_test_spec.js, cypress/integration/clue/full/student_tests/image_tool_spec.js, cypress/integration/clue/full/student_tests/left_nav_test_spec.js, cypress/integration/clue/full/student_tests/right_nav_test_spec.js, cypress/integration/clue/full/student_tests/student_test_spec.js, cypress/integration/clue/full/student_tests/table_tool_spec.js, cypress/integration/clue/full/student_tests/text_tool_spec.js, cypress/integration/clue/full/student_tests/workspace_test_spec.js, cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js, cypress/integration/clue/smoke/single_student_canvas_test.js, cypress/support/commands.js, cypress/support/elements/clue/TeacherDashboard.js, cypress/support/elements/clue/cCanvas.js, cypress/support/index.js
teacher-dashboard-tests branch wouldn't compile so created a new branch from master and moved new teacher dashboard tests into this branch.
=> Adding teacher dashboard test directly to master

package-lock.json, package.json, src/models/stores/stores.test.ts, src/models/tools/geometry/jxg-board.ts, tsconfig.json
Some new features supported by TypeScript 3.7 that will be very useful:
[Optional Chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html?from=hackcv&hmsr=hackcv.com#optional-chaining)
- `let x = foo?.bar.baz();`
- `if (foo?.bar?.baz) { ... }`
- `array?.[0]`
- `fn?.(...)`
[Nullish Coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html?from=hackcv&hmsr=hackcv.com#nullish-coalescing)
- `let x = foo ?? bar();`
=> Update to TypeScript 3.7.2

src/clue/components/teacher/sixpack-right-controls.sass, src/clue/components/teacher/teacher-group-six-pack.sass, src/clue/components/teacher/teacher-group-tab.sass, src/components/pager.sass
[NP/DL] This PR addresses a drawing issue when displaying the CLUE teacher's dashboard on an iPad.
[168671769] Teacher Dashboard Scroll & rendering issue
This problem was addressed by switching a particular grid with a flex. This fixed the display problem but introduced a few other styling issues.
=> 168671769 ipad scrolling bug

src/components/tools/geometry-tool/rotate-polygon-icon.tsx, src/models/tools/geometry/geometry-utils.ts
Perform rotation in screen coordinates rather than user coordinates [#169557380]
=> Fix polygon rotation with unequal axis scales

src/dataflow/utilities/time.test.ts
Tests for the timestamps in the Dataflow program titles!
=> [#168498321] Unit Tests for Human Readable Timestamps

cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js, src/components/document/document-content.tsx, src/components/document/document.tsx, src/components/toolbar.tsx, src/components/tools/geometry-tool/geometry-tool.tsx, src/components/tools/geometry-tool/geometry-toolbar.tsx, src/components/tools/image-tool.tsx, src/components/tools/text-tool.tsx, src/components/tools/tool-tile.tsx, src/models/document/document-content.test.ts, src/models/document/document-content.ts, src/models/stores/ui.test.ts, src/models/stores/ui.ts, src/utilities/event-utils.ts
This currently adds multiple selection.
TODO:  update drag/drop to handle multiple tiles
=> Added multiple selection and drag/drop

src/components/document/document-content.tsx, src/components/tools/placeholder-tool/placeholder-tool.sass, src/components/tools/placeholder-tool/placeholder-tool.tsx, src/components/tools/section-header.tsx, src/components/tools/tool-tile.tsx
- click on a section header
- click on a placeholder tile
- click on empty space in the document
=> Deselect all tiles when any of the following occur:

src/clue/components/teacher/teacher-group-six-pack-fourup.tsx, src/components/document/document.tsx, src/components/thumbnail/right-nav-tab-contents.tsx, src/lib/logger.test.ts, src/lib/logger.ts
Also changes the logged username to include the portal so that the portal user reports can select the log messages.
=> Sticky note logging [#169870176]

.gitignore, CHANGELOG.md, package-lock.json, package.json
- Bug fixes
|---|---|---|
| index.css | 499,791 bytes | 0.0% |
| index.js | 4,365,952 bytes | 0.0% |
=> Release 1.0.2

cypress/integration/common/canvas_test_spec.js, cypress/integration/dataflow/full/blocks-spec.js, cypress/integration/dataflow/full/canvas_test_spec.js, cypress/integration/dataflow/full/data_storage_block_spec.js, cypress/integration/dataflow/full/generator_block_spec.js, cypress/support/commands.js, cypress/support/elements/dataflow/dfCanvas.js, cypress/support/elements/dataflow/dfHeader.js
Removed resetting generators.
Changed verifications in generator block test
=> Remove reset

cypress/integration/common/canvas_test_spec.js, cypress/integration/dataflow/full/blocks-spec.js, cypress/integration/dataflow/full/canvas_test_spec.js, cypress/integration/dataflow/full/data_storage_block_spec.js, cypress/integration/dataflow/full/generator_block_spec.js, cypress/support/commands.js, cypress/support/elements/dataflow/dfCanvas.js, cypress/support/elements/dataflow/dfHeader.js, src/dataflow/components/dataflow-program.tsx, src/dataflow/utilities/node.ts
Use Date.now() to compute generator values to sync editor generators with cloud generators.  Also remove noise generator, for now, and adds commenting around obsolete test function.
[#169870710]
=> Sync generator nodes using Date.now as method time

cypress/fixtures/teacher-dash-data.json, src/components/document/document-context.tsx, src/components/document/document.tsx
Add additional fields to DocumentContext (required by Dataflow) [#169766396]
=> Add additional fields to DocumentContext [#169766396]

cypress/support/elements/dataflow/dfCanvas.js, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/tools/dataflow-tool.tsx, src/dataflow/utilities/time.test.ts, src/dataflow/utilities/time.ts
[PT [#169766396]](https://www.pivotaltracker.com/story/show/169766396)
=> Run asks for filename [#169766396]

src/components/toolbar.tsx, src/models/document/document-content.ts, src/models/tools/drawing/drawing-content.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/image/image-content.ts, src/models/tools/placeholder/placeholder-content.ts, src/models/tools/table/table-content.ts, src/models/tools/text/text-content.ts, src/models/tools/tool-content-info.ts
Refactoring to facilitate the content post-processing required by [[#169277749]](https://www.pivotaltracker.com/story/show/169277749).
=> Post-process tile content

src/dataflow/components/dataflow-program.tsx
This PR implements changes so a selected node is moved in front of other nodes in the editor by changing the node's  z-index property.  Node order is preserved as nodes are clicked.  So if nodes appear in the following order z sort order (A on bottom, C on top): 
A, B, C
And then the user clicks, C, B, and then A, the nodes will then have the following z sort order (A on top, C on bottom):
C, B, A
=> Move node to front of z-order when selected

cypress/integration/dataflow/full/canvas_test_spec.js, cypress/integration/dataflow/smoke/single_student_canvas_test.js, src/components/navigation/right-nav.tsx, src/components/thumbnail/documents-section.tsx, src/components/thumbnail/right-nav-tab-contents.tsx, src/dataflow/app-config.json, src/dataflow/components/dataflow-app-content.tsx, src/dataflow/dataflow.sass, src/models/stores/ui.test.ts, src/models/stores/ui.ts
This PR addresses various UI items in Dataflow, including:
* [169755811] Accordion Filters
* Adding 2 new sections (Relay Programs and Data Stories)
* Making the scroll bar within a section more visible
* [169747822] My Work/Shared Work open by default, with a couple of changes from the story:
* Not open is the right-nav bar open, by default, it is always open
* Since it can't be collapsed, the access bar was remove to add screen real estate to the program document
* Similarly, the fold-out arrow is no longer required
* [168183085] Data/program file sort order (partially implemented)
* More work is required to properly filter on document metadata that does not yet exist.
* Sorting behavior approximates the desired behavior by displaying documents with the most recently used document at …
=> 169755811 accordion filters

cypress/integration/dataflow/full/canvas_test_spec.js, src/dataflow/components/dataflow-program-topbar.sass, src/dataflow/components/dataflow-program-topbar.tsx, src/dataflow/components/dataflow-program.tsx
This PR adds a countdown timer to the program editor topbar that is displayed when the program is running.  The countdown timer displays the time remaining of the running program.  Times are shown in hours:minutes:seconds (even for programs that run for more than a day).
=> add program countdown timer

src/dataflow/components/dataflow-program.tsx, src/dataflow/components/nodes/controls/num-control.tsx, src/dataflow/components/nodes/factories/timer-rete-node-factory.tsx, src/dataflow/utilities/node.ts
This PR adds changes to the timer block so that a unique on and off interval can be set by the user.
=> Allow timer block to have unique on and off intervals

CHANGELOG.md, cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, package-lock.json, package.json, src/clue/components/teacher/teacher-group-six-pack.tsx, src/models/tools/drawing/drawing-content.ts
- Bug fixes
- Dependency updates
|---|---|---|
| index.css | 502,376 bytes | 0.5% |
| index.js | 4,376,662 bytes | 0.2% |
=> Release 1.0.3

src/dataflow/components/dataflow-program.tsx
Add relays to the program data that is sent to the AWS lambda function.
=> Add relays to program data

.travis.yml, s3_deploy.sh, s3_website.yml
Testable at https://dataflow-app.concord.org/branch/s3-deploy-dataflow/?demo.
=> Configure S3 deployment for Dataflow

src/components/document/document-workspace.tsx, src/lib/db.ts, src/models/document/document-content.ts, src/models/stores/app-config-model.ts, src/models/tools/tool-content-info.ts
Cherry-pick master commits from #607.
=> Merge dataflow

src/dataflow/components/dataflow-program.tsx, src/dataflow/utilities/aws.ts
This PR fetches a list of active relays when a user presses the run program button.  If the program contains a relay that is already in use, then a warning is displayed to the user, and the user cannot run their program.
=> Warn user of in use relay when running a program

cypress/integration/dataflow/full/data_storage_block_spec.js, cypress/support/elements/dataflow/dfBlock.js, src/dataflow/components/nodes/controls/text-control.sass, src/dataflow/components/nodes/controls/text-control.tsx, src/dataflow/components/nodes/dataflow-node.tsx, src/dataflow/components/nodes/factories/data-storage-rete-node-factory.tsx
This PR incorporates a small set of changes to the Data Storage program editor node.  Changes include the following:
- do not show the sequence name input field until an input node is connected to the connection pin
- derive the sequence name from the input node rather than using "my-sequence"
- add a colored dot indicator on the sequence name entry field that matches the colors used in the dataset graph
=> 168419912 data storage updates

src/assets/dataflow/icons/delete/delete-active.svg, src/assets/dataflow/icons/delete/delete-disabled.svg, src/assets/dataflow/icons/delete/delete-hover.svg, src/assets/dataflow/icons/delete/delete.svg
Update existing delete document icons to use a new trashcan icon so the operation is not confused with a window or display x-close.
=> Update SVGs to use trashcan

cypress/integration/dataflow/full/canvas_test_spec.js, src/components/document/document-workspace.tsx, src/components/navigation/right-nav.tsx, src/components/thumbnail/right-nav-tab-contents.tsx, src/dataflow/app-config.json, src/dataflow/components/dataflow-app-content.tsx, src/dataflow/components/tools/dataflow-tool.tsx, src/models/stores/app-config-model.ts, src/models/stores/stores.ts, src/models/stores/ui.test.ts, src/models/stores/ui.ts
- Support Dataflow-specific behaviors via application configuration
- Re-enable disabled unit and cypress tests
=> Refactor of accordion filters PR

package-lock.json, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/nodes/controls/plot-button-control.tsx
This PR closes the node mini-graph when a the program is in the completed state.  This needs to occur in 3 places:
- when a document is opened that contains a completed program
- when a program run completes because the end time is hit
- when a program run completes because the user stops the program
=> Close mini-graph when program run is complete

cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/support/elements/common/RightNav.js, src/clue/app-config.json, src/components/document/document-workspace.tsx, src/components/navigation/right-nav.tsx, src/components/thumbnail/documents-section.tsx, src/components/thumbnail/right-nav-tab-contents.tsx, src/models/stores/app-config-model.ts, src/models/stores/stores.ts, src/models/stores/ui.test.ts, src/models/stores/ui.ts
Changes were identified by manual differencing.
=> Merge accordion filter changes from `dataflow` branch

src/components/app.tsx, src/dataflow/app-config.json, src/models/stores/app-config-model.ts
Bypasses group chooser dialog [#170120148]
=> Auto-assign students to individual groups of single students [#170120148]

src/dataflow/components/nodes/controls/dropdown-list-control.tsx, src/dataflow/components/nodes/controls/relay-select-control.tsx, src/dataflow/components/nodes/controls/sensor-select-control.tsx
Clicks on node menus bring the node to the front as well as showing the menu [#167505150]
=> Clicks on node menus bring the node to the front [#167505150]

CHANGELOG.md, package-lock.json, package.json, src/components/navigation/right-nav.tsx, src/components/tools/geometry-tool/geometry-content.tsx, src/index.html, src/models/document/document-content.ts, src/models/tools/drawing/drawing-content.ts, webpack.config.js
Merge `master` branch to `dataflow`
Update `package.json` for Dataflow including project name/version, page title/description and rollbar settings.
=> Merge master to dataflow; update package.json for Dataflow

cypress/support/elements/common/Canvas.js, src/components/document/document-workspace.tsx
Note that since this is common code it is based on the `master` branch and so will need to be merged to the `dataflow` branch before it will take effect there.
=> Add confirmation dialog before publishing [#170222571]

src/components/document/document-workspace.tsx, src/components/document/document.tsx, src/components/thumbnail/documents-section.tsx, src/components/tools/tool-tile.tsx, src/models/document/document.ts, src/models/stores/app-config-model.ts, src/utilities/time.test.ts, src/utilities/time.ts
This PR contains cherry-picked common-code commits from recent PRs merged to the `dataflow` branch. This should bring common code (more) in line between the branches in preparation for the next merge from `master` to `dataflow`. Common-code commits are merged from PRs: #648, #649, #650, #653, #654.
=> Cherry pick dataflow

src/dataflow/components/nodes/controls/dropdown-list-control.tsx, src/dataflow/components/nodes/controls/num-control.tsx, src/dataflow/components/nodes/controls/plot-button-control.tsx
- showing/hiding miniplot calls `this.emitter.trigger('process')`
- reviewed other nodes/controls to identify other possible improvements
- tweaked implementation of a couple other controls
=> Showing/hiding miniplot triggers program save [#170348318]

cypress/integration/dataflow/full/control_panel_spec.js, cypress/integration/dataflow/full/sensor_block_spec.js, package-lock.json, package.json, src/dataflow/components/dataflow-program-graph.tsx
Also updates chart.js dependency to latest in hopes of fixing a types error. The update required a fewer minor configuration changes.
=> Add x-axis tick label at origin if there is room for one [#168655222]

cypress/integration/dataflow/full/canvas_test_spec.js, cypress/integration/dataflow/full/control_panel_spec.js, cypress/integration/dataflow/full/data_storage_block_spec.js, cypress/integration/dataflow/full/running-program-spec.js, cypress/integration/dataflow/full/workspace_test_spec.js, cypress/support/elements/common/Canvas.js, cypress/support/elements/common/Dialog.js, cypress/support/elements/common/RightNav.js, cypress/support/elements/dataflow/dfBlock.js, cypress/support/elements/dataflow/dfCanvas.js
Added tests for running programs
skipped tests that require a hub
=> Running program tests

src/assets/dataflow/icons/refresh/refresh-active.svg, src/assets/dataflow/icons/refresh/refresh-hover.svg, src/assets/dataflow/icons/refresh/refresh.svg, src/dataflow/components/dataflow-program-topbar.sass, src/dataflow/components/dataflow-program-topbar.tsx, src/dataflow/components/dataflow-program.tsx, src/dataflow/dataflow.sass, src/dataflow/lib/iot.ts
Adds a refresh button to the program toolbar that allows users to request the list of devices on each hub which, in turn, will update the list of sensors and relays that appear on each node.
=> Add refresh button

package.json, src/index.html
Configure Dataflow with its own Rollbar project, rather than sharing the CLUE Rollbar project.
=> Configure Rollbar for Dataflow [#170589292]

package-lock.json, package.json, src/components/app.tsx
>So to be correct, the wording could be something like: "We're sorry, but you need to start again at the Concord site." and the button could be "Return to Concord".
=> 3.0.1: Update token expiration error message

src/dataflow/lib/iot.ts, tslint-build.json
- the invalid message is logged for debugging purposes
=> Ignore invalid MQTT messages [#170609881]

src/dataflow/components/dataflow-program.tsx
Do not fetch the program data if the program does not include a data storage node
=> Do not fetch data is no data storage node

cypress/integration/dataflow/full/running-program-spec.js, src/dataflow/components/dataflow-program.tsx
Notify user with alert when a program run is complete
=> Notify user when program is complete

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/branch/student_tests/right_nav_test_spec.js, cypress/support/elements/clue/cCanvas.js, cypress/support/elements/common/Canvas.js
Added tests for deleting canvases, rename canvases, bookmarking canvases. Reinstated save and restore of canvases
=> Add canvas tests

src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jxg-comment.ts, src/models/tools/geometry/jxg-movable-line.ts
Also, propagate user axis names from #717 to movable line equation.
=> Make movable line comment authorable [#170084203]

src/components/tools/geometry-tool/axis-settings-dialog.sass, src/components/tools/geometry-tool/axis-settings-dialog.tsx, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jxg-board.ts, src/models/tools/geometry/jxg-dispatcher.ts
Allow user to add additional axis label/annotation that appears in parentheses after axis name [#170957446]
=> User axis annotation [#170957446]

src/components/document/document-content.tsx, src/components/navigation/left-nav.sass, src/components/toolbar.tsx, src/lib/logger.test.ts, src/models/document/document-content.ts
1. Can't drag tiles from curriculum to existing row [#164184930]
2. Drag highlight persists after dragging tile from curriculum [#171098080]
3. Drag highlight should not appear over curriculum
=> Fix tile drags from curriculum

src/components/app.tsx, src/lib/auth.ts, src/models/stores/stores.ts
We were not properly updating the `appMode` in the preview launch path.
=> Fix preview button launch from portal

package-lock.json, package.json, tsconfig.json
cf. https://github.com/microsoft/TypeScript/issues/32431
=> Eliminate --importHelpers -- not yet ES2015 module-savvy

CHANGELOG.md
=> Release 1.1.0 take 2

src/components/tools/table-tool/table-tool.tsx
- clean up the table properly when unmounting the table component
=> Fix table errors logged by rollbar

src/components/tools/geometry-tool/geometry-content.tsx
- clean up properly in endDragSelectedPoints()
=> Fix drag state bug which manifested on switching to/from 4-up view

cypress/integration/dataflow/branch/header_test_spec.js, src/components/app-header.ts, src/dataflow/components/dataflow-app-content.sass, src/dataflow/components/dataflow-app-content.tsx, src/dataflow/components/dataflow-program-graph.tsx, src/dataflow/components/stats.sass, src/dataflow/components/stats.tsx, src/dataflow/utilities/export.ts, src/lib/firebase.ts
Add Stats panel when logged in as teacher that displays some basic classroom statistics which can be downloaded as a CSV file.  Stats include:
- total, average, and per student number of documents created (a document is created when a program is run and when a user presses the new program button. An initial document is created when the user first logs into the app)
- total, average, and per student number of editable programs created (this includes the default program that is created when the user logs in and any new programs created with the new button)
- total, average, and per student number of run programs (every time the user presses the run button)
- total, average, and per student number of run programs that include a data storage block and have some form of data collection …
=> 171131867 data collection

package-lock.json, package.json, scripts/patch-rete.js, src/dataflow/components/nodes/controls/dropdown-list-control.tsx, src/dataflow/components/nodes/controls/relay-select-control.tsx, src/dataflow/components/nodes/controls/sensor-select-control.tsx, webpack.config.js
- Eliminate Drag button patch by updating to Rete 1.4.3-rc.1 which contains the fix that we proposed
- Eliminate Zoom wheel patch by adding wheel event handlers to menu code
=> Eliminate rete patches

src/dataflow/components/dataflow-program.tsx, src/dataflow/components/stats.tsx
This PR adds protection in the DataflowProgram and Stats components around trying to set state on an unmounted component.
=> Prevent setState on unmounted component

src/lib/db-listeners/db-latest-group-id-listener.ts, src/lib/db-listeners/db-problem-documents-listener.ts, src/lib/db-listeners/index.ts, src/lib/db.test.ts, src/lib/db.ts
- Fix DB unit tests to prevent open handle warnings
- Simplify DB listeners
=> Improve DB unit tests; simplify DB listeners

src/assets/icons/arrow/arrow-open.svg, src/assets/icons/arrow/arrow.svg, src/assets/icons/check/check-selected.svg, src/assets/icons/check/check.svg, src/clue/components/clue-app-header.sass, src/clue/components/clue-app-header.tsx, src/clue/components/problem-select.sass, src/clue/components/problem-select.tsx, src/components/four-up.sass, src/components/vars.sass
Update the CLUE app header to match the new UI specs:
- update header bg color
- update member area colors and styling
- add (currently disabled) problem select
- update unit/investigation information in upper left and revise styling
- add updated content divider
- update student name area styling
Prototype: https://om2cbt.axshare.com
Specs - web: https://zpl.io/boLO9EX
=> 174236904 header ui

src/components/tools/image-tool.tsx
- don't scale image larger than natural size
- add debounce to prevent resize loops
=> Fix image auto-sizing

src/clue/clue.sass
Small PR to update the tab colors to match changes in the CLUE UI spec.
=> Update tab colors to match spec

cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/support/elements/clue/TeacherDashboard.js, src/clue/components/clue-app-header.sass, src/clue/components/clue-app-header.tsx, src/clue/components/custom-select.sass, src/clue/components/custom-select.tsx, src/clue/components/toggle-buttons.scss, src/clue/components/toggle-buttons.scss.d.ts, src/components/class-menu-container.tsx, src/components/problem-menu-container.tsx
This PR makes improvements to the teacher version of the CLUE header to be more in line with the UI spec.  We do not have final specs for the teacher header so for now changes are based on the style and layout of the student header.  Eventually, once the specs are completed, we will need to return to the teacher header and make additional improvements.
=> 174403959 teacher header

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/branch/student_tests/graph_tool_spec.js, cypress/support/elements/common/Canvas.js, cypress/support/elements/common/RightNav.js, src/components/document/document-or-browser.tsx, src/components/document/document-workspace.tsx, src/components/document/document.tsx, src/components/thumbnail/tab-panel-documents-section.tsx, src/components/thumbnail/thumbnail-document-item.tsx
- fixes/reenables some of the skipped cypress tests
- adds some cypress utility functions which demonstrate how to write tests with the new UI
- eliminates the restriction on deleting the last personal document now that it's possible to create the first one
=> Fix some cypress tests

cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, src/clue/clue.sass, src/clue/components/teacher/teacher-group-six-pack-fourup.tsx, src/clue/components/teacher/teacher-group-six-pack.tsx, src/components/document/canvas.sass, src/components/document/document-workspace.tsx, src/components/document/group-virtual-document.sass, src/components/document/group-virtual-document.tsx, src/components/document/student-group-view.scss, src/components/document/student-group-view.tsx, src/components/four-up.tsx, src/components/navigation/nav-tab-panel.tsx, src/hooks/use-stores.ts, src/models/stores/ui.ts
- shows in Student Workspaces tab
- support button in teacher dashboard brings up group in Student Workspaces tab
=> Add StudentGroupView

.eslintrc.js, cypress/.eslintrc.js, src/clue/components/progress-widget-item.tsx, src/clue/components/teacher/teacher-group-six-pack-fourup.tsx, src/clue/components/teacher/teacher-group-tab.tsx, src/components/class-menu-container.tsx, src/components/document/student-group-view.tsx, src/components/navigation/nav-tab-panel.tsx, src/components/tools/drawing-tool/drawing-layer.tsx, src/components/tools/drawing-tool/drawing-toolbar.tsx, src/components/tools/geometry-tool/rotate-polygon-icon.tsx
Enable a few more rules (some of which identified some code worth changing) and gather some data on rules we might like to enable in the future.
=> More ESLint configuration tweaks

cypress/support/elements/common/Canvas.js, src/assets/icons/new/add.svg, src/clue/app-config.json, src/components/document/document-file-menu.tsx, src/components/document/document-or-browser.tsx, src/components/document/document-workspace.tsx, src/components/document/document.tsx, src/components/navigation/document-tab-content.tsx, src/components/navigation/document-tab-panel.tsx, src/components/thumbnail/tab-panel-documents-section.sass, src/components/thumbnail/tab-panel-documents-section.tsx
~~Still need to update the cypress tests but the basic code is reviewable.~~
Cypress tests updated.
=> File menu III: Replace New menu item with New thumbnail in document browser

src/clue/app-config.json
This PR changes the problem tab label from "Problems" to "Problem".
=> Change problem tab label from "problems" to "problem"

src/components/navigation/document-tab-content.sass, src/components/navigation/document-tab-content.tsx, src/components/thumbnail/tab-panel-documents-section.tsx, src/hooks/use-stores.ts
This PR adds a document title to the reference document displayed in the left tab panel.
=> Add document title to reference document

cypress/integration/clue/branch/student_tests/image_tool_spec.js, cypress/support/elements/common/Canvas.js, src/clue/app-config.json
Make the problem workspaces the first tab that appears under my work and class work
=> Change sub tab order so problem workspaces is the first tab

src/components/document/document-or-browser.tsx, src/components/navigation/document-tab-panel.tsx, src/components/thumbnail/tab-panel-documents-section.sass, src/components/thumbnail/tab-panel-documents-section.tsx, src/components/thumbnail/thumbnail-document-item.tsx
In primary workspace:
- document browser opens to section of current document initially
- current document is highlighted in document browser
=> Fix selected document bugs

CHANGELOG.md, package-lock.json, package.json
- Edit button in document title bar
- Supports tab defaults to Teacher Supports subtab
- Fix publishing teacher supports to multiple classes
|---|---|---|
| index.css | 505,055 bytes | 0.2% |
| index.js | 4,888,343 bytes | 0.0% |
=> Release 1.4.1

src/components/tools/drawing-tool/drawing-layer.tsx
[[#175339037]](https://www.pivotaltracker.com/story/show/175339037)
Store `objects` map as instance member rather than React state [#175339037]
The root of the bug is that the map from object id to object was being maintained in React state, which meant that updates to the map were asynchronous, which led to race conditions in which the command to delete or update an object could be processed before the map had been updated to include the object. The fix is to move the map to an instance member where it can be manipulated synchronously.
=> Fix drawing tool bug: deleted objects don't stay deleted

cypress.json, cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/graph_tool_spec.js, cypress/integration/clue/branch/student_tests/image_tool_spec.js, cypress/integration/clue/branch/student_tests/text_tool_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/integration/clue/full/student_tests/group_chooser_spec.js, cypress/support/elements/clue/GraphToolTile.js, cypress/support/elements/common/Canvas.js, cypress/support/elements/common/RightNav.js, src/clue/app-config.json, src/components/document/document-workspace.sass, src/components/navigation/document-tab-panel.sass, src/components/navigation/document-tab-panel.tsx, src/components/navigation/nav-tab-panel.sass, src/components/navigation/problem-panel.sass, src/components/navigation/problem-tab-content.sass, src/components/thumbnail/tab-panel-documents-section.sass, src/components/thumbnail/tab-panel-documents-section.tsx, src/components/vars.sass
Combined Problem Workspace and Extra Workspace subtab of My Work tab into one subtab called Workspaces.
Fixes the css sizes for the primary workspace and the tabs to match the design specs.
Fixes Cypress related to the tabs.
Fixed some skipped Cypress tests
Changes default viewport for Cypress test to 1400x1000
=> 175176453 combine personal documents

cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/graph_tool_spec.js, src/components/toolbar.tsx, src/components/tools/drawing-tool/drawing-tool.sass, src/components/tools/drawing-tool/drawing-tool.tsx, src/components/tools/drawing-tool/drawing-toolbar.tsx, src/components/tools/geometry-tool/geometry-content-wrapper.tsx, src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/geometry-tool/geometry-shared.tsx, src/components/tools/geometry-tool/geometry-tool-buttons.tsx, src/components/tools/geometry-tool/geometry-tool.sass, src/components/tools/geometry-tool/geometry-tool.tsx, src/components/tools/geometry-tool/geometry-toolbar.sass, src/components/tools/geometry-tool/geometry-toolbar.tsx, src/components/tools/geometry-tool/use-tile-selection-pointer-events.ts, src/components/tools/hooks/use-floating-toolbar-location.ts, src/components/tools/hooks/use-toolbar-tool-api.ts, src/components/tools/image-tool.tsx, src/components/tools/image/image-toolbar.scss, src/components/tools/image/image-toolbar.tsx, src/components/tools/text-toolbar.sass, src/components/tools/text-toolbar.tsx, src/components/tools/tool-tile.tsx, src/hooks/use-current.ts
[[#174764257]](https://www.pivotaltracker.com/story/show/174764257)
Geometry toolbar
- floats and shows only when tile is selected
- adds button to upload a background image
- more closely matches UI spec
- adds tooltips
=> Floating geometry toolbar [#174764257]

src/clue/components/custom-select.sass, src/components/class-menu-container.tsx
[[#175564004]](https://www.pivotaltracker.com/story/show/175564004)
Fix issues with the class switcher menu:
- switching to classes that haven't been assigned the current problem didn't work
- menu didn't support multiple assignments of the same problem to a single class
Note that there are cosmetic issues with the longer class menu item text that results from the above, but I'm inclined to leave those for later now that the basic functionality is fixed.
=> Fix issues with the class switcher menu: [#175564004]

CHANGELOG.md, package-lock.json, package.json
- Combined Problem and Extra Workspaces under single Workspaces tab
- Text, Drawing, Geometry, and Image tools have "floating" toolbars that show only when the tile is selected
- Improved appearance of teacher's publish support icon
- Teacher's problem menu shows problem subtitles
- Teacher's class menu handles multiple assignments of the same problem
- Fixed drawing tool update bug
- Fixed display of images in cross-class teacher supports
- Dragging a tile selects the tile first
- Student names/initials are now more legible
|---|---|---|
| index.css | 517,550 bytes | 2.5% |
| index.js | 4,950,264 bytes | 1.3% |
=> CLUE 1.5.0

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/graph_tool_spec.js, cypress/integration/clue/branch/student_tests/image_tool_spec.js, cypress/integration/clue/branch/student_tests/right_nav_test_spec.js, cypress/integration/clue/branch/student_tests/workspace_test_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_curation_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_support_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js, cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/integration/clue/smoke/single_student_canvas_test.js, cypress/support/commands.js, cypress/support/elements/common/RightNav.js
Adds cypress test for the navigation edit button.
=> Edit button cypress test

src/assets/icons/error.svg, src/components/app.tsx, src/components/document/document-content.tsx, src/components/document/tile-row.tsx, src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/table-tool/editable-table-title.tsx, src/components/tools/table-tool/header-cell-input.tsx, src/components/tools/table-tool/table-tool.scss, src/components/tools/table-tool/table-tool.tsx, src/components/tools/table-tool/use-data-set.ts, src/components/tools/table-tool/use-grid-context.ts, src/components/tools/table-tool/use-set-expression-dialog.tsx, src/components/tools/table-tool/use-table-title.ts, src/components/tools/tool-tile.tsx, src/components/utilities/error-alert.scss, src/components/utilities/error-alert.tsx, src/components/utilities/use-error-alert.tsx, src/components/utilities/use-single-string-dialog.tsx, src/hooks/custom-modal.scss, src/hooks/use-custom-modal.tsx, src/models/document/document-content.ts, src/models/tools/table/table-content.md, src/models/tools/table/table-content.ts, src/utilities/js-utils.ts
- improve table change types
- add table change documentation
- use optional chaining where appropriate
It was harder to determine whether our change mechanism would require any enhancements to support multiple columns/attributes with expressions than it should have been because there's no documentation and our types were fairly loose, so I decided to rectify the situation.
=> Table improvements (#878) Table default title (#879)

CHANGELOG.md, README.md, package-lock.json, package.json
- Draw toolbar styling improvements
- Content updates
|---|---|---|
| index.css | 502,372 bytes | -2.9% |
| index.js | 4,964,769 bytes | 0.3% |
=> Release 1.5.2

src/components/tools/table-tool/cell-formatter.tsx, src/components/tools/table-tool/expression-utils.ts, src/components/tools/table-tool/use-column-extensions.ts, src/components/tools/table-tool/use-columns-from-data-set.ts, src/components/tools/table-tool/use-data-set.ts, src/components/tools/table-tool/use-editable-expressions.ts, src/models/tools/table/table-content.ts
Editing and expression handling improvements
- don't generate changes if cells are edited but not changed
- handle x name change properly
=> Editing and expression handling improvements

src/components/class-menu-container.tsx
[[#176046008]](https://www.pivotaltracker.com/story/show/176046008)
Fix class switcher menu issues:
- exclude problems from other units as matching targets
- exclude classes which don't assign the same problem from the same unit
- only show the activity title in the menu when class name would be ambiguous, i.e. when the same activity is assigned multiple times to the same class (which is uncommon)
Note that this isn't really testable without logging in from the portal as a teacher with multiple classes.
=> Fix class switcher menu issues [#176046008]

CHANGELOG.md, README.md, cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, package-lock.json, package.json
- Content updates
- Fixed teacher class switcher menu
|---|---|---|
| index.css | 502,372 bytes | 0.0% |
| index.js | 4,964,293 bytes | 0.0% |
=> Release 1.5.3

CHANGELOG.md, package-lock.json, package.json
- Content updates (Comparing and Scaling)
|---|---|---|
| index.css | 502,372 bytes | 0.0% |
| index.js | 4,964,293 bytes | 0.0% |
=> Release 1.5.4

src/public/curriculum/comparing-and-scaling/comparing-and-scaling.json
Comparing and Scaling tweaks from Nathan.
=> Comparing and Scaling tweaks

src/clue/app-config.json, src/clue/clue.sass, src/components/document/document-workspace.tsx, src/components/navigation/nav-tab-panel.tsx, src/components/navigation/problem-tab-content.tsx, src/models/curriculum/unit.ts, src/models/stores/app-config-model.ts, src/models/stores/stores.ts, src/models/view/nav-tabs.ts
[[#176622025]](https://www.pivotaltracker.com/story/show/176622025)
=> Support Teacher Guide panel [#176622025]

src/components/document/tile-row.sass, src/components/document/tile-row.tsx, src/components/tools/geometry-tool/geometry-tool.sass, src/components/tools/table-tool/table-tool.sass, src/components/tools/tool-tile.sass, src/components/tools/tool-tile.tsx
[[#176622026]](https://www.pivotaltracker.com/story/show/176622026)
https://www.pivotaltracker.com/story/show/176622026/comments/221690589
=> Update teacher solutions styling to spec (#904)[#176622026]

src/models/tools/geometry/jxg-board.ts, src/models/tools/geometry/jxg-comment.ts, src/models/tools/geometry/jxg-polygon.ts
Unfortunately, I'm not sure what led to the occurrence of this problem in the first place.
=> Fix getPolygonEdge() function so it handles the case in which a required point isn't present

src/components/tools/table-tool/table-tool.tsx, src/components/tools/table-tool/use-geometry-linking.ts, src/utilities/color-utils.ts
https://www.pivotaltracker.com/story/show/176582684/comments/221774706
=> Table selection color reflects link color for linked tables

CHANGELOG.md, package-lock.json, package.json
- New Table design supports multiple columns
- Graph tile supports linking multi-column tables
- Teacher-only curriculum content (solutions)
- Support for separate teacher guide content
- Smaller bundle size
|---|---|---|
| index.css | 389,427 bytes | -22.5% |
| index.js | 4,148,062 bytes | -16.4% |
=> Release 1.6.0

src/components/tools/tool-tile.tsx, src/models/document/document-content.ts, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/jxg-dispatcher.ts, src/models/tools/tool-content-info.ts, src/models/tools/tool-tile.ts
- copying a geometry tile with its table preserves linked points
- copying a geometry tile without its table loses linked points
=> Fix bugs with copying linked tiles [#176829255]

src/components/tools/table-tool/table-tool.tsx, src/components/tools/table-tool/use-data-set.ts
[[#176602050]](https://www.pivotaltracker.com/story/show/176602050)
=> Fix bug that allowed delete row icon to be out of sync with row selection [#176602050]

cypress/integration/clue/branch/student_tests/table_tool_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_support_spec.js, cypress/support/elements/clue/TableToolTile.js, src/components/tools/table-tool/use-controls-column.tsx
Adds back table cypress tests with new functionalities and new UI.
=> Update table cypress tests

cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js, src/components/navigation/document-tab-content.tsx
Removes document from nav-tab  view when deleted from primary workspace
Adds test for document deletion shows tab thumbnails
=> Nav area reverts to show thumbnail when document is deleted.

cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/table_tool_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/support/commands.js, cypress/support/elements/clue/GraphToolTile.js, cypress/support/elements/clue/TableToolTile.js, src/components/tools/table-tool/editable-table-title.tsx, src/components/tools/table-tool/link-geometry-button.tsx, src/components/tools/table-tool/table-tool.tsx, src/components/tools/table-tool/use-content-change-handlers.ts, src/components/tools/table-tool/use-geometry-linking.ts, src/components/tools/table-tool/use-link-geometry-dialog.tsx, src/models/tools/geometry/geometry-content.ts, src/models/tools/table-links.ts, src/models/tools/table/table-content.md, src/models/tools/table/table-content.ts
Adds ability to unlink a table from a graph using the link dialog. 
If there are no graphs to link, the link section of the select graph dropdown will be hidden. If there are no graphs to unlink, the unlink section will be hidden.
=> 176834983 unlink table

cypress/integration/clue/branch/teacher_tests/teacher_curation_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, src/assets/icons/resize-tile/expand-handle.svg, src/components/document/tile-row.sass, src/components/document/tile-row.tsx, src/components/tools/tool-tile.sass, src/components/tools/tool-tile.tsx
Adds a resize icon to bottom right of a tile. Current functionality only allows user to resize the row. Ths icon is just so that the resize row is more discoverable by the user
=> 175081175 tile resize

src/components/tools/geometry-tool/geometry-content.tsx, src/components/tools/geometry-tool/geometry-tool.sass, src/components/tools/geometry-tool/link-table-button.scss
Added a wrapper to title area to allow positioning.
Made title area smaller so it doesn't interfere with y-axis label click
=> Fixes bug not being able to click on y-axis label

src/lib/db-listeners/index.ts, src/lib/logger.test.ts, src/lib/logger.ts, src/models/tools/drawing/drawing-content.test.ts, src/models/tools/geometry/geometry-content.test.ts, src/models/tools/table/table-content.test.ts
- Only log unmonitoring of user's own documents
- Log document details with tool changes
=> Logging tweaks

CHANGELOG.md, package-lock.json, package.json
- Additional logging improvements (#951)
- Geometry: Fix click on Y axis label (#950)
|---|---|---|
| index.css | 390,895 bytes | 0.0% |
| index.js | 4,586,117 bytes | 0.0% |
=> Release 1.8.1

CHANGELOG.md, package-lock.json, package.json
- Network status monitoring/alerting (#953)
|---|---|---|
| index.css | 391,321 bytes | 0.1% |
| index.js | 4,587,574 bytes | 0.0% |
=> Release 1.8.2

src/models/stores/groups.test.ts, src/models/stores/groups.ts
[[#178165267]](https://www.pivotaltracker.com/story/show/178165267)
@eireland The changes include some reformatting of code. Viewing the differences without whitespace changes should make the actual changes easier to see.
=> Validate students in teacher dashboard

src/models/document/document-content.test.ts, src/models/document/document-content.ts
[[#178162887]](https://www.pivotaltracker.com/story/show/178162887)
=> Don't log DELETE_TILE when specified tile doesn't exist

package-lock.json, package.json, src/components/tools/geometry-tool/geometry-toolbar.test.tsx, src/components/tools/geometry-tool/geometry-toolbar.tsx, src/setupTests.ts
[[#178148390]](https://www.pivotaltracker.com/story/show/178148390) [[#178166203]](https://www.pivotaltracker.com/story/show/178166203)
=> Trigger toolbar render on selection change

CHANGELOG.md, cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js, package-lock.json, package.json
- Log presentation of network status alerts [#178163876] (#967)
- Validate students in teacher dashboard [#178165267] (#964)
- Don't log DELETE_TILE when specified tile doesn't exist [#178162887] (#965)
- Geometry: Update toolbar on selection change [#178148390] [#178166203] (#966)
|---|---|---|
| index.css | 391,321 bytes | 0.0% |
| index.js | 4,588,222 bytes | 0.0% |
=> Release 1.8.4

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/support/elements/clue/cCanvas.js, package-lock.json, package.json, src/components/delete-button.test.tsx, src/components/delete-button.tsx, src/components/network-status.test.tsx, src/components/tool-button.test.tsx, src/components/tool-button.tsx, src/components/toolbar.test.tsx, src/components/toolbar.tsx
@eireland For review purposes, the changes are less extensive than they might appear. I split the `<ToolButtonComponent>` into its own file so it could be unit tested. The `<DeleteButton>` component is just a modified version of `<ToolButtonComponent>` that has the delete-specific code. Those two components and the `<ToolbarComponent>` now have their own unit tests.
=> Add confirmation dialog for tile deletion; add unit tests

src/models/tools/geometry/geometry-export.test.ts, src/models/tools/geometry/geometry-export.ts, src/models/tools/geometry/geometry-import.test.ts, src/models/tools/geometry/geometry-import.ts, src/models/tools/geometry/jxg-comment.ts
[[#178324795]](https://www.pivotaltracker.com/story/show/178324795)
Note that this is based off the previous PR branch, which seems to confuse Codecov. The confusion should be cleared up once the previous PR is merged.
=> Geometry: implement import/export of comments [#178324795]

src/dataflow/components/dataflow-program-topbar.sass, src/dataflow/components/dataflow-program-topbar.tsx, src/dataflow/utilities/node.ts, src/dataflow/vars.sass
This PR disables program run times greater than 30 minutes in preparation of making a Dataflow a demo product only.
Can demo/test here:
http://dataflow-app.concord.org/branch/limit-run-time/?appMode=demo&demoName=Dataflow&fakeClass=1&fakeUser=student:1&unit=dataflow&problem=1.1
=> 178533340 limit run time

src/components/document/document-workspace.tsx, src/components/document/document.tsx, src/components/navigation/right-nav.sass, src/components/utilities/dialog.sass, src/components/utilities/dialog.tsx, src/dataflow/components/dataflow-program-graph.sass, src/dataflow/components/dataflow-program-toolbar.tsx, src/dataflow/components/dataflow-program.tsx, src/dataflow/components/nodes/controls/delete-control.tsx, src/dataflow/components/nodes/controls/plot-button-control.tsx, src/dataflow/components/nodes/dataflow-node.tsx, src/dataflow/components/split-view-buttons.sass, src/models/stores/ui.ts
This PR adds a welcome dialog that appears when the app is launched giving an overview of the demo version of Dataflow and how to use it.  It also updates in app text to match the terms used in the welcome dialog.
Changes include:
- add welcome dialog that appears when app is launched
- change "workspace" references to "program"
- change "node" references to "block"
- add mouse cursor states
=> 178762358 getting started

src/components/navigation/document-tab-panel.sass, src/components/navigation/document-tab-panel.tsx, src/components/navigation/problem-tab-content.sass
Changes subtabs with new styling per spec https://app.zeplin.io/project/5d62a554d64a9e02dcad80de/screen/608bd1c724f8352e0324148e
=> Changes border styling of navigation sub tabs

cypress/integration/clue/branch/teacher_tests/teacher_curation_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_support_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js, cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/support/commands.js, src/clue/components/clue-app-content.tsx, src/clue/components/clue-app-header.sass
Changes wording and styling of Dashboard/Workspace toggle per spec
=> Changes the wording and styling on the teacher dashboard toggle

src/components/navigation/problem-tab-content.sass, src/components/navigation/problem-tab-content.tsx
Changes the solution toggle to colors to match learning log green per spec
=> Restyles Solutions toggle

src/components/utilities/dialog.tsx
This PR updates the welcome text to the requested text from the Dataflow research team.
=> Update welcome text

package-lock.json, package.json
Bump Dataflow version to 3.1.0
=> Bump Dataflow version to 3.1.0

cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js, src/components/app.tsx, src/components/demo/demo-creator.test.tsx, src/components/demo/demo-creator.tsx, src/lib/auth.test.ts, src/lib/auth.ts, src/models/stores/user.test.ts, src/models/stores/user.ts
Demo teacher 1 is not in a network.
Demos teachers 2 & 3 are in a network together.
=> Demo teachers 2-3 are in a network

cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/table_tool_spec.js, cypress/integration/clue/branch/student_tests/workspace_test_spec.js, cypress/integration/clue/smoke/single_student_canvas_test.js, cypress/support/commands.js, cypress/support/elements/clue/TableToolTile.js, src/components/chat/chat-panel-header.scss, src/components/document/collapsed-workspace-tab.tsx, src/components/document/document-workspace.tsx, src/components/document/resize-panel-divider.scss, src/components/document/resize-panel-divider.tsx, src/components/navigation/collapsed-resources-tab.scss, src/components/navigation/collapsed-resources-tab.tsx, src/components/navigation/nav-tab-panel.sass, src/components/navigation/nav-tab-panel.tsx
- Fixes chat close button styling to match spec
- Adds drag thumbnail active state
- Fixes restore of subtab state after resource tabs collapsed and expanded
- Fixes failing Cypress tests
=> - Fixes collapsed workspace tab text

src/lib/firestore-schema.ts
TypeScript representation of the proposed Firestore schema.
=> Documentation of proposed Firestore schema

firebase-test/.eslintrc.js, firebase-test/jest.config.js, firebase-test/package-lock.json, firebase-test/package.json, firebase-test/src/setup-rules-tests.ts, firebase-test/src/supports-rules.test.ts, firebase-test/tsconfig.json, firebase.json, firestore.rules, package.json
- primarily tests rules for supports documents
- update rules to enforce some document contents
=> Add tests for existing security rules

firebase-test/src/documents-rules.test.ts, firebase-test/src/setup-rules-tests.ts, firebase-test/src/supports-rules.test.ts, firestore.rules
plus jest tests for the new security rules
=> Firestore security rules for documents and comments

functions/test/get-network-resources.test.ts
The last commit to #1057 added additional class information to the response but failed to update the tests accordingly. 🤦
=> Fix tests for getNetworkResources() function

functions/package.json, functions/src/get-network-resources.ts, functions/src/shared.ts, functions/test/get-network-resources.test.ts
[[#179154370]](https://www.pivotaltracker.com/story/show/179154370)
- problem/planning documents
- personal documents and learning logs
@mklewandowski let me know if you'd like to do a sync review.
=> Add `My Work` documents to those returned by the `getNetworkResources()` function

src/models/document/document.test.ts, src/models/document/document.ts
Followup to #1068 which fixes the content bug noted there.
cc @Concord-Jim
=> Fix handling of remote document content

functions/src/get-network-resources.ts, functions/src/shared.ts, functions/test/get-network-resources.test.ts, src/hooks/network-resources.test.ts, src/hooks/network-resources.ts
[[#179154370]](https://www.pivotaltracker.com/story/show/179154370)[[#178762452]](https://www.pivotaltracker.com/story/show/178762452)
Fix handling of network publications by `getNetworkResources()` function and `useNetworkResources()` hook
=> Fix handling of network publications

src/components/chat/chat-panel.tsx
[[#179986752]](https://www.pivotaltracker.com/story/show/179986752)
This is another manifestation of the bug we fixed in [this commit](https://github.com/concord-consortium/collaborative-learning/pull/1089/commits/e51a08b9aa28a573b26a06b79457281827dd5a2f). Because of the use of the modal dialog to confirm the deletion, sometimes the `deleteComment()` callback has stale dependencies. We use refs updated with current values to avoid these stale dependencies.
=> Use refs to deal with stale values in deleteComment() callback [#179986752]

src/public/curriculum/moving-straight-ahead/moving-straight-ahead.json, src/public/curriculum/moving-straight-ahead/msa-teacher-guide.json
(cherry picked from commit e5b87ad8deab39cb853d77335c7760a8a1a9b598)
=> subtle typos in MSA TOC

src/lib/logger.test.ts, src/lib/logger.ts
[[#180522053]](https://www.pivotaltracker.com/story/show/180522053)
=> Don't log in demo mode

dependencies-notes.md, package-lock.json, package.json
Looks like they [fixed in 9.1.1](https://docs.cypress.io/guides/references/changelog#9-1-1) whatever they broke in 9.1.0.
=> Update to Cypress 9.1.1

src/public/curriculum/stretching-and-shrinking/sas-teacher-guide.json
making TG content for problem 0 so it doesn't look dumb.
=> fixes undefined TG tab and adds boilerplat TG content.

src/models/curriculum/support.test.ts
Tying up another loose end in the form of a piece of unfinished test code I had stashed a while back.
=> Improve SupportModel unit tests

src/components/navigation/document-tab-panel.sass, src/models/view/nav-tabs.ts
PT: [[#180731966]](https://www.pivotaltracker.com/story/show/180731966)
Demo: https://collaborative-learning.concord.org/branch/subtab-colors/?demo
Fix default/unselected subtab colors.
=> Fix subtab colors [#180731966]

src/lib/logger.ts, src/models/document/document-content.ts
Adds section name to log tile log events.
=> 180680837 log section info

cypress/support/elements/clue/GraphToolTile.js, src/lib/logger.ts, src/utilities/js-utils.test.ts, src/utilities/js-utils.ts
[[#180680858]](https://www.pivotaltracker.com/story/show/180680858)
=> Log time zone offset [#180680858]

firebase-test/package-lock.json, firebase-test/package.json, firebase-test/src/user-rules.test.ts, firestore.rules, src/components/thumbnail/tab-panel-documents-subsection-panel.tsx, src/hooks/firestore-hooks.test.ts, src/hooks/firestore-hooks.ts
[[#181124146]](https://www.pivotaltracker.com/story/show/181124146)
Note that this can't be fully tested until the rules changes are deployed, which is pending review.
@eireland Assigning you for review of the front-end React component part.
@scytacki Assigning you for review of the firestore rules changes.
=> Show teacher names in network document captions [#181124146]

functions/src/index.ts
Bring back the baby thrown out with the bath water in #1181.
=> Fix firebase functions deploy

src/clue/app-config.json, src/components/document/document-or-browser.tsx, src/components/document/document-workspace.tsx, src/components/navigation/document-tab-panel.tsx, src/models/curriculum/unit.ts, src/models/stores/app-config-model.ts, src/models/stores/nav-tabs.ts, src/models/stores/stores.ts, src/public/curriculum/mothed/mothed.json
Uses unit level nav tabs if specified. Otherwise uses app level config.
=> 181034371 switch nav tab config by unit

functions/src/get-network-resources.ts, functions/test/get-network-resources.test.ts
In #1187, we fixed a bug that could result in multiple planning documents where there should be only one. Client-side code resolves its promise with the first document it encounters, but prior to this the `getNetworkResources()` firebase function could still return multiple problem or planning documents. This brings the behavior of the `getNetworkResources()` firebase function in sync with the client-side behavior of only returning the first problem or planning document encountered.
=> Limit of one returned problem/planning document

src/clue/app-config.json, src/components/document/document-workspace.tsx, src/models/stores/app-config-model.test.ts, src/models/stores/app-config-model.ts, src/public/curriculum/example-curriculum/example-curriculum.json
PT: [[#180424338]](https://www.pivotaltracker.com/story/show/180424338)
Demo: https://collaborative-learning.concord.org/branch/toolbar-config/?demo&unit=example
=> Example unit: configurable toolbar and nav-tab configuration [#180424338]

cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js, s3_deploy.sh, src/clue/app-config.json, src/components/navigation/document-tab-panel.sass, src/components/navigation/document-tab-panel.tsx, src/components/navigation/problem-panel.sass, src/components/navigation/problem-tab-content.sass, src/components/navigation/problem-tab-content.tsx, src/components/thumbnail/tab-panel-documents-section.tsx, src/public/curriculum/example-curriculum/example-config-subtabs.json, src/public/curriculum/example-curriculum/example-no-section-problem-tab.json, src/public/curriculum/example-curriculum/example-show-nav-panel.json
Removes subtabs from browser panel when there is only one section specified for the top tab.
Adds sample documents that shows the different configurations for the nav panel and File > Open browser panel
=> 181191264 remove subtabs

CHANGELOG.md, package-lock.json, package.json
- Stretching and Shrinking content updates #1214
- Moving Straight Ahead content updates #1214 #1216
- Section information, time zone and activityUrl are now logged [179924865] [180680837] [#180680858] #1179 #1183 #1191
- Improved captions of network documents [#180876987] [#181124146] #1185 #1189 #1197
- Improved network status logging #1201
- Improved drag preview image [180876905] #1205
- Geometry: handle axis bounds changes more efficiently #1165
- Geometry: Adjust X axis bounds to leave room for Y axis labels [#180817314] #1166
- Table: Handle expression evaluation exceptions #1168
- Fixed bug which could result in showing the wrong teacher guide #1169 #1170
- Fixed promise-handling bug in creation of planning documents [#181124054] #1187
- Fixed display and copy of images in …
=> Release 2.1.3

src/components/document/canvas.tsx, src/components/four-up.tsx
Also removes the Editable icon from the top left workspace in 4-up view
=> Removes copy only icon in 4-up view

webpack.config.js
Split the application into three bundles:
```
-rw-r--r--   1 kswenson  staff     5243 Mar 14 17:24 concord.ec7155c7.css
-rw-r--r--   1 kswenson  staff  1632189 Mar 14 17:24 concord.ec7155c7.js
-rw-r--r--   1 kswenson  staff   158273 Mar 14 17:24 main.4f2e13b6.css
-rw-r--r--   1 kswenson  staff   551200 Mar 14 17:24 main.4f2e13b6.js
-rw-r--r--   1 kswenson  staff   275937 Mar 14 17:24 vendor.895e7666.css
-rw-r--r--   1 kswenson  staff  2322045 Mar 14 17:24 vendor.895e7666.js
```
=> Bundle splitting: main, concord, and vendor bundles

package-lock.json, package.json, src/components/tools/text-toolbar.tsx, src/plugins/shared-variables/slate/variable-chip.tsx, src/plugins/shared-variables/slate/variables-plugin.tsx
This isn't fully working, but at least with this change, double clicking brings up the dialog.
=> Fix chip double click

package-lock.json, package.json, src/plugins/diagram-viewer/diagram-types.ts
this brings in the changes with the new node style and expression editor
=> update the diagram view

cypress/integration/clue/branch/student_tests/shared_variables_test_spec.js, src/clue/app-config.json, src/public/curriculum/example-curriculum/example-variables.json
the m2studio content is being actively changed, so relying on it for this test was not goot
=> isolate the shared variable cypress test

src/lib/db-clear.ts
=> Eliminate firebase console warning

package-lock.json, package.json
this brings in a fix for cycles in the diagram
and updates some peerDependencies that might fix
a build problem.
=> update diagram-view to 0.0.15

src/models/image-map.test.ts, src/models/image-map.ts, src/utilities/image-utils.ts
I also added a few comments based on stuff that I took a while
figuring out while groking the code.
=> switch ImageMap to async/await, remove extra action

src/plugins/dataflow-tool/model/utilities/node.ts
Real quick and easy PR for changing the datarate options in dataflow tiles.
=> Update data rate options

cypress/integration/clue/branch/student_tests/dataflow_tool_spec.js, cypress/support/elements/clue/DataflowToolTile.js
Just a starter file with a few basic tests. Needs to be expanded with many more tests, including creating connections and making sure data is passing from node to node properly.
=> Dataflow cypress tests

cypress/integration/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/integration/clue/full/teacher_tests/teacher_dashboard_spec.js, src/clue/components/clue-app-content.tsx, src/components/playback/marker-toolbar.tsx, src/components/playback/slider.tsx, src/lib/logger.ts, src/plugins/drawing-tool/model/drawing-content.ts
Changes teacher default view to workspace instead of dashboard. 
Retained the code for defaulting to dashboard if we ever decide to switch back.
Most of the changes were in Cypress tests.
=> Changes default teacher view to workspace instead of dashboard.

src/components/playback/marker-toolbar.scss, src/components/playback/marker-toolbar.tsx, src/components/playback/playback.scss, src/components/playback/slider.tsx
Fixes time travel slider width
Fixes time travel toggle button hover colors
Fixes slider background color for class work, and student group themes
Hides Comment button from toolset
=> UI bug fixes

src/components/four-up.tsx, src/components/playback/playback.scss
Adds playback to the student one up view in Student Group teacher nav tab
=> Adds playback controls to student group one up view

src/components/four-up.tsx, src/components/tools/geometry-tool/geometry-content.tsx, src/models/tools/geometry/geometry-content.ts, src/models/tools/geometry/geometry-migrate.test.ts, src/models/tools/geometry/geometry-migrate.ts
This PR fixes two bugs:
- Images on legacy geometry tiles are not migrated properly.
- Scale is not set properly for documents focused in 4-up view, which caused geometry tiles to render incorrectly.
=> 182203544 geometry tile bugs

package-lock.json, package.json, tsconfig.json
This fixes an issue seen in the table tile when using time travel
This uses our build of mobx-state-tree that includes: 
https://github.com/mobxjs/mobx-state-tree/pull/1952
#183085799
=> Fix afterCreate child access

dependencies-notes.md, package-lock.json, package.json
Fixes scaled rendering issue, e.g. in four-up views.
=> Downgrade jsxgraph

src/models/tools/geometry/geometry-model.ts
PT: [[#183098645]](https://www.pivotaltracker.com/story/show/183098645)
=> Fix null values in table links for geometry tiles

cypress/integration/clue/branch/student_tests/canvas_test_spec.js, cypress/integration/clue/branch/student_tests/dataflow_tool_spec.js, cypress/integration/clue/branch/student_tests/drawing_tool_spec.js, cypress/integration/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/integration/clue/branch/student_tests/graph_tool_spec.js, cypress/integration/clue/branch/student_tests/image_tool_spec.js, cypress/integration/clue/branch/student_tests/nav_panel_test_spec.js, cypress/integration/clue/branch/student_tests/shared_variables_test_spec.js, cypress/integration/clue/branch/student_tests/table_tool_spec.js, cypress/integration/clue/branch/student_tests/workspace_test_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_curation_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_network_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_support_spec.js, cypress/integration/clue/branch/teacher_tests/teacher_workspace_spec.js, cypress/integration/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/integration/clue/smoke/single_student_canvas_test.js, cypress/support/elements/clue/ChatPanel.js, src/components/chat/chat-panel.tsx, src/components/document/document-content.tsx, src/components/navigation/focus-document-tracker.tsx, src/components/navigation/problem-tab-content.tsx, src/components/workspace/workspace.tsx, src/models/stores/ui.test.ts, src/models/stores/ui.ts
Makes the nav tab panel default to be open to 50-50 and showing the problem tab.
=> 183081515 default nav panel open

cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, src/hooks/use-stores.ts
I made this commit on the wrong branch -- it should have been part of [182565408-list-comments](https://github.com/concord-consortium/collaborative-learning/tree/182565408-list-comments) so making (and immediately merging) a PR to get get in there.
=> Fix comments for teacher guides and update cypress tests.

src/plugins/dataflow-tool/nodes/dataflow-node-plot.tsx, src/plugins/dataflow-tool/nodes/factories/control-rete-node-factory.tsx
When running the cypress tests I got warnings around these lines.
I'm not sure if this approach is OK.
=> dataflow error handling

package-lock.json, package.json
Addresses chrome 105 issues from tickets:
[Ticket #183226311](https://www.pivotaltracker.com/n/projects/2441242/stories/183226311)
[Ticket #183226359](https://www.pivotaltracker.com/n/projects/2441242/stories/183226359)
[Ticket #183233621](https://www.pivotaltracker.com/n/projects/2441242/stories/183233621)
=> Updated slate-editor from 0.8.1 to 0.8.2

src/components/tools/table-tool/table-tool.scss, webpack.config.js
Link button is now on top right of "table-title", and adjusts for multiple columns. 
Added logging ability in webpack to debug CSS.
=> 183367991 table link icon in far corner

s3_deploy.sh
Add memory to deploy since we're seeing OOM errors.
=> Update memory for deploy.

database.rules.json
We already made this change in the console/production so I could get some testing setup between the portal and the staging environment.
=> Add learn-migrate to allowed portals section.

docs/history-framework.md, src/hooks/document-comment-hooks.ts, src/hooks/use-document-sync-to-firebase.test.ts, src/models/history/tree-manager.test.ts, src/models/history/tree-manager.ts
this uses an incrementing index and a query for the last history entry
It also records the created time, and previous history entry id.
It uses a promise to make sure this information is available
before writing the entry.
=> 183340035-history-entry-ordering

src/components/chat/chat-thread.tsx
182565433: Fix bug found in testing of comments.
=> Do not show number when there are no comments

firebase-test/src/documents-rules.test.ts, firestore.rules
Adds rules for reading and writing history entries as well as corresponding tests.
=> Rules for history documents

functions/src/shared.ts, src/components/chat/chat-thread.tsx, src/components/document/document-content.tsx, src/components/document/tile-row.tsx, src/components/toolbar.tsx, src/models/curriculum/problem.ts, src/models/curriculum/section.ts, src/models/document/document-content.ts, src/models/stores/ui.ts
- Scroll to tile when comment about tile is selected.
- Fix scrolling to tile when it is added to a doc.
=> Scrolling to tiles

src/hooks/use-user-context.ts
This is quick fix, really we should try to fix this issue in a better way.
=> update user context when teacher network is known

src/components/thumbnail/collapsible-document-section.tsx, src/components/thumbnail/decorated-document-thumbnail-item.tsx, src/components/thumbnail/documents-type-collection.tsx, src/components/thumbnail/thumbnail-document-item.tsx
This makes it a little easier to figure out which documents
go in which section on the left.
=> add displayName to components on left side

src/lib/logger.test.ts, src/lib/logger.ts
#183575574 - Add the tile type to the logs for comment events.
=> Add tile type to comment log events

src/lib/db-listeners/db-publications-listener.ts
This removes one source of a console warning about duplicate documents.
The published documents were being added first in the firebase `once` handler. And then the same documents were being added again by the `child_added` listener. It might be possible to remove the `once` handler, but the comment above it made it sound like it was required.
=> fix duplicate publication docs

.github/workflows/release-production.yml
This is a workflow for copying the index-top.html file from the version folder up to the index.html at the root.
It is basically the same as the release-staging.yml workflow with just the DEST_FILE changed.
=> production release workflow

src/components/tiles/geometry/geometry-content.tsx, src/models/shared/shared-model-document-manager.test.ts, src/models/shared/shared-model-document-manager.ts, src/models/shared/shared-model-manager.ts, src/models/tiles/geometry/geometry-content.ts, src/models/tiles/geometry/jxg-table-link.ts, src/models/tiles/table/table-content.ts, src/plugins/diagram-viewer/diagram-content.test.ts, src/plugins/shared-variables/slate/variables-text-content.test.tsx
There's still work to be done here, but basic linking/unlinking works as expected.
=> Improve linked table/geometry behavior

CHANGELOG.md, package-lock.json, package.json
Version 3.6.0 updates CLUE to use the AWS Log Ingester in place of the old Heroku Log Ingester and there are also content updates to the unti Growing Growing Growing's 1.3 and 2.3 questions to show the problem sections.
- [CLUE] Create section headers for GGG 1.3 and 2.3 [#184065115](https://www.pivotaltracker.com/story/show/184065115)
- Logging URL Update [#184067926](https://www.pivotaltracker.com/story/show/184067926)
| File                                                                                  | Size | % Change from Previous Release |
| ------------------------------------------------------------------------------------- | ---- | ------------------------------ |
| common-DataCard-Diagram-SharedVariables-Drawing-Geometry-Image-Table-Text.1c62df70.js | 51K  | …
=> ## Version 3.6.0 - Dec 19, 2022

src/public/curriculum/m2studio/m2studio.json
- add the undo/redo buttons
- in the single problem do not include the extra task tabs
- update the content to describe the undo/redo buttons
=> add spring 2023 investigation

src/models/tiles/geometry/geometry-model.ts
Fixes a bug reported from the classroom. When loading the offending user document it has `null` values for some object positions, which are defined to be of type `number | undefined`. It's not entirely clear what the circumstances are that results in `null` values, but presumably it has to do with passing `undefined` values through `JSON.stringify()` which converts `undefined` values to `null` (rather than just ignoring them, which would be preferable in this case).
The solution here is to pre-process the `GeometryModel` snapshot so that `null` values are converted back to `undefined`.
=> Fix bug: handle null positions in Geometry tiles

CHANGELOG.md, package-lock.json, package.json
Version 3.6.1 has a few bug fixes related to 4-up views, pressure sensors and document loading problems.
- Pressure Sensor should range from 0 [#184186983](https://www.pivotaltracker.com/story/show/184186983)
- Four-up view allows editing other users' documents [#184276344](https://www.pivotaltracker.com/story/show/184276344)
- Dragger handle on the Diagram Tile doesn't move tile [#184163782](https://www.pivotaltracker.com/story/show/184163782)
- Error loading document [#184275225](https://www.pivotaltracker.com/story/show/184275225)
- DF Corner indicator should only flash when disconnected [#184186985](https://www.pivotaltracker.com/story/show/184186985)
| File                                                                                  | Size | % Change from Previous Release |
| …
=> Version 3.6.1 - Jan 24, 2023

package-lock.json, package.json, src/plugins/shared-variables/slate/variables-text-content.test.tsx, src/plugins/shared-variables/slate/variables-text-content.ts
- handle unknown element types
=> fix: Update to slate-editor library 0.9.0-pre.5; silence some noisy warnings

package-lock.json, package.json
Updates diagram-view to v0.0.27. [Release Notes](https://github.com/concord-consortium/quantity-playground/releases/tag/diagram-view-0.0.27)
=> Updates diagram-view to the latest version.

functions/.eslintrc.js, functions/dependencies-notes.md, functions/jest.config.js, functions/package-lock.json, functions/package.json, functions/test/get-image-data.test.ts, functions/test/get-network-document.test.ts, functions/test/get-network-resources.test.ts, functions/test/post-document-comment.test.ts, functions/test/publish-support.test.ts, functions/test/test-utils.ts, functions/test/validate-commentable-document.test.ts, functions/tsconfig.json, src/test/setupTests.ts
I'm not sure if the switch to 127.0.0.1 will work on all machines.
It was required for them to work on my machine.
=> changes to get the jest function tests running

package-lock.json, package.json
This fixes some crashing errors with units in the M2S Diagram Tile.
PT-184564582
=> update diagram view to 0.0.38

package-lock.json, package.json
[Release notes for diagram-view 0.0.40](https://github.com/concord-consortium/quantity-playground/releases/tag/diagram-view-0.0.40)
=> Update diagram-view to 0.0.40

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, cypress/e2e/clue/branch/student_tests/diagram_tool_spec.js, cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js, cypress/e2e/clue/branch/student_tests/graph_tool_spec.js, cypress/e2e/clue/branch/student_tests/image_tool_spec.js, cypress/e2e/clue/branch/student_tests/nav_panel_test_spec.js, cypress/e2e/clue/branch/student_tests/student_test_spec.js, cypress/e2e/clue/branch/student_tests/table_tool_spec.js, cypress/e2e/clue/branch/student_tests/text_tool_spec.js, cypress/e2e/clue/branch/student_tests/workspace_test_spec.js, cypress/e2e/clue/branch/teacher_tests/history_playback_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_workspace_spec.js, cypress/support/commands.js, cypress/support/elements/clue/DataflowToolTile.js, cypress/support/elements/clue/DiagramToolTile.js, cypress/support/elements/clue/DrawToolTile.js, cypress/support/elements/clue/GraphToolTile.js, cypress/support/elements/clue/ImageToolTile.js, cypress/support/elements/clue/TeacherDashboard.js, cypress/support/elements/clue/TextToolTile.js, cypress/support/elements/clue/cCanvas.js, cypress/support/elements/common/Header.js
* CLUE Automation for additional scenarios in student & teacher tests
* Text tile selection & verifying various tool bar buttons
* Toggling the 4 quadrants of a 4-up view in the teacher dashboard
* Undo/Redo automation
* Playback and History Automation
=> CLUE Automation for missing test cases & new functionalities

src/models/curriculum/unit.ts
PT Story: https://www.pivotaltracker.com/story/show/184501394
With these changes, fetching of all external problem sections for a unit will be done in parallel. This will significantly speed up the load time of the unit in CLUE.
=> feat: Problem sections as separate files, part 2 (PT-184501394)

docs/cms.md
This duplicates some of what is in PT, but I'm guessing we won't
get to many of these issues for a while. So having them here
might help developers keep track of them.
=> update the CMS TODO section

cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/e2e/clue/branch/student_tests/graph_tool_spec.js, cypress/e2e/clue/branch/student_tests/group_test_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_curation_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_support_spec.js, cypress/support/commands.js, cypress/support/elements/clue/TeacherDashboard.js, cypress/support/elements/clue/TextToolTile.js
* Fixing skipped/commented tests
* Automation for #184641622 -**[CLUE]** Automation for students to check each other's tiles in 4-up view read-only
=> Fixing skipped/commented test

package-lock.json, package.json
PT story: https://www.pivotaltracker.com/story/show/184931580
=> 184931580 Bump diagram view version

src/models/document/document-content.ts, src/models/tiles/table/table-content.ts
PT Story: https://www.pivotaltracker.com/story/show/184931920
=> 184931920 Handle copying shared model when dragging single table or datacard tile.

package-lock.json, package.json
[Release notes for diagram-view 0.0.43](https://github.com/concord-consortium/quantity-playground/releases/tag/diagram-view-0.0.43)
=> Update diagram view to v0.0.43

package-lock.json, package.json
PT Story: https://www.pivotaltracker.com/story/show/184955306
=> fix: undefined in expression calculation (PT-184667373)

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, src/models/stores/ui.ts, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/components/dataflow-tile.tsx, src/plugins/dataflow/components/types/dataflow-tile-types.ts, src/plugins/dataflow/components/ui/dataflow-program-topbar.tsx, src/plugins/dataflow/components/ui/dataflow-rateselector-playback.tsx, src/plugins/dataflow/components/use-link-table-dialog-dataflow.tsx, src/plugins/dataflow/components/use-table-linking-dataflow.tsx, src/plugins/dataflow/model/dataflow-content.ts
Fulfills this [ticket](https://www.pivotaltracker.com/n/projects/2441242/stories/184880058) (which includes 3 features - see description)
=> 184880058 dataflow block saves recording state

src/plugins/dataflow/components/ui/dataflow-program-topbar.tsx, src/plugins/dataflow/components/ui/dataflow-rateselector-playback.tsx
Quick bug fix where confirmation dialog was showing up when hitting **Stop** instead of **Clear**
=> Bug fix -  Leslie reported bug with clear confirmation dialog coming up with record

src/models/document/base-document-content.ts, src/models/document/document-environment.ts, src/models/document/document.ts, src/models/stores/documents.ts, src/models/tiles/tile-environment.ts
Replacement for #1737 (which GitHub wouldn't let me reuse).
=> chore: incorporate IDocumentEnvironment into ITileEnvironment

cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js, src/components/tiles/table/use-consumer-tile-linking.ts, src/models/document/base-document-content.ts, src/models/tiles/tile-link-types.ts, src/plugins/graph/components/attribute-label.tsx, src/plugins/graph/components/graph-axis.tsx, src/plugins/graph/components/graph-component.tsx, src/plugins/graph/components/graph.tsx, src/plugins/graph/models/graph-controller.ts, src/plugins/graph/models/graph-model.ts
PT Story: https://www.pivotaltracker.com/story/show/184867297
- Sets a default range for axes with values from -10 to 10
- Sets default axis labels of "x" and "y"
- Axis tick, extent, and labels change when linked to match first and second columns of linked Table tile
- Unlinking Table tile returns Graph tile to default view
=> feat: XYplot default axis limits (PT-184867297)

cypress/e2e/clue/branch/student_tests/graph_table_integraton_test_spec.js, cypress/e2e/clue/branch/student_tests/shared_variables_test_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_4_quadrants_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/support/elements/clue/ChatPanel.js, cypress/support/elements/clue/cCanvas.js, src/components/chat/commented-documents.tsx, src/plugins/dataflow/nodes/controls/humidifier-animation.tsx, src/plugins/dataflow/nodes/controls/sensor-select-control.tsx, src/plugins/diagram-viewer/diagram-tile.tsx
This PR cleans up a few files where warnings were showing up in our code coverage reports. It involved working with code I'm not familiar with, so I'm hoping the original authors will have time to look at my proposals here and make sure I didn't do anything that will break their work.
`commented-documents.tsx`: Two `useEffect`s did not have any dependencies specified. I added the suggested dependencies and used `useMemo` to try to reduce how often those dependencies update. I believe @dennisrcao was the original author here.
`humidifier-animation.tsx`: One `useEffect` had some missing dependencies. In order to add them, I had to wrap some functions in `useCallback` to try to reduce how often the `useEffect` reruns. I think the original author was @bacalj.
`sensor-select-control.tsx`: A …
=> Cleanup strays

src/components/chat/chat-panel.tsx
Fulfills this ticket
[#185407691**[CLUEAI]** Comments on this class Student Workspaces View - Group View commenting](https://www.pivotaltracker.com/n/projects/2441242/stories/185407691)
=> 185407691-comments-on-this-class-student-workspaces-view-group-view-commenting

src/components/chat/chat-thread.scss, src/components/chat/comment-card.scss, src/components/vars.sass
Fulfills ticket 
[185382879-comments-yellow-styling
](https://www.pivotaltracker.com/n/projects/2441242/stories/185382879)
=> 185382879-comments-yellow-styling

cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, src/components/document/editable-document-content.scss, src/components/navigation/problem-panel.sass, src/components/navigation/section-document-or-browser.sass, src/components/tiles/tile-component.sass, src/components/vars.sass, src/plugins/data-card/data-card-tile.tsx
Do not review yet: 
Fix failing cypress tests
Also added yellow highlighting
old PR: https://github.com/concord-consortium/collaborative-learning/pull/1762
=> 185382879-fix-comments-yellow-styling

docs/variables.md
PT Story: https://www.pivotaltracker.com/story/show/185405106
This PR adds documentation about the `SharedVariables` model and its two use cases.
=> 185405106 Shared Variables Documentation

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, src/plugins/dataflow/model/utilities/node.ts, src/plugins/dataflow/nodes/control-node-states.scss, src/plugins/dataflow/nodes/controls/dropdown-list-control.tsx, src/plugins/dataflow/nodes/dataflow-node.scss, src/plugins/dataflow/nodes/dataflow-node.tsx, src/plugins/dataflow/nodes/factories/control-rete-node-factory.tsx, src/plugins/dataflow/nodes/utilities/view-utilities.ts
This PR:
- addresses the requested changes to the Hold/Control node[ PT#185279571](https://www.pivotaltracker.com/n/projects/2441242/stories/185279571)
- leverages the new `displayName` to display "Gripper" instead of "Grabber", [PT#185397554](https://www.pivotaltracker.com/n/projects/2441242/stories/185397554)
=> 185279571 signal indicator

src/models/data/data-set-actions.ts, src/plugins/graph/hooks/use-init-graph-layout.ts, src/plugins/graph/models/data-configuration-model.ts, src/plugins/graph/models/graph-model.ts
[PT-185464592](https://www.pivotaltracker.com/story/show/185464592)
=> fix: graph link/unlink sync over firebase

src/components/document/editable-document-content.tsx, src/components/navigation/document-view.tsx, src/components/navigation/section-document-or-browser.scss, src/components/navigation/section-document-or-browser.tsx, src/components/navigation/sub-tabs-panel.sass
Fixes starred document list when in My Work tab. We were not filter for only owner's documents
Fixes scrolling in various views.
Fixes document height when not in Starred tab
To test, use this user http://localhost:8080/?appMode=demo&demoName=tejalFlipperWorkspace&fakeClass=1&fakeUser=student:2&unit=sas&problem=1.1
=> Fixes various bugs.

src/components/navigation/nav-tab-panel.tsx
Fixed so that students can see and make comments in the UI.
=> enable UI for students to see and make comments

src/plugins/simulator/simulations/terrarium/terrarium.tsx
PT Story: https://www.pivotaltracker.com/story/show/185425830
This changes the minimum humidity from 20 to 0. The starting humidity remains 20.
=> 185425830 Change minimum humidity.

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, cypress/e2e/clue/branch/student_tests/graph_tool_spec.js, cypress/support/commands.js, src/plugins/dataflow/model/utilities/node-operations.test.ts, src/plugins/dataflow/model/utilities/node.ts
This adds round, floor, and ceil functions to the Dataflow transform node, as described in [PT#185422637](https://www.pivotaltracker.com/n/projects/2441242/stories/185422637)
=> 185422637 round function

src/components/chat/comment-card.tsx, src/components/chat/commented-documents.tsx, src/public/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
https://collaborative-learning.concord.org/branch/fix-crash/?appMode=demo&fakeUser=teacher:3&fakeClass=2&unit=https://collaborative-learning.concord.org/branch/fix-crash/curriculum/stretching-and-shrinking/stretching-and-shrinking.json
=> 185492962 - Fixes crash in master when you open up the comments tab

src/components/navigation/document-view.tsx, src/components/navigation/section-document-or-browser.scss
Adds styling to document title
Adds document owner name to all class work titles
=> Add document owner to document title in Class Work tab

src/plugins/dataflow/nodes/utilities/view-utilities.ts
This fixes a compilation error that started cropping up in master.
=> specify Input as type when testing for flow in

package-lock.json, package.json
This version of Concord's MST includes this fix:
https://github.com/mobxjs/mobx-state-tree/pull/2054
=> upgrade MST with fix for detach

src/components/toolbar.tsx, src/plugins/simulator/assets/simulator-icon.svg
This changes the Simulation tile icon as described in [PT#185683070](https://www.pivotaltracker.com/story/show/185683070)
=> 185683070 one sim tile

README.md, docs/history-framework.md, src/components/document/canvas.tsx, src/models/history/tree-manager.ts
also add `historyDocument` global
=> print full history if history debugging is on

src/components/document/document-content.tsx
The old code would trigger the reaction again and again.
I didn't find out exactly why, but it was partly because the
`data` of reaction was an object that was being recreated
each time something changed in the UI Store. This was fixed
by having the data be a simple string. It could also have been
fixed by passing options to the reaction of `{equals: comparer.shallow}`
PT-185826033
=> FIX scroll jittering

src/components/navigation/sub-tabs-panel.sass
it was broken both in the My Work and Class Work main tabs
=> Fix vertical scrolling on Workspaces subtab

cypress.config.ts, cypress/e2e/clue/branch/author_tests/doc-editor_spec.js, cypress/e2e/clue/branch/student_tests/arrow_annotation_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_dashboard_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_six_pack_spec.js, cypress/e2e/clue/branch/teacher_tests/teacher_support_note.js
This PR does the following things:
1. Splits branch/teacher_dashboard_spec.js into 3 separate spec files
2. Makes all tests in teacher_dashboard_spec.js, doc_editor_spec.js and arrow_annotation_spec.js independent so that retries work.
3. Change `numTestsKeptInMemory` to `20` from `0` since this was causing playback of local tests to not work.
=> 185895047 teacher dashboard tests

cypress/e2e/clue/branch/student_tests/xy_plot_tool_spec.js, cypress/support/elements/clue/XYPlotToolTile.js, cypress/support/elements/clue/cCanvas.js
=> XYPlot Automation

.editorconfig, .gitattributes, .gitignore, .vscode/extensions.json, .vscode/settings.json
Co-authored-by: Aden <433eros@users.noreply.github.com>
=> saving vscode settings, setup .editorconfig

cypress/e2e/clue/branch/student_tests/dataflow_tool_spec.js, src/models/stores/serial.ts, src/plugins/dataflow-tool/arduino/ccemgfsr/ccemgfsr.ino, src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/model/utilities/channel.ts
This adds in live temperature readings to the Dataflow sensor node, as described in PT-186082591.  I have tested programs that: 
- process all three sensor streams and operate the new gripper
- process EMG only and operate the old gripper
=> 186082591 live temperature readings

cypress/e2e/clue/full/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_dashboard_six_pack_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_dashboard_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_dividers_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_problem_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_network_workspace_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/fixtures/teacher-dash-data.json, cypress/support/elements/clue/cCanvas.js
Migrate Automated Test To New Portal Staging
=> Migrate Automated Test To New Portal Staging

scripts/add-ids-to-tiles.ts, scripts/count-tiles-without-ids.ts
=> scripts for checking and adding ids to tiles

cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/support/elements/clue/ChatPanel.js
=> Comment Tags Automation

.github/workflows/manual-regression.yml, cypress/e2e/clue/branch/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_chat_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_dashboard_six_pack_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_dashboard_spec.js, cypress/e2e/clue/full/teacher_tests/teacher_workspace_spec.js, cypress/fixtures/teacher-dash-data.json, cypress/support/elements/clue/ChatPanel.js
=> Failure Fixes

cypress/e2e/clue/branch/student_tests/drawing_tool_spec.js, src/models/document/document-content-tests/dc-general.test.ts, src/plugins/drawing/drawing-registration.ts
For PT-186420374
Change the default title of drawing tiles to "Sketch <n>".
=> rename drawing tile

src/plugins/graph/adornments/connecting-lines/connecting-lines-model.ts, src/plugins/graph/adornments/connecting-lines/connecting-lines.tsx, src/plugins/graph/components/graph-axis.tsx, src/plugins/graph/components/graph.tsx, src/plugins/graph/models/graph-model.test.ts, src/plugins/graph/models/graph-model.ts
Port the fix from [CODAP #890](https://github.com/concord-consortium/codap/pull/890)
=> fix: x-axis drag rescale on XY plot

cypress/config/cypress.local.json, cypress/e2e/functional/teacher_tests/teacher_scrolling_spec.js, cypress/support/elements/common/Scrolling.js
Scrolling Automation Covered:
1) Resources (left panel)
- Problem subtabs
- Teacher guide subtabs
- My Work subtabs
- Workspaces subtab
- Starred subtab (single flipper views)
- Class Work subtabs
- Workspaces subtab
- Starred subtab (singleflipper views)
- Student Workspaces individual student workspaces (expanded)
2) Workspace (right panel)
- Problem document
- Personal document
3) Dashboard
- Current Work (via up and down arrows at bottom right)
- Published Work (via up and down arrows at bottom right)
- Individual student workspaces (expanded)
=> Scrolling Automation

.github/workflows/manual-regression.yml, cypress/e2e/functional/teacher_tests/teacher_document_flipper_spec.js, cypress/e2e/functional/teacher_tests/teacher_starreddocument_scroller_spec.js, cypress/support/elements/common/StarredTab.js
=> Document Flipper Automation

cypress/e2e/functional/teacher_tests/teacher_starreddocument_scroller_spec.js, cypress/support/elements/common/StarredTab.js
Fixing failures in document flipper
=> Fixing failures

cypress/e2e/functional/tile_tests/data_card_tool_spec.js
@tejal-shah - this is a PR for the story [Automation for Duplicate Data Card Tile](https://www.pivotaltracker.com/story/show/186639366). Thank you!
=> added automation for Duplicate Card in Datacard tile

cypress/e2e/functional/document_tests/tiles_copy_test_spec.js
Automation for copy tiles from other published/unpublished documents
=> Automation for copy tiles

cypress/e2e/functional/document_tests/student_teacher_4up_readonly_spec.js
Student and teacher 4-up & 1-up views Tiles Read Only Automation
=> 4up Tiles Read Only Automation

cypress/e2e/functional/tile_tests/data_card_tool_spec.js, cypress/e2e/functional/tile_tests/diagram_tool_spec.js, cypress/e2e/functional/tile_tests/drawing_tool_spec.js, cypress/e2e/functional/tile_tests/expression_tool_spec.js, cypress/e2e/functional/tile_tests/geometry_tool_spec.js, cypress/e2e/functional/tile_tests/image_tool_spec.js, cypress/e2e/functional/tile_tests/numberline_tool_spec.js, cypress/e2e/functional/tile_tests/simulator_tile_spec.js, cypress/e2e/functional/tile_tests/table_tool_spec.js, cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
Tile title changes restore upon page reload.
Image
Drawing
Geometry
Table
Data Card
Diagram
Expression
Numberline
Simulator
XY Plot
=> Tile title changes restore

docs/document-types.md
I decided to try the experiment of tracking down the pieces of one of the demo documents that has generated a lot of rollbar errors. (`Error retrieving metadata for document '-NGcmVCT1ZLr_7a5pzVI' of type 'personalPublication' for user '1001'`.) In this case, it was a `personalPublication` for which the type-specific metadata and the document contents were present but the common metadata was missing. I deleted the remaining pieces of the document in the database which should eliminate the errors related to this particular document. In the process, however, I noted some information missing from `document-types.md` and took the time to update the documentation.
=> chore: update documentation on publications

cypress/e2e/functional/tile_tests/dataflow_tool_spec.js, src/plugins/dataflow/model/utilities/node.ts, src/plugins/dataflow/nodes/factories/transform-rete-node-factory.tsx
This adds a ramp function to the Dataflow Transform block, as described in PT-186714042
Testing link and instructions are in the story.
=> 186714042 ramp transform

cypress/e2e/functional/tile_tests/data_card_tool_spec.js, cypress/e2e/functional/tile_tests/diagram_tool_spec.js, cypress/e2e/functional/tile_tests/drawing_tool_spec.js, cypress/e2e/functional/tile_tests/expression_tool_spec.js, cypress/e2e/functional/tile_tests/geometry_tool_spec.js, cypress/e2e/functional/tile_tests/numberline_tool_spec.js, cypress/e2e/functional/tile_tests/simulator_tile_spec.js, cypress/e2e/functional/tile_tests/table_tool_spec.js, cypress/e2e/functional/tile_tests/text_tool_spec.js, cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
=> Tile Restore Automation

src/hooks/use-consumer-tile-linking.ts
Fix an old bug that was made visible by the changes in the consumer tile linking dialog in #2100 , and reported in [this comment](https://www.pivotaltracker.com/story/show/186566168/comments/239648553) .
Before this fix, using the "Link Table" button to connect `Table 1`'s data into `Table 2` would first unlink all shared models from `Table 2`, then add the link from to `Table 1`'s data to `Table 2`. But in between (after the unlink and before the new link was added), `Table 2` would react to the lack of any dataset by creating a new default dataset.  The end result was that `Table 2` was now linked to two datasets, only one of which could be displayed, causing some subtle errors.
This change delays the removal until the new dataset is linked.
=> Fix table-dataset-linking bug

cypress/e2e/functional/tile_tests/text_tool_spec.js
cypress tests for undo/redo for formatting text
=> added cypress tests for undo/redo for formatting text

.vscode/settings.json, scripts/ai/annotation-documents.ts, scripts/ai/count-docs.ts, scripts/ai/download-documents-with-info.ts, scripts/ai/sparrow-documents.ts
PT Story: https://www.pivotaltracker.com/story/show/186935965
This PR introduces three scripts that help analyze documents.
- `download-documents-with-info.ts` downloads documents from firebase and saves them to the user's machine. In addition to document content, the script also saves class id, offering id, user id, document id, and document title (this last one might not work) for each document. This is kept separate from the old `download-documents.ts`, which only downloads document content, because the `document-screenshots.ts` script requires files with just content to render documents properly.
- `annotation-documents.ts` saves information about documents downloaded with `download-documents-with-info.ts` that include annotations of specified types. Currently there's just one type of …
=> 186935965 Find Sparrow Docs

src/plugins/dataflow/components/ui/dataflow-program-topbar.tsx
This adds a line to the Clear Program dialog as described in PT-186974159
=> add line to dialog

docs/launch-sequence-abstract.md, docs/launch-sequence.md, docs/unit-configuration.md
Add mermaid docs describing the startup sequence.
The loading events are in the source of the diagram but not visible in the diagram rendering. We haven't found a simple way to render them. 
Future work that would be nice:
- Update the complex diagram to include real function names and file names. This will make it easier to keep it up-to-date
- try adding "return" nodes for all the subgraphs, so it is clear when the subgraph is done.
- try to get initializePersistenUISync to be below Resolve app mode
- figure out why "Re-set unit and problem (if different)" doesn't connect directly to "Resolve app mode" the arrow stops a bit above for some reason.
=> 186993588-startup-doc

src/hooks/use-consumer-tile-linking.ts, src/hooks/use-link-consumer-tile-dialog.tsx, src/plugins/shared-variables/shared-variables-link-button.tsx
Fulfills the following ticket
[  **[Algebra]** Log Linking of Table Toolbar Icons[XY Plot]](https://www.pivotaltracker.com/n/projects/2441242/stories/187091535)
____________________________________________________________________________________________________
Deployment
______________________________________________________________________________________________
Localhost:
http://localhost:8080/?appMode=demo&demoName=CLUE&fakeClass=1&fakeUser=student:4&problem=1.1&unit=msa
=> 187091535 log linking of table toolbar

src/components/tiles/table/table-tile.tsx
[PT-187100087](https://www.pivotaltracker.com/story/show/187100087)
=> fix: loading images in table causes infinite loop

cms/src/cms-collections.ts, cms/src/cms-constants.ts, cms/src/init-cms.ts, cms/src/preview-link-control.tsx
PT-186665226
at the moment, these are the required parameters for testing
```
http://{{ clue url }}
?cmsEditorBase=http://localhost:8080
&unit=moth
&curriculumBranch=exemplar-3#
/collections/exemplars/entries/investigation-1/problem-1/first-exemplar/content
```
=> 186665226 exemplar schema 3

cypress/e2e/functional/tile_tests/xy_plot_tool_spec.js
This PR just adds a test to make sure the issue in PT-185225429 does not recur.
=> Add Cypress test of linking table with expression

package-lock.json, package.json
This update is after the react components was updated:
https://github.com/concord-consortium/concord-react-components/pull/24 
It seems to be working to me.
=> update shared react components

src/plugins/drawing/components/wrapped-svg-text.tsx
=> Properly display text objects in 4-up drawings

cypress/e2e/functional/document_tests/exemplar_test_spec.js, cypress/support/elements/common/SortedWork.js, src/components/tiles/text/text-tile.tsx, src/components/workspace/workspace.tsx, src/lib/db-listeners/db-exemplars-listener.ts, src/lib/db.ts, src/lib/firebase.ts, src/lib/logger.ts, src/models/stores/documents.ts, src/models/stores/exemplar-controller-rules.ts, src/models/stores/exemplar-controller.ts, src/models/stores/stores.ts, src/models/tiles/text/text-content.ts, src/utilities/string-utils.ts
PT-187242048
After every 3 drawing actions (defined for now as creation of a new object on the canvas), one randomly-chosen exemplar is revealed.
For testing purposes, also defines a hotkey -- Cmd-Shift-e -- to reset all exemplars to their normal hidden state.
=> exemplars on action

src/plugins/dataflow/nodes/control-node.ts, src/plugins/dataflow/nodes/controls/num-control.sass, src/plugins/dataflow/nodes/controls/num-control.tsx
Add simple support for read-only units on number controls.
=> add secs to hold block field

src/plugins/dataflow/nodes/controls/plot-button-control.tsx, src/plugins/dataflow/nodes/rete-manager.tsx
- fix toggle minigraph log event
- add logging of connection and node creation and removal
=> log same events in rete v2

src/plugins/dataflow/components/dataflow-program.tsx, src/plugins/dataflow/dataflow-registration.ts, src/plugins/dataflow/model/convert-legacy-dataflow.test.ts, src/plugins/dataflow/model/convert-legacy-dataflow.ts, src/plugins/dataflow/model/dataflow-content.test.ts, src/plugins/dataflow/model/dataflow-content.ts, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/model/dataflow-state-versions.ts, src/plugins/dataflow/nodes/controls/demo-output-control.tsx, src/plugins/dataflow/test-docs/dataflow-0.1.0.json, src/plugins/dataflow/test-docs/dataflow-1-three-node.json, src/plugins/dataflow/test-docs/readme.md
=> load in old dataflow docs

src/plugins/dataflow/model/dataflow-content.test.ts, src/plugins/dataflow/model/dataflow-content.ts
=> dataflow export with full state

cypress/e2e/functional/tile_tests/dataflow_table_graph_integration_test_spec.js, cypress/e2e/functional/tile_tests/dataflow_tool_spec.js, src/plugins/dataflow/model/dataflow-program-model.ts, src/plugins/dataflow/nodes/base-node.ts, src/plugins/dataflow/nodes/dataflow-node.tsx, src/plugins/dataflow/nodes/editable-node-name.tsx, src/plugins/dataflow/nodes/rete-manager.tsx, src/plugins/dataflow/nodes/utilities/indexed-name.test.ts
PT-187083097
_in draft until below completed_
=> 187083097 df node labels

src/plugins/dataflow-tool/arduino/dataflowarduino/dataflowarduino.ino, src/plugins/simulator/simulations/potentiometer-servo/potentiometer-servo.tsx
This changes the pot max value to 1023, as described in PT-187570577.  It also adds the latest firmware to the repo, which does not need to be here to run, but we keep here by convention.
=> change max potentiometer value to 1023, add "universal" firmware to repo

cypress/e2e/functional/tile_tests/arrow_annotation_spec.js, cypress/support/elements/common/cCanvas.js, src/components/tiles/geometry/geometry-content.tsx, src/models/tiles/geometry/geometry-content.ts
PT-187496227
This adds the ability to connect Sparrows to "linked points" in the Shapes Graph tile.
Linked points are points derived from a linked dataset; eg if you link a table to the Shapes Graph.
=> Linked point sparrows

cypress/e2e/functional/document_tests/exemplar_test_spec.js, src/models/stores/exemplar-controller-rules.ts
Implement changes in PT-187924928
Exemplar will be shown after 2 drawings and 2 labels rather than 3.
=> Change exemplar rule

src/models/data/data-types.test.ts, src/models/data/data-types.ts
=> fix: images as first category makes graph unusable (PT-187848781)

src/plugins/graph/hooks/use-plot.ts
[#188014234](https://www.pivotaltracker.com/story/show/188014234)
=> fix: Moving manually-added points causes axes to autoscale (PT-188014234)

cypress/e2e/functional/tile_tests/geometry_table_integraton_test_spec.js, src/components/tiles/geometry/geometry-content.tsx
=> Rescale coordinate grid on all data changes

cypress/e2e/functional/document_tests/exemplar_test_spec.js, cypress/support/elements/common/SortedWork.js, src/models/document/base-document-content.ts, src/models/stores/create-exemplar-docs.ts, src/models/stores/documents.ts, src/models/stores/sorted-documents.ts, src/models/stores/stores.ts, src/public/demo/units/qa-moth-plot/exemplars/investigation-1/problem-1/exemplar-1/content.json
PT-188007327
Include Exemplars in the sort & filtered views.
=> Show exemplars in sort-work view

scripts/ai/download-documents-with-info.ts, scripts/ai/get-offering-info.ts, scripts/ai/update-class-metadata.ts, scripts/lib/fetch-portal-entity.ts, scripts/lib/script-utils.ts
[#188108798](https://www.pivotaltracker.com/story/show/188108798)
=> feat: Permissions migration script to create/update Firestore class documents (PT-188108798)

README.md, src/lib/db.ts, src/lib/debug.ts, src/lib/teacher-network.test.ts, src/lib/teacher-network.ts
This also includes a new debug option so it is easier to see the Firestore debug logs.
=> only teachers can sync classes and offerings

cypress/e2e/functional/tile_tests/bar_graph_tile_spec.js, cypress/support/elements/tile/BarGraphTile.js, src/plugins/bar-graph/assets/bar-graph-icon.svg, src/plugins/bar-graph/bar-graph-content.test.ts, src/plugins/bar-graph/bar-graph-content.ts, src/plugins/bar-graph/bar-graph-registration.ts, src/plugins/bar-graph/bar-graph-tile.test.tsx, src/plugins/bar-graph/bar-graph-tile.tsx, src/plugins/bar-graph/bar-graph-types.ts, src/plugins/bar-graph/bar-graph.scss, src/public/demo/units/qa/content.json, src/register-tile-types.ts
Implements a placeholder tile for bar graphs.
PT-181498727 -- creating the tile
PT-188127101 -- giving it an editable title
I did not spend any time on the content & design since those will be completely replaced in the next stories.
=> Bar graph tile

src/models/data/attribute.ts, src/plugins/bar-graph/bar-graph-content.test.ts, src/plugins/bar-graph/bar-graph-content.ts, src/plugins/bar-graph/bar-graph-utils.ts, src/plugins/bar-graph/chart-area.tsx, src/plugins/bar-graph/legend-secondary-row.tsx
PT-188285608
Makes bar charts work better when there are images in the dataset.
=> bar chart images

src/components/app.tsx, src/lib/db-listeners/db-groups-listener.ts, src/models/stores/class.test.ts, src/models/stores/class.ts, src/models/stores/user-types.ts
PT-188285964
Adds a fictitious "Ada Insight" user to the class that will be associated with comments generated by AI analysis.
=> Create AI user

src/clue/components/clue-app-content.tsx, src/components/app.tsx, src/components/document/document-content.tsx, src/components/document/document.tsx, src/components/document/editable-document-content.tsx, src/components/navigation/nav-tab-panel.tsx, src/components/navigation/problem-tab-content.tsx, src/lib/db-listeners/db-docs-content-listener.ts, src/models/document/document-utils.ts, src/models/stores/class.ts, src/models/stores/stores.ts, src/models/stores/user.ts
This adds an isTeacherOrResearcher getter to user and replaces many user.isTeacher references to enable researchers to see teacher only UI.
This also adds some comments prefixed with RESEARCHER-ACCESS that should be resolved before this feature branch is merged.
=> feat: Enable UI elements for researchers [PT-188754125]

src/clue/components/teacher/teacher-group-six-pack-fourup.tsx, src/components/thumbnail/thumbnail-document-item.tsx, src/components/workspace/workspace.tsx
- Only show left nav tab panel for researchers to avoid auto creating docs for researchers.
- Remove "send message to group" button from dashboard for researchers
- Disable bookmarks for researchers
=> feat: More researcher UI updates [PT-188754125]

src/components/document/sort-work-view.scss, src/components/four-up.sass, src/components/playback/playback-control.scss, src/components/playback/playback-control.tsx, src/components/playback/playback.scss
This updates the styling of the playback controls to make them more integrated into the page.
This also fixes a bug with the minutes when they are 0 that I happened to see as my history entry was at the top of the hour.
=> fix: Styling of playback controls and minute bug [CLUE-42]

cypress/e2e/functional/document_tests/group_test_readonly_spec.js, cypress/e2e/functional/document_tests/student_teacher_4up_readonly_spec.js, cypress/e2e/functional/teacher_tests/history_playback_spec.js, cypress/e2e/functional/teacher_tests/teacher_dashboard_4_quadrants_spec.js, cypress/support/elements/common/ResourcesPanel.js, cypress/support/elements/common/TeacherDashboard.js, cypress/support/elements/common/cCanvas.js, src/components/document/canvas.tsx, src/components/four-up.tsx
This also fixes the missing student name in the 4-up view in the teacher dashboard
(found when teacher_dashboard_4_quadrants_spec.js failed) and a bug introduced in
history playback where history was being retrieved for right side documents.
=> fix: Cypress regression tests

src/components/utilities/dialog.sass, src/components/utilities/dialog.tsx
=> fix: Added hover/active style to dialog close button [CLUE-79]

cypress/e2e/functional/teacher_tests/teacher_sort_work_view_spec.js, src/components/document/document-scroller.scss, src/components/document/document-scroller.tsx
[CLUE-56](https://concord-consortium.atlassian.net/browse/CLUE-56?atlOrigin=eyJpIjoiZDEzYzU4YjBkZGRiNDRlYzgyNGJhYmVmZjI2ZjdkZjIiLCJwIjoiaiJ9)
This PR adds a header that displays the selected sort options in the document scroller.
[CLUE-56]: https://concord-consortium.atlassian.net/browse/CLUE-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLUE-56] - Document Scroller Header

src/components/standalone/auth.tsx
Since we are already connected the db module will throw an error.
=> fix: Multiple calls to authAndConnect at end of standalone auth

cypress/support/elements/tile/TextToolTile.js, package-lock.json, package.json, src/components/tiles/text/text-tile.tsx, src/plugins/shared-variables/slate/variables-plugin.tsx
Update @concord-consortium/slate-editor to [0.10.1](https://github.com/concord-consortium/slate-editor/blob/master/CHANGELOG.md) in the hopes that it fixes CLUE-112
=> Update slate-editor to 0.10.x

src/components/standalone/auth.test.tsx, src/components/standalone/auth.tsx, src/lib/portal-api.ts, src/models/curriculum/unit.ts
This also fixes a bug where the problem in the url at the standalone initial render was not being updated before login.
=> feat: Add create of all offerings for a unit in standalone [CLUE-125]

src/plugins/drawing/objects/text.tsx
Fixes CLUE-69
The `Content` component was previously defined inside `TextComponent`, which resulted in the re-creation of `Content` and loss of the current input value in its `<textarea>` when the `TextComponent` was re-rendered.  In particular, the user re-sizing the text object would cause a re-render and loss of the edits.
`Content` is refactored to be its own component. In addition, the `<textarea>` is now managed so that any edits should survive re-renders.  We maintain the ability to use 'ESC' to abandon edits, blur or enter to accept them, and only updating the model (and causing event logging) at the point of accepting the edits.
=> Maintain text editor state when resizing

src/iframe/iframe.html, src/index.html
This is to reduce the amount of requests.
=> fix: Enable rollbar on production only

docs/data-set-upgrade.md, docs/formula-system.md
It is unlikely that we will upgrade the CLUE Dataset.
It is likely that we will either bring in the CODAP Formula system as package or copy the code and modify it.
=> Docs:  upgrading dataset and using CODAP formulas

cypress/e2e/functional/teacher_tests/teacher_sort_work_view_4_spec.js, src/components/document/document.tsx, src/lib/db-listeners/db-exemplars-listener.ts
[CLUE-111](https://concord-consortium.atlassian.net/browse/CLUE-111)
[CLUE-111]: https://concord-consortium.atlassian.net/browse/CLUE-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLUE-111: Fix exemplars with broken links showing in wrong problems

cypress/e2e/functional/tile_tests/drawing_tool_spec.js, src/plugins/drawing/components/drawing-tile.tsx
[CLUE-147](https://concord-consortium.atlassian.net/browse/CLUE-147)
[CLUE-147]: https://concord-consortium.atlassian.net/browse/CLUE-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLUE-147]: User can copy + paste objects in drawing tile with hot keys

src/models/document/document-content.ts
[CLUE-256](https://concord-consortium.atlassian.net/browse/CLUE-256?atlOrigin=eyJpIjoiNjBlZGE2OWEyODM0NDZlMmI5YzU4OThiMDJhYWM2NTMiLCJwIjoiaiJ9)
[CLUE-256]: https://concord-consortium.atlassian.net/browse/CLUE-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: exported content includes nested tiles in sharedModels (CLUE-256)

cypress/e2e/functional/document_tests/exemplar_test_spec.js, src/components/chat/comment-card.tsx, src/components/chat/commented-documents.tsx, src/components/document/document.tsx, src/components/document/mywork-document-or-browser.tsx, src/models/stores/exemplar-controller.ts, src/models/stores/persistent-ui/persistent-ui.test.ts, src/models/stores/persistent-ui/persistent-ui.ts, src/models/stores/stores.ts
[CLUE-273](https://concord-consortium.atlassian.net/browse/CLUE-273)
With these changes, when the current curriculum unit supports AI evaluation and a student clicks on the Ideas button, their current document will open in the left panel in the appropriate tab based on what tabs are available in the unit. The order of preference for the tabs is:
1. Sort Work
2. My Work
3. No Tab -- document will not be displayed in left panel in this case.
In all cases, the Chat panel will also open when the Ideas button is clicked.
When there is no Sort Work or My Work tab, we also enable the File menu in the right panel so students can open and publish documents.
**EXAMPLES**
**Unit with My Work and Sort Work tab**
Clicking “Ideas” opens the chat panel and the document in the Sort Work tab, with Name …
=> feat: Ideas button opens document in available tab (CLUE-273)

src/authoring/components/app.scss, src/authoring/components/app.tsx, src/authoring/components/left-nav.scss, src/authoring/components/left-nav.tsx, src/authoring/components/media-library.scss, src/authoring/components/media-library.tsx
This commit introduces a new media library component to the authoring interface, allowing users to browse, search, and select images for their content. The media library features a responsive grid layout, search functionality, and integration with the existing left navigation panel.
In this first iteration, the media library supports selecting existing images.
A follow on PR will add the ability to upload new images.
=> feat: Added media library [CLUE-289]

authoring-api/src/index.ts, src/authoring/components/workspace/nav-tabs.tsx
- Fixed comment about body size limit
- Removed unnecessary div key
=> Misc fixes from stacked PRs
